### PR TITLE
[iOS Maps] Pin rendering customization

### PR DESCRIPTION
**Pull request by jcmanke**
### Description of Change ###

- #893 without breaking change to iOS MapRenderer base class.
- Continuation of #844 to create customization feature parity between Android and iOS.
- [Evolution Forum Post](https://forums.xamarin.com/discussion/91907/map-renderer-extensibility/)

### API Changes ###

Removed:
 - MapDelegate class -> Methods moved into MapRenderer class

Changed:
- private void AttachGestureToPin(MKPinAnnotationView mapPin, IMKAnnotation annotation) => protected void AttachGestureToPin(MKAnnotationView mapPin, IMKAnnotation annotation) 
  - So the Pin.Clicked event can be used when GetViewForAnnotation is overridden and/or native pin is rendered as a different subclass of MKAnnotationView

### Behavioral Changes ###

Should not change any existing functionality in the base library, makes it easier to customize pins when extending the iOS MapRenderer.

### PR Checklist ###

- [x] Has tests (if omitted, state reason in description)
- [x] Rebased on top of master at time of PR
- [x] Changes adhere to coding standard
- [x] Consolidate commits as makes sense

### CODE REVIEW

**Comment by hartez** [comment]
This needs a UI test demonstrating gestures on pins.

**Comment by jcmanke** [comment]
@hartez Test added.

**Comment by rmarinho** [comment]
build

**Comment by rmarinho** [comment]
@jcmanke can you rebase so we can run tests again? 

Thanks

**Comment by jcmanke** [comment]
@rmarinho Rebased.

**Comment by rmarinho** [comment]
he @jcmanke  it's failing a test on iOS11 for map click 

Xamarin.Forms.Core.UITests.MapUITests.MapGalleryPinClicked_apple_iphone_7-11_0_3

**Comment by jcmanke** [comment]
@rmarinho Can you tell me anything about how the test is actually failing? 

I ran it on both test devices I have in my office, an iPad Mini 3 with iOS 11.0, and an iPhone 6 Plus with iOS 11.2.1 and it passed on both.

**Comment by rmarinho** [comment]
@jcmanke 
```
System.Exception : Error while performing Tap(Text("Colosseum")) ----> System.Exception : Unable to tap element. Query for Text("Colosseum") gave no results.
at Xamarin.UITest.Utils.ErrorReporting.With (System.Action func, System.Object[] args, System.String memberName) [0x00060] in <cd88903cbd9c486785416cbc55d6a68e>:0
at Xamarin.UITest.iOS.iOSApp.Tap (System.Func`2[T,TResult] query) [0x00014] in <cd88903cbd9c486785416cbc55d6a68e>:0
at Xamarin.Forms.Controls.ScreenshotConditionalApp.Tap (System.Func`2[T,TResult] query) [0x00001] in <1ab57ec0679d40e68819fbf3cfde24f2>:0
at Xamarin.Forms.Core.UITests.MapUITests.MapGalleryPinClicked () [0x00016] in <1ab57ec0679d40e68819fbf3cfde24f2>:0
at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00032] in <48b95f3df5804531818f80e28ec60191>:0
--Exception
at Xamarin.UITest.iOS.iOSApp+<Tap>c__AnonStoreyA.<>m__0 () [0x0004f] in <cd88903cbd9c486785416cbc55d6a68e>:0
at Xamarin.UITest.Utils.ErrorReporting.With (System.Action func, System.Object[] args, System.String memberName) [0x00006] in <cd88903cbd9c486785416cbc55d6a68e>:0
```

**Comment by jcmanke** [comment]
@rmarinho I added a WaitForElement to the UI test that will hopefully fix it.

**Pull request merged**
