### PR TITLE
Added ReturnType to Editor

### LINKED ISSUE #4832: Editor crashes when my app was updated to latest xamarin.forms 3.4 .0.1008975
### Description

My App crashes by using Editor, when I updated xamarin.forms from 3.2 to3.4 .

It crashes only when  my smartphone's orientation is landscape.  

It happens only by Andriod. There is no such a  bug by iOS.

### Steps to Reproduce

1. Andriod, uses portable project, one of tagets is .NET Framework 4.5
2. smartphone's orientation is landscape ( portrait is ok)
3. Input some text for Editor then press "DONE"
4. Crashes:

Java.Lang.IllegalStateException: focus search returned a view that wasn't able to take focus!

### Basic Information

- Version with issue:
- Last known good version:
- IDE: 
Visual Studio 2017
- Platform Target Frameworks:  
   
  - Android: <  7.1 -->

### PR DESCRIPTION
**Pull request by andreinitescu**
### Description of Change ###

Added support for ReturnType property to Editor. Moved ReturnType from Entry to base class InputView.
It also fixes several reported issues.

Probably ReturnCommand property should also be moved to InputView, something which will be handled in a future ticket.

### API Changes ###

- Core/XAML (all platforms)
- iOS
- Android
- UWP
- Tizen

### Behavioral/Visual Changes ###

None

### Before/After Screenshots ### 

Not applicable

### PR Checklist ###

- [x] Has automated tests 
- [x] Rebased on top of the target branch at time of PR
- [x] Changes adhere to coding standard

### CODE REVIEW

**Comment by adrianknight89** [comment]
@andreinitescu Regarding the future ticket, ideally I'd like to see `ReturnCommand` moved into `InputView` at the same time as `ReturnType`. Would it be too much work to do that in the same PR or do you expect to submit another PR for this soon? Thanks for the work.

Off-topic: It'd be neat to have a keyboard type for posting long text for social apps which includes the `@` and `#` symbols. iOS has a built-in [keyboard type](https://stackoverflow.com/questions/11751673/how-does-instagram-customize-the-uikeyboard-returnkey-to-an-and-a) for this. Not sure about Android though.

**Comment by jcmanke** [comment]
@StephaneDelcroix So you've decided moving public properties and fields to the base class doesn't constitute an unacceptable ABI break? (In relation to #4477)

**Comment by jcmanke** [comment]
Another thing, #3248 made `SearchBar` another subclass of `InputView`, do we really want `ReturnType` for that?

**Comment by adammeaney** [comment]
Why would we want to have a return type on an Editor?

I am just asking for the use case for this? I can't imagine wanting my editors to ever do things besides add a new line in the editor or close it, potentially. Any other thing would just be weird for an editor.

**Comment by StephaneDelcroix** [comment]
@jcmanke moving a public property should be fine, as property accessors are invoked using `callvirt`. moving the actual BP (the field) is a breaking change. thanks for your sharps eyes.

**Comment by jcmanke** [comment]
@rmarinho The ImeAction is shown on Android when you have the phone in landscape.

Screenshot_1553180558

**Comment by samhouts** [comment]
I've seen a couple of comments here asking for a use case for ReturnType on Editor/SearchBar. Do we have an answer for that? Thanks!

**Comment by andreinitescu** [comment]
My initial goal was to fix crash issue, but since I was on it, I wanted to do a bit extra and surface the native feature to allow setting the return key for Editor just like Entry has it. No good deed goes unpunished 😆

**Comment by samhouts** [comment]
@andreinitescu Thank you for the work! Let's table this one for now, since we don't have a clear need for it. We appreciate the time you spent here!!!

**Pull request closed without merging**
