### PR TITLE
Fix hangs and NREs with Entry Observer

### LINKED ISSUE #14788: NsRangeException while leaving content page containing custom entry with Xamarin Forms (v5.0.0.2196)
### Description
While rendering the custom entry and leaving the page containing custom entry throws the following exception. This issue is breaking in Xamarin Forms version (v 5.0.0.2196). 

image

### Steps to Reproduce

1. Run the attached sample
2. Click on the open entry button
3. And followed by click on the back button. Application will crashes with NsRangeException

### Expected Behavior
Application should not crashes with No exception

### Actual Behavior
Crashes with NsRangeException exception.

### Basic Information

- Version with issue:
- NuGet Packages: 
Same scenario, working fine with Xamarin Forms version (v 5.0.0.2125).
Affected version : Xamarin Forms version (v 5.0.0.2196)
.
- Affected Devices: Xamarin IOS platform with iPad 8th Gen 14.3 stimulator

### Environment
Microsoft Visual Studio Professional 2019
Version 16.7.7
VisualStudio.16.Release/16.7.7+30621.155
Microsoft .NET Framework
Version 4.8.03752

Installed Version: Professional

Visual C++ 2019   00435-20310-61412-AA219
Microsoft Visual C++ 2019

ASP.NET and Web Tools 2019   16.7.532.28833
ASP.NET and Web Tools 2019

ASP.NET Core Razor Language Services   16.1.0.2035807+72d099b977d3a85e65fa3b0614ca8cfc803fef02
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2019   16.7.532.28833
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.7.532.28833
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   16.7.532.28833
Azure Functions and Web Jobs Tools

C# Tools   3.7.0-6.20514.1+600c0dadd199296df3ed07dfabdc014563a77f7c
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2019 - v2.9.30701.1

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.79+ge3567815aa.RR
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   16.7.5 (112c7bc)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   5.7.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

SQL Server Data Tools   16.0.62008.03130
Microsoft SQL Server Data Tools

Syncfusion Xamarin Project Templates   13.4.0.53
A multi-project template for building iOS, Android, and Windows apps using Syncfusion Xamarin components.

Syncfusion Xamarin Toolbox   16.2.0.19
Syncfusion Essential Studio for Xamarin Toolbox Visual Studio extension.

SyncfusionMenu Extension   1.0
SyncfusionMenu Visual Studio Extension Detailed Info

TypeScript Tools   16.0.20702.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.7.0-6.20514.1+600c0dadd199296df3ed07dfabdc014563a77f7c
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual C++ for Cross Platform Mobile Development (Android)   16.0.30309.115
Visual C++ for Cross Platform Mobile Development (Android)

Visual F# Tools 10.10.0.0 for F# 4.7   16.7.0-beta.20361.3+3ef6f0b514198c0bfa6c2c09fefe41a740b024d5
Microsoft Visual F# Tools 10.10.0.0 for F# 4.7

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions (Preview)   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Foo   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   16.7.000.463 (d16-7@5209782)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.7.0.495 (remotes/origin/d16-7@79c0c522c)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.7.85 (1bcbbdf)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   11.0.2.0 (d16-7/025fde9)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: 83105ba
    Java.Interop: xamarin/java.interop/d16-7@1f3388a
    ProGuard: Guardsquare/proguard/proguard6.2.2@ebe9000
    SQLite: xamarin/sqlite/3.32.1@1a3276b
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-7@017078f

Xamarin.iOS and Xamarin.Mac SDK   14.2.0.12 (e0ce49680)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

### Screenshots
image

### Reproduction Link

[PDFViewerApp (2).zip](https://github.com/xamarin/Xamarin.Forms/files/7409189/PDFViewerApp.2.zip)

### Workaround

No

### PR DESCRIPTION
**Pull request by jfversluis**
### Description of Change ###

The fix in #14828 caused, again, issues unfortunately. I have now taken the changes from Javier in #14790 which do seem to work better. Reverted the one commit and added Javiers fix.

### Issues Resolved ### 

- fixes #14788

### API Changes ###
 
 None

### Platforms Affected ### 

- iOS

### Behavioral/Visual Changes ###

None

### Before/After Screenshots ### 

Not applicable

### PR Checklist ###

- [x] Targets the correct branch
- [ ] Tests are passing (or failures are unrelated)

### CODE REVIEW

**Review by jsuarezruiz — APPROVED** [review]

**Comment by lee-m** [comment]
@jfversluis Does Javier's change actually fix the issue? In #14790 you commented 

> Seeing the response from @tylerjnettleton it doesn't seem to fix it, just waiting for them to confirm so we can move forward on the other fix.

Where the "other fix" is the change that has now been reverted in favour of those in #14790. What is a huge concern for me is the severity of this (bit of a showstopper for us) and that the description of why the crash occurs does not match what I'm seeing with my own code. 

It'd be a real pain to have to wait a month for SR8 for any follow on fixes for this.

**Comment by jfversluis** [comment]
@lee-m you're welcome to try out version 5.0.0.7816 on the PR feed and let me know :)

My fix was causing crashes/hangs in other areas, so clearly that wasn't the way as well

**Comment by lee-m** [comment]
@jfversluis I'll happily test out the PR NuGet but I won't be in a position to do this until tomorrow, unfortunately. Hopefully everything still works :)

**Comment by jfversluis** [comment]
No rush! Let me know how it goes! This one, among others, I have found a couple of things to iron out before creating the actual release. It will probably be early next week.

**Comment by lee-m** [comment]
@jfversluis Using 5.0.0.7816 on the PR feed also fixes the crash I'm seeing. I've still got no idea how given the explanation but it does so I must be missing something :)

Looking forward to getting my hands on this in SR7!

**Comment by jfversluis** [comment]
YES! That is great news. Thanks for working together on this @lee-m 

Be on the lookout for the new release!

**Pull request merged**
