### PR TITLE
[Android] Fixes TimePicker FontSize & FontFamily 

### LINKED ISSUE #2745: TimePicker ignores FontSize setting on android
### Description
the TimePicker view control ignores the FontSize property in android. ios behaviour is as expected.
### Steps to Reproduce

1. create a new Mobile App (Xamarin.Forms), named TimePickerTest, select Blank App and .NET Standard
2. In the MainPage.xaml paste the following code:

```xaml
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:local="clr-namespace:TimePickerTest"
             x:Class="TimePickerTest.MainPage">
    <StackLayout Orientation="Vertical">
        <TimePicker HorizontalOptions="Center" VerticalOptions="Center" FontSize="24"/>
        <TimePicker HorizontalOptions="Center" VerticalOptions="Center" FontSize="16"/>
        <TimePicker HorizontalOptions="Center" VerticalOptions="Center" />
        <DatePicker HorizontalOptions="Center" VerticalOptions="Center" FontSize="24"/>
        <DatePicker HorizontalOptions="Center" VerticalOptions="Center" FontSize="16"/>
        <DatePicker HorizontalOptions="Center" VerticalOptions="Center" />
    </StackLayout>
</ContentPage>
```

3. start the project with android

### Expected Behavior
the timepicker controls should have different font sizes.
the datepicker controls should have different font sizes.

### Actual Behavior
the timepicker controls have all the same font size.
the datepicker controls should have different font sizes.

### Basic Information

- Version with issue: Xamarin.Forms 3.0.0.482510
- Last known good version: -
- IDE: Visual Studio 2017 Community
- Platform Target Frameworks:
  - Android: 8.1
- Android Support Library Version: 27.0.3
- Affected Devices: emulator, acer iconia

### Screenshots

image

### PR DESCRIPTION
**Pull request by ravinderjangra**
### Description of Change ###
Fixes #2745

### Bugs Fixed ###
Fixes #2745

### PR Checklist ###

- [ ] Has tests (if omitted, state reason in description)
- [x] Rebased on top of the target branch at time of PR
- [x] Changes adhere to coding standard
- [x] Consolidate commits as makes sense

### CODE REVIEW

**Comment by StephaneDelcroix** [comment]
could you please rebase your fix on top of `3.1.0`, and retarget the PR ?

**Comment by ravinderjangra** [comment]
@StephaneDelcroix on rebase and retarget on 3.1.0 it is showing over 100 commits? 
It is an Issue?
Or should I just make a new PR to 3.1.0?

**Comment by StephaneDelcroix** [comment]
@ravinderjangra not merging 3.1.0 into your branch, but rebasing. let me guide you

the easiest way might be to reset your branch to the 3.1.0 head, and cherry-pick the fix
```
git co Picker //go to your branch
git reset --hard 3.1.0 //reset your branch to 3.1.0
git cherry-pick d5fc5d7e6dd4ab8ceca126876776a6dd07e63e40 //pick your commit
git push -f //push your branch
```

**Comment by ravinderjangra** [comment]
thanks @StephaneDelcroix for lesson & It's done.

**Comment by StephaneDelcroix** [comment]
👍

**Pull request merged**
