### PR TITLE
Fix PanGesture inside scroll issue https://github.com/xamarin/Xamarin…

### LINKED ISSUE #3840: Changing TranslationX/Y causes setting scrollView to initial position (0, 0)
Here is small reproduction code.
Try to pan this view and it set scroll view to 0.0 immediately

I've investigated a little
HandleScrolled is called but ContentOffset is (0,0) - i have no idea "Why?"

Tested on iOS simulator (iphone X)

```csharp
public class App : Application
	{
		public App()
		{

			var panGesture = new PanGestureRecognizer();

			var scroll = new ScrollView
			{
				GestureRecognizers = {
						panGesture
					},
				Content = new StackLayout
				{
					Children = {
							new BoxView { Color = Color.Red, HeightRequest = 500 },
							new BoxView { Color = Color.Gray, HeightRequest = 500 },
							new BoxView { Color = Color.Yellow, HeightRequest = 500 }
						}
				}
			};

			panGesture.PanUpdated += (sender, e) => {
				if(e.StatusType == GestureStatus.Running)
				{
					((View)sender).TranslationX = e.TotalX;
				}
			};

			var mainLayout = new AbsoluteLayout();
			mainLayout.Children.Add(scroll, new Rectangle(0, 0, 1, 1), AbsoluteLayoutFlags.All);

			MainPage = new ContentPage
			{
				Content = mainLayout
			};

			scroll.Scrolled += (sender, e) => {

			};

			MainPage.Appearing += (sender, e) => {
				scroll.ScrollToAsync(0, 300, true);
			};
		}
	}
```

### PR DESCRIPTION
**Pull request by AndreiMisiukevich**
fixes #3840
added private RetrieveElementContentSize method to ScrollViewRenderer for iOS
changed private OnNativeControlUpdated method: set content size directly
affected iOS

### CODE REVIEW

**Comment by PureWeen** [comment]
build --uitests

**Comment by PureWeen** [comment]
@AndreiMisiukevich  it looks like the UI test is failing for ios11  can you take a look?

**Comment by AndreiMisiukevich** [comment]
@PureWeen hmm, I think, yes.
Firstly I will try on iOS12, because all simulators are on this version now.

**Comment by AndreiMisiukevich** [comment]
@PureWeen could you please share details of iOS11 validation?
I'm not authorized to see the details of test.

**Comment by PureWeen** [comment]
@AndreiMisiukevich   oops :-/ that would have been an important detail
The failure is happening on ios11 from the test I added for the PR.

**Comment by AndreiMisiukevich** [comment]
@PureWeen hm, do you think, that it's something related to my changes?

**Comment by PureWeen** [comment]
build --uitests

**Comment by PureWeen** [comment]
@AndreiMisiukevich  it looks like the ios11 test runner is just having issues finding the button on the view :-/  I modified the UI test slightly so let's see if this next run goes through ok

**Comment by AndreiMisiukevich** [comment]
@PureWeen it's failed again =(

**Comment by PureWeen** [comment]
build --uitests

**Comment by PureWeen** [comment]
@AndreiMisiukevich  the iOS once did pass actually but they reported back to github incorrectly :-/
I'm rerunning the Android tests though as they don't look to have completed.

**Pull request merged**
