### PR TITLE
Adds a test scenario for another Previewer Markup Extension issue

### PR DESCRIPTION
**Pull request by TimBarham**
See #5473

### CODE REVIEW

**Comment by TimBarham** [comment]
FYI @alanmcgovern @drewgillies @samhouts

**Comment by StephaneDelcroix** [comment]
that's not a markup extension issue, but a type-finding one

**Comment by samhouts** [comment]
@TimBarham Can you verify for me that #5485 fixes the issue? Thanks!

**Comment by TimBarham** [comment]
@samhouts - @StephaneDelcroix's PR contains the same test case from this PR, so I'm confident it does.

**Pull request closed without merging**
