### PR TITLE
[Android] Fix bug : Frame outline color not rendering

### LINKED ISSUE #1347: [Android] Frame outline color not rendering
### Description
Migrated from https://bugzilla.xamarin.com/show_bug.cgi?id=27460

The original issue was that the color wouldn't appear unless padding was set. In my sample I don't see the color on Android at all. iOS renders as I'd expect.

screenshot 2017-12-07 08 14 26

### Steps to Reproduce

1. Create a Frame with an outline color.
2. Run and observe on Android the outline doesn't show the color.

### Expected Behavior
The outline should be the color I've chosen, regardless of padding.

### Actual Behavior
iOS renders as expected. Android outline isn't the chosen color, red.

### Basic Information

- Version with issue: 2.5.0.121934
- IDE: VS Mac
- Platform Target Frameworks: 
  - iOS:  11.1
  - Android: 7.1 running on 8.0 using FormsAppCompatActivity
- Android Support Library Version: 25.4.0.2

### Reproduction Link

[Archive.zip](https://github.com/xamarin/Xamarin.Forms/files/1539431/Archive.zip)

### PR DESCRIPTION
**Pull request by mohachouch**
### Description of Change ###

The original issue was that the color wouldn't appear unless padding was set. In my sample I don't see the color on Android at all. iOS renders as I'd expect.

This PR fix this issue

### Bugs Fixed ###

fixes #1347

### API Changes ###

None

### Behavioral Changes ###

None

### PR Checklist ###

- [ ] Has tests (if omitted, state reason in description)
- [ ] Rebased on top of master at time of PR
- [ ] Changes adhere to coding standard
- [ ] Consolidate commits as makes sense

### CODE REVIEW

**Comment by adrianknight89** [comment]
Does `_backgroundDrawable` need to be properly disposed?

**Comment by rmarinho** [comment]
I m not sure, but does Frame mess with elevation on Android? one of the problems with BackgroundDrawables is that with the Elevation API25, but could not be a problem..

**Comment by mohachouch** [comment]
I tried it on API 15 and API 25.

**Comment by jassmith** [comment]
Can you please include before and after screenshots? My cursory glance seems to indicate this would result in a noticeable visual change beyond the bug fix.

**Comment by mohachouch** [comment]
Sure @jassmith, bellow the screenshots : 

Before : 
before_fix

After fix:
after_fix

After fix with shadow:
after_fix_shadow

**Comment by rmarinho** [comment]
#1173

**Comment by kaushalyacs** [comment]
@jassmith When this change will be released?

**Pull request merged**
