### PR TITLE
gracefully handle null values in BindingExpression.TryConvert

### LINKED ISSUE #15381: [Bug] Crash with NullReferenceException in Xamarin.Forms.BindingExpression.TryConvert on iOS
### Description

We see iOS crashes with NullReferenceException in Xamarin.Forms.BindingExpression.TryConvert in our production reporting on a regular basis.

**Stacktrace:**

```plaintext
System.NullReferenceException: Object reference not set to an instance of an object
  at Xamarin.Forms.BindingExpression.TryConvert (System.Object& value, Xamarin.Forms.BindableProperty targetProperty, System.Type convertTo, System.Boolean toTarget) <0x1013fc370 + 0x000ac> in <2fe29b4d6c234e81aa144e4fab19c5e5#55def4f169c1257471695f92a55c1c15>:0
  at Xamarin.Forms.BindingExpression.ApplyCore (System.Object sourceObject, Xamarin.Forms.BindableObject target, Xamarin.Forms.BindableProperty property, System.Boolean fromTarget) <0x1014ae7a8 + 0x00373> in <2fe29b4d6c234e81aa144e4fab19c5e5#55def4f169c1257471695f92a55c1c15>:0
  at Xamarin.Forms.BindingExpression.Apply (System.Object sourceObject, Xamarin.Forms.BindableObject target, Xamarin.Forms.BindableProperty property) <0x1014ae534 + 0x00117> in <2fe29b4d6c234e81aa144e4fab19c5e5#55def4f169c1257471695f92a55c1c15>:0
  at Xamarin.Forms.Binding.Apply (System.Object context, Xamarin.Forms.BindableObject bindObj, Xamarin.Forms.BindableProperty targetProperty, System.Boolean fromBindingContextChanged) <0x1014abde4 + 0x0010b> in <2fe29b4d6c234e81aa144e4fab19c5e5#55def4f169c1257471695f92a55c1c15>:0
  at Xamarin.Forms.BindableObject.ApplyBindings (System.Boolean skipBindingContext, System.Boolean fromBindingContextChanged) <0x1014a67c4 + 0x000d3> in <2fe29b4d6c234e81aa144e4fab19c5e5#55def4f169c1257471695f92a55c1c15>:0
  at Xamarin.Forms.Element.OnChildAdded (Xamarin.Forms.Element child) <0x1014dd708 + 0x00063> in <2fe29b4d6c234e81aa144e4fab19c5e5#55def4f169c1257471695f92a55c1c15>:0
  at Xamarin.Forms.VisualElement.OnChildAdded (Xamarin.Forms.Element child) <0x1015bd644 + 0x0002f> in <2fe29b4d6c234e81aa144e4fab19c5e5#55def4f169c1257471695f92a55c1c15>:0
  at Xamarin.Forms.Layout.OnInternalAdded (Xamarin.Forms.View view) <0x10151a5c0 + 0x00097> in <2fe29b4d6c234e81aa144e4fab19c5e5#55def4f169c1257471695f92a55c1c15>:0
  at Xamarin.Forms.Layout.InternalChildrenOnCollectionChanged (System.Object sender, System.Collections.Specialized.NotifyCollectionChangedEventArgs e) <0x10151a3cc + 0x00163> in <2fe29b4d6c234e81aa144e4fab19c5e5#55def4f169c1257471695f92a55c1c15>:0
  at System.Collections.ObjectModel.ObservableCollection`1[T].OnCollectionChanged (System.Collections.Specialized.NotifyCollectionChangedEventArgs e) <0x101a6fdbc + 0x0004f> in <5d6e75c514094a0784a0885f6eeb75ed#55def4f169c1257471695f92a55c1c15>:0
  at System.Collections.ObjectModel.ObservableCollection`1[T].OnCollectionChanged (System.Collections.Specialized.NotifyCollectionChangedAction action, System.Object item, System.Int32 index) <0x101a7004c + 0x0007b> in <5d6e75c514094a0784a0885f6eeb75ed#55def4f169c1257471695f92a55c1c15>:0
  at System.Collections.ObjectModel.ObservableCollection`1[T].InsertItem (System.Int32 index, T item) <0x101a6f9a8 + 0x00057> in <5d6e75c514094a0784a0885f6eeb75ed#55def4f169c1257471695f92a55c1c15>:0
  at System.Collections.ObjectModel.Collection`1[T].Add (T item) <0x1012c4d7c + 0x0009f> in <25bf495f7d6b4944aa395b3ab5293479#55def4f169c1257471695f92a55c1c15>:0
  at Xamarin.Forms.TemplateUtilities.OnContentChanged (Xamarin.Forms.BindableObject bindable, System.Object oldValue, System.Object newValue) <0x1015acbc8 + 0x001e7> in <2fe29b4d6c234e81aa144e4fab19c5e5#55def4f169c1257471695f92a55c1c15>:0
  at Xamarin.Forms.BindableObject.SetValueActual (Xamarin.Forms.BindableProperty property, Xamarin.Forms.BindableObject+BindablePropertyContext context, System.Object value, System.Boolean currentlyApplying, Xamarin.Forms.Internals.SetValueFlags attributes, System.Boolean silent) <0x1014a6574 + 0x001e3> in <2fe29b4d6c234e81aa144e4fab19c5e5#55def4f169c1257471695f92a55c1c15>:0
  at Xamarin.Forms.BindableObject.SetValueCore (Xamarin.Forms.BindableProperty property, System.Object value, Xamarin.Forms.Internals.SetValueFlags attributes, Xamarin.Forms.BindableObject+SetValuePrivateFlags privateAttributes) <0x1014a6134 + 0x0020b> in <2fe29b4d6c234e81aa144e4fab19c5e5#55def4f169c1257471695f92a55c1c15>:0
  at Xamarin.Forms.BindingExpression.ApplyCore (System.Object sourceObject, Xamarin.Forms.BindableObject target, Xamarin.Forms.BindableProperty property, System.Boolean fromTarget) <0x1014ae7a8 + 0x00467> in <2fe29b4d6c234e81aa144e4fab19c5e5#55def4f169c1257471695f92a55c1c15>:0
  at Xamarin.Forms.BindingExpression.Apply (System.Boolean fromTarget) <0x1014ae488 + 0x0006f> in <2fe29b4d6c234e81aa144e4fab19c5e5#55def4f169c1257471695f92a55c1c15>:0
  at Xamarin.Forms.BindingExpression+BindingExpressionPart.<PropertyChanged>b__49_0 () <0x1014b1abc + 0x00017> in <2fe29b4d6c234e81aa144e4fab19c5e5#55def4f169c1257471695f92a55c1c15>:0
  at Foundation.NSAsyncActionDispatcher.Apply () <0x102139184 + 0x00027> in <5b08e01cb6df409eb2fea153e6177e5d#55def4f169c1257471695f92a55c1c15>:0
  at (wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
  at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) <0x10216a774 + 0x00063> in <5b08e01cb6df409eb2fea153e6177e5d#55def4f169c1257471695f92a55c1c15>:0
  at Sepp.Mobile.iOS.Application.Main (System.String[] args) <0x100f3a8b8 + 0x00033> in <7d8fcb42deff4618a06b1d050978b187#55def4f169c1257471695f92a55c1c15>:0
```

**Analysis:**

Our analysis of the issue revealed, that the only possible origin of such an exception is to have `convertTo` with value `null`. The only possible origin of `null` for this case, is to have `BindingExpression.SetterType` assigned to `null` (or not assigned at all).

We suggest to check for `null` in `TryConvert`, and to return `false` for that case.

### Steps to Reproduce

Unfortunately none.

### Expected Behavior

No crash.

### Actual Behavior

Crash

### Basic Information

- Version with issue: 5.0.0.2401
- Last known good version: -
- Platform Target Frameworks: 
  - iOS:  15
- Affected Devices: iPhones, iPads, ...

### PR DESCRIPTION
**Pull request by thisisthekap**
### Description of Change ###

Added null handling to BindingExpression.TryConvert to mitigate an `NullReferenceException` which thereafter leads to app crash in production.

### Issues Resolved ### 

- fixes #15381

### API Changes ###

None

### Platforms Affected ### 

- Core/XAML (all platforms)

### Behavioral/Visual Changes ###

None

### Before/After Screenshots ### 

Not applicable

### Testing Procedure ###

None

### PR Checklist ###

- [ ] Targets the correct branch
- [ ] Tests are passing (or failures are unrelated)

### CODE REVIEW

**Comment by jfversluis** [comment]
Hey @thisisthekap thanks for this PR! I'm kind of on the fence about this one. I see how this makes sense, on the other hand you might want to include that null check earlier in your own code?

But even more so, this is technically a breaking change since this changes the behavior of how it has always worked.

**Review by StephaneDelcroix — APPROVED** [review]
as it only happens from time to time in prod, and you can't reproduce, I can't say if the attempted fix will solve your problem, or if you won't have another issue later on. but the fix is safe, I don't see any reasons not to merge it

**Comment by jfversluis** [comment]
Verified on our non-public pipeline that this builds

**Pull request merged**
