### PR TITLE
[Android] Update Android X packages

### LINKED ISSUE #12504: [Enhancement] Upgrade for Xamarin.Forms maps
Hi, I see that the latest version of Xamarin.Forms maps is still dependent of Xamarin.Android.Support.v4. When can we expect the upgrade for AndroidX (without support libraries)? 

Additional: This is causing androidX issue when combined with one of our native libraries that is using AndroidX.
Thanks!
image

### PR DESCRIPTION
**Pull request by rmarinho**
### Description of Change ###

Update packages and make sure everything builds fine with Android 30 API

### Issues Resolved ### 

fixes #12504 

### API Changes ###

 
 None

### Platforms Affected ### 

- Android

### Behavioral/Visual Changes ###

None

### Before/After Screenshots ### 

Not applicable

### PR Checklist ###

- [ ] Targets the correct branch
- [ ] Tests are passing (or failures are unrelated)

### CODE REVIEW

**Comment by VladislavAntonyuk** [comment]
With Android 11 make sure you added ```<EmbedAssembliesIntoApk>true</EmbedAssembliesIntoApk>``` into csproj file, otherwise you will get runtime errors: More description with examples: https://github.com/xamarin/Essentials/issues/1391

**Comment by mattleibow** [comment]
@VladislavAntonyuk  I had a chat with the Android team and the issue is that Android 11 decided not to work as it always has. As a result, the fastdev support is broken, right now, but is actually fixed again in an upcoming preview of VS 16.9 Preview 1. I am not sure of the timeline for that exactly, but for now you can disable the fastdev by adding `<EmbedAssembliesIntoApk>true</EmbedAssembliesIntoApk>` or unchecking the "Use Fast Deployment" box in VS:

image

Thanks for the comments and research!

**Comment by rmarinho** [comment]
the tests are actually failing but not related

**Comment by rmarinho** [comment]
Failing tests not related.

**Comment by mattleibow** [comment]
It looks OK as is, but not sure if we want to wait for this: https://github.com/xamarin/AndroidX/pull/193

**Review by PureWeen — APPROVED** [review]
Looks good!

I removed the Support Library package references from the Android ControlGallery and the Android Platform unit tests as well

**Pull request merged**
