### PR TITLE
[Android] Ability to skip adding status bar underlay

### PR DESCRIPTION
**Pull request by adrianknight89**
### Description of Change ###

AppCompat adds status bar underlay when the top-level layout is being constructed, and there is no way to skip this process. When `AdjustResize` is used, we end up with a status bar that has no background color AND the underlay below it.

Also changed variable and method names for retrieving status bar height to status bar underlay height to avoid confusion when previously-named `GetStatusBarHeight()` starts returning zero. Moved API >= 21 checks into the method to simplify callers.

Not sure how to add this test code since it's changing `MainPage`: https://gist.github.com/adrianknight89/e35d769961fc367edad9d19ca73b0679

### Bugs Fixed ###

- https://bugzilla.xamarin.com/show_bug.cgi?id=47548

### API Changes ###

Added:
 - protected bool ShouldAddStatusBarUnderlay = true;

### PR Checklist ###

- [x] Has tests (if omitted, state reason in description)
- [x] Rebased on top of master at time of PR
- [x] Changes adhere to coding standard
- [x] Consolidate commits as makes sense

### CODE REVIEW

**Comment by adrianknight89** [comment]
Note that IMO the underlay should go away and we shouldn't need to use a property to turn it off. `MasterDetailPage` should be improved upon so that it doesn't use a hack.

**Comment by adrianknight89** [comment]
@hartez Can we get some attention to this? See the blank space at the top for `Resize`.

pan-resize-large

**Comment by TadasNorbutas** [comment]
Hello,

this problem is killing everybody who wants to do MasterDetailPage!

Please fix it!

Thanks
Tadas

**Comment by hartez** [comment]
This is on my radar; I'm out next week but I'll be reviewing it on the 1st.

**Comment by hartez** [comment]
> Note that IMO the underlay should go away and we shouldn't need to use a property to turn it off. MasterDetailPage should be improved upon so that it doesn't use a hack.

Agreed. I've just submitted a [PR to remove it entirely](https://github.com/xamarin/Xamarin.Forms/pull/892).

**Pull request closed without merging**
