### PR TITLE
[toolbox] add tooltip to toolbox items

### PR DESCRIPTION
**Pull request by StephaneDelcroix**
### Description of Change ###

add tooltips and uri to toolbox items

NOTE: this bumps the xml file version !

### Issues Resolved ###

- implements user story 660445

### PR Checklist ###

- [ ] Has automated tests 
- [x] Rebased on top of the target branch at time of PR
- [x] Changes adhere to coding standard

### CODE REVIEW

**Comment by alanmcgovern** [comment]
Just marking this as 'do not merge' until we have translations in place!

**Comment by alanmcgovern** [comment]
We need to finalize the spec before we implement it too! That part is still in progress :) /cc @maddyleger1

**Comment by StephaneDelcroix** [comment]
> We need to finalize the spec before we implement it too! That part is still in progress :)
@alanmcgovern @maddyleger1: ping me when you're done

**Comment by samhouts** [comment]
@alanmcgovern @maddyleger1 Any update on this? Thanks!

**Comment by alanmcgovern** [comment]
The most recent update I'm aware of was a few months ago - I believe the plan of action at the time was to reword a bunch of the tooltips to make them use consistent terminology.

Apart from that we never solved the problem of localizations, so that is a blocker for this feature too.

**Comment by maddyleger1** [comment]
The wording on here was consistent with what the docs team said is good - I can give them a once over just to double check! Who should be the person solving localization?

Sam - thanks for following up :)

**Comment by alanmcgovern** [comment]
Future work on this will have to be scheduled on a sprint and prioritised against the rest of our deliverables. Please file it against us if that's not already the case and we'll do so!

**Comment by samhouts** [comment]
I'll go ahead and close this until we're ready for scheduling. Thanks!!

**Pull request closed without merging**
