### PR TITLE
Prevent FocusSearch from focusing disabled element

### PR DESCRIPTION
**Pull request by KyNam**
### API Changes ###

 None

### Platforms Affected ### 

- Core/XAML (all platforms)

### Behavioral/Visual Changes ###

Prevent FocusSearch from focusing disabled element when pressing Tab key.

### PR Checklist ###

- [ ] Targets the correct branch
- [ ] Tests are passing (or failures are unrelated)

### CODE REVIEW

**Comment by KyNam** [comment]
I am trying to display modal dialog (in MacOS) without creating a separate window.
Currently, pressing Tab key while focusing a control in the modal dialog will move focus outside dialog.

Possible workarounds are hiding views, disabling all child views, or setting IsTabStop of all child views to false.
Hiding views or disabling all child views affect appearance.
Setting IsTabStop is complicated because of the need of tracking changed views.

If FocusSearch ignore all child views of disabled parent view, I can just disable a few views instead of most of views in page.

**Comment by rmarinho** [comment]
Can you please add a sample so we can test the issue? Thanks

**Comment by KyNam** [comment]
I want pressing Tab while focusing a Entry in **StackLayout x:Name="Dialog"** does not focus Entries in **StackLayout IsEnabled="False"**


<ContentPage
    x:Class="App1.MainPage"
    xmlns="http://xamarin.com/schemas/2014/forms"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml">

    <Grid>

        <StackLayout
            IsEnabled="False"
            Orientation="Vertical">
            <Entry WidthRequest="100" />
            <Entry WidthRequest="100" />
            <Entry WidthRequest="100" />
        </StackLayout>

        <Grid x:Name="DialogContainer"
            BackgroundColor="#80000000"
            InputTransparent="False">

            <StackLayout x:Name="Dialog"
                Padding="10"
                VerticalOptions="Center"
                BackgroundColor="White"
                Orientation="Vertical">
                <Entry WidthRequest="100" />
                <Entry WidthRequest="100" />
                <Entry WidthRequest="100" />
            </StackLayout>

        </Grid>

    </Grid>

</ContentPage>

**Review by jsuarezruiz — CHANGES_REQUESTED** [review]
Could you include a sample in the Gallery (and an UITest would be awesome) to validate the changes?. Thanks!

**Comment by KyNam** [comment]
I am sorry I no longer use the official Xamarin Forms.
I modified Xamarin Forms and completely rewrote Mac OS render architect / renderers for my projects. I use just one native view per Xamarin Forms visual element.
Regards "Focusing", I removed Xamarin Forms's "tab to focus" and let Mac OS to handle Tab / Shift Tab.
I added a service to lock keyboard focus within a Xamarin Forms visual element, I use it for my custom "flyout", "dialog".

**Comment by jfversluis** [comment]
Thank you so much for your time and effort on this. Too bad it didn't work out.

**Pull request closed without merging**
