### PR TITLE
[GH-6220 and GH-3083] - Label visibility for Shell and TabbedPage

### LINKED ISSUE #3083: [Enhancement] Implement fixed mode for Bottom Navigation Bar Android
### Description
Currently if you add more then 3 icons to the bottom tab bar on android it will use an animated shifting mode to display all the tabs.  

Support libraries v28 surface a new setting on BottomNavigationView 
LabelVisibilityMode

Once we take a dependency on v28 with forms then we should surface that enumeration for the platform specifics.

### API Changes

Add an android platform specific api for
```C#
public enum BottomToolBarLabelVisibilityMode
{
      Default;
      Auto ;
      Labeled 
      Selected 
      Unlabeled 
}
SetBottomToolBarLabelVisibilityMode(BottomToolBarLabelVisibilityMode labelVisibilityMode)
SetBottomToolBarItemHorizontalTranslationEnabled(bool)
```
When implementing these settings make sure to just ignore these if they haven't been set and to retain the default if changed

### Notes
https://github.com/xamarin/Xamarin.Forms/issues/1675#issuecomment-394419356
https://montemagno.com/remove-shifting-bottomnavigationview-android/

### LINKED ISSUE #6220: [Enhancement][Shell] Icon only Shell Bottom Tab Bar.
## Summary
Should provide a xaml attribute, e.g. DisplayTextOnly, in Shell/TabBar top and bottom. To either display button text or not. The height of Tab Bar should be changed accordingly.

## Current behavior
We can set Tab text to empty, but no text in flyout menu, and height of bottom Tab bar not changed, some space below Icon

### PR DESCRIPTION
**Pull request by pictos**
## Description of Change ###

Added an Attached property for Shell and a Platform Specific for TabbedPage to handle with the Label Visibility for bottom tabs.

### Issues Resolved ### 

- fixes #6220 
- fixes #3083 

### API Changes ###

Added:
 - void TabbedPage.SetBottomToolBarLabelVisibilityMode(BindableObject element, BottomToolBarLabelVisibilityMode value);
 - BottomToolBarLabelVisibilityMode TabbedPage.GetBottomToolBarLabelVisibilityMode(BindableObject element);
 - BottomToolBarLabelVisibilityMode Shell.GetBottomToolBarLabelVisibilityMode(BindableObject element);
- void Shell.SetBottomToolBarLabelVisibilityMode(BindableObject element, object value);
- BottomToolBarLabelVisibilityMode BottomToolBarLabelVisibilityModeProperty {get; set;} // Bindable Property

### Platforms Affected ### 

- Core/XAML (all platforms)
- Android

### Behavioral/Visual Changes ###
Now when the dev creates a bottom tab without title, the Android resizes the area to fit.

### Before/After Screenshots ### 

*Before*
Before

*After*
After

### PR Checklist ###

- [ ] Targets the correct branch
- [ ] Tests are passing (or failures are unrelated)

### CODE REVIEW

**Comment by rmarinho** [comment]
I think it doesnt "look" good, shouldn't the Icon be centered ? 

Also why would we want this only on Android?  
Can you explain better the enum `BottomToolBarLabelVisibilityMode`

**Comment by pictos** [comment]
@rmarinho I updated the screenshots, I'm sorry for that.

> Also why would we want this only on Android?

Because this is a platform-specific feature for Android. I tried to access the PlatformSpecific feature from Shell, but a couldn't. As I discussed with @PureWeen, for now in Shell will be an Attached Property. You can see the discussion [here](https://github.com/xamarin/Xamarin.Forms/issues/3083#issuecomment-617465780)

> Can you explain better the enum BottomToolBarLabelVisibilityMode

This enum is a Core version off the Android's enum for this feature. This enum controls the behavior of the bottom tab, so for example, if you have a Tab just with icon, you don't need the space for the Title, that way you can use the LabelVisibilityMode = Unlabeled. In the screenshot, now you can see that before the icon is miss alignment for another, and the second one both icons are alignment.

Any question feel free to ask, I'll answer it at the end of the day (Brazil time).

**Comment by samhouts** [comment]
@pictos Should we move this to the XCT?

**Comment by pictos** [comment]
I'm ok with that, @PureWeen are you ok?

**Comment by jfversluis** [comment]
Either move to the Toolkit or target for .NET MAUI, not adding it to Forms at least :( thanks for all your time and effort here @pictos <3

**Pull request closed without merging**
