### PR TITLE
Add fake Platform property to Page to keep Previewer happy

### LINKED ISSUE #4351: Previewer broken with latest Xamarin.Forms master builds
We have removed iPlatform in a PR and we think we broke the Forms Previewer.
This PR removed it: https://github.com/xamarin/Xamarin.Forms/pull/4235

To Reproduce: 
You can try a nightly package 3.5.0.987565-nightly from MyGet feed  and try run the previewer.

Logs :
```
[2018-11-07 22:08:55.5] ERROR: : AndroidXamlRenderer had a rendering error: System.NullReferenceException: Object reference not set to an instance of an object
Xamarin.Forms.Previewer.XamarinFormsLoader.SetPlatform (System.Object page)
Xamarin.Forms.Previewer.XamarinFormsLoader.LoadFromXaml (MonoTouch.Design.XamlRenderContext context)
AndroidFormsRendering.XFPageRendererView.Initialize (System.Int32 contentId)

[2018-11-07 22:08:55.5] ERROR: : The renderer encountered an error while rendering this file: System.NullReferenceException: Object reference not set to an instance of an object
Xamarin.Forms.Previewer.XamarinFormsLoader.SetPlatform (System.Object page)
Xamarin.Forms.Previewer.XamarinFormsLoader.LoadFromXaml (MonoTouch.Design.XamlRenderContext context)
AndroidFormsRendering.XFPageRendererView.Initialize (System.Int32 contentId)
```

```
2018-11-07 22:29:45.2] INFO: Reloading: Server rendering completed in 19ms
[2018-11-07 22:29:45.2] ERROR: : iOSXamlRenderer had a rendering error: System.NullReferenceException: Object reference not set to an instance of an object
Xamarin.Forms.Previewer.XamarinFormsLoader.SetPlatform (System.Object page) in /Users/vsts/agent/2.141.1/work/1/s/Xamarin.Designer.iOS/MonoTouch.Design.Server/XamlViewer/XamarinFormsLoader.cs:217
Xamarin.Forms.Previewer.XamarinFormsLoader.LoadFromXaml (MonoTouch.Design.XamlRenderContext context) in /Users/vsts/agent/2.141.1/work/1/s/Xamarin.Designer.iOS/MonoTouch.Design.Server/XamlViewer/XamarinFormsLoader.cs:255
MonoTouch.Design.Server.XamlToPng.RenderOneXaml (MonoTouch.Design.XamlRenderContext context, MonoTouch.Design.XamlFormFactor formFactor) in /Users/vsts/agent/2.141.1/work/1/s/Xamarin.Designer.iOS/MonoTouch.Design.Server/XamlViewer/XamlToPng.cs:64
```

> VS bug [#725896](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/725896)

### PR DESCRIPTION
**Pull request by hartez**
### Description of Change ###

Forms Elements used to have an internal API property `Platform` which needed to be set on each Element. That property is no longer needed and has been removed. But the Previewer still sets that property via reflection, which now causes a NullReferenceException.

This change creates a dummy property for the Previewer to set, avoiding the NRE. 

### Issues Resolved ### 

- fixes #4351

### API Changes ###
 
 None

### Platforms Affected ### 

None

### Behavioral/Visual Changes ###

None

### Before/After Screenshots ### 

Not applicable

### Testing Procedure ###

Open the previewer.

### CODE REVIEW

**Comment by hartez** [comment]
The relevant Previewer method: https://github.com/xamarin/designer/blob/master/Xamarin.Designer.iOS/MonoTouch.Design.Server/XamlViewer/XamarinFormsLoader.cs#L214

**Comment by alanmcgovern** [comment]
We can't remove it from the codebase as it'd break support for all previous versions of Xamarin.Forms :)

**Comment by StephaneDelcroix** [comment]
@alanmcgovern you can remove it for anything newer than 3.4

**Comment by rmarinho** [comment]
I think the unitest is a great idea. can we add one @hartez since we remove setting the platform on the unit tests  ?

**Comment by alanmcgovern** [comment]
We still cannot remove it from Xamarin.Forms as then anyone who upgrades their X.F without upgrading their IDE will have an (unnecessarily) broken experience :)

**Comment by hartez** [comment]
> I think the unitest is a great idea. can we add one @hartez since we remove setting the platform on the unit tests ?

Working on adding tests for all the reflection stuff now.

**Pull request merged**
