### PR TITLE
[UWP] BoxView using default BackgroundColor and GestureRecognizers

### LINKED ISSUE #12755: [UWP] BoxView gestures not being recognised when BackgroundColor set to Default
### Description
When setting the background colour on a boxview to Default, tap gestures are no longer recognised

### Steps to Reproduce
With attached test project:
1. Run the sample project
2. Click the pink BoxView  which should show an alert.
3. Click the button to toggle the colour to Default. 
4. Click the BoxView again - the alert no longer shows. 

Without attached test project:
1. Add a BoxView to a view with a tap gesture recognizer
2. Set the BoxView background to default
3. Gesture is not recognised.

### Expected Behavior
Gesture should be recognised when then the background is set to Default. 

### Actual Behavior
Gesture is not recognised when then the background is set to Default. 

### Basic Information
This seems to be related to the changes around BoxViewRenderer being replaced with BoxViewBorderRenderer https://github.com/yurkinh/Xamarin.Forms/commit/f77047164439e233b399741e81717cb789f861ff#diff-2b073de552e7a39143ac9c03fb7f28420cabf7c939984efb99656e0d1c3785d2

When BackgroundColor is set to Default on UWP the Control's Background property is being set to null which is not the previous behaviour. 

- Version with issue:
- Last known good version: 4.5.0.7.25
- IDE:
- Platform Target Frameworks: 
  - UWP:   16299

### Reproduction Link
[BoxViewRendererTestApp.zip](https://github.com/xamarin/Xamarin.Forms/files/5500677/BoxViewRendererTestApp.zip)

### PR DESCRIPTION
**Pull request by jsuarezruiz**
### Description of Change ###

This PR include changes to allow the `BoxView` gestures being recognized when BackgroundColor set to Default.
 
### Issues Resolved ### 

- fixes #12755 

### API Changes ###
 
 None

### Platforms Affected ### 

- UWP

### Behavioral/Visual Changes ###

None

### Before/After Screenshots ### 

fix12755

### Testing Procedure ###
Launch Core Gallery and navigate to the issue 12755. Press the Button and then tap the BoxView that has just changed color. If a dialog appears, the test has passed.

### PR Checklist ###

- [ ] Targets the correct branch
- [ ] Tests are passing (or failures are unrelated)

### CODE REVIEW

**Comment by jsuarezruiz** [comment]
Team, could we include this requested fix in the upcoming Release?

**Comment by rachelkang** [comment]
hmm I see the dialog but not the color change

image

**Comment by jfversluis** [comment]
Not sure if this fix is still correct and seeing where we are in the Xamarin lifecycle, we probably won't be merging this anymore

**Pull request closed without merging**
