### PR TITLE
[iOS] Scroll locked issue using SwipeView

### LINKED ISSUE #12518: [Bug] SwipeView is too sensitive - opens when scrolling
Hi.

Issue one: SwipeView is great. I use it for deleting chat messages and leaving chat rooms, by the user swiping left on a message or a chat. However, there seems to be absolutely no threshold for the swipe to happen, as it constantly opens whenever I scroll the list of chat messages or chat rooms. It is almost impossible to swipe perfectly vertically, so any even absolutely slight horizontal movement opens the swipe menu. The threshold value should be at least equal to a tap gesture recognisers default threshold value (and preferably scriptable) - because currently both a tap and swipe start open overlap.

This might sound like a small thing, but it completely breaks the experience as almost every scroll opens the swipe menu.

I think this would be a small fix that would make it immensely more usable so I am eagerly awaiting a fix for it.

Tested with latest XF 5 pre-release on iOS. I used the SwipeView in a bindable stack layout, enclosed in a scroll view.

Thank you.

### PR DESCRIPTION
**Pull request by jsuarezruiz**
### Description of Change ###

The issue 12518 describes different issues. This PR apply some changes to fix the more critical issue, always  allow the scroll while not swiping in the SwipeView

### Issues Resolved ### 

- fixes #12518 

### API Changes ###

 None

### Platforms Affected ### 

- iOS

### Behavioral/Visual Changes ###

None

### Before/After Screenshots ### 

Not applicable

### Testing Procedure ###
Launch Core Gallery and navigate to the issue 12518. Start swiping horizontally swipe half long of the screen width). Then, keep your finger pressed on the swiped item, start scrolling up and down and release your finger. If you can scroll vertically, the test has passed.

### PR Checklist ###

- [ ] Targets the correct branch
- [ ] Tests are passing (or failures are unrelated)

### CODE REVIEW

**Comment by jsuarezruiz** [comment]
Changes in the SwipeView when used with collections:
- If you are scrolling the collection (ListView, CollectionView etc), cannot open the SwipeView. This avoids erroneous parcial opening errors.
- If you are doing a swipe in the SwipeView, to facilitate the opening, the collection scroll is disabled until the swipe is finished (opening or closing it).

**Comment by FrankSzendzielarz** [comment]
when is this getting merged in? app due to beta test soon and still waiting for fix for scroll-lock with collectionview of swipeviews

**Comment by F-Goncalves** [comment]
This PR is open for more than 4 months now, although it seems to be the fix to an issue that makes the SwipeView unusable in CollectionViews. Why is nothing happening here?

**Comment by jsuarezruiz** [comment]
Team, could we include this requested fix in the upcoming Release?

**Comment by rachelkang** [comment]
@jsuarezruiz I'm having issues building this branch :/

/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/iOS/Xamarin.Shared.targets(3,3): Error MSB4062: The "Xamarin.MacDev.Tasks.GetDirectories" task could not be loaded from the assembly /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/iOS/../iOS/Xamarin.iOS.Tasks.dll.  Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. (MSB4062) (Xamarin.Forms.ControlGallery.iOS)

**Review by jfversluis — APPROVED** [review]

**Pull request merged**
