### PR TITLE
[iOS] Fixes for null check for Shell classes

### PR DESCRIPTION
**Pull request by KSemenenko**
### Description of Change ###
**Several fixes for null checks:**
_ShellContent.cs_ - extra null check
_ShellItem.cs_ - added a check for null, as in the previous parameter.
_ShellSection.cs_ - extra null check
_ShellUriHandler.cs_ - added a check for null, as in the previous code block.
_ShellSectionRenderer.cs_ - added a check for null, as in the previous code block.
_TemplatedCell.cs_ - added a check for null

### API Changes ###
 None

### Platforms Affected ### 

- Core/XAML (all platforms)
- iOS
- Android
- UWP

### Behavioral/Visual Changes ###

None

### PR Checklist ###

- [x] Targets the correct branch
- [x] Tests are passing (or failures are unrelated)

### CODE REVIEW

**Comment by kvpt** [comment]
@KSemenenko Good things, as Murphy's Law, NullReferenceException always end up happening if possible. So prevent them as soon as possible.

I just have a little remark, the "**is**" operator/expression prevent null, so two of your null checks are useless.

**Comment by KSemenenko** [comment]
Hi @kvpt that's why I removed the checks for null in the if-is block.

**Comment by rmarinho** [comment]
@KSemenenko can you rebase on master so I can run tests again? thanks

**Comment by KSemenenko** [comment]
@rmarinho done

**Pull request merged**
