### PR TITLE
[Evolution] Add RetainsRenderer option for page, improve page performance

### PR DESCRIPTION
**Pull request by huangjinshe**
### Description of Change ###

The feature based on [ACCEPTED - Configurable retention of ContentPage renderers](https://forums.xamarin.com/discussion/84504/accepted-configurable-retention-of-contentpage-renderers), I've had update my old code from [Pull634](https://github.com/xamarin/Xamarin.Forms/pull/634).

Currently I  improve performance only for UWP, improve performance of page types: 
`ContentPage`, `NavigationPage`, `MasterDetailPage` in these situations:
```

App.MainPage = page;
Navigation.Push(page);
MasterDetailPage.Detail = page;

```

I need other developers help add other platform or other page types.

**API Changes**

Added:

`RetainsRendererExtentions` class in `Xamarin.Forms.Core`:

```
namespace Xamarin.Forms
{
    public static class RetainsRendererExtentions
    {
        public static Xamarin.Forms.Page SetRetainsRendererValue(this Xamarin.Forms.Page page, bool value)
        {
            SetRetainsRenderer(page, value);
            return page;
        }

        public static bool GetRetainsRendererValue(this Xamarin.Forms.Page page)
        {
            return GetRetainsRenderer(page);
        }


        public static readonly BindableProperty RetainsRendererProperty = BindableProperty.CreateAttached("RetainsRenderer", typeof(bool), typeof(RetainsRendererExtentions), false);

        public static bool GetRetainsRenderer(BindableObject view)
        {
            return (bool)view.GetValue(RetainsRendererExtentions.RetainsRendererProperty);
        }

        public static void SetRetainsRenderer(BindableObject view, bool value)
        {
            view.SetValue(RetainsRendererExtentions.RetainsRendererProperty, value);
        }
    }

}

```

For access or change it in code:
```
anyPage.SetRetainsRendererValue(true);
bool value = anypage.GetRetainsRendererValue();
```

For access or change it in XAML:
`
xmlns:forms="clr-namespace:Xamarin.Forms;assembly=Xamarin.Forms.Core" forms:RetainsRendererExtentions.RetainsRenderer="False"
`

```



### PR Checklist ###

- [ ] Has tests (if omitted, state reason in description)
- [ ] Rebased on top of master at time of PR
- [ ] Changes adhere to coding standard
- [ ] Consolidate commits as makes sense

### CODE REVIEW

**Comment by rmarinho** [comment]
Hi @huangjinshe we are now ready to go ahead with this feature. do you mind rebase with master so we can run UITests ? 

Thanks

**Comment by huangjinshe** [comment]
Hi @rmarinho , I'm really sorry I'm too much busy for another business right now, also after this half year I don't know what is going on in Xamarin of UWP version, could you guys let some Xamarin developer do this job please? he could contact with me any time for any discussion.

**Comment by huangjinshe** [comment]
I think currently there will be too much conflicting files, I worry if don't take some times to merge and check, It will affect other future.

**Comment by pauldipietro** [comment]
We'll revisit this PR when we can assign someone from the Forms team.

**Comment by huangjinshe** [comment]
@pauldipietro .Sure, but I think this is a huge performance problem, I hope you guys more serious on it.

**Comment by maxim-saplin** [comment]
JIC, Retain Renderers feature would be much appreciated.

**Comment by huangjinshe** [comment]
@maxim-saplin  you could discuss it with us in here: #9788

**Pull request closed without merging**
