### PR TITLE
[UWP] Center Image when Aspect is Aspect.Fit (Bug 58987)

### PR DESCRIPTION
**Pull request by jgold6**
### Description of Change ###

Added Aspect.AspectFit to the aspect ratios that will center the image in the containing view.

### Bugs Fixed ###

https://bugzilla.xamarin.com/show_bug.cgi?id=58987

### API Changes ###

Changed:
 - Xamarin.Forms.Platform.UWP.ImageRenderer.UpdateAspect 

### Behavioral Changes ###

This will center an Image in UWP when the image uses all of the default layout options, i.e. only an ImageSource is set, everything else is default. Before this PR, the image would be centered by default on Android and iOS but left or top aligned on UWP. 

### PR Checklist ###
 My first PR so forgive me if I am not sure how to properly do 1, 2, and 4
- [ ] Has tests (if omitted, state reason in description)
Not sure best way to test this. 
- [ ] Rebased on top of master at time of PR
- [*] Changes adhere to coding standard
- [ ] Consolidate commits as makes sense

### CODE REVIEW

**Comment by rmarinho** [comment]
Do we have crop on the image ?

**Comment by jgold6** [comment]
AspectFit should not crop the image. Or perhaps I am misunderstanding.

**Comment by rmarinho** [comment]
Sorry i m asking if it doesn't look crop using this patch.

**Comment by jgold6** [comment]
The image does not look cropped using this patch. 

What I see with this patch is the same thing I see on iOS and Android, the Image maintains aspect ratio and fits into the available area without cropping (as expected).

**Comment by rmarinho** [comment]
build

**Pull request merged**
