### PR TITLE
[Android] Editor should display keyboard on text change while focused

### PR DESCRIPTION
**Pull request by adrianknight89**
### Description of Change ###

Android `Editor` does not show soft keyboard on initial focus when its text is changed while focused. This should fix that.

### Bugs Fixed ###

- https://bugzilla.xamarin.com/show_bug.cgi?id=32600

### PR Checklist ###

- [ ] Has tests (if omitted, state reason in description)
- [x] Rebased on top of master at time of PR
- [x] Changes adhere to coding standard
- [ ] Consolidate commits as makes sense

### CODE REVIEW

**Comment by rmarinho** [comment]
I think this changes a behaviour that users are now expecting and that some might want, i can see a page opening, i see the first entry with focus but i still can see the page, if i touch it the keyboard appears.

**Comment by samhouts** [comment]
Perhaps we can have users opt in to this fix with a platform specific option...?

**Comment by adrianknight89** [comment]
What would be a real-world scenario where you would want to see the whole page when an input view is focused? Soft keyboards are supposed to adjust display so focused content is always visible. Also, AFAIK, on iOS, keyboard always comes up. If a platform specific option is introduced, we first need to decide which behavior is defaulted.

**Comment by pauldipietro** [comment]
The default behavior should stay as-is to maintain users' current expectations.

**Comment by rmarinho** [comment]
Like a 1st overview of the page, see every fields of a form, .. at least in my mind i see that scenario but maybe that's not that important. The thing is it breaks a behaviour users are deploying apps rely on. I think this is best a platform specific feature.

**Comment by adrianknight89** [comment]
I'd like to think it actually fixes a broken behavior. :), but I can convert it to a platform specific option.

**Comment by rmarinho** [comment]
@adrianknight89 this seems better as a platform specific option like @samhouts , specially because  of changes on the behaviour for all users. Thanks for the pr.

**Comment by samhouts** [comment]
Thank you, @adrianknight89 !! We thoroughly appreciate your contributions. Hey, since you've implemented a few Platform Specific options, do you have any feedback on the API? 😄

**Comment by adrianknight89** [comment]
@samhouts I think it's a great feature. I've had to use it multiple times, and I'm sure there will be more need for it. Perhaps there needs to be a VS template in one of those Xamarin updates so less typing is needed for all those methods. :)

In the meantime, I don't know where to ask off-topic questions. I'm thinking of adding basic services (screen dimensions, toggling status bar, etc.). I think most people expect these features to be part of XF instead of relying on third parties. Where would be the right place to add services? Should there be a place to create `Dependency` services or should we add methods/properties to `Application`?

**Comment by adrianknight89** [comment]
@samhouts I think platform-specifics can be used for version control as well. IMO, new apps should have different default values for certain properties. For example, the soft input mode should be `AdjustResize`, `Done` button should be enabled on iOS numeric keyboard, `AppCompat` should not be sending appearing/disappearing events on pause/resume. The list of platform specific options is going to pile up eventually. They can be used to avoid breaking changes, but as I said, new apps shouldn't suffer from the compatibility loose ends.

**Pull request closed without merging**
