### PR TITLE
[Core] Fixed leaking reference to popped Page in PopAsync()

### LINKED ISSUE #1429: [Android, iOS] NavigationPage.PopAsync() cause memory leak by still holding on popped Page
Migrated from https://bugzilla.xamarin.com/show_bug.cgi?id=31171

### Description
Found with profiler that Task<Page> holds popped Page from the CurrentNavigationTask property of NavigationPage. 

Potential PR was closed and not merged. https://github.com/xamarin/Xamarin.Forms/pull/625

### Steps to Reproduce
Simple test case:
1) get start with Page1
2) navigate to Page2,
3) get back to Page1 with PopAsync() or back button.

### Basic Information

- Version with issue: 1.4.3

### Reproduction Link
[PagePopMemory.zip](https://github.com/xamarin/Xamarin.Forms/files/2369102/PagePopMemory.zip)

[XamarinFormsBugs.zip](https://github.com/xamarin/Xamarin.Forms/files/1573715/XamarinFormsBugs.zip)

### PR DESCRIPTION
**Pull request by kicsiede**
### Description of Change ###

fixed by using a private wait handle the same way as when there is a pending task

### Bugs Fixed ###

- [https://bugzilla.xamarin.com/show_bug.cgi?id=31171](https://bugzilla.xamarin.com/show_bug.cgi?id=31171)
- fixes #1429

### API Changes ###

-

### Behavioral Changes ###

-

### PR Checklist ###

- [x] Has tests (if omitted, state reason in description)
- [x] Rebased on top of master at time of PR
- [x] Changes adhere to coding standard
- [x] Consolidate commits as makes sense

### CODE REVIEW

**Comment by adrianknight89** [comment]
Ref: Similar work was done in #625 in a somewhat more thorough manner.

**Comment by kicsiede** [comment]
imho that's a pretty bad solution introducing a lot of unnecessary changes in the source code. all you have to do is wait on a naked handle without the reference.

**Comment by adrianknight89** [comment]
I only put it there as a reference since it at least contains a test case. :) Thanks for the work. This is an important bug that should have been fixed a long time ago.

**Comment by pauldipietro** [comment]
The original was closed because it was in fact messy, but as alluded to in the prior comment, this should contain a test case if at all possible. Also, please do try to use the provided template when submitting PRs.

**Comment by StephaneDelcroix** [comment]
please use the PR template for your description

**Comment by rmarinho** [comment]
@kicsiede you mind target this to 15-5

**Comment by rmarinho** [comment]
@kicsiede can you rebase this to 15-5 ?

**Comment by rmarinho** [comment]
moved to pr #2092

**Pull request closed without merging**
