### PR TITLE
[Android] ScrollView should send correct ScrollX and ScrollY

### PR DESCRIPTION
**Pull request by adrianknight89**
### Description of Change

Android `ScrollView` was incorrectly sending `ScrollX` and `ScrollY` values when scroll orientation was `Both`. This is because a horizontal scrollview is a child of a vertical scrollview and they are raising scroll events independently of each other. The user saw alternating 0 values for both positions.

This should send the final `ScrollX` and `ScrollY` to Core with every position update.

**EDIT:**

While testing horizontal + vertical scrolling, I discovered a bug. `ScrollToAsync()` method did not work when orientation was set to `Both`. Maybe I should have created a bug report for this and submitted it in a new PR. However, the fix works nicely with the fix for this bug. See the switch blocks for proper scroll calls. I also added a unit test to watch out for possible incorrect animation positioning. When you do back to back scroll animations, there shouldn't be an intermediate position. The second animation should begin where the first left off. 
### Bugs Fixed
- https://bugzilla.xamarin.com/show_bug.cgi?id=41415

### CODE REVIEW

**Comment by jamesl77** [comment]
I'm getting 0 values for `ScrollX` when scrolling, just like in the description of this PR I think.
Any update on merging this fix and releasing it in the NuGet?

**Comment by adrianknight89** [comment]
@samhouts I made improvements so we monitor changes during flight instead of only looking at final values.

**Comment by rmarinho** [comment]
Hey @adrianknight89 this test is failing on CI on all iOS version 

Failing for Ipad Air iOS 9

Failing for iPhone 6 plus on iOS 8

Failing for Iphone 6 on iOS 10

Also if i run in my sim i don't get the 100 100 values we are expecting when clicking.

simulator screen shot 7 dec 2016 12 37 01

I m reverting this PR for now..

**Comment by rmarinho** [comment]
Better i will not revert, i will just run the test in Android.

**Pull request merged**
