### PR TITLE
[iOS] Labels with WordWrap or CharacterWrap will Expand

### PR DESCRIPTION
**Pull request by samhouts**
### Description of Change ###

iOS `LabelRenderer` will now expand the width of the `Label` to the width constraint if the `Label`'s `LineBreakMode` is set to `WordWrap` (default) or `CharacterWrap`.

### Bugs Fixed ###
- [Bug 28650 - In a Listview on iOS, "andExpand" does not expand when text is two lines long](https://bugzilla.xamarin.com/show_bug.cgi?id=28650)

### API Changes ###

None

### Behavioral Changes ###

None

### PR Checklist ###

- [x] Has tests (if omitted, state reason in description)
- [x] Rebased on top of master at time of PR
- [x] Changes adhere to coding standard
- [x] Consolidate commits as makes sense

### CODE REVIEW

**Comment by rmarinho** [comment]
Can you rebase this @samhouts thanks.

**Comment by escamoteur** [comment]
Is this already in any release?

**Comment by samhouts** [comment]
@escamoteur It is in the latest prerelease (2.3.4) and in the latest [nightly build](https://blog.xamarin.com/try-the-latest-in-xamarin-forms-with-nightly-builds/).

**Comment by escamoteur** [comment]
Thanks, it turns out that the real reason is the problem that the OnAppearing Event on iOS still comes too late for the RxUI Bindings with Xaml bindings it works

see
https://forums.xamarin.com/discussion/84510/proposal-improved-life-cycle-support

**Pull request merged**
