### PR TITLE
[Mac] Added support AutomationProperty

### PR DESCRIPTION
**Pull request by paymicro**
### Description of Change ###

Added support `AutomationProperty` for _regular renderer_'s, _cells_ and _toolbar_ buttons.
This is part of PR #3955

### Issues Resolved ### 

none

### API Changes ###
 
 None

### Platforms Affected ### 

- Mac

### Behavioral/Visual Changes ###

None

### Before/After Screenshots ### 

Before
before

After
after

### Testing Procedure ###

- check AutomationPropertyGallery

### PR Checklist ###

- [ ] Has automated tests 
- [x] Rebased on top of the target branch at time of PR
- [x] Changes adhere to coding standard

### CODE REVIEW

**Comment by rmarinho** [comment]
I think there was a scenario we need the defaults? @samhouts you remember ?

**Comment by samhouts** [comment]
We use the defaults to make sure that we don't overwrite or lose any values that the customer may have set via custom renderer or effects.

**Comment by rmarinho** [comment]
Why you are removing the default @paymicro ? like @samhouts said users could have set that in there own renderers.

**Comment by rmarinho** [comment]
@PureWeen after you activate voice over there's a special instructions for navigating a table, I think is command + option plus arrows , I got it to tell "option a"

**Pull request merged**
