### PR TITLE
[Core] Fix Shapes issue using AppThemeBinding

### LINKED ISSUE #13093: [Bug] Line's Stroke and Rectangle's Fill doesn't rendered as expected while changing the system's appearance.
### Description
I have already set both Line's Stroke and Rectangle's Fill with AppThemeBinding, but when I changing the system's appearance in settings, their appearance doesn't change as expected. This problem occurs on both iOS and Android platforms.

### Steps to Reproduce
1. Create a Line or Rectangle.
2. Set the Line's Stroke or Rectangle's Fill with AppThemeBinding.
3. Run the application, change the system's appearance in settings.
4. You'll find that the Line or Rectangle's color doesn't rendered as excepted, but if you go back and re-enter, their color can be rendered correctly.

### Expected Behavior
微信截图_20201210132438

### Actual Behavior
微信截图_20201210132507

### Basic Information
- Version with issue: 5.0-pre5
- Platform Target Frameworks:
  - iOS: 14.2
  - Android: 11

### Screenshots
GIF 2020-12-10 12-00-32

### LINKED ISSUE #13173: [Bug] Line's Stroke and Rectangle's Fill doesn't rendered as expected with SolidColorBrush while changing the system's appearance.
### Description
I have already set both Line's Stroke and Rectangle's Fill to a **SolidColorBrush** with **AppThemeBinding**, but when I changing the system's appearance in settings, their appearance doesn't change as expected. This problem occurs on both iOS and Android platforms.

### Steps to Reproduce
1. Create a Line or Rectangle.
2. Set the Line's Stroke or Rectangle's Fill with a **SolidColorBrush** and **AppThemeBinding**.
3. Run the application, change the system's appearance in settings.
4. You'll find that the Line or Rectangle's color doesn't rendered as excepted, but if you go back and re-enter, their color can be rendered correctly.

### Expected Behavior, Actual Behavior and Screenshots
See #13093 

### Basic Information

- Version with issue: 5.0-pre5
- Platform Target Frameworks:
  - iOS:  14.2
  - Android: 11

### Code sample
`<Rectangle HorizontalOptions="Start" HeightRequest="80" WidthRequest="200"> <Rectangle.Fill> <SolidColorBrush Color="{AppThemeBinding Light=Green, Dark=Red}" /> </Rectangle.Fill> </Rectangle>`

### LINKED ISSUE #13359: [Bug] Line's Stroke and Rectangle's Fill doesn't rendered as expected with SolidColorBrush while changing the system's appearance.
### Description
Related issue: #13173 

### Steps to Reproduce
See the reference issue.
Same problem still occurs on the latest 5.0 version.

### Basic Information
- Version with issue: 5.0
- Platform Target Frameworks: 
  - iOS:  14.3
  - Android: 11

### Workaround
May be fixed by #13181

### PR DESCRIPTION
**Pull request by jsuarezruiz**
### Description of Change ###

Fix Shapes issue using AppThemeBinding with SolidColorBrush.

### Issues Resolved ### 

- fixes #13093
- fixes #13173
- fixes #13359

### API Changes ###
 
 None

### Platforms Affected ### 

- Core/XAML (all platforms)
- iOS
- Android
- macOS

### Behavioral/Visual Changes ###

None

### Before/After Screenshots ### 

fix13173

### Testing Procedure ###
Launch Core Gallery and navigate to the issue 13173. Change between system dark and light theme. If the Rectangle is green with the light theme and red with the dark theme, the test has passed.

### PR Checklist ###

- [ ] Targets the correct branch
- [ ] Tests are passing (or failures are unrelated)

### CODE REVIEW

**Review by rachelkang — COMMENTED** [review]
Created this sample based on the original issue and applied the nuget. On Android, it works great. On iOS, it works fine if I rebuild after switching the app theme, but not if I just switch the app theme and then return to the running app. Looks great in CG on both platforms for both scenarios though

[Issue13093.zip](https://github.com/xamarin/Xamarin.Forms/files/6417638/Issue13093.zip)

**Comment by AlleSchonWeg** [comment]
Hi @jfversluis ,
i ran into this issue. Could we merge this PR in the next SR?
Thank you

**Comment by jfversluis** [comment]
@AlleSchonWeg NuGet should be here, let me know if it looks OK to you!

**Review by jfversluis — APPROVED** [review]
Looks OK to me!

**Comment by AlleSchonWeg** [comment]
@jfversluis 
Yes. Works as expected.
Thx

**Pull request merged**
