### PR TITLE
[iOS] Fixed blurry Shape using Scale

### LINKED ISSUE #11480: [Enhancement] Scale on shapes are blurry (iOS)
## Summary
Might be a bug, I'm not sure. But with the new Shapes API, if you create an ellipse and use scale on it to make it larger, it's all blurry. The vectors are not really scaled up, it's just zoomed. On Android, it's working as expected.

## API Changes
None

## Intended Use Case
Animations with ScaleTo()

### PR DESCRIPTION
**Pull request by jsuarezruiz**
### Description of Change ###

Fixed blurry Shape using Scale on iOS.

### Issues Resolved ### 

- fixes #11480 

### API Changes ###
 
 None

### Platforms Affected ### 

- iOS

### Behavioral/Visual Changes ###

None

### Before/After Screenshots ### 

```
var ellipse = new Ellipse
{
    Stroke = Brush.Red,
    StrokeThickness = 5,
    HeightRequest = 50,
    WidthRequest = 50
};
```

#### Before
11480-before

#### After
11480-after

### Testing Procedure ###
Launch Core Gallery and navigate to the issue 11480. If the ellipse is not blurry, the test has passed.
### PR Checklist ###

- [ ] Targets the correct branch
- [ ] Tests are passing (or failures are unrelated)

### CODE REVIEW

**Comment by rachelkang** [comment]
@jsuarezruiz build failed :(

**Comment by jfversluis** [comment]
Not sure if this fix is still correct and seeing where we are in the Xamarin lifecycle, we probably won't be merging this anymore

**Pull request closed without merging**
