### PR TITLE
Dismiss UISearchController when losing focus

### LINKED ISSUE #10124: [Bug] Shell SearchHandler blocks touch to view
### Description

I have the following ContentPage that implements a SearchHandler to filter the CollectionView items source on the page. I set the ShowsResults to false, however there's still a view being displayed over the page preventing touches from getting to my CollectionView. 

### Steps to Reproduce

```
public partial class PapersPage : ContentPage
    {
        public PapersPage()
        {
            InitializeComponent();

            BindingContext = new PapersViewModel();

            Shell.SetSearchHandler(this,
                new PaperSearchHandler() { VM = (BindingContext as PapersViewModel) });
        }

    }

    class PaperSearchHandler : SearchHandler
    {
        public PapersViewModel VM { get; set; }

        public PaperSearchHandler()
        {
            SearchBoxVisibility = SearchBoxVisibility.Expanded;
            ShowsResults = false;
        }

        protected override void OnQueryChanged(string oldValue, string newValue)
        {
            base.OnQueryChanged(oldValue, newValue);
            if (string.IsNullOrEmpty(newValue))
            {
                //ItemsSource = null;
                VM.FilterPapers(string.Empty);
            }
            else
            {
                VM.FilterPapers(newValue);
            }
        }
    }
```

```
<?xml version="1.0" encoding="UTF-8"?>
<ContentPage
    xmlns="http://xamarin.com/schemas/2014/forms"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    xmlns:d="http://xamarin.com/schemas/2014/forms/design"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    xmlns:vm="clr-namespace:WhitePaperBible.ViewModels"
    mc:Ignorable="d"
    x:Class="WhitePaperBible.Views.PapersPage"
    Title="Papers">
    <CollectionView
        x:Name="cv"
        ItemsSource="{Binding Papers}">
        <CollectionView.ItemsLayout>
            <GridItemsLayout
                Orientation="Vertical"
                Span="1" />
        </CollectionView.ItemsLayout>
        <CollectionView.EmptyView>
            <StackLayout>
                <Label
                    HorizontalOptions="CenterAndExpand"
                    VerticalOptions="CenterAndExpand"
                    Text="Loading Papers" />
            </StackLayout>
        </CollectionView.EmptyView>
        <CollectionView.ItemTemplate>
            <DataTemplate>
                <ContentView
                    Padding="10">
                    <Frame
                        HasShadow="false"
                        BackgroundColor="#f1f1f1"
                        OutlineColor="#f2f2f2"
                        Padding="15,8"
                        CornerRadius="4">
                        <StackLayout
                            Padding="0">
                            <Label
                                FontSize="15"
                                MaxLines="1"
                                TextColor="Black"
                                d:Text="{Binding .}"
                                Text="{Binding title}" />
                            <Label
                                FontSize="11"
                                TextColor="Gray"
                                d:Text="Sally Someone"
                                Text="{Binding Author.Name}" />
                        </StackLayout>
                    </Frame>
                    <ContentView.GestureRecognizers>
                        <TapGestureRecognizer
                            Command="{Binding PaperSelectedCommand,
                                Source={RelativeSource AncestorType={x:Type vm:PapersViewModel}}}"
                            CommandParameter="{Binding .}"/>
                    </ContentView.GestureRecognizers>
                </ContentView>
            </DataTemplate>
        </CollectionView.ItemTemplate>
    </CollectionView>
</ContentPage>
```

### Expected Behavior

Everything works as it does not, but the content of the page isn't behind a partially transparent view that blocks my touches.

### Actual Behavior

Touches are blocked. 

### Basic Information

- Version with issue: 4.6-pre2
- Platform Target Frameworks:
  - iOS:  13.x

### Screenshots

https://www.screencast.com/t/hciTVvHnU

### Reproduction Link

https://github.com/davidortinau/wpbf/tree/bugs/search/WhitePaperBible

### PR DESCRIPTION
**Pull request by kazo0**
### Description of Change ###

Dismiss UISearchController when losing focus

### Issues Resolved ### 
- fixes #10124 

### API Changes ###
 None

### Platforms Affected ### 
- iOS

### Behavioral/Visual Changes ###
When a query is confirmed in SearchHandler, the search handler will lose focus and will no longer display a dimmed view on top of the remaining page

### Before/After Screenshots ### 

Not applicable

### Testing Procedure ###

1. Add a Shell SearchHandler
2. Tap the search bar to focus
3. Notice the main page is dimmed
4. Enter a search term
5. Execute the search
6. Notice the SearchHandler no longer displays a dimmed background and the main content is tappable

out

### PR Checklist ###
- [ ] Targets the correct branch
- [ ] Tests are passing (or failures are unrelated)

### CODE REVIEW

**Comment by mrkrk** [comment]
Any update?

**Comment by varyamereon** [comment]
Is there a plan to get this merged soon? Seems there are a few fixed issues in pull requests that would fix bugs in my app but they are not being merged. Just wondering whether I need to write a workaround or wait.

**Comment by demoh2019** [comment]
Any update?

**Comment by jsuarezruiz** [comment]
@kazo0 Could you rebase your branch to fix the conflicts?. Thanks!

**Comment by kazo0** [comment]
@jsuarezruiz done!

**Review by jsuarezruiz — APPROVED** [review]

**Comment by jfversluis** [comment]
I know, after more than a year, you are still anxiously looking every day at this PR @kazo0, but today is the day it is finally merged. You can now go forth and call yourself a Xamarin.Forms contributor! 🦸 

Thank you so much for your time and effort on this and sorry we didn't get to it sooner!

**Pull request merged**
