### PR TITLE
[CollectionView] Support custom objects binded to SelectedItems

### LINKED ISSUE #8155: [Bug] CollectionView ItemSelected only binds to List<object> and not to custom objects
### Description
When binding `List<FilterOption>` (which is a custom object) to the SelectedItems property of the CollectionView, the pre-selection doesn't work properly. It only works if you bind the SelectedItems property to a `List<object>`. The online documentation also uses a `List<object>` to bind to the SelectedItems property of a CollectionView, but I was expecting to be able to use my own custom objects inside a List (or ObservableCollection) and properly bind to the SelectedItems property of a CollectionView.

### Steps to Reproduce

1. Bind the ItemsSource and SelectedItems properties of your CollectionView to a property in your ViewModel.
```
<CollectionView SelectionMode="Multiple" ItemsSource="{Binding Options}" SelectedItems="{Binding SelectedOptions}">
...
</CollectionView>
```
2. Add the following properties to your ViewModel
```
        private ObservableCollection<FilterOption> _options = new ObservableCollection<FilterOption>();
        public ObservableCollection<FilterOption> Options
        {
            get => _options;
            set
            {
                SetProperty(ref _options, value); // using the Prism BindableBase SetProperty() method here
                RaisePropertyChanged(nameof(SelectedOptions));
            }
        }

        // works
        //public List<object> SelectedOptions
        //{
        //    get => new List<object>(Options?.Where(o => o.IsSelected));
        //}

        // doesn't work
        public List<FilterOption> SelectedOptions
        {
            get => new List<FilterOption>(Options?.Where(o => o.IsSelected));
        }
```
Note: FilterOption is just a class with 2 properties: Title and IsSelected

### Expected Behavior
Binding the SelectedItems to a `List<FilterOption>` highlights (selects) the items inside the CollectionView.

### Actual Behavior
Highlighting of the SelectedItems doesn't work, nor does it throw a decent exception to be told that you should bind to a `List<object>` instead.

### Basic Information

- Version with issue: Xamarin.Forms v4.3.0.908675 (thus stable version of CollectionView and not the experimental version, which also has the same behavior)
- Last known good version: unknown
- IDE: Visual Studio 2019 v16.3.5
- Platform Target Frameworks: 
  - iOS:  11 
  - Android: 9  
  - UWP:  N/A 
- Android Support Library Version: N/A 
- Nuget Packages: N/A
- Affected Devices: tested on multiple devices and OS

### Screenshots

Non working example (binding to `List<FilterOption>`)
Non working example

Working example (binding to `List<object>`)
Working example

### Reproduction Link
N/A

### PR DESCRIPTION
**Pull request by jsuarezruiz**
### Description of Change ###

Fixed issue with **CollectionView** using custom object in collections minded to `SelectedItems`.

What happened was that we were having an error while trying to do the casting:
`Binding: System.Collections.Generic.List1[Xamarin.Forms.Controls.Issues.Issue8155Model] can not be converted to type 'System.Collections.Generic.IList1[System.Object]`

Captura de pantalla 2019-10-31 a las 14 30 38

### Issues Resolved ### 

- fixes #8155

### API Changes ###

Changed:
 - `public IList<object> SelectedItems`
 
 Removed:
 - `public IList SelectedItems`
 
### Platforms Affected ### 

- Core/XAML (all platforms)
- iOS
- Android
- UWP

### Behavioral/Visual Changes ###

None

### Before/After Screenshots ### 

Not applicable

### Testing Procedure ###
Launch Core Gallery and navigate to the Issue8155. If the cell 'Option 2' is selected (BackgroundColor), the test has passed.

### PR Checklist ###

- [ ] Targets the correct branch
- [ ] Tests are passing (or failures are unrelated)

### CODE REVIEW

**Comment by jfversluis** [comment]
> "Xamarin.Forms.Platform.iOS\CollectionView\SelectableItemsViewController.cs(152,41): Error CS1503: Argument 2: cannot convert from 'System.Collections.IList' to 'System.Collections.Generic.IList<object>'"
Review

**Review by hartez — CHANGES_REQUESTED** [review]
Mostly looks fine, but CollectionView Gallery -> Selection Galleries -> Selection Modes crashes if I change the SelectionMode to "Multiple".

**Comment by rmarinho** [comment]
Build is failing @jsuarezruiz

**Comment by Tommigun1980** [comment]
@jsuarezruiz I really need this fix soon to get rid of tons of code smell. Do you think there's any chance it will land at some point? A year for a pull request to pend is a long time :/
Thank you.

**Comment by jfversluis** [comment]
I think at this point it's safe to say that we won't be taking this for Xamarin.Forms anymore. Thank you all so much for your time and effort on this. It hasn't gone unnoticed!

**Pull request closed without merging**
