### PR TITLE
Fix spaces to tabs indentation to match the coding style

### PR DESCRIPTION
**Pull request by ylatuya**
### Description of Change ###

Reopening https://github.com/xamarin/Xamarin.Forms/pull/3743 since there is a way to fix indentation issues and still keep the history of changes using the --ignore-all-space switch in git:
git show --ignore-all-space
git log -p  --ignore-all-space Xamarin.Forms.Plaform.Gtk
git diff origin/master --ignore-all-space -- Xamarin.Forms.Plaform.Gtk

### CODE REVIEW

**Comment by jassmith** [comment]
Okay its up to the GTK guys if they want to take this then :)

**Comment by ylatuya** [comment]
Attaching an example of history with the switch enabled:

screen shot 2018-09-07 at 20 52 33

**Comment by davidortinau** [comment]
fyi @jsuarezruiz

**Comment by jsuarezruiz** [comment]
Seem right to me.

**Comment by ylatuya** [comment]
After @jsuarezruiz  approval is there anything else missing to merge it ?

**Pull request merged**
