### PR TITLE
[Android] Entry Clear button invisible if BackgroundColor is a dark color

### LINKED ISSUE #12380: [Bug] Android: Entry Clear button becomes invisible when changing Entry.BackgroundColor to dark color
### Description
If the background property of an entry is updated to be a dark color, then the clear button isn't visible. 
Clear button color should always match the TextColor property (or at least offer dark/light setting). This is needed for theme support.

### Steps to Reproduce

1.  Add an entry, and set the BackgroundColor to Black, and TextColor to white, and ClearButtonVisibility to WhileEditing
2. Start typing in the entry
3. The clear button isn't visible, because the color of the clear icon is also black.

### Expected Behavior
Clear button icon color should match the TextColor property

### Actual Behavior
Clear button icon is always black - which makes it invisible when making entry BackgroundColor = Black

### Screenshots
image

### PR DESCRIPTION
**Pull request by jsuarezruiz**
### Description of Change ###
If the background property of an entry is updated to be a dark color, then the clear button isn't visible.
This PR include changes to set the ClearButton color using the TextColor property.

### Issues Resolved ### 

- fixes #12380 

### API Changes ###
 
 None

### Platforms Affected ### 

- Android
- iOS

### Behavioral/Visual Changes ###

None

### Before/After Screenshots ### 
fix12380

### Testing Procedure ###
Launch Core Gallery and navigate to the issue 12380. If the ClearButton is visible in all cases, the test has passed.

### PR Checklist ###

- [ ] Targets the correct branch
- [ ] Tests are passing (or failures are unrelated)

### CODE REVIEW

**Comment by jsuarezruiz** [comment]
We have the same problem on iOS, added changes to tint the clear image icon.

**Comment by transis2** [comment]
@jsuarezruiz what do you think about change the underline entry color too?

**Review by transis2 — APPROVED** [review]

**Comment by MrAndrewAu** [comment]
We have been suffering from this bug for a while. Greatly looking forward to it in the next Xamarin.Forms release!

**Comment by InquisitorJax** [comment]
@jsuarezruiz is there something blocking this guy from getting merged?

**Review by mattleibow — APPROVED** [review]

**Pull request merged**
