### PR TITLE
Shell handle clear refactoring

### PR DESCRIPTION
**Pull request by felipebaltazar**
### Description of Change ###

Refactoring suggestion for  this PR: https://github.com/xamarin/Xamarin.Forms/pull/9615#discussion_r380329354

### API Changes ###
Only created a base collection class for shell inner objects

### Behavioral/Visual Changes ###
None

### Before/After Screenshots ### 

Not applicable

### Testing Procedure ###
Not applicable

### PR Checklist ###

- [ ] Targets the correct branch
- [ ] Tests are passing (or failures are unrelated)

### CODE REVIEW

**Comment by PureWeen** [comment]
Can you rebase against 4.5?

**Comment by felipebaltazar** [comment]
> Can you rebase against 4.5?

@PureWeen  Its done! 💪

**Comment by felipebaltazar** [comment]
Ive updated this branch

**Comment by PureWeen** [comment]
Alright

Sorry for the delay on this one @felipebaltazar can you rebase this to master?

**Comment by felipebaltazar** [comment]
> Alright
> 
> Sorry for the delay on this one @felipebaltazar can you rebase this to master?

No problem! 😁
Its done!

**Comment by PureWeen** [comment]
@felipebaltazar don't worry about looking at this

I have a different PR I was working on that fixes this issue. It's a bit involved.
I actually stopped working on that PR because I wanted your work from this PR!

**Pull request merged**
