### PR TITLE
[iOS] Fix SwipeItems lose position issue

### LINKED ISSUE #13184: [Bug] SwipeView Items Lose their Positions when Scrolled & Swiped (iOS)
### Description

When swipe item is open and at the same time pressed/scrolled, it sometimes loses its original position. Best way to describe it is by the video below. 

While it is reproducible on the simulator, it is occurs more on real devices. 

### Steps to Reproduce
On a real device, simply scroll up/down while titling your finger to swipe at the same time.  On the simulator, it becomes easier to reproduce if you open an item then scroll at about 45degree angle.  

### Expected Behavior
Items should never be displaced! they must maintain their position. 

### Actual Behavior
Items get displaced. 

### Basic Information

- Version with issue: All releases including the latest XF 5.0.0.1791-pre5
- Last known good version: none, but it was less obvious XF 4.8.
- Platform Target Frameworks: 
  - iOS:  13 - 14.2
- NuGet Packages: 5.0.0.1791-pre5 , 1.6.0-pre5
- Affected Devices: Physical iPhones and simulator. 

### Environment

VS 2019 Community 16.8.3 

### Screenshots

ezgif com-gif-maker (4)

### Reproduction Link

https://github.com/darrabam/SwipeViewDisplacementBug

### Workaround

None

### PR DESCRIPTION
**Pull request by jsuarezruiz**
### Description of Change ###

Fix SwipeItems lose position issue on iOS (scroll up/down while titling your finger to swipe at the same time).

### Issues Resolved ### 

- fixes #13184 

### API Changes ###
 
 None

### Platforms Affected ### 

- iOS

### Behavioral/Visual Changes ###

None

### Before/After Screenshots ### 

Not applicable

### Testing Procedure ###
Using a device, launch Core Gallery and navigate to the issue 13184. Scroll up/down while titling your finger to swipe at the same time, if the SwipeItems maintain the position, the test has passed.

### PR Checklist ###

- [ ] Targets the correct branch
- [ ] Tests are passing (or failures are unrelated)

### CODE REVIEW

**Comment by jsuarezruiz** [comment]
Team, could we include this requested fix in the upcoming Release?

**Review by rachelkang — CHANGES_REQUESTED** [review]
I'm still seeing the issue in both the CG sample and the original issue :/

IMG_0028
IMG_0027

**Comment by jfversluis** [comment]
Stale and probably not going to fix this anymore

**Pull request closed without merging**
