### PR TITLE
Fix for bugzilla issue #33714

### LINKED ISSUE #2252: UITest 33714 missing Preserve attribute, instructions, should be automated
33714 is missing on-screen instructions for manual testing. Also, the test can be automated. And the test is not runnable on Android with linking enabled because the test is missing a Preserve attribute.

### PR DESCRIPTION
**Pull request by mkieres**
### Description of Change ###

Creating automated UI Test for the Bugzilla issue 33714

NOTE: I'm not sure how useful this automation is, considering that the original issue was a Windows Phone problem. Nevertheless I automated it, therefore this github issue could be closed off.

### Issues Resolved ### 

- fixes #2252

### API Changes ###
None

### Platforms Affected ### 

- iOS
- Android
- UWP

### Behavioral/Visual Changes ###
None

### Before/After Screenshots ### 

Not applicable

### Testing Procedure ###

Run UI tests

### PR Checklist ###

- [ ] Targets the correct branch <-- I'm not sure if I should be targeting `master` or `4.2.0`?
- [x] Tests are passing on UWP
- [ ] Tests are passing on Android
- [ ] Tests are passing on iOS

### CODE REVIEW

**Comment by mkieres** [comment]
I'm running into issues when trying to run this test on Android. Here's what I'm getting in my output when the build process tries to build `Xamarin.Forms.Platform.Android`

```
4>------ Build started: Project: Xamarin.Forms.Platform.Android, Configuration: Debug Any CPU ------
\Xamarin.Forms\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs(14,58,14,72): error CS0246: The type or namespace name 'FormsViewGroup' could not be found (are you missing a using directive or an assembly reference?)
\Xamarin.Forms\Xamarin.Forms.Platform.Android\AppCompat\ButtonRenderer.cs(197,8,197,24): error CS0246: The type or namespace name 'IOnClickListener' could not be found (are you missing a using directive or an assembly reference?)
\Xamarin.Forms\Xamarin.Forms.Platform.Android\AppCompat\ButtonRenderer.cs(199,8,199,24): error CS0246: The type or namespace name 'IOnTouchListener' could not be found (are you missing a using directive or an assembly reference?)
\Xamarin.Forms\Xamarin.Forms.Platform.Android\AppCompat\ButtonRenderer.cs(197,8,197,24): error CS0538: 'IOnClickListener' in explicit interface declaration is not an interface
\Xamarin.Forms\Xamarin.Forms.Platform.Android\AppCompat\ButtonRenderer.cs(199,8,199,24): error CS0538: 'IOnTouchListener' in explicit interface declaration is not an interface
\Xamarin.Forms\Xamarin.Forms.Platform.Android\AppCompat\ButtonRenderer.cs(17,39,17,61): error CS0535: 'ButtonRenderer' does not implement interface member 'View.IOnClickListener.OnClick(View)'
\Xamarin.Forms\Xamarin.Forms.Platform.Android\AppCompat\ButtonRenderer.cs(17,63,17,85): error CS0535: 'ButtonRenderer' does not implement interface member 'View.IOnTouchListener.OnTouch(View, MotionEvent)'
\Xamarin.Forms\Xamarin.Forms.Platform.Android\AppCompat\NavigationPageRenderer.cs(287,27,287,45): error CS0115: 'NavigationPageRenderer.OnAttachedToWindow()': no suitable method found to override
\Xamarin.Forms\Xamarin.Forms.Platform.Android\AppCompat\NavigationPageRenderer.cs(308,27,308,47): error CS0115: 'NavigationPageRenderer.OnDetachedFromWindow()': no suitable method found to override
\Xamarin.Forms\Xamarin.Forms.Platform.Android\AppCompat\NavigationPageRenderer.cs(33,97,33,113): error CS0535: 'NavigationPageRenderer' does not implement interface member 'IJavaObject.Handle'
\Xamarin.Forms\Xamarin.Forms.Platform.Android\AppCompat\CarouselPageRenderer.cs(102,27,102,45): error CS0115: 'CarouselPageRenderer.OnAttachedToWindow()': no suitable method found to override
\Xamarin.Forms\Xamarin.Forms.Platform.Android\AppCompat\CarouselPageRenderer.cs(111,27,111,47): error CS0115: 'CarouselPageRenderer.OnDetachedFromWindow()': no suitable method found to override
\Xamarin.Forms\Xamarin.Forms.Platform.Android\AppCompat\CarouselPageRenderer.cs(11,75,11,106): error CS0535: 'CarouselPageRenderer' does not implement interface member 'IJavaObject.Handle'
\Xamarin.Forms\Xamarin.Forms.Platform.Android\Renderers\CarouselPageRenderer.cs(42,27,42,45): error CS0115: 'CarouselPageRenderer.OnAttachedToWindow()': no suitable method found to override
\Xamarin.Forms\Xamarin.Forms.Platform.Android\Renderers\CarouselPageRenderer.cs(57,27,57,47): error CS0115: 'CarouselPageRenderer.OnDetachedFromWindow()': no suitable method found to override
\Xamarin.Forms\Xamarin.Forms.Platform.Android\Renderers\CarouselPageRenderer.cs(110,27,110,36): error CS0115: 'CarouselPageRenderer.OnMeasure(int, int)': no suitable method found to override
\Xamarin.Forms\Xamarin.Forms.Platform.Android\AppCompat\TabbedPageRenderer.cs(226,27,226,45): error CS0115: 'TabbedPageRenderer.OnAttachedToWindow()': no suitable method found to override
\Xamarin.Forms\Xamarin.Forms.Platform.Android\AppCompat\TabbedPageRenderer.cs(234,27,234,47): error CS0115: 'TabbedPageRenderer.OnDetachedFromWindow()': no suitable method found to override
\Xamarin.Forms\Xamarin.Forms.Platform.Android\AppCompat\TabbedPageRenderer.cs(26,71,26,103): error CS0535: 'TabbedPageRenderer' does not implement interface member 'IJavaObject.Handle'
\Xamarin.Forms\Xamarin.Forms.Platform.Android\Renderers\EntryRenderer.cs(545,39,545,53): error CS0246: The type or namespace name 'TouchEventArgs' could not be found (are you missing a using directive or an assembly reference?)
\Xamarin.Forms\Xamarin.Forms.Platform.Android\Renderers\ListViewRenderer.cs(109,27,109,45): error CS0115: 'ListViewRenderer.OnAttachedToWindow()': no suitable method found to override
\Xamarin.Forms\Xamarin.Forms.Platform.Android\Renderers\ListViewRenderer.cs(121,27,121,47): error CS0115: 'ListViewRenderer.OnDetachedFromWindow()': no suitable method found to override
\Xamarin.Forms\Xamarin.Forms.Platform.Android\NativeViewWrapperRenderer.cs(66,27,66,36): error CS0115: 'NativeViewWrapperRenderer.OnMeasure(int, int)': no suitable method found to override
\Xamarin.Forms\Xamarin.Forms.Platform.Android\Renderers\NavigationRenderer.cs(97,27,97,45): error CS0115: 'NavigationRenderer.OnAttachedToWindow()': no suitable method found to override
\Xamarin.Forms\Xamarin.Forms.Platform.Android\Renderers\NavigationRenderer.cs(103,27,103,47): error CS0115: 'NavigationRenderer.OnDetachedFromWindow()': no suitable method found to override
\Xamarin.Forms\Xamarin.Forms.Platform.Android\Renderers\PageRenderer.cs(56,27,56,45): error CS0115: 'PageRenderer.OnAttachedToWindow()': no suitable method found to override
\Xamarin.Forms\Xamarin.Forms.Platform.Android\Renderers\PageRenderer.cs(65,27,65,47): error CS0115: 'PageRenderer.OnDetachedFromWindow()': no suitable method found to override
\Xamarin.Forms\Xamarin.Forms.Platform.Android\Renderers\ButtonRenderer.cs(317,39,317,55): error CS0246: The type or namespace name 'IOnClickListener' could not be found (are you missing a using directive or an assembly reference?)
\Xamarin.Forms\Xamarin.Forms.Platform.Android\Renderers\ButtonRenderer.cs(329,39,329,55): error CS0246: The type or namespace name 'IOnTouchListener' could not be found (are you missing a using directive or an assembly reference?)
\Xamarin.Forms\Xamarin.Forms.Platform.Android\ViewRenderer.cs(31,114,31,142): error CS0535: 'ViewRenderer<TView, TNativeView>' does not implement interface member 'IJavaObject.Handle'
\Xamarin.Forms\Xamarin.Forms.Platform.Android\Renderers\TabbedRenderer.cs(42,27,42,45): error CS0115: 'TabbedRenderer.OnAttachedToWindow()': no suitable method found to override
\Xamarin.Forms\Xamarin.Forms.Platform.Android\Renderers\TabbedRenderer.cs(48,27,48,47): error CS0115: 'TabbedRenderer.OnDetachedFromWindow()': no suitable method found to override
\Xamarin.Forms\Xamarin.Forms.Platform.Android\Platform.cs(1197,4,1197,20): error CS0246: The type or namespace name 'IOnTouchListener' could not be found (are you missing a using directive or an assembly reference?)
\Xamarin.Forms\Xamarin.Forms.Platform.Android\Renderers\TableViewRenderer.cs(62,27,62,45): error CS0115: 'TableViewRenderer.OnAttachedToWindow()': no suitable method found to override
\Xamarin.Forms\Xamarin.Forms.Platform.Android\Platform.cs(1277,44,1277,60): error CS0246: The type or namespace name 'IOnTouchListener' could not be found (are you missing a using directive or an assembly reference?)
\Xamarin.Forms\Xamarin.Forms.Platform.Android\Platform.cs(1194,65,1194,79): error CS0535: 'Platform.DefaultRenderer' does not implement interface member 'ILayoutChanges.LayoutChange'
\Xamarin.Forms\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs(37,24,37,36): error CS0115: 'VisualElementRenderer<TElement>.OnTouchEvent(MotionEvent)': no suitable method found to override
\Xamarin.Forms\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs(42,24,42,45): error CS0115: 'VisualElementRenderer<TElement>.OnInterceptTouchEvent(MotionEvent)': no suitable method found to override
\Xamarin.Forms\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs(54,24,54,42): error CS0115: 'VisualElementRenderer<TElement>.DispatchTouchEvent(MotionEvent)': no suitable method found to override
\Xamarin.Forms\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs(165,25,165,36): error CS0115: 'VisualElementRenderer<TElement>.FocusSearch(View, FocusSearchDirection)': no suitable method found to override
\Xamarin.Forms\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs(269,27,269,34): error CS0115: 'VisualElementRenderer<TElement>.Dispose(bool)': no suitable method found to override
\Xamarin.Forms\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs(372,27,372,35): error CS0115: 'VisualElementRenderer<TElement>.OnLayout(bool, int, int, int, int)': no suitable method found to override
\Xamarin.Forms\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs(14,74,14,96): error CS0535: 'VisualElementRenderer<TElement>' does not implement interface member 'IDisposable.Dispose()'
```

Any suggestions how to get it to run?

**Comment by mkieres** [comment]
It looks like the test is failing in few cases on iOS and Android. Any suggestions how can this be fixed? How does one run iOS UI tests locally?

I still cannot build `Xamarin.Forms.Platform.Android` project to even check if the test app is compiling and running fine.

**Comment by samhouts** [comment]
@mkieres You can run iOS tests locally from your Mac by using the tests explorer.

**Comment by samhouts** [comment]
I'm going to close this one for now until we're ready to return to it. Thanks, @mkieres !

**Pull request closed without merging**
