### PR TITLE
synchronized access to VisualElement._measureCache

### LINKED ISSUE #9402: [Bug] Concurrent Dictionary access in VisualElement.GetSizeRequest
### Description

Got the issue through an AppCenter crash report.

#### Stacktrace:

`    Dictionary`2[TKey,TValue].FindEntry (TKey key)
    Dictionary`2[TKey,TValue].TryGetValue (TKey key, TValue& value)
    VisualElement.GetSizeRequest (System.Double widthConstraint, System.Double heightConstraint)
    Layout.GetSizeRequest (System.Double widthConstraint, System.Double heightConstraint)
    VisualElement.Measure (System.Double widthConstraint, System.Double heightConstraint, Xamarin.Forms.MeasureFlags flags)
    FlexLayout+<>c__DisplayClass61_0.<AddChild>b__0 (Xamarin.Flex.Item it, System.Single& w, System.Single& h)
    Item.layout_item (Xamarin.Flex.Item item, System.Single width, System.Single height)
    Item.Layout ()
    FlexLayout.OnMeasure (System.Double widthConstraint, System.Double heightConstraint)
    VisualElement.GetSizeRequest (System.Double widthConstraint, System.Double heightConstraint)
    Layout.GetSizeRequest (System.Double widthConstraint, System.Double heightConstraint)
    VisualElement.Measure (System.Double widthConstraint, System.Double heightConstraint, Xamarin.Forms.MeasureFlags flags)
    StackLayout.CalculateNaiveLayout (Xamarin.Forms.StackLayout+LayoutInformation layout, Xamarin.Forms.StackOrientation orientation, System.Double x, System.Double y, System.Double widthConstraint, System.Double heightConstraint)
    StackLayout.CalculateLayout (Xamarin.Forms.StackLayout+LayoutInformation layout, System.Double x, System.Double y, System.Double widthConstraint, System.Double heightConstraint, System.Boolean processExpanders)
    StackLayout.OnSizeRequest (System.Double widthConstraint, System.Double heightConstraint)
    VisualElement.OnMeasure (System.Double widthConstraint, System.Double heightConstraint)
    VisualElement.GetSizeRequest (System.Double widthConstraint, System.Double heightConstraint)
    Layout.GetSizeRequest (System.Double widthConstraint, System.Double heightConstraint)
    VisualElement.Measure (System.Double widthConstraint, System.Double heightConstraint, Xamarin.Forms.MeasureFlags flags)
    TemplatedView.OnSizeRequest (System.Double widthConstraint, System.Double heightConstraint)
    VisualElement.OnMeasure (System.Double widthConstraint, System.Double heightConstraint)
    VisualElement.GetSizeRequest (System.Double widthConstraint, System.Double heightConstraint)
    Layout.GetSizeRequest (System.Double widthConstraint, System.Double heightConstraint)
    VisualElement.Measure (System.Double widthConstraint, System.Double heightConstraint, Xamarin.Forms.MeasureFlags flags)
    StackLayout.CalculateNaiveLayout (Xamarin.Forms.StackLayout+LayoutInformation layout, Xamarin.Forms.StackOrientation orientation, System.Double x, System.Double y, System.Double widthConstraint, System.Double heightConstraint)
    StackLayout.CalculateLayout (Xamarin.Forms.StackLayout+LayoutInformation layout, System.Double x, System.Double y, System.Double widthConstraint, System.Double heightConstraint, System.Boolean processExpanders)
    StackLayout.OnSizeRequest (System.Double widthConstraint, System.Double heightConstraint)
    VisualElement.OnMeasure (System.Double widthConstraint, System.Double heightConstraint)
    VisualElement.GetSizeRequest (System.Double widthConstraint, System.Double heightConstraint)
    Layout.GetSizeRequest (System.Double widthConstraint, System.Double heightConstraint)
    VisualElement.Measure (System.Double widthConstraint, System.Double heightConstraint, Xamarin.Forms.MeasureFlags flags)
    ScrollView.LayoutChildren (System.Double x, System.Double y, System.Double width, System.Double height)
    Layout.UpdateChildrenLayout ()
    Layout.OnSizeAllocated (System.Double width, System.Double height)
    Layout+<>c.<OnChildMeasureInvalidated>b__45_0 ()
    NSAsyncActionDispatcher.Apply ()
    (wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
    UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate)
    UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName)
    Application.Main (System.String[] args)`

#### Analysis

I found out, that the Dictionary `_measureCache` in `VisualElement` is potenially vounerable to concurrent access issues. I would suggest to use `System.Collections.Concurrent.ConcurrentDictionary` to mitigate this issue.

### Basic Information

- Version with issue: 4.2.0.910310
- Platform Target Frameworks: iOS
  - iOS:  13.10.0.17
- Affected Devices: iPhone 5S

### PR DESCRIPTION
**Pull request by thisisthekap**
### Description of Change ###

Synchronized the uses of `_measureCache` in `VisualElement` using a `ReaderWriterLockSlim`.

### Issues Resolved ### 

- fixes #9402

### PR Checklist ###

- [ ] Targets the correct branch
- [ ] Tests are passing (or failures are unrelated)

### CODE REVIEW

**Comment by rmarinho** [comment]
Hi @thisisthekap do you mind rebase, we had a problem with our ci script needs to get the updated one. Thanks

**Comment by thisisthekap** [comment]
@rmarinho I am not sure if a understand what you want from me resp. what I am supposed to do :)

**Comment by rmarinho** [comment]
asking if you can rebase this branch on top of 4.4.0

**Comment by thisisthekap** [comment]
@rmarinho (hopefully) done. If I screwed up something, please let me know.

**Comment by thisisthekap** [comment]
@samhouts @rmarinho @StephaneDelcroix Is anything left on my side concerning this pull request?

**Comment by rmarinho** [comment]
this should target master now you should rebase

**Comment by thisisthekap** [comment]
@rmarinho Everything should be fine now. If there is anything else that i have to do, please just let me know.

**Comment by thisisthekap** [comment]
@samhouts @rmarinho Is there anything else from my side that is blocking this PR?

**Comment by rmarinho** [comment]
Can we add a unit test or a reproduction for this so we can test? 

Thanks

**Comment by thisisthekap** [comment]
@rmarinho Adding a unit test for this specific issue is imho difficult, because this fix addresses an issue that arises when a dictionary is modified concurrently. Therefore I currently have no idea on how to create a deterministic unit test for this one.

**Comment by thisisthekap** [comment]
@rmarinho Is there anything else from my side that is blocking this PR?

**Comment by thisisthekap** [comment]
@StephaneDelcroix @PureWeen @samhouts Is there anything else from my side that is blocking this PR?

**Comment by thisisthekap** [comment]
@StephaneDelcroix @PureWeen @samhouts Is this PR abandoned? Are there plans to solve this differently?

**Comment by thisisthekap** [comment]
@samhouts What is the state of this PR?

**Comment by thisisthekap** [comment]
Closing this PR as this seems to be as designed.

**Pull request closed without merging**
