### PR TITLE
[Mac] fixes NRE when changing MainPage. Refactoring tab order.

### LINKED ISSUE #4156: Forms 3.3 + Mac (Regression+Crash) Changing MainPage
### Description
Crash after updating to 3.3 Stable. In Forms + Mac, changing Applications Main Page crashes. Working in 3.2

### Steps to Reproduce
Steps for regression crash
1. Create a new Project with Forms 3.2 + iOS (Android not required now)
2. Add a MacOS cocoa project with Forms 3.2 dependency. Set this as default project.
3. Make necessary changes in macOS files and ensure the MainPage is visible. 
4. Add a new SecondPage.XAML
5. In App.xaml.cs, change the app's MainPage to SecondPage.XAML (just to verify its working)
6. To the SecondPage add a button 'Click Me'. In the button handler add the following code
`var myApp = (App)Xamarin.Forms.Application.Current;`
`myApp.MainPage = new MainPage();`
7. Run the macOS app, click the button 'Click Me'. Wait for few seconds >>CRASH <<

### Expected Behavior
Specified page must be visible and application continues to work.
### Actual Behavior
 >>CRASH<<
### Basic Information

- Version with issue: 3.3.0.912450
- Last known good version:3.2.0871581
- IDE: Visual Studio for Mac
- Platform Target Frameworks: 
  - macOS: 10.11 
- Nuget Packages: forms 3.3.0.912450
- Affected Devices:

### PR DESCRIPTION
**Pull request by paymicro**
### Description of Change ###

Tabulation on the Mac has been rewritten with using KeyUp method

### Issues Resolved ### 

- fixes #4156 

### API Changes ###
 
 None

### Platforms Affected ### 

- Mac

### Behavioral/Visual Changes ###

None

### Testing Procedure ###

- run ControlGallery on Mac
- click on `SwapRoot - ContentPage` twice or more
- app should't crash
- run uitest 1700
- check tab order on controls

### PR Checklist ###

- [ ] Has automated tests 
- [x] Rebased on top of the target branch at time of PR
- [x] Changes adhere to coding standard

### CODE REVIEW

**Comment by samhouts** [comment]
@paymicro Please rebase to 3.4.0. Thanks!

**Comment by DennisWelu** [comment]
@samhouts I am trying to interpret the expected release version of items that are "Done". Based on the above activity is this currently expected for release on a 3.4 update of some sort? But 3.5 is out now... I did not see it in the release notes for 3.5 and I see "2 of 3 tasks complete" on this PR when I see the link to it from #4156. Appreciate any info you can share on how to interpret the item status.

**Comment by samhouts** [comment]
It didn't make it into 3.5.0 on time, but it will be there in the next 3.5 service release. You will also find it in the latest nightly, if you'd like to test it before the next service release is due. Thanks!

**Comment by DennisWelu** [comment]
Awesome, thanks! I've been watching the nightlies and I havent seen an update since 1/20. But I'll keep watching!

**Pull request merged**
