### PR TITLE
[macOS] Dark Theme support

### LINKED ISSUE #3777: Dark mode on Mojave doesn't work right
### Description

When using Dark Mode on Mojave, controls are unusable due to the way they are drawn (for example no visible text on buttons).

### Steps to Reproduce

1. Create a macOS Forms app.
2. Run it on macOS Mojave (beta)
3. 

### Expected Behavior

Apps should be usable

### Actual Behavior

Parts of the controls are not visible

### Basic Information

- Version with issue: 3.1.0.697729
- Last known good version: None
- IDE: VS for Mac
- Platform Target Frameworks:
  - macOS
- Affected Devices: macOS running Mojave

### Screenshots

Light mode:

light

Dark Mode:

dark

### Reproduction Link

https://github.com/jimbobbennett/SqueakyAppLinuxAndMac

### LINKED ISSUE #8864: [Bug] MacOS Xamarin Forms does not support dark mode
### Description
Out of box XF does not support Dark Mode

### Steps to Reproduce

1. Create a Cross platform app iOS+Android
2. Add a macOS Project
3. Amend Mac project to use Xamarin Forms (see below)
4. Run app

### Steps to convert to XF
Change AppDelegate to ...

    public class AppDelegate : FormsApplicationDelegate
    {
        NSWindow _window;

        public override NSWindow MainWindow
        {
            get { return _window; }
        }

        public AppDelegate()
        {
            var style = NSWindowStyle.Closable | NSWindowStyle.Resizable | NSWindowStyle.Titled;

            var rect = new CoreGraphics.CGRect(200, 200, 800, 600);
            _window = new NSWindow(rect, style, NSBackingStore.Buffered, false);
            _window.TitleVisibility = NSWindowTitleVisibility.Hidden;
            _window.Title = "No Dark Mode";
        }

        public override void DidFinishLaunching(NSNotification notification)
        {
            Forms.Init();
            LoadApplication(new App());
            base.DidFinishLaunching(notification);
        }

Change MainClass to
        static void Main(string[] args)
        {
            NSApplication.Init();
            NSApplication.SharedApplication.Delegate = new AppDelegate();
            NSApplication.Main(args);
        }

Remove story board reference from info.plist

### Expected Behavior
Window should be in dark mode

### Actual Behavior
Window is not in dark mode, always in light mode.

### Basic Information
Run the macOS app before converting to XF and confirm that the Window shows in dark mode.

- Version with issue: latest
- Last known good version: none
- IDE: VS4Mac
- Platform Target Frameworks:
  - macOS:  Catalina
- Nuget Packages: XF 4.4
- Affected Devices:

### PR DESCRIPTION
**Pull request by jfversluis**
### Description of Change ###

Add necessary bits to support both native Dark Mode from 10.14 and up and the Forms xplat APIs

### Issues Resolved ### 

- fixes #8864 
- fixes #3777

### API Changes ###
- added on macOS project: `public class FormsNSView`

### Platforms Affected ### 

- macOS

### Behavioral/Visual Changes ###
Some colors might be different than before when running on 10.14+. Colors where changed to use dynamic colors so the values might be different than the hard-coded ones earlier.

### Before/After Screenshots ### 

image

image

### Testing Procedure ###
Switch your Mac to Dark Mode and run the gallery app. Everything should look easy on the eyes.
When switching while the app is running, everything should transition back and forth

### PR Checklist ###

- [ ] Targets the correct branch
- [ ] Tests are passing (or failures are unrelated)

### CODE REVIEW

**Comment by jamesmontemagno** [comment]
I would love to try this puppy out on https://github.com/jamesmontemagno/MyStreamTimer as it is pretty small and could use some dark mode

**Comment by jamesmontemagno** [comment]
Looking really good. 
I do get a crash when I change between light and dark mode when the app is running. It looks like it is coming from internal XF. 

Screen Shot 2020-05-15 at 3 49 31 PM

**Comment by jamesmontemagno** [comment]
Editor does not seem to have the correct text color in dark mode.
Entry is alright

**Comment by Domik234** [comment]
> Looking really good.
> I do get a crash when I change between light and dark mode when the app is running. It looks like it is coming from internal XF.
> 
> Screen Shot 2020-05-15 at 3 49 31 PM

Same problem here, but on Honor 20 (Android 10).
X.F 4.6.0.772
I have to figure out first what exactly does the crash.

**Comment by jfversluis** [comment]
Retargeted to 5.0 and removed DNM. I think I got most of the things done for this. There might be some tweaks needed here and there, but for now it seems good enough.

**Comment by jamesmontemagno** [comment]
All of the crashes were fixed in the latest commits. I am shipping an app today with the nightly builds btw

**Comment by knocte** [comment]
Would this PR fix https://github.com/xamarin/Xamarin.Forms/issues/3777 properly (instead of the workaround that was put in place there?)?

**Comment by jfversluis** [comment]
@knocte yes :)

**Pull request merged**
