### PR TITLE
[Xaml, Android] Fix bugs;

### PR DESCRIPTION
**Pull request by as94**
### Bugs Fixed ###

Fix errors in code;

### CODE REVIEW

**Comment by rmarinho** [comment]
build all

**Comment by rmarinho** [comment]
build

**Comment by rmarinho** [comment]
build

**Comment by rmarinho** [comment]
build

**Comment by StephaneDelcroix** [comment]
Hi @as94,

Thanks for this first contribution. Unfortunately, we can not accept this as-is for the following reason:
- This (tries to) fix different unrelated errors (I assume 3),
- We have no idea what it fixes,
- There are no tests, so we can't make sure it doesn't regress in the future,
- This PR has no description.

While I'm quite sure this fixes errors for you, and maybe for other people, we just can't accept this and I will close this PR.

I recommend that you:
- report one issue per problem in bugzilla (bugzilla.xamarin.com) with a test case
- open one PR per fix, referencing the bugzilla issue
- ideally add unit-tests

Thanks.

The XF team

**Pull request closed without merging**
