### PR TITLE
[Android] TalkBack now reads name and helptext on buttons.

### LINKED ISSUE #1529: [Android] Using AutomationId prevents TalkBack screenreader accessibility
### Description

When using the `AutomationId` property on Android, apps end up almost completely inaccessible to users who use Android's TalkBack screenreader.

Xamarin.Forms "borrows" the `ContentDescription` property on Android for Automation IDs. These IDs  polute Android's TalkBack accessibility tree, making apps almost impossible to navigate.

This means you can support test automation or accessibility, not both. Our app needs to support both 😃 

I can't find any easy way of working around this restriction, short of walking the Android view tree and setting `ContentDescription` to null. Being unable to update `AutomationId` once set also adds to the difficulty of working around this issue.

### Potential solutions

**1. Use another system for setting AutomationIDs**

Probably a non-starter for backwards compatibility?

**2. Monitor AccessibilityManager to see if accessibility is enabled**

Assuming there’s no alternative property to use for setting IDs, one solution would be for Xamarin.Forms to use Android's `AccessibilityManager` and check the `IsTouchExplorationEnabled` property.

This is true when the TalkBack screen-reader is being used, and Forms could ignore `AutomationId` and not set `ContentDescription`. Forms should then also use an `ITouchExplorationStateChangeListener` to monitor changes to this state.

### Steps to Reproduce

1. Create any element with an AutomationId set
2. Go to that element on an Android device with TalkBack enabled

### Expected Behavior
Element is ignored, or its actual content is read.

### Actual Behavior
Element's AutomationId is read to the user.

### Basic Information

- Version with issue: 2.5.0.121934
- Last known good version: none. Always happened since AutomationId supported.

### LINKED ISSUE #5150: AutomationProperties.Name, AutomationProperties.HelpText on Button not read by Android TalkBack
### Description

`AutomationProperties.Name` and `AutomationProperties.HelpText` are not read by TalkBack on Android when placed on a `Button` element.

### Steps to Reproduce

1. Set`Text` property on a button.
2. Add `AutomationProperties.Name` and `AutomationProperties.HelpText` values to button.
3. Enable TalkBack through Android Settings.
4. Navigate to button, notice neither `Name`, nor `HelpText` are read.

### Expected Behavior

I expect an experience more similar to iOS.

Text is not null, Name is Null, HelpText is not null
"Text. HelpText" is read by TalkBack

Text is not null, Name is Not Null, HelpText is not null
"Name. HelpText" is read by TalkBack 

### Actual Behavior

Name and HelpText are not read when Text is set.

### Basic Information

- Version with issue: 3.4, 3.5
- Last known good version: n/a
- IDE: Visual Studio 2017 Professional Mac
- Platform Target Frameworks: 
  - Android: Android SDK 9.0
- Android Support Library Version: 
- Nuget Packages: none
- Affected Devices: Any android device it seems.

### PR DESCRIPTION
**Pull request by ryl**
### Description of Change ###

Modified `AutomationPropertiesProvider` such that `AutomationProperties.Name` and `AutomationProperties.HelpText` will be read by TalkBack.

Re-created from https://github.com/xamarin/Xamarin.Forms/pull/5237

### Issues Resolved ### 

- fixes #5150
- fixes #1529

### API Changes ###
 
 None

### Platforms Affected ### 

- Android

### Behavioral/Visual Changes ###

TalkBack will read `AutomationProperties.Name` and `AutomationProperties.HelpText` on a button if provided.

### Before/After Screenshots ### 

Not applicable

### Testing Procedure ###

In the Control Gallery, visit G5150. Labels containing the ContentDescription for each button should appear with appropriate text.

### PR Checklist ###

- [x] Has automated tests 
- [x] Rebased on top of the target branch at time of PR
- [x] Changes adhere to coding standard

### CODE REVIEW

**Comment by ryl** [comment]
@samhouts here's a recreation of https://github.com/xamarin/Xamarin.Forms/pull/5237 sorry about the noise.

**Comment by samhouts** [comment]
@ryl No worries! Thanks!!

**Review by rmarinho — CHANGES_REQUESTED** [review]
Build is failing

```
  D:\agent\1\s\Xamarin.Forms.ControlGallery.Android\ContentDescriptionEffectRenderer.cs(8,26): error CS0234: The type or namespace name 'View' does not exist in the namespace 'Android.Support.V4' (are you missing an assembly reference?) [D:\agent\1\s\Xamarin.Forms.ControlGallery.Android\Xamarin.Forms.ControlGallery.Android.csproj]
  D:\agent\1\s\Xamarin.Forms.ControlGallery.Android\ContentDescriptionEffectRenderer.cs(9,26): error CS0234: The type or namespace name 'View' does not exist in the namespace 'Android.Support.V4' (are you missing an assembly reference?) [D:\agent\1\s\Xamarin.Forms.ControlGallery.Android\Xamarin.Forms.ControlGallery.Android.csproj]
```

**Review by PureWeen — CHANGES_REQUESTED** [review]
@ryl  A couple things

- I think the code for this one that fixes AutomationId needs to be part of a different PR
- I created a different PR here https://github.com/xamarin/Xamarin.Forms/pull/13244 that fixes the issue with #5150 . That should fix Button and Switch.

**Comment by jfversluis** [comment]
Seems like this has been fixed in other PRs. Thanks for all your time and effort here! We're doing big investments in .NET MAUI to make accessibility even better there!

**Pull request closed without merging**
