### PR TITLE
[UWP] Fixed sync of ListView items with ListViewProxy

### LINKED ISSUE #2485: [UWP] Removing items from Listview shows white rows
### Description
Seems that removing items for the collection leaves a empty white row. 

### Steps to Reproduce

1. Open control gallery issues page
2. Go to issue B56771
3. Click Remove 2

### Expected Behavior
Should not see white space

### Actual Behavior
We see a empty white row.

### Basic Information

- Version with issue: 3.0.0
- Last known good version:
- IDE: VS WIN
- Platform Target Frameworks: 
  - UWP:   

### Screenshots
screenshot 2018-04-17 12 05 06

### PR DESCRIPTION
**Pull request by paymicro**
### Description of Change ###

`ItemsSource` wrapped in an `ObservableCollection`
Added processing for adding and removing items.
Screencast: https://www.screencast.com/t/LrPoEiM8a6v0

### Bugs Fixed ###

Fixes #2485

### API Changes ###

--

### Behavioral Changes ###

Correct Items shown when the collection is changed

### PR Checklist ###

- [ ] Has tests (if omitted, state reason in description)
- [x] Rebased on top of master at time of PR
- [ ] Changes adhere to coding standard
- [ ] Consolidate commits as makes sense

### CODE REVIEW

**Comment by rmarinho** [comment]
@hartez can you run uwp tests on this?

**Comment by rmarinho** [comment]
this doesn't fix #2486 i wonder if the root cause si not the same.

**Comment by paymicro** [comment]
@rmarinho in #2486 more serious problem with equals `string` items in different groups.
In test when creates a first cell in second group https://github.com/xamarin/Xamarin.Forms/blob/4c92ed338b3edd2bd145107d61b81a712a1cfd41/Xamarin.Forms.Platform.UAP/CellControl.cs#L355 `templatedItems.GetGroupAndIndexOfItem("I am a short text")` returns the first cell of the first group.
The second group begins to have cells of the first group.

**Comment by hartez** [comment]
When I run the [Issue 1875 test](https://github.com/xamarin/Xamarin.Forms/blob/74cb5c4a97dcb123eb471f6b1dffa1267d0305aa/Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue1875.cs) with this code, I get an ArgumentOutOfRange exception:

```
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.ObjectModel.Collection`1.Insert(Int32 index, T item)
   at Xamarin.Forms.Platform.UWP.ListViewRenderer.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs e)
   at Xamarin.Forms.Internals.TemplatedItemsList`2.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at Xamarin.Forms.Internals.TemplatedItemsList`2.OnProxyCollectionChanged(Object sender, NotifyCollectionChangedEventArgs e)
   at Xamarin.Forms.ListProxy.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at Xamarin.Forms.ListProxy.<>c__DisplayClass33_0.<OnCollectionChanged>b__0()
   at Xamarin.Forms.ListProxy.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs e)
   at Xamarin.Forms.ListProxy.WeakNotifyProxy.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.ObservableCollection`1.InsertItem(Int32 index, T item)
   at System.Collections.ObjectModel.Collection`1.Add(T item)
   at Xamarin.Forms.Controls.Issue1875.MainViewModel.<LoadData>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Xamarin.Forms.Controls.Issue1875.<LoadData>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Xamarin.Forms.Controls.Issue1875.<<-ctor>b__0_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Threading.WinRTSynchronizationContextBase.Invoker.InvokeCore()
```

**Comment by jassmith** [comment]
Feel free to reopen if 1875 starts working

**Comment by paymicro** [comment]
ready!

**Pull request merged**
