### PR TITLE
Calling API not available in all versions

### PR DESCRIPTION
**Pull request by kingces95**
### Description of Change ###

Calling an API not available in all versions of Android.

### Bugs Fixed ###

https://forums.xamarin.com/discussion/comment/267383/#Comment_267383
https://bugzilla.xamarin.com/show_bug.cgi?id=55230

### API Changes ###

None

### Behavioral Changes ###

None

### PR Checklist ###

- [x] Has tests (if omitted, state reason in description)
- [x] Rebased on top of master at time of PR
- [x] Changes adhere to coding standard
- [x] Consolidate commits as makes sense

### CODE REVIEW

**Comment by kingces95** [comment]
Looks like @StephaneDelcroix removed the call entirely. We should remove the comment too if the call's not needed. @rmarinho checked in the file. Do we not need that call? The comment makes it seem like it's a fix for a regression..

**Comment by kingces95** [comment]
@rmarinho, you noted in the channel that because this is a fast renderer that it cannot be a regression. From that I assume it does not need to be backported.

**Comment by rmarinho** [comment]
Sorry may i expressed myself wrong, it has to be backported to 2.3.5 , but **is not a regression** because it's a new feature, it's just a bugfix on a new feature that needs to be cherrypicked to 2.3.5 branch for 2.3.5-pre2

**Comment by kingces95** [comment]
Cherry-picked to 2.3.5; https://github.com/xamarin/Xamarin.Forms/commit/2dba30562cb4db7114207b7095d5660a4ca616a7

**Pull request merged**
