### PR TITLE
Make CancelAnimations an extension method

### PR DESCRIPTION
**Pull request by mattleibow**
### Description of Change ###

All the other extension methods are extension methods... except the cancel.

### Issues Resolved ### 

- fixes #

### API Changes ###

 
 None

### Platforms Affected ### 

- Core/XAML (all platforms)
- iOS
- Android
- UWP

### Behavioral/Visual Changes ###

None

### Before/After Screenshots ### 

Not applicable

### PR Checklist ###

- [ ] Targets the correct branch
- [ ] Tests are passing (or failures are unrelated)

### CODE REVIEW

**Review by rmarinho — APPROVED** [review]

**Comment by mattleibow** [comment]
Is this the right base? should it be 4.8.0?

**Comment by rmarinho** [comment]
Main -> Maui
5.0.0 -> Xamarin.Forms

4.8.0 is just for regressions

**Comment by mattleibow** [comment]
This feels like a "regression" because I want it sooner 😉

**Comment by rmarinho** [comment]
Yeah i don't think so, retarget for 5.0.0!

**Comment by rmarinho** [comment]
i think what you need is a rebase :) @mattleibow

**Comment by mattleibow** [comment]
Lol, yeah. AFK right now.

**Comment by mattleibow** [comment]
There we go! Fixed this PR!

**Comment by samhouts** [comment]
This is _technically_ possibly maybe could be a breaking change in the rarest of circumstances. 

https://github.com/dotnet/csharplang/issues/665 

I'm going to label it as such. Let's see what happens. :D

**Pull request merged**
