### PR TITLE
[Windows] Fix custom fonts not working in NavigationPage

### PR DESCRIPTION
**Pull request by jimmgarrido**
### Description of Change ###

For some reason removing the PageControl.xaml file resolves customs fonts not working inside NavigationPages on Windows. The xaml file doesn't seem necessary since it's empty and the change doesn't seem to break the NavigationPage.

### Bugs Fixed ###

- https://bugzilla.xamarin.com/show_bug.cgi?id=51427

### API Changes ###

None

### Behavioral Changes ###

None hopefully

### PR Checklist ###

- [ ] Has tests (if omitted, state reason in description)
- [x] Rebased on top of master at time of PR
- [x] Changes adhere to coding standard
- [x] Consolidate commits as makes sense

### CODE REVIEW

**Comment by rmarinho** [comment]
I don't understand how this fixes it.

**Comment by rmarinho** [comment]
Can you rebase please @jimmgarrido

**Comment by jimmgarrido** [comment]
Rebased

**Comment by rmarinho** [comment]
@jimmgarrido you need to verify the nuspec and the verify nuspec script

**Comment by hartez** [comment]
@jimmgarrido Here's the output from the script:
```
XBF entry ..\Xamarin.Forms.Platform.WinRT\bin\$Configuration$\PageControl.xbf doesn't have a corresponding XAML file
XBF entry ..\Xamarin.Forms.Platform.WinRT\bin\$Configuration$\PageControl.xbf doesn't have a corresponding XAML file
XBF entry ..\Xamarin.Forms.Platform.UAP\bin\$Configuration$\PageControl.xbf doesn't have a corresponding XAML file
```

Looks like the nuspec still has entries for that XAML file you removed; just need to take those lines out of the nuspec and it should be fine.

**Comment by jimmgarrido** [comment]
@rmarinho @hartez nuspec updated and rebased!

**Comment by StephaneDelcroix** [comment]
@jimmgarrido please add a manual test and merge

**Pull request merged**
