### PR TITLE
Android Entry/Editor disable automatic keyboard dismiss

### LINKED ISSUE #4298: [Android] Refocusing a focused Entry inside the event handler of another view hides and shows the keyboard
### Steps to Reproduce

1. Run the attached repro
2. Focus the entry by tapping on it
3. Keyboard shows up
4. Now, click the button below
5. Keyboard hides and shows again.

### Expected Behavior

On iOS, the keyboard never hides which is a more natural experience than what's happening on Android. I'd expect the keyboard to stay on instead of losing focus due to button tap.

### Reproduction Link

[App1hjl.zip](https://github.com/xamarin/Xamarin.Forms/files/2546214/App1hjl.zip)

### LINKED ISSUE #10703: [Bug] [Android] Editor Focusing is not smooth, the keyboard disappears then appears
### Description
Android Editor focusing is not smooth, when we call Focus( ) the keyboard will blink, it will disappear and then appear again. All I want is to keep the keyboard open when I click a button to send message so I can keep typing. while it works, but the UI is jumping up and down because of that keyboard disappearing then appearing whenever I call Focus( ).

The main problem is that, an Edit shouldn't lose focus when we click a button. just like most chat apps do! I am surprised I am reporting this in 2020 to be honest!

### Steps to Reproduce
1. Run the solution attached, nothing special in there just 4 lines of Xaml.
2. Tap the button, it may not appear from the first time but few taps will let you see it
3. If you are using an emulator don't use the mouse to click the button, the mouse will not reproduce the bug

### Expected Behavior
Keyboard to keep open

### Actual Behavior
Keyboard will close then open

### Workaround
Here is the workaroud that will help you understand the issue [Original Post Here](https://forums.xamarin.com/discussion/56523/entry-cell-loses-focus-on-button-press-in-android-but-not-ios-work-around)

```csharp
public static class AndroidFlags
    {
        public static bool IgnoreFocusChanges { get; internal set; }
    }
```

In my XF page:
```csharp
 void Editor_Focused(object sender, FocusEventArgs e)
        {
            AndroidFlags.IgnoreFocusChanges = true;
        }

void Editor_Unfocused(object sender, FocusEventArgs e)
        {
            AndroidFlags.IgnoreFocusChanges = false;
        }
protected override void OnDisappearing()
        {
            AndroidFlags.IgnoreFocusChanges = false;
            base.OnDisappearing();
        }
```

In Android MainActivity
```csharp
 public override View CurrentFocus
        {
            get
            {
                if (AndroidFlags.IgnoreFocusChanges)
                {
                    return null;
                }

                return base.CurrentFocus;
            }
        }
```

[EditorFocusTest.zip](https://github.com/xamarin/Xamarin.Forms/files/4633876/EditorFocusTest.zip)

### PR DESCRIPTION
**Pull request by sreerajPR**
### Description of Change ###

Currently, there is no provision to avoid automatic dismissal of Keyboard attached to an Entry/Editor in the Android platform, when a user taps anywhere else. This is a required feature in many applications, especially chat applications where the user would expect the Input Keyboard to stay after tapping the "Send" button. This issue was raised earlier in [#2136](https://github.com/xamarin/Xamarin.Forms/issues/2136) and was fixed for iOS alone with PR [#8740](https://github.com/xamarin/Xamarin.Forms/pull/8740). Similar to fix done for iOS, here a new Platform-specific property is added to Entry & Editor which can disable automatic dismissal of Keyboard.

### Issues Resolved ### 

- fixes #10703
- fixes #4298

### API Changes ###

Added:
 - bool InputValue.DismissKeyboardOnOutsideTapProperty { get; set; } //Bindable Property, Android.PlatformSpecific, Default => True

### Platforms Affected ### 

- Android

### Behavioral/Visual Changes ###

If an Editor's /Entry's DismissKeyboardOnOutsideTapProperty (AndroidSpecific Property) is set to false, Keyboard will not dismiss on tapping elsewhere.

### Before/After Screenshots ### 

Not applicable

### Testing Procedure ###
1. Please deploy the Xamarin.Forms.ControlGallery.Android app and open Test Case 10703
2. You will find UI Controls in this order
 a) Editor
 b) Entry
 c) Entry
 d) Button
3. On tapping any of the Entry/Editor controls, the keyboard comes up. 
4. The newly created Android Platform-specific API (which defaults to True) has been set to false for first Editor and Entry.
5. On tapping the button when the focus is on the first Editor or Entry, the keyboard is not dismissed. 
6. But the keyboard dismissed for the last Entry when we tap anywhere (which has been the default behaviour till now).
7. When the focus is on the first Editor, and user taps on Page (not button), Keyboard dismissed. Because a TapGesture has been configured to dismiss the Editor on tapping on the page.

### PR Checklist ###

- [x] Targets the correct branch
- [x] Tests are passing (or failures are unrelated)

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/xamarin/Xamarin.Forms?pullRequest=11191) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/xamarin/Xamarin.Forms?pullRequest=11191) before we can accept your contribution.<br/><br/>:x: sreerajPR [sign now](https://cla.dotnetfoundation.org/xamarin/Xamarin.Forms?pullRequest=11191)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/xamarin/Xamarin.Forms?pullRequest=11191) it.</sub>

**Comment by sreerajPR** [comment]
@divyesh008 Not really. Please check my [comment](https://github.com/xamarin/Xamarin.Forms/issues/10703#issuecomment-654623576).

**Comment by sreerajPR** [comment]
@samhouts Can you please update what is the status of this PR? If some modifications are required from my end, I would love to do that and use this feature from official Xamarin.Forms NuGet package. This will be useful for anyone who is developing a chat-like application. If this PR cannot be merged due to some reason, please update so that I generate package from my fork and use it temporarily until there is another fix for this issue. Thanks.

**Comment by sreerajPR** [comment]
@samhouts @jfversluis  Not really sure if this PR is a good candidate for [Xamarin Community Toolkit](https://github.com/xamarin/XamarinCommunityToolkit) as this PR has got changes in [Android PlatformRenderer class](https://github.com/xamarin/Xamarin.Forms/blob/main/Xamarin.Forms.Platform.Android/PlatformRenderer.cs) also.

**Comment by jfversluis** [comment]
Hey there @sreerajPR thank you so much for your time and effort on this one! Unfortunately we won't be able to add it to Forms anymore. As you already noticed, it might be a good candidate for the Toolkit, although we're not adding too many new things there anymore as well. 

If you're still interested your best bet is probably to open a feature request on the .NET MAUI (Community Toolkit) repo so we can discuss implementing it there. Thank you!

**Pull request closed without merging**
