### PR TITLE
Rename MDP to Flyoutpage

### PR DESCRIPTION
**Pull request by PureWeen**
### Description of Change ###

Rename MDP to Flyoutpage

### API Changes ###
Added:
```C#
	public class FlyoutPage
	{
		Page Flyout,
                Page Detail
	}
```

```C#
	public enum FlyoutLayoutBehavior
	{
		Default = 0,
		SplitOnLandscape = 1,
		Split = 2,
		Popover = 3,
		SplitOnPortrait = 4
	}
```
 

### Platforms Affected ### 

- Core/XAML (all platforms)
- iOS
- Android
- UWP

### Behavioral/Visual Changes ###

None

### Before/After Screenshots ### 

Not applicable

### PR Checklist ###

- [ ] Targets the correct branch
- [ ] Tests are passing (or failures are unrelated)

### CODE REVIEW

**Comment by jsuarezruiz** [comment]
The build is failing in the Tizen project _"'IMasterDetailPageController' is obsolete: 'FLYOUTPAGE'"_.

**Review by jsuarezruiz — CHANGES_REQUESTED** [review]
There are pending changes mostly in the issues project. What will happen to all the tests where `TestMasterDetailPage` is used? Will be changed to use `FlyoutPage`?

**Comment by PureWeen** [comment]
@jsuarezruiz eventually yes but I wanted to keep the CG setup for MDP so the UI tests can validate that it still works

**Review by rmarinho — APPROVED** [review]
Failing tests not related

**Review by jsuarezruiz — APPROVED** [review]

**Comment by Tommigun1980** [comment]
This change broke the NuGets in my project, https://github.com/xamarin/Xamarin.Forms/issues/12224, so I had to revert back to Xamarin.Forms 4 as it may take months for plugins to get updated, in case they ever will.

**Pull request merged**
