### PR TITLE
iOS Cell default bgcolor to transparent

### LINKED ISSUE #7680: [Bug] ListView item background color not set on tap
### Description
On iOS, tapping a ListView item no longer provides visual feedback about which item was tapped. This is a regression; it worked before I updated to XF 4.2.0.815419 and iOS 13.

### Steps to Reproduce

1. Create a ListView such that tapping on an item navigates to another page.
2. On iOS, tap on an item in the ListView.

### Expected Behavior
On finger down, the background of the selected item should turn grey. It should stay grey after finger up and until the page transition is complete.

### Actual Behavior
The background of the selected item remains white and the bottom border of the selected selected line disappears.

### Basic Information

- Version with issue: 4.2.0.815419
- Last known good version: 4.0?
- IDE: VS 16.3.0 (Windows), VS 3.8 (build 1805) (Mac), Xcode 11
- Platform Target Frameworks:
  - iOS: 13.1

### LINKED ISSUE #7850: ListView Selection Color disappeared  on ios 13
### Steps to Reproduce

1.  Download the sample project for List View →https://docs.microsoft.com/en-us/samples/xamarin/xamarin-forms-samples/workingwithlistview/
2. Update Xamarin forms to 4.2.0.848062
3. Run the sample to any device with ios 13

### Expected Behavior
when you tab to the cell view the selection color should be appeared 
### Actual Behavior
the tab event invoked but the selection color not appeared
### Basic Information

- Version with issue: Xamarin 4.2.0.848062
- Last known good version: Xamarin 3.4.0.1008975
- IDE: Visual Studio 2019
- Platform Target Frameworks: 
  - iOS: 
- Affected Devices:
iphone 11 pro max 13.0 and ipad pro 12.9 inch 3rd generation 13.0

### PR DESCRIPTION
**Pull request by jfversluis**
### Description of Change ###

Set the default background color for a cell to transparent

### Issues Resolved ### 

- fixes #7680
- fixes #7850

### API Changes ###

 
 None

### Platforms Affected ### 

- iOS

### Behavioral/Visual Changes ###

To my knowledge, and as far as I have checked with the gallery app, this still works fine so people should not notice any changes. However, people who do some customization with the background color of underlaying elements for these cells might suddenly see something weird.

This change is needed to make the selection work again on apps that are built agains the iOS 13 APIs (see #7680 for some background (hi-hi) information)

This change was imminent also because of the preparation on dark mode support.

### Before/After Screenshots ### 

Before (with Dark Mode, notice the selection is not visible only barely because of the seperator line being gone)

image

After (with Dark Mode)

image

After (without Dark Mode)

image

### PR Checklist ###

- [x] Targets the correct branch
- [x] Tests are passing (or failures are unrelated)

### CODE REVIEW

**Comment by samhouts** [comment]
@jfversluis Can you doublecheck that this isn't a problem? https://github.com/xamarin/Xamarin.Forms/pull/4002#issuecomment-431049817 Thanks!

**Comment by hartez** [comment]
@jfversluis  Maybe we should we limit this to iOS 13 and up? It'd be easy enough to add a version check here. That way, we're definitely not messing up any current apps that run on older iOS versions. Stuff running on iOS 13 might have issues, but they were going to anyway.

**Comment by jfversluis** [comment]
@samhouts shouldn't be a problem, the group background is still intact

image

@hartez that might be a good idea, let me add that

**Comment by samhouts** [comment]
@jfversluis Can you please rebase and run iOS tests? Thanks!

**Comment by jfversluis** [comment]
Kicked off build and tests

**Pull request merged**
