### PR TITLE
Xamarin Forms WPF Backend - Platform Project

### PR DESCRIPTION
**Pull request by mohachouch**
### Description of Change ###

This PR adds support for WPF backend on Xamarin.Forms.

NOTE: This PR only includes the Xamarin.Forms.Platform.WPF project. Other PRs will include maps, nuspec, ControlGallery...

### API Changes (Xamarin.Forms.Core) ###

Added:

public const string Device.WPF = "WPF";

### Behavioral Changes ###

You can create applications for **Windows 7/8/10** with Xamarin.Forms using the WPF backend.

### PR Checklist ###

- [ ] Has tests (if omitted, state reason in description)
- [ ] Rebased on top of master at time of PR
- [ ] Changes adhere to coding standard
- [ ] Consolidate commits as makes sense

### CODE REVIEW

**Comment by rmarinho** [comment]
Can you rebase please @mohachouch

**Comment by mohachouch** [comment]
It's done for the rebase. Regarding the cla I have already signed. :)

**Comment by rmarinho** [comment]
@mohachouch still have conflits

**Comment by davidortinau** [comment]
@mohachouch looks like the CLA tool isn't finding your previously signed CLA. Please hit the link above and do it again. Sorry for the inconvenience.

**Pull request closed without merging**
