### PR TITLE
Fix 6693 - [Bug] [WPF] ViewRenderer does not work properly with FrameworkElement derived native controls

### LINKED ISSUE #6693: [Bug] [WPF] ViewRenderer does not work properly with FrameworkElement derived native controls
### Description
The ViewRenderer contains _wcontrol field that uses 'as' to attempt casting Control to a System.Windows.Controls.Control and uses it to update IsEnabled, Focus, TabStop, TabIndex, and UpdateBackground. For custom controls that derive from FrameworkElement (like SkiaSharp's SKElement), _wcontrol will be null and therefore prevent IsEnabled, Focus, TabStop, TabIndex, and UpdateBackground from functioning.
### Steps to Reproduce

1. Create a custom Xamarin.Forms control 
2. Create a custom renderer for that control with a WPF custom control that derives from FrameworkElement
2. Set IsEnabled to false in Xamarin.Forms (for example) 
3. Notice the native control is not disabled.

### Expected Behavior
Native control is disabled (for example)

### Actual Behavior
Xamarin.Forms IsEnabled property is set to false, but the native control is still enabled

### Basic Information

- Version with issue: Xamarin.Forms v4.1.0.496342-pre2
- Last known good version:
- IDE: Visual Studio 2017
- Platform Target Frameworks: 
  - WPF:   v4.1.0.496342-pre2

### PR DESCRIPTION
**Pull request by ChaseMarsh**
### Description of Change ###
Refactored ViewRenderer to use Control, which is the TNativeElement where T is FrameworkElement. This replaces the use of _wcontrol (System.Windows.Controls.Control) which was preventing FrameworkElement derived controls' IsEnabled property from working.

### Issues Resolved ### 
Fixes #6693 

### API Changes ###
None

### Platforms Affected ### 
WPF

### Behavioral/Visual Changes ###
None

### Before/After Screenshots ### 
Not applicable

### Testing Procedure ###
Added Issue6693.xaml page as well as Issue6693Control with WPF renderer to demonstrate issue fix. Undo changes to ViewRenderer to see issue.

### PR Checklist ###

- [ ] Targets the correct branch
- [ ] Tests are passing (or failures are unrelated)

### CODE REVIEW

**Comment by jfversluis** [comment]
Build fails

> "Xamarin.Forms.Controls.Issues\Xamarin.Forms.Controls.Issues.Shared\Issue6693.xaml.cs(20,4): Error CS0103: The name 'InitializeComponent' does not exist in the current context"

I think you might need to wrap it in a `#if APP` directive

**Comment by ChaseMarsh** [comment]
@samhouts @mohachouch @jfversluis What should be done about the build error CS8314: An expression of type 'TNativeElement' cannot be handled by a pattern of type 'Control' in C# 7.0. Please use language version 7.1 or greater. I'm getting mixed answers searching...from switch the build agent to VS2019, specify the LangVersion to _latest_, to an unintentional bug in VS2019 that should only allow that syntax for C#8. Help?!

**Comment by samhouts** [comment]
Build is failing. Looks like this uses C#7.1, and we're currently only supporting 7.0.

**Comment by PureWeen** [comment]
I think we are on 7.3 and it's controlled by a directory.build.props file

It might be these lines inside the WPF proj that are messing it up

```
<LangVersion>default</LangVersion>
```

@ChaseMarsh can you try removing those from the wpf csproj file and rebasing to master? see if that resolves?

**Comment by ChaseMarsh** [comment]
> I think we are on 7.3 and it's controlled by a directory.build.props file
> 
> It might be these lines inside the WPF proj that are messing it up
> 
> ```
> <LangVersion>default</LangVersion>
> ```
> 
> @ChaseMarsh can you try removing those from the wpf csproj file and rebasing to master? see if that resolves?

@PureWeen I removed the LangVersion, but apparently did something wrong trying to get my fork rebased onto master. Resulted in all the extra commits. Any remedy?

**Comment by PureWeen** [comment]
@ChaseMarsh 

I think this will work

- get your master branch in sync with our master branch
   - https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/syncing-a-fork
- then do
   - git checkout fix-6993
   - git rebase master
   - fix the conflicts (I think there will only be one)
   - Force push

**Comment by ChaseMarsh** [comment]
> @ChaseMarsh
> 
> I think this will work
> 
> * get your master branch in sync with our master branch
>   
>   * https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/syncing-a-fork
> * then do
>   
>   * git checkout fix-6993
>   * git rebase master
>   * fix the conflicts (I think there will only be one)
>   * Force push

Thanks @PureWeen ! I think I fixed it. Now to see if it builds...

**Pull request merged**
