### PR TITLE
SwipeGestureRecognizer

### PR DESCRIPTION
**Pull request by seano2o6**
### Description of Change ###

Added a SwipeGestureRecognizer to Xamarin.Forms which works on iOS, Android and Windows.

### API Changes ###

SwipeGestureGalleryPage.cs
CoreGallery.cs
SwipeGestureRecognizerTests.cs
ISwipeGestureController.cs
SwipeDirection.cs
SwipeGestureRecognizer.cs
SwipeEventArgs.cs
SwipeGestureHandler.cs
GestureManager.cs
VisualElementTracker.cs
EventTracker.cs

### PR Checklist ###

- [x] Has tests (if omitted, state reason in description)
- [x] Rebased on top of master at time of PR
- [x] Changes adhere to coding standard
- [x] Consolidate commits as makes sense

### CODE REVIEW

**Comment by opcodewriter** [comment]
This is great work. Swipe gesture right in the framework is a must have.
When is the PR going to be reviewed?

**Comment by seano2o6** [comment]
It would be nice if we could get some feedback on this PR?

**Comment by rmarinho** [comment]
Is it possible to move this PR to target the 3.0 branch ?

**Comment by seano2o6** [comment]
Yeah sure I can look into putting up a new PR today. @rmarinho

**Comment by rmarinho** [comment]
thanks @seano2o6

**Comment by seano2o6** [comment]
@rmarinho https://github.com/xamarin/Xamarin.Forms/pull/1007

**Comment by vodevil** [comment]
Hi,

Do you have news about the swipe reconizer ?

Thanks

**Comment by seanyda** [comment]
@vodevil It will be released in 3.2.0 Xamarin.Forms.

https://github.com/xamarin/Xamarin.Forms/pull/2727

**Pull request closed without merging**
