### PR TITLE
Use the MoreNavigationController DidShowViewController callback for shell sections

### LINKED ISSUE #6784: [Bug] [Shell] [iOS] ShellItem.CurrentItem not set when selecting shell section aggregated in more tab
### Description

There is this known [issue](https://stackoverflow.com/questions/5803352/didselectviewcontroller-not-getting-called-when-in-more-section) with UITabBarController where didSelectViewController does not trigger for items aggregated in more tab.

`ShellItemRenderer` is relying on [this](https://github.com/xamarin/Xamarin.Forms/blob/78385f9fc1fc56dc88bd98e73bf9c8f2f2d0a90a/Xamarin.Forms.Platform.iOS/Renderers/ShellItemRenderer.cs#L67) to set the `CurrentItem` of the `ShellItem`. For the above reason `ShellItem.CurrentItem` is not set when selecting shell section aggregated in more tab.

#### With debugger

1. Set breakpoint in `ShellItemRenderer.SelectedViewController`
2. Open StoreShell from ControlsGallery
3. Click on Books (aggregated in more tab)
4. Verify breakpoint not getting hit

#### Visually

1. Open StoreShell from ControlsGallery
2. Click on Books (aggregated in more tab)
3. Verify that BooksShell style is not applied (Shell.Background should change to #039BE6) because `CurrentItem` will not get set

### Expected Behavior

`ShellItem.CurrentItem` should be set when selecting shell section aggregated in more tab

### Actual Behavior

`ShellItem.CurrentItem` is not set when selecting shell section aggregated in more tab

### Basic Information

- Platform Target Frameworks:
  - iOS

### PR DESCRIPTION
**Pull request by Dresel**
### Description of Change ###

When `SelectedViewController` is called for `MoreNavigationController`, register for `DidShowViewController` to make it possible to set `ShellItem.CurrentItem` when selecting shell sections aggregated in more tab. Implementation is based on this [SO](https://stackoverflow.com/questions/5803352/didselectviewcontroller-not-getting-called-when-in-more-section) thread.

~~Automated test is skipped because lack of information (is there any guidance available?) of how to setup UI tests for XF.~~

### Issues Resolved ### 

- fixes #6784

### API Changes ###
 
None

### Platforms Affected ### 

- iOS

### Testing Procedure ###

Check #6784.

### PR Checklist ###

- [x] Has automated tests
- [x] Rebased on top of the target branch at time of PR
- [x] Changes adhere to coding standard

### CODE REVIEW

**Comment by samhouts** [comment]
Xamarin.Forms.Core.UnitTests.ShellTests.NavigationBetweenShellContentsPassesQueryString
System.ArgumentException : Duplicated Route: "details"

**Comment by PureWeen** [comment]
@Dresel can you rebase against master? That should fix the unit test error

**Comment by Dresel** [comment]
Rebase done

**Comment by Dresel** [comment]
Currently busy but I'll be able to tackle this latest end of this month

**Comment by woutervanoorschot** [comment]
@PureWeen I think that this is the correct behaviour. At least on iOS it is the default behaviour that a tab stays the same (also within the more page) when navigated to and from. If a page has been opened in the more tab, navigating to another tab and returning to it should return you to the opened page. The second tap returns you to the root of the tab (in the more tab: the list of pages).

This works the same as in other tabs, if you navigate within a tab it stays the same after navigating between tabs. When tapping on a tab which is selected, navigationpage within the tab goes to the root page.

Anyway, very nice that someone is looking after this, as it seems to fix the very long standing issue of the more tab in xamarin.

**Comment by Dresel** [comment]
Sorry, took me longer than expected.

> 
> 
> @Dresel I ran into a slight issue while testing this
> 
> it looks like after you select the item from the more list the first time then it won't reopen the more list when navigating back to it unless you click it twice.

This can be "corrected" by calling PopToRootViewController on the `MoreNavigationController`.

For consistency we should also set `CustomizableViewControllers` to an empty array to avoid the "Edit" button on top of the `MoreNavigationController`:

> This property controls which items in the tab bar can be rearranged by the user. When the user taps the More item on the tab bar view, a custom interface appears displaying any items that did not fit on the main tab bar. This interface also contains an Edit button that allows the user to rearrange the items. Only the items whose associated view controllers are in this array can be rearranged from this interface. If the array is empty or the value of this property is nil, the tab bar does not allow any items to be rearranged.



Let me know if you want this in a separate PR or if I can combine it with this one.

I have rebased and pushed latest changes, let me know what you think.

I'm now working on a UI test case for that, it's a pity that this does not work with remote debugger on windows...

**Comment by woutervanoorschot** [comment]
I think you should combine it in this PR, as it creates inconsistent behavior across platforms if the edit button is visible (as you said already). Just my 2 cents

Great work!

**Comment by Dresel** [comment]
UI test added.

**Comment by Dresel** [comment]
Could not reproduce the failing UI tests (SDK 12.4 build, iPhone X 11.4 simulator).

**Comment by woutervanoorschot** [comment]
@PureWeen any chance this can be included in Xamarin Forms 4.5?

**Pull request merged**
