### PR TITLE
[Android/iOS] support locale LayoutDirection on MasterDetailPage

### LINKED ISSUE #2818: [Android] Right-to-Left MasterDetail in Xamarin.Forms v3 Hamburger icon issue
### Description
We have a masterdetail navigation in our app, the issue is when we set culture to RTL and set FlowDriection to RTL, the Hamburger icon is not going to right side and still is on the left side !
### Steps to Reproduce

1. Add master detail page to your app
2. Set device culture to Arabic or Persian 
3. Set FlowDirection to RTL

### Expected Behavior
Seeing Hamburger and back button on the right side
### Actual Behavior
Seeing Hamburger and back button on the left side
### Basic Information

- Version with issue: 3.0.0.482510
- Last known good version: -
- IDE: Visual Studio 15.7.2
- Platform Target Frameworks: 
  - Android: 8.1
- Android Support Library Version: 27.0.2
- Nuget Packages: Xamarin.Forms 
- Affected Devices: Android Emulator

### PR DESCRIPTION
**Pull request by paymicro**
### Description of Change ###

Support locale LayoutDirection on MasterDetailPage.

### Issues Resolved ### 

- fixes #2818

### API Changes ###
 
 None

### Platforms Affected ### 

- All

### Behavioral/Visual Changes ###

Controls of MasterDetalPage shown on the correct side.

### Before/After Screenshots ### 
Screencast:
http://recordit.co/nlOXpzGDrU

**Android**
Before
before

After
screenshot_3

**iOS**

Before
screenshot_9

After
screenshot_15

screenshot_14

### Testing Procedure ###

**Android**
- setup RTL locale on device
- run Control gallery
- check hamburger position on MasterDetailPage

**iOS**
- setup RTL locale on device
- run Control gallery
- tap/click on "Master" title
- check red box position

### PR Checklist ###

- [ ] Has automated tests 
- [x] Rebased on top of the target branch at time of PR
- [ ] Changes adhere to coding standard

### CODE REVIEW

**Comment by rmarinho** [comment]
build

**Comment by rmarinho** [comment]
Can we add iOS screenshots too?

**Comment by paymicro** [comment]
> do we follow device's RTL setting usually, or do we only follow our own FlowLayout property ?

Apparently we only follow our own FlowLayout property and ignore device RTL...
But root element isn't setted to device RTL if it is implicit

**Comment by PureWeen** [comment]
@paymicro  can you rebase to fix conflict please

**Comment by samhouts** [comment]
We need to make sure that we keep this statement true:

>As with UWP, respecting the device's layout direction based on the selected language/locale is the developer's explicit choice and does not happen automatically. Set the FlowDirection of the root View/Page to the Device.FlowDirection value. All other child views with MatchParent will inherit this value. (#1222)

**Comment by rmarinho** [comment]
@paymicro can you confirm this only happens if setting the property explicitly like @samhouts said?

**Comment by paymicro** [comment]
@rmarinho yes. Set `FlowDirection` works correctly. http://recordit.co/pcNTb0wQnP
This PR is fixes if `FlowDirection` has not been set or it has been set to `MatchParent` and it has no parent, then it will be taken from device's layout.

**Comment by rmarinho** [comment]
"This PR is fixes if FlowDirection has not been set or it has been set" 

But I think we should not settle locale if the user didn't specified

**Comment by samhouts** [comment]
This is not the correct fix. We don't want to use the device locale automatically. We want the user to do that explictly if that is what they want to do. We need to figure out why the hamburger button doesn't respect the FlowDirection property instead of trying to set the FlowDirection property based on the device locale. Thanks!

**Comment by candidodmv** [comment]
@samhouts I need only the navigation menu of MasterDetail page stay on rightToLeft side, everthing else stay on leftToRight, how can I succed after this update? because when I was targeting to version 3.4 working very well.

**Pull request closed without merging**
