### PR TITLE
Forward Orientation Methods in PlatformRenderer and ModalWrapper

### PR DESCRIPTION
**Pull request by maxpiva**
### Description of Change ###

PlatformRenderer and ModalWrapper are Wrappers around the real UIViewController, rotation and orientations methods are not correctly forwarded in IOS. Per example, you cannot programatically lock the rotation of the IOS screen. This changes will fix that.

No Unit test was made. Will do if you need checking, but the code is pretty straightforward.

### Bugs Fixed ###

None

### API Changes ###

None

### Behavioral Changes ###

PlataformRender and ModalWrapper will forward orientation methods from their first child (The Actual Controller).

### PR Checklist ###

- [ ] Has tests (if omitted, state reason in description)
- [ ] Rebased on top of master at time of PR
- [ ] Changes adhere to coding standard
- [ ] Consolidate commits as makes sense

### CODE REVIEW

**Comment by pauldipietro** [comment]
Please format the code to match the coding guidelines and resubmit.

**Comment by hartez** [comment]
@maxpiva I think he's specifically referring to spaces->tabs: https://github.com/xamarin/Xamarin.Forms#coding-style

**Comment by jassmith** [comment]
:+1:

**Comment by jassmith** [comment]
kicked off tests

**Comment by rmarinho** [comment]
Hi @maxpiva we need you to sign the CLA so we can be able to merge this. 

thanks

**Comment by maxpiva** [comment]
CLA Signed.
Regards

**Comment by rmarinho** [comment]
👍

**Pull request merged**
