### PR TITLE
StackLayout should be able to add children on OnAppearing

### PR DESCRIPTION
**Pull request by adrianknight89**
### Description of Change

User claims this was a regression bug between 2.0.1.6505 and 2.1.0.6521. Can't find history to see what happened. Attempting to add a child to an empty `StackLayout` while the page is appearing throws an exception. This is because the code isn't calculating layout when layout information isn't available. 

`_layoutInformation` is initialized at the top of the page. Its value types should have a default value whereas the reference types (`Plots` and `Requests`) are null. Adding a null check fixes the problem.

Also, `LayoutInformation` should be deep copied because of the array fields. There was no issue incorrectly copying the object in the current code, but future use cases can introduce one.
### Bugs Fixed
- https://bugzilla.xamarin.com/show_bug.cgi?id=44910

### CODE REVIEW

**Comment by adrianknight89** [comment]
I think it should be UI tested instead. I'll look into it.

**Comment by StephaneDelcroix** [comment]
this change is only in Core, so it can be unit tested. and if it can be, it should be.

In addition, a UITest or two would not make any damage...

**Comment by adrianknight89** [comment]
I'm having difficulty properly unit testing this. The root of the problem is actually more complex. This bug happens when you are _pushing_ a page that modifies its stacklayout on appearing if the `HorizontalLayoutOptions` and `Padding` (top or bottom) are set at the same time.

You could look at the bug repro (`OnAppearingCrashPageWithStackLayout.xaml`) and see what I'm talking about.

**Comment by adrianknight89** [comment]
I'm going to close this. I think the fix should be made somewhere else, but I don't know where. Although the change I made seems to fix the issue, it's probably hiding the root of the problem.

**Pull request closed without merging**
