### PR TITLE
[Android] Fix ClearButton not working when changing the ClearButtonVisibility while the Entry field is focused (#13819)

### LINKED ISSUE #13819: [Bug] Android: ClearButtonVisibility doesn't work correctly when enabled while the field is already focused
### Description
The clear text button in an Entry field doesn't work on Android when changing ClearButtonVisibility to WhileEditing while the field is already focused. Pressing the button has no effect and does not clear the text. Unfocusing and refocusing the field "fixes" the button.

### Steps to Reproduce

1.  Set ClearButtonVisibility to Never
2. Focus a field and type some text
3. Set ClearButtonVisibility to WhileEditing while focused

### Expected Behavior
Clear button should clear the text

### Actual Behavior
Clear button doesn't do anything.

### Basic Information

- Version with issue: 5.0.0.2012
- Last known good version: No idea
- Platform Target Frameworks: 
  - Android: 10
- Affected Devices: All android

### Reproduction Link

Minimal repro case solution attached in zip file

[XamarinFormsBug.zip](https://github.com/xamarin/Xamarin.Forms/files/6017677/XamarinFormsBug.zip)

### Workaround

Unfocus and refocus the field enables the button again

### PR DESCRIPTION
**Pull request by jgoyvaerts**
### Description of Change ###
Fixed button listener on Clear button not being attached correctly if ClearButtonVisibility was changed while the entry field was already focused

### Issues Resolved ### 
Fixes #13819 

### Platforms Affected ### 
- Android

### Behavioral/Visual Changes ###

None

### Before/After Screenshots ### 

Not applicable

### Testing Procedure ###
Run the test page, type some text in the entry field, press the clear button. If it works, the bug is fixed.

### PR Checklist ###

- [ ] Targets the correct branch
- [ ] Tests are passing (or failures are unrelated)

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/xamarin/Xamarin.Forms?pullRequest=13820) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/xamarin/Xamarin.Forms?pullRequest=13820) before we can accept your contribution.<br/><br/>:x: jgoyvaerts [sign now](https://cla.dotnetfoundation.org/xamarin/Xamarin.Forms?pullRequest=13820)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/xamarin/Xamarin.Forms?pullRequest=13820) it.</sub>

**Comment by jsuarezruiz** [comment]
Rebased latest changes and new Build released.

**Review by jsuarezruiz — APPROVED** [review]
fix-13819

**Pull request merged**
