### PR TITLE
[iOS/Android] Move Map camera to correct region on layout change

### PR DESCRIPTION
**Pull request by adrianknight89**
### Description of Change ###

Move to correct region when `Map` control changes layout. Ref #172.

The repro attached to the bug has two maps in a vertical StackLayout. The second one is invisible on load and made visible on button click. Both maps should have the same camera view when visible; however, the first one is not re-adjusting its view region when control layout changes.

@rmarinho I don't believe checking visibility change on the second map on iOS is the right approach. For now, I removed it. I also ran `Bugzilla38284` on Android device and confirmed that it's not working as it is.

### Bugs Fixed ###

- https://bugzilla.xamarin.com/show_bug.cgi?id=38284
- https://bugzilla.xamarin.com/show_bug.cgi?id=43639 (possibly. There is no repro there, so I can't decide if it represents the same or a different bug.)

### PR Checklist ###

- [ ] Has tests (if omitted, state reason in description)
- [x] Rebased on top of master at time of PR
- [x] Changes adhere to coding standard
- [x] Consolidate commits as makes sense

### CODE REVIEW

**Comment by rmarinho** [comment]
needs rebase

**Comment by adrianknight89** [comment]
Done.

**Comment by rmarinho** [comment]
@adrianknight89 build is failing
` \Bugzilla35736.cs(6, 33): error CS1002: ; expected `

**Comment by adrianknight89** [comment]
I have not touched that file, so why is it failing?

**Comment by rmarinho** [comment]
GalleryTest failure is normal.

**Comment by suggyd** [comment]
It might be only me but I don't feel like using the Element.LastMoveToRegion in this way gives the correct behaviour in all cases because this is only set by calls to Map.MoveToRegion(..) and not when the user interacts with the map.  For example on iOS changing the device orientation triggers Height changes and resets the map view, which is frustrating for users if they have panned or zoomed.  On android anything that triggers OnLayout also resets the view.  The LastMoveToRegion in many cases is an fairly arbitrary starting point, e.g. the current users location, when the map is first shown.  On iOS when the device is rotated I would expect the map to stay centered on the same point at the same zoom level.  On Android if the map is resized I would also expect the map to be centered and zoomed as I left it.

**Pull request merged**
