### PR TITLE
[Android] Fix BottomNavigationItemView issue with MasterDetailPage

### LINKED ISSUE #9143: Android: Master Navigation page displayed as third bottom tabbar item
### Description
We have the following pages structure:
MainPage = MasterDetailPage:
 - Master: a Navigation page with a single Content page
 - Detail: a Tabbed page with 5 tabs:
 --- each tab is a Navigation page with a single Content page in it

Toolbar placement is set to Bottom for Android.

### Steps to Reproduce
Run the attached test project on android device.

### Expected Behavior
Third bottom tabbar item is displayed similar to other tabbar items.
Master page is accessible via the hamburger icon.

### Actual Behavior
Master page is displayed instead of third bottom tabbar item.
Master page is not displayed when tapping on the hamburger icon.

### Basic Information

- Version with issue: 4.3.0.908675
- Last known good version: 4.2.0.910310
- IDE: Visual Studio 2019 (16.4.0) for Windows
- Platform Target Frameworks:
  - Android: 9.0
- Nuget Packages: NETStandard.Library (2.0.3), Xamarin.Essentials (1.3.1)
- Affected Devices: HUAWEI VTR-L09 and others (we experienced this on multiple of our test devices)

### Screenshots
Screenshot_20200120-173631
Screenshot_20200120-173639

### Reproduction Link
[AppWithMenuInsteadOfTabbedItem.zip](https://github.com/xamarin/Xamarin.Forms/files/4041450/AppWithMenuInsteadOfTabbedItem.zip)

### Notes
Looks like the issue was introduced with this pull request: https://github.com/xamarin/Xamarin.Forms/pull/6471 (we reverted this file and the bottom tabbar behaved correctly).
Using random numbers as Ids for MasterDetailContainer also solves the issue (looks like Master navigation page gets the same ID assigned as third bottom tabbar item?).

### PR DESCRIPTION
**Pull request by kvpt**
### Description of Change ###
On certains conditions MasterDetailPage can be in conflict with BottomNavigationView.
Like this : 
Screenshot_1578940463

The issue disappear if the BottomNavigationItem id are correctly set.
The BottomNavigationItem id was 0, 1, 2 ... which seem to cause issue with the ViewPager because these id are already used is others views in Android.
ViewId

I tried to make an UI test case based on the reproduction in #9143, and you know what, impossible to reproduce in the UI test app. The problem seem to only occur during the app start.

### Issues Resolved ### 
- fixes #9143 

### API Changes ###
None

### Platforms Affected ### 
- Android

### Behavioral/Visual Changes ###
None

### Before/After Screenshots ### 
Not applicable

### Testing Procedure ###
Use reproduction in #9143

### PR Checklist ###
- [x] Targets the correct branch
- [x] Tests are passing (or failures are unrelated)

### CODE REVIEW

**Comment by jsuarezruiz** [comment]
@kvpt The fix makes sense to me. However, it would be great if we could add a repro sample to validate it in Core Gallery. I downloaded the repro sample from https://github.com/xamarin/Xamarin.Forms/issues/9143 but there must be an error since it is an App using the empty project template.

The structure that causes the error is:

```
MainPage = MasterDetailPage:

Master: a Navigation page with a single Content page
Detail: a Tabbed page with 5 tabs:
--- each tab is a Navigation page with a single Content page in it
Toolbar placement is set to Bottom for Android.
```

Right?.

**Comment by kvpt** [comment]
@jsuarezruiz The code of the reproduction is in the App.xaml.cs.
I tried to move it in a TestCase, but the issue doesn't appear there.
I don't really understand why it cause a problem with this reproduction and not in the others cases.

**Comment by jsuarezruiz** [comment]
@kvpt Could you attach the repro sample again?. I would like to add a test to validate the issue. I have looked at #9143 but the `App.xaml.cs` in the attached repro sample is empty.

**Comment by kvpt** [comment]
@jsuarezruiz 
It's really strange, I re-checked it and the App.xaml.cs code is present.
I copied it in a gist : https://gist.github.com/kvpt/0e8b099773e3c89e933c09518ef013cf

**Comment by jsuarezruiz** [comment]
I added a repro sample, although I can't reproduce the issue in Core Gallery.

**Comment by PureWeen** [comment]
It seems like this doesn't reproduce because the ID overlap happens here
https://github.com/xamarin/Xamarin.Forms/blob/7a52542d50797ccc69ae1d8dd84259190d96bdb4/Xamarin.Forms.Platform.Android/AppCompat/MasterDetailContainer.cs#L27

Once you're in the context of the gallery the generated ids aren't at a value that will overlap any menu items

**Pull request merged**
