### PR TITLE
Expose the Source for a StyleSheet

### PR DESCRIPTION
**Pull request by kzu**
This would allow previewer/designer/reloader to determine the source of a
stylesheet and refresh its content when appropriate.

### CODE REVIEW

**Comment by kzu** [comment]
@StephaneDelcroix yeah, I wonder why XamlC won't just invoke the instantiated `StyleSheetExtension.ProvideValue`, but ¯\_(ツ)_/¯. In any case, when a custom `ResourceLoader` is present (such as in my case and the previewer), the code-path is different, it goes through `LoadFromXaml` and that in turn goes through the markup extension and calls its [IValueProvider.ProvideValue](https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Xaml/ApplyPropertiesVisitor.cs#L237), so it's properly set for me. The day XamlC switches to invoking the value provider like everything else, things will "just work". I can file a bug for that if you want me to.

I didn't add a unit test for the `StyleSheetExtension` because I couldn't find any for it:

image

**Comment by StephaneDelcroix** [comment]
@kzu 
> I wonder why XamlC won't just invoke the instantiated `StyleSheetExtension.ProvideValue`

it usually does, on custom ValueProvider. but this one is decorated with `[ProvideCompiled]` meaning the `ProvideValue` is short-circuited and everything is resolved at compile time. see https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Build.Tasks/CompiledValueProviders/StyleSheetProvider.cs

A good place to test would be in 
https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Xaml.UnitTests/StyleSheet.xaml
https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Xaml.UnitTests/StyleSheet.xaml.cs

**Comment by kzu** [comment]
There you go. Also, proof that it works with XamlC for the scenario I need.

Also, @jassmith @davidortinau if this doesn't ship in 3.0.0, I'd say it's pointless since I'm not going to take a dependency for Live Reload on an unreleased version of XF that will come who knows when. So this property will be unused until such time when vNext ships (although, for such an optimization, I doubt it will be worth forcing people to 3.0+1 even then... dunno).

**Comment by jassmith** [comment]
This wont make 3.0.0, closing as requested

**Comment by kzu** [comment]
Merge it to master then, some day it may be useful ¯\_(ツ)_/¯

**Comment by kzu** [comment]
It's the only code path we care about. Feel free to modify the test as you see fit.

**Comment by StephaneDelcroix** [comment]
it's a public API, it has to work in the cases you do not care about too... or we can turn that into something internal...

**Comment by kzu** [comment]
And what would those scenarios be @StephaneDelcroix? Because there isn't any other besides the one mentioned in the original description.

Feel free to add more, but blocking this for supposed uses it's not intended to solve (or don't exist, even), doesn't make much sense to me.

**Comment by StephaneDelcroix** [comment]
@kzu serializing a visual tree back to xaml ?

**Comment by kzu** [comment]
Who's asking for that? Is that a true feature request for something you want to support in the product? I can't see how it's related to adding this property anyway. Can't you just traverse the visual tree already with current APIs and turn that into a XAML file? Is there even an API we expose to do that or would someone have to do that manually? 

I also don't know enough of how the XamlC does its codegen to fix whatever is broken, so it would be great if you could take a look and make it work the way you prefer.

**Pull request merged**
