### PR TITLE
Update Platform.cs

### PR DESCRIPTION
**Pull request by dmitrymov**
### Description of Change ###

Added ActionBar is null check

### Bugs Fixed ###

No link. App crash when using NoActionBar theme in Android.

### Behavioral Changes ###

No changes in behavior.

### PR Checklist ###

- [ ] Has tests (if omitted, state reason in description)
- [ ] Rebased on top of master at time of PR
- [ ] Changes adhere to coding standard
- [ ] Consolidate commits as makes sense

### CODE REVIEW

**Comment by StephaneDelcroix** [comment]
this probably does not even compile 👎

**Comment by dmitrymov** [comment]
Why do you think so?
I just added:
`((Activity)_context).ActionBar == mull ||`
to the **if** condition

**Comment by StephaneDelcroix** [comment]
what's `mull` ?

**Comment by dmitrymov** [comment]
Sorry, my bad. Its suppose to be **null**.

**Comment by StephaneDelcroix** [comment]
actually, you're supposed to test your changes before sending a PR :)

**Comment by dmitrymov** [comment]
You are rigth :)

**Pull request closed without merging**
