### PR TITLE
[GTK] Fix wrong indentation using spaces instead of tabs

### PR DESCRIPTION
**Pull request by ylatuya**
### Description of Change ###

Fix wrong indentation in some files in the GTK backend project that are using tabs instead of spaces

For those using auto-indentation in vs4mac having different indentations and policies makes it harder to contribute to the project.

It would be also nice to have the code formatting policies added at the solution level so it's easier for contributors to follow to same code formatting standard.

### CODE REVIEW

**Comment by samhouts** [comment]
Per the [Coding Style](https://github.com/xamarin/Xamarin.Forms#coding-style):
>We use hard tabs over spaces. You can change this setting in VS 2015 via Tools > Options and navigating to Text Editor > C# and selecting the "Keep tabs" radio option. In Visual Studio for Mac it's set via preferences in Source Code > Code Formatting > C# source code and disabling the checkbox for Convert tabs to spaces.

**Comment by ylatuya** [comment]
Most of the files in the Xamarin.Forms.Platform.Gtk uses spaces instead of tabs, that's why I though the default was spaces instead of tabs :) I will fix this PR fixing it the other way around, changing spaces with tabs in the rest of the files.

I know how to change the settings on the IDE, but the format policies can be also included in the solution file and it would avoid inconsistencies in the formatting like the ones in the Xamarin.Forms.Platform.Gtk project

Example of a solution including them:
```
	GlobalSection(MonoDevelopProperties) = preSolution
		Policies = $0
		$0.DotNetNamingPolicy = $1
		$1.DirectoryNamespaceAssociation = PrefixedHierarchical
		$0.TextStylePolicy = $2
		$2.FileWidth = 80
		$2.scope = text/x-csharp
		$2.TabsToSpaces = True
		$0.CSharpFormattingPolicy = $3
		$3.scope = text/x-csharp
		$0.TextStylePolicy = $4
		$4.FileWidth = 80
		$4.TabsToSpaces = True
		$4.scope = text/plain
		$0.TextStylePolicy = $5
		$5.inheritsSet = null
		$5.scope = application/config+xml
		$0.XmlFormattingPolicy = $6
		$6.inheritsSet = null
		$6.scope = application/config+xml
		$0.TextStylePolicy = $7
		$7.inheritsSet = null
		$7.scope = application/xml
		$0.XmlFormattingPolicy = $8
		$8.scope = application/xml
		$0.TextStylePolicy = $9
		$9.inheritsSet = null
		$9.scope = application/android+xml
		$0.XmlFormattingPolicy = $10
		$10.inheritsSet = null
		$10.scope = application/android+xml
		$0.TextStylePolicy = $11
		$11.inheritsSet = null
		$11.scope = application/xaml+xml
		$0.XmlFormattingPolicy = $12
		$12.inheritsSet = null
		$12.scope = application/xaml+xml
		$0.TextStylePolicy = $13
		$13.inheritsSet = null
		$13.scope = text/x-json
		$0.JSONFormattingPolicy = $14
		$14.AutoStructureCompletion = True
		$14.BracePositions = SemiExpanded
		$14.FormatOnPaste = True
		$14.scope = text/x-json
		$0.TextStylePolicy = $15
		$15.inheritsSet = null
		$15.scope = text/x-web
		$0.TextStylePolicy = $16
		$16.inheritsSet = null
		$16.scope = text/x-vs
		$0.TextStylePolicy = $17
		$17.inheritsSet = null
		$17.scope = application/vnd.apple-xcode-storyboard
		$0.XmlFormattingPolicy = $18
		$18.inheritsSet = null
		$18.scope = application/vnd.apple-xcode-storyboard
		$0.StandardHeader = $19
	EndGlobalSection
```

**Comment by jassmith** [comment]
Unfortunately this is a total history destruction kind of deal so we're not going to take this PR :( It would be nice but it means anything before this PR in any of these files is effectively lost when trying to do things like git blame. Maybe there is a way around this I dont know, if there is please feel free to re-open and drop some knowledge on me :)

**Comment by ylatuya** [comment]
This makes contributing to Xamarin.Forms very difficult, specially when trying to follow the coding style defined by your team. Auto-indentation is a key feature in any IDE and loot of people use with VS and vs4mac, and with the current status of Xamarin.Forms.Platform.Gtk it's impossible to use. If standards for coding style are not set and respected code will get worst long term.
How will reviews be done on those files not following the coding style? Does new code need to respect the file indentation or the coding style?

**Comment by ylatuya** [comment]
And there is a way in git to ingore spaces/tabs with the --ignore-all-space switch:
git log -p --ignore-all-space Xamarin.Forms.Platform.GTK

**Pull request closed without merging**
