### PR TITLE
Creating category constants for UI test categories

### PR DESCRIPTION
**Pull request by hartez**
### Description of Change

Breaking down UI tests into smaller categories for smaller Test Cloud runs

### CODE REVIEW

**Comment by adrianknight89** [comment]
@hartez I haven't played around with Test Cloud yet, but just out of curiosity, can those small batches be run in parallel with multiple devices/VMs? Seems like it would reduce the total running time every time the entire suite of tests is triggered. Not sure if you guys are doing something similar already (i.e. parallelization).

**Comment by StephaneDelcroix** [comment]
@hartez I hate those enums, they clutter my IDE search results why looking for, say, `Label`, the Top Result is the enum, not the class :(

**Comment by hartez** [comment]
@StephaneDelcroix What enums?

**Comment by hartez** [comment]
@adrianknight89 - yes, Test Cloud can run tests in parallel on multiple devices. In fact, that's how we run them by default. And that _does_ make an individual set of tests run faster in theory. In practice, several limitations outside our control prevent us from running every single set of UI tests in parallel.

Even if we could, each test run takes a long time (it's a few hundred multi-step tests) and we don't get the results back until the test run is finished. By breaking the tests up into smaller batches, we start getting test feedback much earlier, and a device falling over in the middle of a test run costs us less.

**Pull request merged**
