### PR TITLE
Don't reset implicit style (#6635)

### LINKED ISSUE #6635: [Bug] Template applied several times
### Description

I have a `MyViewA` derived from `TemplatedView` and `MyViewB` derived from `MyViewA`.
The `ControlTemplate` of `MyViewB` is set to a `MyLabel` derived from `Label`. The c-tor of `MyLabel` is called two times! I am using a Label derived class just so I can see the number of times the c-tor is called, any other view would work.

While trying to debug the root cause of the issue, I noticed that the 
`TemplateUtilities:OnControlTemplateChanged(BindableObject bindable, object oldValue, object newValue)` is called 3 times for `bindable` parameter of type `MyViewB`:

**oldValue**: null, **newValue**: ControlTemplate instance (this is when `MyLabel` is created 1st time)
**oldValue**: ControlTemplate instance, **newValue**: null
**oldValue**: null, **newValue**: ControlTemplate instance (this is when `MyLabel` is created 2nd time)

It looks to me like the ControlTemplate is removed and set back.

Also, if `MyViewB` derives from `TemplatedView` instead of deriving from `MyViewA` it works correctly! `MyLabel` is only entered once! So apparently the issue is related with the hierarchy and implicit style.

### Steps to Reproduce

```
    class MyViewA : TemplatedView
    {
    }

    class MyViewB : MyViewA
    {
    }

    class MyLabel : Label
    {
        static int _iCount;

        public MyLabel()
        {
            ++_iCount;
            Text = $"Created {_iCount} times";
        }
    }
```

```
   <Application.Resources>
        <ResourceDictionary>
            <Style TargetType="app:MyViewA">
                <Style.Setters>
                    <Setter Property="ControlTemplate">
                        <ControlTemplate>
                            <StackLayout />
                        </ControlTemplate>
                    </Setter>
                </Style.Setters>
            </Style>

            <Style TargetType="app:MyViewB">
                <Style.Setters>
                    <Setter Property="ControlTemplate">
                        <ControlTemplate>
                            <app:MyLabel />
                        </ControlTemplate>
                    </Setter>
                </Style.Setters>
            </Style>
        </ResourceDictionary>
    </Application.Resources>
```

### Actual Behavior

The c-tor of `MyLabel` should be called once.

### Basic Information

- Version with issue: I tried with XF code compiled from master
- Last known good version: I don't know
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android: 9.0  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Reproduction Link

[TemplateIssueApp.zip](https://github.com/xamarin/Xamarin.Forms/files/3318525/TemplateIssueApp.zip)

### PR DESCRIPTION
**Pull request by andreinitescu**
### Description of Change ###

During my investigation for #6635 I saw that `ImplicitStyle` is set to null before the `while` loop which is actually calculating the implicit style to apply:

		void OnImplicitStyleChanged()
		{
			var first = true;
			ImplicitStyle = null;
			foreach (BindableProperty implicitStyleProperty in _implicitStyles)
			{
				var implicitStyle = (Style)Target.GetValue(implicitStyleProperty);
				if (implicitStyle != null)
				{
					if (first || implicitStyle.ApplyToDerivedTypes)
					{
						ImplicitStyle = implicitStyle;
						return;
					}
				}
				first = false;
			}
		}

https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Core/MergedStyle.cs#L108

 This change makes sure the implicit style is set to `null` only when the `while` loop didn't set an implicit style in order to prevent re-applying the implicit style.

### Issues Resolved ### 

- fixes #6635

### API Changes ###

 
 None

### Platforms Affected ### 

- Core/XAML (all platforms)
- iOS
- Android
- UWP

### Behavioral/Visual Changes ###

None

### Before/After Screenshots ### 

Not applicable

### PR Checklist ###

- [ ] Has automated tests 
- [x] Rebased on top of the target branch at time of PR
- [x] Changes adhere to coding standard

### CODE REVIEW

**Comment by andreinitescu** [comment]
I had to update the description

**Comment by andreinitescu** [comment]
Can please get this prioritized to get released sooner than vNext+1 (which would mean several months)? It has an important impact when using implicit styles, which is very common to have in almost every app. Thank you.

**Comment by kvpt** [comment]
I think it's an automation in function of the branch you target.
I you target master it's vNext+1.

**Comment by andreinitescu** [comment]
@kvpt Thanks. How do I know which branch to target so it gets released as soon as possible?
Currently, 4.0.0.497661 is the most recent released version. Is there any other 4.0.x release planned? Or now it's only 4.1.x planned? I think the team can always merge from master to a release branch.

**Comment by StephaneDelcroix** [comment]
@andreinitescu please rebase and retarget to 4.1

**Comment by andreinitescu** [comment]
@StephaneDelcroix Done.

Do you have any general advice, can I just always try to target the next version? Thanks.

**Comment by StephaneDelcroix** [comment]
@andreinitescu as a rule of thumb, bug fix goes to the latest branch (4.1) at this time, and new features goes to master. when 4.1 hit stable, we will branch for 4.2 and so on.

that's the rule, then there are the exceptions...

**Comment by andreinitescu** [comment]
@StephaneDelcroix Thanks for letting me know so I can understand.

However, to make it easier, when I open a PR with an enhancement I think it makes sense to still target the current vNext branch (4.1.0 in this case) because it's much easier than targeting master and than having to rebase against vNext+1, it's much less work to do. I sometimes had to spent a lot of time resolving conflicts.

**Pull request merged**
