### PR TITLE
VisualStateManager - Bindable CurrentState

### LINKED ISSUE #5864: [Enhancement] binding VisualStateManager.CurrentState
## Summary

Basically a way to control the current state based on a Bindable Property

## API Changes

N/A

## Intended Use Case

Maybe the idea is not applicable, but basically would be a way to set the current VisualState of a View based of a current value of your bindable context. 

imagine a list of items which state would be :
* read
* new
* not applicable 
* ...

each of these states has any rules, that would be applicable by the value of the item.

### PR DESCRIPTION
**Pull request by KSemenenko**
### Description of Change ###
Adding **VisualStateManager.CurrentState** property, 
and **VisualStateManager.GetCurrentState(VisualElement element)** method
### Issues Resolved ### 

- fixes #5864

### API Changes ###
Added:
``` cs
VisualStateManager.CurrentState {get;set;}
```
VisualStateManager:
```cs
string GetCurrentState(VisualElement element)
```
### Platforms Affected ### 
- Core/XAML (all platforms)

### Behavioral/Visual Changes ###

None

### Before/After Screenshots ### 
Not applicable

### Testing Procedure ###
1. Open ControlGallery
2. Open "VisualStateManager Gallery"
3. Press VisualStates Bindable CurrentState
4. Press buttons

### PR Checklist ###

- [x] Targets the correct branch
- [x] Tests are passing (or failures are unrelated)

### CODE REVIEW

**Comment by KSemenenko** [comment]
@StephaneDelcroix @hartez @kingces95 @samhouts  Maybe you have already watched this PR and have any comments?

**Comment by KSemenenko** [comment]
@StephaneDelcroix @hartez @kingces95 I updated the branch from the last develop

**Comment by KSemenenko** [comment]
@samhouts @StephaneDelcroix @hartez @kingces95
any updates?

**Comment by KSemenenko** [comment]
@samhouts @PureWeen 
any updates?

**Comment by samhouts** [comment]
@KSemenenko It's on our list to review! It's a big list... 😆

**Comment by hartez** [comment]
@KSemenenko What is this for? What problem does it solve?

**Comment by KSemenenko** [comment]
@hartez This is to find out the current state, and change it from the ViewModel.
Now it’s difficult to do this. In current implementation we need to write extra code to get link to ViewElement and so on.
I think Bindable CurrentState is a good option for VSM

**Comment by PureWeen** [comment]
@KSemenenko how does this improve the story over StateTriggers?

You can bind to a StateTrigger
https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/triggers#state-trigger

which will activate/deactive current states.

Plus the StateTrigger behavior has built in logic already for calculating things like state priorities etc... 

For example if you activate multiple state triggers and things like that.

**Comment by KSemenenko** [comment]
@PureWeen I think this code was made a long time ago before StateTrigger. So I don’t think that it is doing anything special :)

**Comment by KSemenenko** [comment]
Perhaps this PR is too old and can be closed.

**Comment by PureWeen** [comment]
Sounds good 👍 Thank you as always @KSemenenko

**Pull request closed without merging**
