### PR TITLE
Fix 15052 NullReferenceException when returning null from DataTemplateSelector

### LINKED ISSUE #15052: [Bug] NullReferenceException when returning null from DataTemplateSelector.OnSelectTemplate
### Description

Returning null from `DataTemplateSelector.OnSelectTemplate(object item, BindableObject container)` results in `NullReferenceException`s. The [Xamarin documentation](https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.datatemplateselector.onselecttemplate?view=xamarin-forms#returns) from MS isn't clear on this being valid or not, However, the [WPF documentation](https://docs.microsoft.com/en-us/dotnet/api/system.windows.controls.datatemplateselector.selecttemplate?view=windowsdesktop-6.0#returns) is clear that null is a valid return value. 

I've always returned null as a default case for desktop apps, and I am surprised this is throwing in Xamarin. It seems reasonable that null would be valid, since the absence of a DataTemplate definition for various `ItemTemplate` properties works without incident. 

### Steps to Reproduce

1. Load and run the provided example
2. Select the VerticalListDataTemplateSelector Page and receive the exception.

### Expected Behavior

Returning null from `DataTemplateSelector.OnSelectTemplate(object item, BindableObject container)` should result in the item being displayed in the default manner, as if the `ItemTemplate` property wasn't set at all. 

### Actual Behavior

See lines 13/14 in `CollectionViewDemos\Controls\MonkeyDataTemplateSelector.cs`

NullReferenceExceptions from a variety of different places. This particular example throws here:

```
**System.NullReferenceException:** 'Object reference not set to an instance of an object.
  at Xamarin.Forms.Platform.Android.TemplatedItemViewHolder.Bind (System.Object itemBindingContext, Xamarin.Forms.ItemsView itemsView, System.Action`1[T] reportMeasure, System.Nullable`1[T] size) [0x0008d] in C:\Advanced Dev\Xamarin.Forms\Xamarin.Forms.Platform.Android\CollectionView\TemplatedItemViewHolder.cs:81 
  at Xamarin.Forms.Platform.Android.ItemsViewAdapter`2[TItemsView,TItemsViewSource].BindTemplatedItemViewHolder (Xamarin.Forms.Platform.Android.TemplatedItemViewHolder templatedItemViewHolder, System.Object context) [0x00001] in C:\Advanced Dev\Xamarin.Forms\Xamarin.Forms.Platform.Android\CollectionView\ItemsViewAdapter.cs:140 
  at Xamarin.Forms.Platform.Android.StructuredItemsViewAdapter`2[TItemsView,TItemsViewSource].BindTemplatedItemViewHolder (Xamarin.Forms.Platform.Android.TemplatedItemViewHolder templatedItemViewHolder, System.Object context) [0x00042] in C:\Advanced Dev\Xamarin.Forms\Xamarin.Forms.Platform.Android\CollectionView\StructuredItemsViewAdapter.cs:103 
  at Xamarin.Forms.Platform.Android.ItemsViewAdapter`2[TItemsView,TItemsViewSource].OnBindViewHolder (AndroidX.RecyclerView.Widget.RecyclerView+ViewHolder holder, System.Int32 position) [0x00044] in C:\Advanced Dev\Xamarin.Forms\Xamarin.Forms.Platform.Android\CollectionView\ItemsViewAdapter.cs:76 
  at Xamarin.Forms.Platform.Android.StructuredItemsViewAdapter`2[TItemsView,TItemsViewSource].OnBindViewHolder (AndroidX.RecyclerView.Widget.RecyclerView+ViewHolder holder, System.Int32 position) [0x00074] in C:\Advanced Dev\Xamarin.Forms\Xamarin.Forms.Platform.Android\CollectionView\StructuredItemsViewAdapter.cs:92 
  at Xamarin.Forms.Platform.Android.SelectableItemsViewAdapter`2[TItemsView,TItemsSource].OnBindViewHolder (AndroidX.RecyclerView.Widget.RecyclerView+ViewHolder holder, System.Int32 position) [0x00001] in C:\Advanced Dev\Xamarin.Forms\Xamarin.Forms.Platform.Android\CollectionView\SelectableItemsViewAdapter.cs:22 
  at Xamarin.Forms.Platform.Android.GroupableItemsViewAdapter`2[TItemsView,TItemsViewSource].OnBindViewHolder (AndroidX.RecyclerView.Widget.RecyclerView+ViewHolder holder, System.Int32 position) [0x00057] in C:\Advanced Dev\Xamarin.Forms\Xamarin.Forms.Platform.Android\CollectionView\GroupableItemsViewAdapter.cs:64 
  at AndroidX.RecyclerView.Widget.RecyclerView+Adapter.n_OnBindViewHolder_Landroidx_recyclerview_widget_RecyclerView_ViewHolder_I (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_holder, System.Int32 position) [0x00010] in D:\a\1\s\generated\androidx.recyclerview.recyclerview\obj\Release\monoandroid9.0\generated\src\AndroidX.RecyclerView.Widget.RecyclerView.cs:581 
  at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.65(intptr,intptr,intptr,int)
```
### Basic Information

- Version with issue: 5.0.0.1874
- Last known good version: none
- Platform Target Frameworks: All

### Reproduction Link

[CollectionViewDemos.zip](https://github.com/xamarin/Xamarin.Forms/files/7865548/CollectionViewDemos.zip)

### Workaround

None that comes to mind at the present.

### PR DESCRIPTION
**Pull request by bakerhillpins**
### Description of Change ###

Allows DataTemplateSelector implementations to return null from `DataTemplateSelector.OnSelectTemplate(object item, BindableObject container)`. This will result in the display of the item/element as if the related DataTemplate were not assigned at all/is null.

### Issues Resolved ### 

- fixes [](https://github.com/xamarin/Xamarin.Forms/issues/15052) #15052

### API Changes ###
 
 None

### Platforms Affected ### 

- Core/XAML (all platforms)
- iOS
- Android
- UWP

### Behavioral/Visual Changes ###

None

### Before/After Screenshots ### 

Not applicable

### Testing Procedure ###

I've attempted to add some simple tests to the Core.UnitTests project.

I've also been executing various xamarin_forms_samples projects where I've altered the code so that DataTemplateSelector implementations return null. I'll add those projects as I clean them up.

NOTE: I've needed to run with Microsoft.NETCore.UniversalWindowsPlatform 6.2.13 on my UWP test apps or I'll get `ExecutionEngineException`s when null is returned from the selectors. Once I upgrade that NuGet my changes seem to correct the remaining problems.

Test Projects: (NOTE: these currently reference released Xamarin.Forms and as such will fail)
[Selector.zip](https://github.com/xamarin/Xamarin.Forms/files/7914648/Selector.zip)
[FlyoutTest.zip](https://github.com/xamarin/Xamarin.Forms/files/7916132/FlyoutTest.zip)
[groupingSampleListView.zip](https://github.com/xamarin/Xamarin.Forms/files/7916700/groupingSampleListView.zip)
[CollectionViewDemos.zip](https://github.com/xamarin/Xamarin.Forms/files/7916781/CollectionViewDemos.zip)
[TabbedPageDemo.zip](https://github.com/xamarin/Xamarin.Forms/files/7916884/TabbedPageDemo.zip)

### PR Checklist ###

- [ ] Targets the correct branch
- [ ] Tests are passing (or failures are unrelated)

### CODE REVIEW

**Comment by jfversluis** [comment]
Awesome stuff @bakerhillpins thanks so much for your help here! Feel free to ping me when you think this is good to go or you need anything :)

**Comment by bakerhillpins** [comment]
@jfversluis  LOL... you asked for it.  Might not be the right place but I can't continue testing/fixing without getting this to work:

I can't get my local xamarin.forms build (windows machine) of the UAP dll to build/execute in a test project.  Android/iOS work fine. When I use a released version of Xamarin.Forms (5.0.0.2291) my UWP project runs with no problems. Update to my locally built NuGet and I get the following Warning:

```
warning MSB3277: There was a conflict between "Microsoft.UI.Xaml.Markup, Version=0.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, ContentType=WindowsRuntime" and "Microsoft.UI.Xaml.Markup, Version=10.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35".
```

Which follows up with a bunch of these errors:
```
error MSB3030: Could not copy the file "C:\Users\bryan.roth\.nuget\packages\xamarin.forms\9.9.2\lib\uap10.0.16299\Xamarin.Forms.Platform.UAP\FormsAutoSuggestBoxStyle.xbf" because it was not found.
```

After a bit of poking around it seems that my local build has a dependency built into it that the production Xamarin.Forms.Platform.UAP.dll does not:

Local:
image

Release (5.0.0.2291):
image

Which is in the project but I can't seem to figure out where it comes from???

image

**Comment by jfversluis** [comment]
Haha glad you figured it out! :D

**Comment by bakerhillpins** [comment]
@jfversluis  I'm testing my changes and have a question for you about `ItemsView.EmptyViewTemplate`.  It's not working [as described here](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/collectionview/emptyview#choose-an-emptyviewtemplate-at-runtime).  The code that's detailed in that section is present in the Xamarin_Forms_Samples CollectionViewDemos project [in this file](https://github.com/xamarin/xamarin-forms-samples/blob/main/UserInterface/CollectionViewDemos/CollectionViewDemos/Views/EmptyView/EmptyViewDataTemplateSelectorPage.xaml).  However, when you search the DataTemplateSelector.OnSelectTemplate is never called. Search isn't coming up with a bug.

So, can you tell me if the documentation details the correct expected behavior?  The code that's responsible for the application of the EmptyViewTemplate [for UAP is here](https://github.com/xamarin/Xamarin.Forms/blob/8f765bd87a2968bef9c86122d88c9c47be9196d2/Xamarin.Forms.Platform.UAP/CollectionView/ItemsViewRenderer.cs#L388). And it's coded to completely ignore the DataTemplate unless the EmptyView is of a type other than `string `or `View`.

Other platforms operate the same so I'm unsure if this is expected or not..

**Comment by bakerhillpins** [comment]
@jfversluis  Sorry for the earlier distractions. 

I'm at the point where I think I've got it all completed. Few things:

1. I don't really know how to test the Tizen code. Never even looked at that stuff before.
2. I've tried all the collection based code I can find. See attached test projects. I'm reviewing the the remainder of the system to see what else there is but I'm really just searching. Do you know of any other support for DataTemplateSelectors outside of collection based controls?
3. I could add Issue tests to the Xamarin source but I have no idea how to validate they work (build/run these tests). Suggestions or should we leave it be?
4. WRT MultiPage default content. It's just a [Page/ContentPage with the title set](https://github.com/xamarin/Xamarin.Forms/blob/8f765bd87a2968bef9c86122d88c9c47be9196d2/Xamarin.Forms.Core/CarouselPage.cs#L21). When this renders it looks empty. If we databound a simple view it would at least print out the Type.Name on the screen.
5. WRT UWP - the default template is rather simplistic and has results in the Header View being clipped a bit with CollectionViews. I didn't really concern myself with this since it's basically operating on no definition from the user rather than crashing. Do we need to adjust this?
image


At the moment that's it. Any comments? Should I move this out of draft?

**Comment by bakerhillpins** [comment]
@jfversluis 
> 4\. WRT MultiPage default content. It's just a [Page/ContentPage with the title set](https://github.com/xamarin/Xamarin.Forms/blob/8f765bd87a2968bef9c86122d88c9c47be9196d2/Xamarin.Forms.Core/CarouselPage.cs#L21). When this renders it looks empty. If we databound a simple view it would at least print out the Type.Name on the screen.

Ok, For the above[ I changed the default template in these cases](https://github.com/xamarin/Xamarin.Forms/pull/15074/commits/1db1c3e85d1effd7ee7bb40d6a39681a6740d8a6) to carry simple label content bound to the object to get something visual on the page (object.ToString).  This way when folks drop a template something's displayed rather than just blank.

At the moment I'm unable to resolve what's going on [in this method: `OnViewTemplateChanged`. ](https://github.com/xamarin/Xamarin.Forms/blob/8f765bd87a2968bef9c86122d88c9c47be9196d2/Xamarin.Forms.Core/Shell/ShellTemplatedViewManager.cs#L43) There are several things I can't make sense out of:

1. The view data `currentViewData` is being cast to a View? I'd expect this to be Item/context data not a View object. 
2.  The CreateContent extension method is being called with `newViewTemplate` as the `item` parameter rather than the `currentViewData` object?
3. If you search for where this method is called, it's actually called from the BindableProperty's OnData**Changing** method? Yet this method is named On**Changed** method.

I think this is what the method really should be:
```
{
	View newContentView  = null;

	DataTemplate template = newViewTemplate?.SelectDataTemplate(currentViewData, shell);

	if (template != null)
	{
		newContentView = (View)template.CreateContent(newViewTemplate, shell);
	}

	SetView(ref localViewRef,
		newContentView,
		OnChildRemoved,
		OnChildAdded);
}
```

**Comment by bakerhillpins** [comment]
Bindable Layout EmptyDataTemplate fixed but found #15093 

@jfversluis - I've not heard from you with regard to my questions so I'm just going to put this into review.

**Comment by bakerhillpins** [comment]
I'd like to understand how to validate platform tests before I commit them.

**Comment by jfversluis** [comment]
> I'd like to understand how to validate platform tests before I commit them.

Not sure what you mean by this? I ran the build and all the unit tests seem green? :)

**Comment by bakerhillpins** [comment]
> > I'd like to understand how to validate platform tests before I commit them.
> 
> Not sure what you mean by this? I ran the build and all the unit tests seem green? :)

@jfversluis Sorry for the confusion. I did put in some Xamarin.Forms.Core.UnitTests which can be run on windows.

I also authored one or two tests in the Platform.UnitTests space (e.g. Xamarin.Forms.Platform.Android.UnitTests) since I figured you'd prefer to have some included. Just a few to test the process, but I didn't commit them because I don't have instructions on how to execute the Platform based tests => The runner fails because I don't have Mono Android. This isn't surprising as I'm on a windows box but I wasn't sure if there was a way to do this besides checking them in and hoping that the Azure Pipelines don't fail.

**Comment by jfversluis** [comment]
I see the new and old tests popping up here and succeeding: https://dev.azure.com/xamarin/public/_build/results?buildId=53229&view=ms.vss-test-web.build-test-results-tab

**Comment by bakerhillpins** [comment]
I'm sorry, I'm not doing a good job of explaining myself I guess. 

Is there any way to run Platform tests locally on my laptop?

**Comment by jfversluis** [comment]
Ah sorry about that! :) 

I think they are being ran as part of the UI tests. In the UITest project for Android you can see the PlatformUnitTest project is referenced. You can run them locally, but it might be easier to just commit them and see what it does in the pipeline :)

**Comment by jfversluis** [comment]
Now that we're so close to the sunsetting of Xamarin.Forms unfortunately we won't be able to take this in anymore, we're really sorry about that. Nevertheless, thank you so much for your time and effort that you have put into this PR.

Please have a look at the evolution of Xamarin.Forms, [.NET MAUI](https://github.com/dotnet/maui). A lot of development has been going on there. Hopefully this issue was already fixed in that codebase. If not, feel free to port this over to there.

Again, thank you so much for being a contributor and Xamarin.Forms user!

**Pull request closed without merging**
