### PR TITLE
[UWP] Update Alert and ActionSheet implementations

### PR DESCRIPTION
**Pull request by jimmgarrido**
### Description of Change ###

Currently on UWP

- Alert uses a MessageDialog, which is [no longer reccommend](https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Popups.MessageDialog#remarks)
- ActionSheet uses a ContentDialog which [may not be the best control](https://docs.microsoft.com/en-us/windows/uwp/controls-and-patterns/dialogs#dialogs-vs-flyouts). For example, the ActionSheet cannot be dismissed by touching outside of it unlike on other platforms.
- On Windows 10 v1493, the ActionSheet has a styling issue where there is no padding around the content

This pull requests resolves the above by

- Implementing Alert to use a ContentDialog instead so it is consistent with the Windows 10 UI

- Utilizing a Flyout for ActionSheet so it behaves more like previous Windows versions and other platforms.  

I used the existing tests in the ControlGallery to verify that there are no new crashes.

### Bugs Fixed ###

- https://bugzilla.xamarin.com/show_bug.cgi?id=46530
- https://bugzilla.xamarin.com/show_bug.cgi?id=53798

### API Changes ###

None

### Behavioral Changes ###

ActionSheet can be dismissed without selecting an option, however this brings the behavior inline with previous Windows versions.

### PR Checklist ###

- [x] Has tests (if omitted, state reason in description)
- [x] Rebased on top of master at time of PR
- [x] Changes adhere to coding standard
- [x] Consolidate commits as makes sense

### CODE REVIEW

**Comment by rmarinho** [comment]
@jassmith can you take a look?

**Comment by rmarinho** [comment]
Windows builds are failing

**Comment by hartez** [comment]
@jimmgarrido Looks like the nuspec verification is failing, do you need to add an `.xbf` entry to the nuspec?

**Comment by jimmgarrido** [comment]
nuspec updated and branch rebased

**Comment by rmarinho** [comment]
build

**Comment by rmarinho** [comment]
@jimmgarrido sorry needs rebase again :p

**Comment by jimmgarrido** [comment]
Should be good now 👍

**Comment by rmarinho** [comment]
@jimmgarrido sorry can you do it again :P we have removed winRT

**Pull request merged**
