### PR TITLE
Fix IndexOutOfRangeException for iOS ListView

### PR DESCRIPTION
**Pull request by kingces95**
### Description of Change ###

If iOS requests height for a cell whose item we just removed then when we ask for the item we'll generate an IndexOutOfRangeException. Fix is to verify index before indexing. 

### Bugs Fixed ###

https://bugzilla.xamarin.com/show_bug.cgi?id=59412
https://github.com/xamarin/Xamarin.Forms/issues/1333 (possible, but no repro)

### API Changes ###

None

### Behavioral Changes ###

None

### PR Checklist ###

- [ ] Has tests (if omitted, state reason in description)
- [x] Rebased on top of master at time of PR
- [x] Changes adhere to coding standard
- [x] Consolidate commits as makes sense

### CODE REVIEW

**Comment by dimonkomaron** [comment]
What version of Xamarin Forms will contain this fix? Is this fix available in pre-release version?

**Comment by NPadrutt** [comment]
Is here any news when this should be available? I checked the available pre versions but it seems it isn't merged to them.

**Comment by zoli13** [comment]
**Xamarin.Forms.3.0.0.296286-pre2**

Crashing. It used to work fine in Xamarin.Forms.2.5.0.122203. After upgrading, I have this issue on iOS only. Android is OK.
I have a tabbed view with 3 tabs. When 2nd tab is clicked:

```
private void PageABC_Appearing(object sender, EventArgs e)
{
	ViewModel.BuildList();
}
```

```
class ViewModel

public ObservableCollection<PersonPaymentList> PersonPaymentList { get; }
internal void BuildList()
{
	MYList.Clear();

	....
}
```

**Comment by samhouts** [comment]
@zoli13 I think you're experiencing #1333/#2145. Please follow those issues for updates. Thanks.

**Pull request merged**
