### PR TITLE
[iOS] Fix for issue 4295 text decorations gone wild after text update

### LINKED ISSUE #4295: Label Underline TextDecoration disappears after text change
### Description

Changed text gets drawn without the underline.
The work around is setting the decoration to none and to underline again.

### Steps to Reproduce

```
<Label Text="Test" TextDecorations="Underline">
	<Label.GestureRecognizers>
		<TapGestureRecognizer Tapped="OnLabelClicked"/>
	</Label.GestureRecognizers>
</Label>
```

```
private void OnLabelClicked(object sender, EventArgs args)
{
	Label oLabel = (Label)sender;
	oLabel.Text = "Hello world";
	oLabel.TextDecorations = TextDecorations.None; // work around
	oLabel.TextDecorations = TextDecorations.Underline; // work around
}
```
### Basic Information

Xamarin Forms 3.3.0.913540

### PR DESCRIPTION
**Pull request by jfversluis**
### Description of Change ###

As described in issue #4295 text decorations get lost after the `Text` is changed on iOS. This PR contains a fix by simply also calling the `UpdateTextDecorations` when the text property is changed.

### Issues Resolved ### 

- fixes #4295

### API Changes ###

 
 None

### Platforms Affected ### 

- iOS

### Behavioral/Visual Changes ###
After updating to this fix, it be working!

### Before/After Screenshots ### 

Here is a (temp) reproduction in the gallery sample app, full video: https://www.dropbox.com/s/vfffvfupfjadlol/UnderlineFix.mov?dl=0

underlinefix

### Testing Procedure ###

See video above, simply create a `Label` with a text and text decoration, then change the text of the label. Before fix: text-decoration is gone, after fix: text-decoration stays.

### PR Checklist ###

- [ ] Has automated tests 
- [x] Rebased on top of the target branch at time of PR
- [x] Changes adhere to coding standard

### CODE REVIEW

**Comment by StephaneDelcroix** [comment]
I think something is wrong with your PR...

**Comment by jfversluis** [comment]
Whaha that I can imagine! Oh wow. I must've messed up somehow... Let me check.

**Comment by jfversluis** [comment]
Much better 🙃

**Comment by alanag13** [comment]
@jfversluis have you checked if this affects spans?

**Comment by jfversluis** [comment]
I did! It does not, let me show you.

spanunderline

**Pull request merged**
