### PR TITLE
Set correct MinWidth for CheckBox style

### LINKED ISSUE #7048: [Bug] CheckBox Has Incosistent Paddings
### Description
The CheckBox control has inconsistent padding/margin on iOS and UWP.

### Steps to Reproduce

1. Add a CheckBox to your view
2. Set `BackgroundColor` to `Color.Silver`
3. You will see the CheckBox not centered in the control.

XAML Content:
```xml
<StackLayout VerticalOptions="Center">
    <StackLayout Orientation="Horizontal" HorizontalOptions="Center">
        <CheckBox BackgroundColor="Silver"/>
        <Label Text="CheckBox" VerticalOptions="Center" />
    </StackLayout>
</StackLayout>
```

Sample Repo: 
[https://github.com/hnabbasi/XamarinFormsIssue7048](https://github.com/hnabbasi/XamarinFormsIssue7048)

### Expected Behavior
CheckBox appears in the middle of the control, with less padding preferably.

### Actual Behavior
CheckBox appears slightly left of the middle of the control.

### Basic Information

- Version with issue: 4.1.0.618606
- Last known good version:
- IDE: VS 2019 Windows & Mac
- Platform Target Frameworks: 
  - iOS:  12.2
  - Android: API 28
  - UWP: 10.0.17763.0
  - Affected Devices: Tested on all three simulators/emulator.

### PR DESCRIPTION
**Pull request by Depechie**
Fixes #7048 

### Description of Change ###

Default MinWidth value for CheckBox was defined as 120 in the CheckBox style on UWP.
Best we set this to the same value as MinHeight, so now both are 32.

### Issues Resolved ### 

- fixes #7048

### API Changes ###

Changed:
 - object FormsCheckBoxStyle.xaml MinWidth property 120 => 32

### Platforms Affected ### 

- UWP

### Behavioral/Visual Changes ###

Right padding will be gone.

None

### Before/After Screenshots ### 

Screenshot (5)
Screenshot (4)

### Testing Procedure ###

Added Issue7048 to Xamarin Controls test app

### PR Checklist ###

- [ ] Targets the correct branch
- [ ] Tests are passing (or failures are unrelated)

### CODE REVIEW

**Comment by jfversluis** [comment]
Although this will fix the biggest part of the problem, in addition it seems like the checkbox itself is aligned to the left, while on other platforms it's on center? So it will still look inconsistent, right?

Also, this would have to go into 4.3 and there is a small conflict :)

**Comment by Depechie** [comment]
Yeah had the same thought to maybe also change the style to center the checkbox, but if we look at the original issue ( https://github.com/xamarin/Xamarin.Forms/issues/7048 ) there is a screenshot of the several OS targets and also iOS is not centered it seems... hence why I left it as is.

**Comment by Depechie** [comment]
Other extra remark, this can have a visual impact on existing apps though!
If people did not manually change this, their apps can look very different after this change :D

**Comment by jfversluis** [comment]
The iOS is actually pretty weird because it's not centred but also not completely to the left

**Comment by Depechie** [comment]
@jfversluis done

**Comment by jfversluis** [comment]
Just a small conflict and then we can merge it!

**Comment by Depechie** [comment]
@jfversluis done

**Pull request merged**
