### PR TITLE
[Evolution] SwipeGestureRecognizer

### PR DESCRIPTION
**Pull request by seanyda**
### Description of Change ###

Added a SwipeGestureRecognizer to Xamarin.Forms which works on iOS, Android and Windows.

### API Changes ###

SwipeGestureGalleryPage.cs
CoreGallery.cs
SwipeGestureRecognizerTests.cs
ISwipeGestureController.cs
SwipeDirection.cs
SwipeGestureRecognizer.cs
SwipeEventArgs.cs
SwipeGestureHandler.cs
GestureManager.cs
VisualElementTracker.cs
EventTracker.cs

### PR Checklist ###

- [x] Has tests (if omitted, state reason in description)
- [x] Rebased on top of master at time of PR
- [x] Changes adhere to coding standard
- [x] Consolidate commits as makes sense

### CODE REVIEW

**Comment by seano2o6** [comment]
Sorted those issues (I hope).

**Comment by mattrichnz** [comment]
@seano2o6 Let me know if you need me to do any further work too.

**Comment by seano2o6** [comment]
Thanks @mattrichnz!

**Comment by rmarinho** [comment]
Hi can you reopen this rebased and against master? 

Thanks

**Comment by eman1986** [comment]
did this ever get into XF 3? I'm looking for this very thing fora  project

**Comment by seanyda** [comment]
@eman1986 Update to pre-release 3.2.0 and it's available there.

**Pull request closed without merging**
