### PR TITLE
Fix 15368 Editor's TextChanged event is fired on Unfocus even when no text changed

### PR DESCRIPTION
**Pull request by JustickDM**
### Description of Change ###

Update OnEnded method

### Issues Resolved ### 

- fixes https://github.com/xamarin/Xamarin.Forms/issues/15368

### API Changes ###
 
 None

### Platforms Affected ### 

- iOS

### Behavioral/Visual Changes ###

None

### PR Checklist ###

- [ ] Targets the correct branch
- [ ] Tests are passing (or failures are unrelated)

### CODE REVIEW

**Comment by jfversluis** [comment]
Thanks for this @JustickDM ! We'll have a look soon :)

**Comment by JustickDM** [comment]
> Thanks for this @JustickDM ! We'll have a look soon :)
> 
> Would you be able to also add a test just like for the initial fix for an `Entry`?

Already, but I'm not sure I did everything right:)

**Review by jfversluis — APPROVED** [review]

**Comment by PawKanarek** [comment]
@jfversluis  do you plan to move / verify this fix in MAUI? I wrote here why this should probably be done https://github.com/dotnet/maui/issues/7536#issuecomment-1141124318

**Pull request merged**
