### PR TITLE
[Build] Add azure pipeline definition

### LINKED ISSUE #3430: Add VSTS YAML Configuration
### Description

Now that VSTS supports YAML configurations, a YAML build configuration should be added to the repo to better assist the community in being able to run custom builds.

#### Goals

By adding a YAML configuration this should help to do the following:

1. Remove barriers of entry for the F100 by ensuring developers can properly build/test before submitting a PR
1. Attract more adoption by making enterprises feel they can patch and run custom builds for their needs with minimal effort
1. Help developers by getting more 1st hand visibility into how Xamarin.Forms itself is built and then tested.

### PR DESCRIPTION
**Pull request by rmarinho**
### Description of Change ###

Add initial yaml draft definition for Xamarin Forms build process

### Issues Resolved ### 

- fixes #3430

### API Changes ###
 
 None

### Behavioral/Visual Changes ###

None

### Before/After Screenshots ### 

Not applicable

### Testing Procedure ###

Check new pipeline on azure devops

### PR Checklist ###

- [ ] Has automated tests 
- [ ] Rebased on top of the target branch at time of PR
- [ ] Changes adhere to coding standard

### CODE REVIEW

**Comment by dansiegel** [comment]
as we discussed... one possible change here on the signing step would be to adopt the use of the [SignService/SignClient](https://github.com/onovotny/SignService) for package signing. It's already widely used for .NET Foundation projects. The benefit here would be that if an enterprise (or anyone really) wanted to generate a custom build that ws still signed, they could do so in a manner that is consistently used among .NET projects. You could also pull in this [script](https://github.com/dansiegel/SoCalCodeCamp.AuthModule/blob/master/build/Sign-Packages.ps1) to make it easy for anyone to simply add the variables for their signing service.

**Comment by jfversluis** [comment]
Not sure how it happened, but I already have a failing check for the YAML file in #4379

**Comment by rmarinho** [comment]
@dansiegel let's open a new issue about the signing part. I have checked and seems we aren't even feature in the .NET foundation website. I will talk internally about this and if is ok to move to that signing service.

**Comment by dansiegel** [comment]
@rmarinho happy to open an issue for that one. Still need to figure out what to do with the variable groups... currently for a community member to just point at the YAML file the build will fail...

**Pull request merged**
