### PR TITLE
[UWP] Fixed NRE load image from ImageSource

### LINKED ISSUE #13109: [Bug] NullReference Exception thrown when load image from ImageSource in Xamarin Forms UWP
### Description

NullReference Exception thrown when load image from ImageSource in Xamarin Forms UWP.

CallStackDetails : 
 	Xamarin.Forms.Platform.UAP.dll!Xamarin.Forms.Platform.UWP.PlatformConfigurationExtensions.OnThisPlatform<Xamarin.Forms.Application>(Xamarin.Forms.Application element)	Unknown
 	Xamarin.Forms.Platform.UAP.dll!Xamarin.Forms.Platform.UWP.FileImageSourceHandler.UpdateImageDirectory(Xamarin.Forms.FileImageSource fileSource)	Unknown
 	Xamarin.Forms.Platform.UAP.dll!Xamarin.Forms.Platform.UWP.FileImageSourceHandler.LoadImageAsync(Xamarin.Forms.ImageSource imagesource, System.Threading.CancellationToken cancellationToken)	Unknown
>	UWPApp.UWP.exe!UWPApp.UWP.ImageHandler.GetImage(Xamarin.Forms.ImageSource source) Line 35	C#
 	UWPApp.UWP.exe!UWPApp.UWP.CloseIconHelper.Reports.View.ICloseIconHelper.SetImage(Xamarin.Forms.ImageSource imageSource) Line 20	C#
 	Reports.dll!Reports.View.CloseIcon.CloseIcon() Line 41	C#
 	Reports.dll!Reports.View.ReportsPage.ReportsPage() Line 18	C#
 	UWPApp.UWP.exe!UWPApp.UWP.ReportsPage.ReportsClicked(object sender, Windows.UI.Xaml.RoutedEventArgs e) Line 34	C#

### Steps to Reproduce

1. Run the attached sample
2. Click the report button to load image from imagesource.
3.  Note the Null Reference exception thrown when load image from imagesouce.

### Expected Behavior

The exception should not be thrown when load images from imagesource.

### Actual Behavior

NullReference Exception thrown when load image from imagesource.

### Basic Information

- Version with issue: 4.8.0.1687
- Last known good version: 3.6.0.709228
- Platform Target Frameworks: 
  - UWP:   
- Android Support Library / AndroidX Version: 
- NuGet Packages:
- Affected Devices:

### Environment

```
```

### Reproduction Link
[XamUWPApp_66841f7f.zip](https://github.com/xamarin/Xamarin.Forms/files/5677123/XamUWPApp_66841f7f.zip)

### PR DESCRIPTION
**Pull request by jsuarezruiz**
### Description of Change ###

Fixed NRE load image from ImageSource in UWP.

### Issues Resolved ### 

- fixes #13109

### API Changes ###
 
 None

### Platforms Affected ### 

- UWP

### Behavioral/Visual Changes ###

None

### Before/After Screenshots ### 

Not applicable

### Testing Procedure ###
Launch Core Gallery and navigate to the issue 13109. Without exceptions, the test has passed.

### PR Checklist ###

- [ ] Targets the correct branch
- [ ] Tests are passing (or failures are unrelated)

### CODE REVIEW

**Comment by rmarinho** [comment]
Hey @jsuarezruiz is it possible to add a UITest ?

**Comment by jsuarezruiz** [comment]
Sure, added!.

**Review by rmarinho — CHANGES_REQUESTED** [review]
@jsuarezruiz  test is failing .

**Review by rmarinho — CHANGES_REQUESTED** [review]
hey @jsuarezruiz  tests is failing on iOS and Android

**Comment by rmarinho** [comment]
@jsuarezruiz  i comment your change and the test still passes, am i holding it wrong ?

**Review by rmarinho — APPROVED** [review]
I tested the nuget on the issue and it solves the issue. But that said the UITest added is not really testing this issue since Application is not null if we do it from the Xamarin.Forms side

**Review by hartez — APPROVED** [review]

**Comment by rmarinho** [comment]
@jsuarezruiz  tests is failing on UWP

**Pull request merged**
