### PR TITLE
fix: Button on ListView should not pass click to listview when disabled

### LINKED ISSUE #8763: [Bug] ContextAction Button on ListView Cell on iOS passes Tap to Cell when CanExecute is false
### Description
When you add a ItemTapped event to a ListView and fill it's ViewCells ContextActions with a MenuItem whose Commands CanExecute is **false**, then tapping that ContextActions button on iOS will simply pass the tap to the underlying ViewCell.
This seems like a bug to us, tapping a disabled button at that point should simply not do anything at all.

### Steps to Reproduce

1. Clone the repository.
2. Start the project on iOS.
3. Open the ContextActions on an Item and Tap on the Context Action.
4. Notice that the Taps on Items counter has increased by one, indicating that the ItemTapped on the ListView has been fired.

### Expected Behavior

The ItemTapped on the ListView should not be fired.

### Actual Behavior

The ItemTapped on the ListView is fired.

### Basic Information

- Version with issue: Noticed in 4.2.0.709249 and later
- Last known good version: -
- IDE: Microsoft Visual Studio Professional 2019
- Platform Target Frameworks: 
  - iOS:  13.1

### Reproduction Link

https://github.com/BasileusBasileon/Xamarin-ListView-ContextAction-iOS-Bug

### PR DESCRIPTION
**Pull request by l4nk4b3l**
### Issues Resolved ### 
fixes #8763 

### Platforms Affected ### 
- iOS

### Behavioral/Visual Changes ###
None

### Before/After Screenshots ### 
Not applicable

### PR Checklist ###

- [] Targets the correct branch
- [] Tests are passing (or failures are unrelated)

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/xamarin/Xamarin.Forms?pullRequest=12370) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/xamarin/Xamarin.Forms?pullRequest=12370) before we can accept your contribution.<br/><br/>:x: l4nk4b3l [sign now](https://cla.dotnetfoundation.org/xamarin/Xamarin.Forms?pullRequest=12370)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/xamarin/Xamarin.Forms?pullRequest=12370) it.</sub>

**Review by rmarinho — CHANGES_REQUESTED** [review]
Is it possible to add a UITest and a sample case so we can see what this is supposed to fix. 

Thanks

**Review by jsuarezruiz — CHANGES_REQUESTED** [review]
@l4nk4b3l  Could you include a sample (and maybe a UITest) where validate the issue and the fix?. Let me know if you need help with something.

**Comment by l4nk4b3l** [comment]
> @l4nk4b3l Could you include a sample (and maybe a UITest) where validate the issue and the fix?. Let me know if you need help with something.

Is the a guide on how to write a uitest ?
Are there sample tests ? 
I don't know where to start.

**Comment by jsuarezruiz** [comment]
The sample should be added here: https://github.com/xamarin/Xamarin.Forms/tree/5.0.0/Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared
About UITest: https://docs.microsoft.com/en-us/appcenter/test-cloud/frameworks/uitest/cheatsheet
Can find many samples in the gallery, but if need anything or you feel blocked let me know and I can create it and share with you.

**Comment by l4nk4b3l** [comment]
I would like to know whats going on. 
I requested review about 6 months ago.

**Comment by thisisthekap** [comment]
@jfversluis Any chance that this one is making it into a Xamarin.Forms service release?

**Comment by jfversluis** [comment]
Now that we're so close to the sunsetting of Xamarin.Forms unfortunately we won't be able to take this in anymore, we're really sorry about that. Nevertheless, thank you so much for your time and effort that you have put into this PR.

Please have a look at the evolution of Xamarin.Forms, [.NET MAUI](https://github.com/dotnet/maui). A lot of development has been going on there. Hopefully this issue was already fixed in that codebase. If not, feel free to port this over to there.

Again, thank you so much for being a contributor and Xamarin.Forms user!

**Pull request closed without merging**
