### PR TITLE
[UWP] improve performance

### PR DESCRIPTION
**Pull request by paymicro**
### Description of Change ###

Improve performance.

### Issues Resolved ### 

none

### API Changes ###

Changed:
```C# 
public interface IElementConfiguration<out TElement>
```
to
```C#
public interface IElementConfiguration<TElement>
```

### Platforms Affected ### 

- Core (all platforms)
- UWP

### Behavioral/Visual Changes ###

None

### Before/After Screenshots ### 

Not applicable

### Testing Procedure ###

- run any UItest

### PR Checklist ###

- [ ] Has automated tests 
- [ ] Rebased on top of the target branch at time of PR
- [ ] Changes adhere to coding standard

### CODE REVIEW

**Comment by PureWeen** [comment]
Oh I see because in that commit it got added to the Cell
Hmmm I still don't think we can remove the out on IElementConfiguration unfortunately as that will change too much. Can we achieve the same thing @AndreiMisiukevich achieved in that PR another way? Maybe create an IElementConfiguration that doesn't have the out parameter? or something else?

**Comment by AndreiMisiukevich** [comment]
> Oh I see because in that commit it got added to the Cell
> Hmmm I still don't think we can remove the out on IElementConfiguration unfortunately as that will change too much. Can we achieve the same thing @AndreiMisiukevich achieved in that PR another way? Maybe create an IElementConfiguration that doesn't have the out parameter? or something else?

Hi
Do you mean this PR https://github.com/xamarin/Xamarin.Forms/pull/4002/files ?

**Comment by paymicro** [comment]
> * Can we make this change? It's a public interface so it'll probably break people right?

Right. Probably breaking change, but i think that such a chance is extremely small.

> * This has had an our parameter since 2016 right? It was an out generic in 3.5 when the performance was fine so it seems like there's a different cause we can look to in order to fix the

In my opinion, this initially reduced productivity, but the number of elements did not reach a critical mass.

> Maybe create an IElementConfiguration that doesn't have the out parameter? or something else?

Hm. Maybe create `IFastElementConfiguration`... or `IElementConfiguration2`. And mark `IElementConfiguration` as obsolete... I'll see what I can do.

**Comment by paymicro** [comment]
@AndreiMisiukevich yes. https://github.com/xamarin/Xamarin.Forms/pull/4002 markedly reduces performance on UWP.

**Comment by StephaneDelcroix** [comment]
any measures ?

**Comment by samhouts** [comment]
@hartez Yeah, it was like three years ago, but do you remember if we had a compelling reason to make `IElementConfiguration` covariant?

**Comment by samhouts** [comment]
This is currently blocking #2432, so we need to address it quickly.

**Comment by PureWeen** [comment]
closed because of
https://github.com/xamarin/Xamarin.Forms/pull/5449

**Pull request closed without merging**
