### PR TITLE
Wpf

### PR DESCRIPTION
**Pull request by Atreides07**
### Description of Change ###

Preview version of Xamarin.Forms.WPF (2.3.2)

### API Changes ###

List all API changes here (or just put None), example:

Added:
   Xamarin.Forms.Platform.WPF
 - BoxViewRenderer
 - EntryRenderer
 - EditorRenderer
 - LabelRenderer
 - ImageRenderer
 - ButtonRenderer
 - SliderRenderer
 - WebViewRenderer
 - SwitchRenderer
 - ProgressBarRenderer
 - ScrollViewRenderer
 - FrameRenderer
 - ListViewRenderer
 - TabbedPageRenderer
 - PageRenderer
 - MasterDetailRenderer

 - Demo project Xamarin.Forms.ControlGallery.WPF

Changed:
 - NavigationProxy (add Message of Navigated event)
 - TemplatedItemsList (Implementation of IList methods for ListProxy)

### CODE REVIEW

**Comment by ismlsmile** [comment]
@Atreides07, you did a great job!

**Comment by Atreides07** [comment]
@ismlsmile Thank you! On Wednesday I will send a more complete version.

**Comment by BradChase2011** [comment]
@Atreides07 Hey thanks a ton for putting all this together.  I bet it was no easy feat.  Can you explain a bit about where this is right now in terms of completeness?  Or what is left to do?  I can test it a bit on our code which is quite large and handles alot of use cases in a real life app when its ready.

**Comment by Atreides07** [comment]
@BradChase2011 Thanks!

Unfortunately there is a lot of work left.

Small road map:

05/11/17
SearchBarRenderer,
StepperRenderer,
ActivityIndicatorRenderer,
NavigationPageRenderer,
CarouselPageRenderer

05/16/17
SearchBarRenderer
DatePickerRenderer,
TimePickerRenderer
PickerRenderer,
NavigationMenuRenderer

06/01/17
Still need to do a lot of work on the ListView:
PullToRefresh
Grouping

Generally
There is also a bug with the Back button and a series of minor flaws.

08/01/17
Implement a series of UI tests to simplify migration to new versions of Xamarin.Forms

10/01/17
Try to implement "live editing" of XAML markup at least for WPF, as it is done in UWP.

There are many other plans but I need to do this at least this year.

**Comment by mohachouch** [comment]
Hi,

Thank you verry much for your work!

Is this project still current?

When building, they announced the development of Xamarin Forms for WPF. Is this PR?

Regards

**Comment by Atreides07** [comment]
Unfortunately I can not connect with the Xamarin team in any way. I wrote a few letters but did not receive any reply. Therefore, the development went slower and to save time and effort I changed my plans and now I'm working on support for Xamarin.Forms 3.0 I also switched to the .NET Framework 4.7 to support such elements as Calendar Control built into .NET 4.7
According to the new plans, I plan to get the beta version for the XF 3.0 release and then I will work on stabilization within a month.

**Comment by mohachouch** [comment]
I think Xamarin develops in-house support for WPF. That's why I was asking if this is the project that was announced during the build.

I wanted to contribute to this project. It would not be necessary to develop a duplicate project as much as to work on the same project.

**Comment by Atreides07** [comment]
@mohachouch We still use my implementation in production, so I still need to continue developing. If there is something else instead of my implementation, then we move on to it.

**Comment by opcodewriter** [comment]
I doubt Xamarin develops in-house support for WPF. We would have seen a branch for that, since XF is open source.

**Comment by jassmith** [comment]
@Atreides07 hey man! Sorry for the delay. We are looking at this now.

**Comment by flyingxu** [comment]
Maybe this is a little bit off-topic, is there any plan to merge master branch to wpf branch? The wpf branch is so outdated, 669 commits behind.

**Comment by Atreides07** [comment]
Now the priorities have changed and I am working on version 3.0. To support the development of two versions at once 2.3 and 3.0, I will not have enough time. 

I'm working but do not put anything into github until I get the minimum working version. All the work is done locally for me, so as not to waste time on PR for non-working intermediate versions. Also there are difficulties with coating tests that increases the development time.

In any case, to release 3.0 I will try to implement a version for WPF but with .NET 4.7

**Pull request merged**
