### PR TITLE
[iOS] Fix NavigationPage memory leak when back button title is set

### PR DESCRIPTION
**Pull request by adrianknight89**
### Description of Change ###

`SetBackButtonTitle` on iOS creates a memory leak when the page on which it's called is popped from the navigation stack.  This is because `BackBarButtonItem` has an event handler that holds a reference to the page. The simplest fix was to remove this handler. It looks like iOS is overriding the behavior so that the handler is never called.

I tried setting the `Clicked` event of `UIBarButtonItem`, using a `UIButton` as custom view and handling its `TouchUpInside`, and removing the tap gesture from `pageRenderer.ViewController.View`. None of those allowed me to invoke `await PopViewAsync(page)`, which makes me believe `BackBarButtonItem` (or something else) is overriding everything. Removing the handler lets us use the default back button logic.

P.S. I can't quite understand what `DidMoveToParentViewController` is doing. The comments were vague to me, and this method is triggering a call to `Task<bool> OnPopViewAsync` where an exception (wrapped in the `Task`) is thrown all the time because `TopViewController` is not the parent of the page being removed. I think there was a bug report related to this exception. @rmarinho 

### Bugs Fixed ###

- https://bugzilla.xamarin.com/show_bug.cgi?id=44047

### PR Checklist ###

- [x] Has tests (if omitted, state reason in description)
- [x] Rebased on top of master at time of PR
- [x] Changes adhere to coding standard
- [x] Consolidate commits as makes sense

### CODE REVIEW

**Comment by rmarinho** [comment]
Hi @adrianknight89 so i was looking at this and specially code of DidMoveToParentViewController was missing stuff, seems that maybe the rebase got wrong, and we merged a incomplete fix.  pr (#291)

At this time i reverted that code so we can ship  stable that doesn't throw that exception, also it was making impossible to dispose some renderers. But i will get back to try to fix that bug again 39908. 

Just to explain you my fix there, the problem is when a page is popped via click on the back button very fast the way we update the stack on the XF side gets mixed up. So i used other aproach: DidMoveToParentViewController is called with parent null when a controller is being removed, and in there we check if we should update the Forms side ( normally always that pop is done via the UI and not using XF api) .. But the current code was missing stuff. I need to get back to it. 

Please rebase and check if this leak that you are trying to fix still happens. 

Thanks.

**Comment by adrianknight89** [comment]
Looks like reverting your changes makes things better. However, I'm still unable to call `await PopViewAsync(page);`. It seems that iOS is ignoring this.

**Comment by rmarinho** [comment]
needs rebase

**Comment by adrianknight89** [comment]
Done.

**Comment by jerone** [comment]
[**@adrianknight89**](https://github.com/adrianknight89) commented on [19 Nov 2016, 17:44 CET](https://github.com/xamarin/Xamarin.Forms/pull/523#issuecomment-261724509 "2016-11-19T16:44:33Z - Replied by Github Reply Comments"):
> Looks like reverting your changes makes things better. However, I'm still unable to call `await PopViewAsync(page);`. It seems that iOS is ignoring this.

I can conclude the same thing, when I assign my own back-button. It's completely ignoring the event-handler and calling page pop on it's own.

**Pull request merged**
