### PR TITLE
[Core] Propagate BindingContext to GradientBrush

### LINKED ISSUE #12339: [Bug] LinearGradientBrush doesn't apply Binding-Colors
### Description
Using a LinearGradientBrush with GradientStops where the ColorProperty is bound, doesn't work as expected.

### Steps to Reproduce

1. Create a Xamarin.Forms-App
2. Add a Frame to the MainPage and set it's BackgroundProperty to LinearGradientBrush
grafik

3. Bind the ColorProperty of GradientStops to a Property in the Code behind or ViewModel (screenshot 2)
grafik

### Expected Behavior
Colors apply to the GradientStops

### Actual Behavior
Color is always transparent and only works when setting Colors manually

### Basic Information

- Version with issue: 4.8.0.1451 (Also tried 5-pre1 but same issue)
- Last known good version: /
- IDE: VS 2019
- Nuget Packages: Xamarin.Forms

### Screenshots

grafik

### Workaround

Setting colors in XAML or code behind by accessing GradientStops directly

### PR DESCRIPTION
**Pull request by jsuarezruiz**
### Description of Change ###

Propagate BindingContext to GradientBrush.

### Issues Resolved ### 

- fixes #12339 

### API Changes ###

 None

### Platforms Affected ### 

- Core/XAML (all platforms)

### Behavioral/Visual Changes ###

None

### Before/After Screenshots ### 

Captura de pantalla 2020-10-27 a las 11 22 20

### Testing Procedure ###
Launch Core Gallery and navigate to the issue 12339. If you can see the gradient below, the test has passed.

### PR Checklist ###

- [ ] Targets the correct branch
- [ ] Tests are passing (or failures are unrelated)

### CODE REVIEW

**Comment by StephaneDelcroix** [comment]
this might not be needed once Brushes and Stops inherit from Element, and are properly parented. I'm working on something

**Review by RobertBickers — APPROVED** [review]

**Comment by jfversluis** [comment]
This seems to have a workaround in the linked issue. Let's not risk any regressions by merging this.

**Pull request closed without merging**
