### PR TITLE
Drag and drop

### LINKED ISSUE #10778: [Spec]  DragGestureRecognizer  DropGestureRecognizer
# DragGestureRecognizer
- Allow users to activate a view for dragging

# DropGestureRecognizer
- Allow users to react to a view being dragged over it and then react 

# API

## VisualStates associated with target drop

```XAML
<VisualStateGroup x:Name="DragAndDropStates">
            <VisualState x:Name="IsDragging">
            </VisualState>
            <VisualState x:Name="DragOver">
            </VisualState>
</VisualStateGroup>
```

## DropGestureRecognizer

```C#
public class DropGestureRecognizer
{
     public bool AllowDrop;
     public DragEventArgs DragOver;
     public DropEventArgs Drop;
}
```

### Properties

| API | Description |
| ------------- | ------------- |
| AllowDrop  | This sets up a view to be receiver of a view that's being dropped.  |

### Events

| API | Description |
| ------------- | ------------- |
| DragOver |  This fires when a dragged view is over the receiver view. This fires on the target view |
| Drop | This fires on the target when the user let's go of the view being dragged |

## DragGestureRecognizer

```C#
public class DragGestureRecognizer
{
     public bool CanDrag;
     public DropCompletedEventArgs DropCompleted;
     public DragItemsStartingEventArgs DragStarting;
}
```

### Properties

| API | Description |
| ------------- | ------------- |
| CanDrag | This indicates that this view will be the draggable one. |

### Events

| API | Description |
| ------------- | ------------- |
| DropCompleted | This fire once the drop operation has completed |
| DragStarting | This fires once it's detected that the user wants to initiate a drag operation. |

## DragState
```C#
public enum DragState
{
     Started, Dragging, Completed, Cancelled
}
```

## DragItemsStartingEventArgs

```C#
public class DragItemsStartingEventArgs
{
     bool Cancel;
     DataPackage Data;
}
```

### Properties

| API | Description |
| ------------- | ------------- |
| Cancel | Don't activate the drag operation. |
| DataPackage | Setup the data package to be dragged. If user doesn't specify anything then we just try our best to infer what it should be based on the source |

## DataPackageOperation

```C#
public enum DataPackageOperation
{
     None, Copy, Move
}
```

 ## DragEventArgs

```C#
public class DragEventArgs
{
     DataPackage Data;
     DragState State;
     DataPackageOperation AcceptedOperation
}
```
### Properties

| API | Description |
| ------------- | ------------- |
| Data | This is the data package associated with the view being dragged. If someone drags an image to an image we'll just load the image into the target. If someone drags a label the data will be text and we'll apply the text. If it's just a view then the data will be a reference to that view and users can then just do something with it |
| State | This will indicate the state of the drag operation | 
| AcceptedOperation | Indicates the types of actions this element will accept for the given data package. This is how you indicate that a given view will accept the given item.  | 

## DropCompletedEventArgs

```C#
public class DropCompletedEventArgs
{
     DataPackageOperation DropResult { get; }
}
```

### Properties

| API | Description |
| ------------- | ------------- |
| DataPackageOperation | Indicates the type of operation and whether or not it was successful. None means unsuccessful |

 ## DropEventArgs

```C#
public class DropEventArgs
{
     DataPackageView Data;
     bool Handled;
}
```

### Properties

| API | Description |
| ------------- | ------------- |
| Data | Readonly view of the data dropped on the target view |
| Handled | Set this to true if you've handled the data in the handler otherwise Forms will try to process the data itself based on the source/target combination |

## DataPackage
This is used to setup the data for transfer

```C#
public class DataPackage
{
     public void SetImage(ImageSource source);
     public void SetText(string value);
     public void SetUri(Uri value);
     public DataPackageView GetView()
}
```

## DataPackageView
This is a read-only copy of the DataPackage object.
This is all the user gets on the drop event to retrieve the data. They can't modify the package

```C#
public class DataPackageView
{
     public ImageSource GetImageAsync();
     public string GetTextAsync();
     public Uri GetUriAsynci();
}
```

#### Basic Xaml Example
```XAML
<StackLayout>
        <Image
           HorizontalOptions="Center"
           VerticalOptions="CenterAndExpand">
            <Image.GestureRecognizers>
                <DragGestureRecognizer CanDrag="{Binding EnableDragging}"></DragAndDropGestureRecognizer>
            </Image.GestureRecognizers>
        </Image>
         <StackLayout
           HorizontalOptions="Center"
           VerticalOptions="CenterAndExpand">
            <StackLayout.GestureRecognizers>
                <DropGestureRecognizer DragOver="DragOverStackLayout"  AllowDrop="true"></DropGestureRecognizer>
            </StackLayout.GestureRecognizers>
        </StackLayout>
        <Image
           HorizontalOptions="Center"
           VerticalOptions="CenterAndExpand">
            <Image.GestureRecognizers>
                <DropGestureRecognizer DragOver="DragOver" Drop="FiresWhenDropped"  AllowDrop="{Binding EnableDrop}"></DropGestureRecognizer>
            </Image.GestureRecognizers>
        </Image>
    </StackLayout>
```

### Workflow
- User LongPresses on the drag target
- DragStarting event fires and the user doesn't do anything
  - Because the user doesn't do anything the ImageSource on the image is set on the data package
- user drags image over the StackLayout but inside `DragOverStackLayout` the user doesn't do anything so the SL won't receive the element if the user drops it herre
- once the finger is over the image `DragOver` fires and the user sets the accepted operation to something other than `None`
- Once the user lifts up their finger `FiresWhenDropped` fires 
  - At this point if the user doesn't do anything than forms will set the ImageSource on the target
  - If they set Handled to True then forms does nothing

## CollectionView considerations
First implementation won't have tight integration with CV

### PR DESCRIPTION
**Pull request by PureWeen**
### Description of Change ###

Preview release of Drag and Drop

FYI only works on iOS11+ because that's when the drag and drop apis were added

### Issues Resolved ### 

- fixes #10778

## DropGestureRecognizer

```C#
public class DropGestureRecognizer
{
     public bool AllowDrop;
     public DragEventArgs DragOver;
     public ICommand DragOverCommand;
     public object DragOverCommandParameter;

     public DropEventArgs Drop;
     public ICommand DropCommand;
     public object DropCommandParameter;

}
```

## DragGestureRecognizer

```C#
public class DragGestureRecognizer
{
     public bool CanDrag;
     public DropCompletedEventArgs DropCompleted;
     public ICommand DropCompletedCommand;
     public object DropCompletedCommandParameter;

     public DragItemsStartingEventArgs DragStarting;
     public ICommand DragStartingCommand;
     public object DragStartingCommandParameter;
}
```

## DragItemsStartingEventArgs

```C#
public class DragItemsStartingEventArgs
{
     bool Cancel;
     DataPackage Data;
}
```

## DataPackageOperation

```C#
[Flags]
public enum DataPackageOperation
{
     None, Copy
}
```

 ## DragEventArgs

```C#
public class DragEventArgs
{
     DataPackage Data;
     DataPackageOperation AcceptedOperation
}
```

## DropCompletedEventArgs

```C#
public class DropCompletedEventArgs
{
}
```

 ## DropEventArgs

```C#
public class DropEventArgs
{
     DataPackageView Data;
     bool Handled;
}
```

## DataPackage
This is used to setup the data for transfer

```C#
public class DataPackage
{
     public ImageSource Image {Get;set;}
     public string Text;
     public DataPackageView View
}
```

## DataPackageView
This is a read-only copy of the DataPackage object.
This is all the user gets on the drop event to retrieve the data. They can't modify the package

```C#
public class DataPackageView
{
     public ImageSource GetImageAsync();
     public string GetTextAsync();
}
```

### Platforms Affected ### 

- Core/XAML (all platforms)
- iOS 11+
- Android
- UWP

### Testing Procedure ###
- Galleries Tests Provided

### PR Checklist ###

- [ ] Targets the correct branch
- [ ] Tests are passing (or failures are unrelated)

### CODE REVIEW

**Comment by rmarinho** [comment]
Testing a comment

**Comment by samhouts** [comment]
Should you have a null image source? No. Was it the first thing I tried? Yes.

```xaml
        <Image x:Name="Image" Margin="10,292,10,0" HeightRequest="338" BackgroundColor="Aqua">
            <Image.GestureRecognizers>
                <DragGestureRecognizer CanDrag="True"></DragGestureRecognizer>
            </Image.GestureRecognizers>
        </Image>
```

```[HotReload] (2020-07-28 15:07:00.9): ERROR: Object reference not set to an instance of an object.
	at Xamarin.Forms.Platform.Android.DragAndDropGestureHandler.ConvertToClipDataItem (Xamarin.Forms.ImageSource source, System.Collections.Generic.List`1[T] mimeTypes) [0x0008a] in D:\agent\1\s\Xamarin.Forms.Platform.Android\DragAndDropGestureHandler.cs:321
	at Xamarin.Forms.Platform.Android.DragAndDropGestureHandler+<>c__DisplayClass18_0.<OnLongPress>b__0 (Xamarin.Forms.DragGestureRecognizer rec) [0x000dd] in D:\agent\1\s\Xamarin.Forms.Platform.Android\DragAndDropGestureHandler.cs:245
	at Xamarin.Forms.Platform.Android.DragAndDropGestureHandler.SendEventArgs[TRecognizer] (System.Action`1[T] func, Xamarin.Forms.View view) [0x00066] in D:\agent\1\s\Xamarin.Forms.Platform.Android\DragAndDropGestureHandler.cs:113
	at Xamarin.Forms.Platform.Android.DragAndDropGestureHandler.OnLongPress (Android.Views.MotionEvent e) [0x00028] in D:\agent\1\s\Xamarin.Forms.Platform.Android\DragAndDropGestureHandler.cs:218
	at Xamarin.Forms.Platform.Android.InnerGestureListener.Android.Views.GestureDetector.IOnGestureListener.OnLongPress (Android.Views.MotionEvent e) [0x00009] in D:\agent\1\s\Xamarin.Forms.Platform.Android\InnerGestureListener.cs:120
	at Android.Views.GestureDetector+IOnGestureListenerInvoker.n_OnLongPress_Landroid_view_MotionEvent_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_e) [0x0000f] in <a522ecdee49144d0b8411a1cab7b9ada>:0
	at at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.49(intptr,intptr,intptr) in :0```

**Comment by samhouts** [comment]
[HotPotato.zip](https://github.com/xamarin/Xamarin.Forms/files/4991470/HotPotato.zip)

Works great on Android.
Doesn't seem to work at all on iOS.
UWP just crashes for me, but that's another story.

**Comment by BurkusCat** [comment]
@PureWeen I really like this API. I've been using it a little bit on UWP and it seems very solid :) (I've posted one issue around the UWP cursor and a docs issue around how to use commands but other than that it is pretty great!)

**Pull request merged**
