### PR TITLE
ios: raise touch event on touchbegin.

### LINKED ISSUE #3320: [iOS] Cells aren't highlighted on touch-down when the ListView's CachingStrategy is set to "RecycleElement"
### Description
On iOS, cells aren't highlighted on touch-down when the ListView's `CachingStrategy` is set to `RecycleElement`. Works fine on Android and with `RetainElement`.

### Steps to Reproduce

1. Create a list and set the `CachingStrategy` to `RecycleElement`
2. Press down on a cell and don't move the finger

### Expected Behavior
The cell should highlight like it does when using `RetainElement`.

### Actual Behavior
The cell is highlighted (default grey color) only on touch-up when `ItemSelected` event is also triggered.

### Basic Information

- Version with issue: Xamarin.Forms 3.1.0.637273
- Last known good version: it's an older issue
- IDE:
- Platform Target Frameworks:
  - iOS:  11.4

### Reproduction Link
[TouchUpHighlight.zip](https://github.com/xamarin/Xamarin.Forms/files/2201382/TouchUpHighlight.zip)

### PR DESCRIPTION
**Pull request by v-haroha**
### Description of Change ###

Under ContextActionCell.cs for iOS under the SelectGestureRecognizer overrode the TouchesBegan method to call Tapped method that passes Tapped event to VeiwCell

### Issues Resolved ### 
- fixes #3320 

### API Changes ###
Added:
```

public override void TouchesBegan(NSSet touches, UIEvent evt)

```

### Platforms Affected ### 

- iOS

### Behavioral/Visual Changes ###
A list View will now select an item when an item is first tapped, not when the tap is released. The recycleelement listview will behave the same as the Retain Element

### Before/After Screenshots ### 
Before
image

After
image

### Testing Procedure ###
On iOS.
Have a listview with cachingstrategy set to Recycle Element
Press on an Item but do not release your pointer. The item will not select
Item is selected on release

After the change you will see that the item is select on Pressing of the pointer.

### PR Checklist ###

- [X] Has automated tests 
- [X] Rebased on top of the target branch at time of PR
- [ X] Changes adhere to coding standard

### CODE REVIEW

**Comment by v-haroha** [comment]
Thanks @jfversluis. Your right on both these issues. I'll take another dive into the behavior of listview.

**Comment by v-haroha** [comment]
Changes now match the behavior of a RetainElement listview. On touch the row is Highlighted but not selected. It will only be selected on a release of touch, which will not fire if the touch moves. Now all selected rows have their highlighting removed while the listview is dragging, just as in retain element, after the dragging is complete the previously selected rows will be highlighted again. 
The row that was highlighted but not selected (because of touch down) will remain unselected.

**Comment by jfversluis** [comment]
I'm wondering how this is handled natively. I'm still note entirely onboard with how this looks. The behavior seems alright, but now the selection you might have seem to disappear whenever you start scrolling and comes back whenever you stop scrolling.

I did check the events that are associated with this, they don't seem to fire more than usual so that is good. Just a visual thing.

**Comment by v-haroha** [comment]
> I'm wondering how this is handled natively. I'm still note entirely onboard with how this looks. The behavior seems alright, but now the selection you might have seem to disappear whenever you start scrolling and comes back whenever you stop scrolling.
> 
> I did check the events that are associated with this, they don't seem to fire more than usual so that is good. Just a visual thing.

Ha i know, i actually had to work extra code in there to do that because that's what Retain element does!

**Comment by jfversluis** [comment]
I was working on another ListView issue and noticed the `UserInteractionEnabledWhileDragging` property on a cell. Maybe that is something we can use?

**Comment by v-haroha** [comment]
I’ll test out what that does and if it will work for this situation.


Sincerely,



Harold (Joe) Harvey

Support Engineer v-haroha@microsoft.com<mailto:v-haroha@microsoft.com>
Developer - Demand On Prem
1 (980) 776-2817

M-F 8:00a – 4:00p EST


[Microsoft]
If you have any feedback about my work, please let either me or my manager Nam Su Kang know at nkang@microsoft.com<mailto:nkang@microsoft.com>

________________________________

**Comment by v-haroha** [comment]
@jfversluis Setting UserInteractionEnabledWhileDragging to either true or false does not change the functionality of the ListView cell. The original issue still presists, the Cell is only highlighted on Tap Release and list view highlighting is not disabled while scrolling.

I'm not sure what the expected behavior of UserInteractionEnabledWhileDragging is, i would imagine it should be False by default, you wouldn't want to interact with cells while scrolling a list.

**Comment by v-haroha** [comment]
@kingces95 Requesting update on PR status please.

**Comment by v-haroha** [comment]
@samhouts @kingces95 @jfversluis 
Update on PR status please, issue still exists.

**Comment by v-haroha** [comment]
So whats with these failed tests? I'm not sure what they are testing or how they are running but the ones that failed dont actually seem to have anything to do with my changes. Was the server having issues or something? Do I need to address anything?

**Comment by samhouts** [comment]
@rmarinho @PureWeen Same failure here. Just need to rebase, or what?

**Comment by PureWeen** [comment]
@samhouts yea should be fixed now

**Pull request merged**
