### PR TITLE
[Android] Fix Label LineHeight

### LINKED ISSUE #3344: [Android, UWP] LineHeight not working on 3.2.0-pre1
### Description
I set the LineHeight to 1.5 (or more) and it looks good on iOS, but on Android it appears to have no impact.

### Basic Information

- Version with issue: 3.2.0.637442-pre1

### Screenshots

screenshot 2018-07-19 14 39 22
screenshot 2018-07-19 14 39 16

### Reproduction Link

https://github.com/davidortinau/TheLittleThingsPlayground/blob/3.2.0-pre/TheLittleThingsPlayground/Views/ThreeTwoPage.xaml

[LineHeight.zip](https://github.com/xamarin/Xamarin.Forms/files/2212038/LineHeight.zip)

### PR DESCRIPTION
**Pull request by kingces95**
### Description of Change ###

Label didn't refresh if LineHeight changes. 

### Issues Resolved ###

fixes #3344

### API Changes ###

None

### Platforms Affected ###

- Android

### Behavioral/Visual Changes ###

None

### PR Checklist ###

- [ ] Has automated tests 
- [ ] Rebased on top of the target branch at time of PR
- [ ] Changes adhere to coding standard

### CODE REVIEW

**Comment by samhouts** [comment]
No test case?

**Comment by samhouts** [comment]
Also, @PureWeen indicated that the issue also occurs in UWP.

**Comment by kingces95** [comment]
Actually fixes an existing unit test: https://github.com/xamarin/Xamarin.Forms/blob/5112f0928fc377550a5dd58213b520a0f6cae518/Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue1734.cs.

Didn't notice the UAP tag! I'll take a look.

**Comment by rmarinho** [comment]
Hey @henricm i wonder if you can take a quick look if everything looks good? 

Thanks

**Comment by kingces95** [comment]
UWP LineHeight seems to work.
45dd52bd-175a-44d4-b2ef-5faf0e4651d2

**Comment by PureWeen** [comment]
@kingces95  did you test when the LineHeight is initialized to a non default value? opposed to changed after it's been rendered?

**Comment by rmarinho** [comment]
hey @kingces95 did you had a chance to look at @PureWeen comment , let's see if we can get this merged. Thanks

**Pull request merged**
