### PR TITLE
[WIP] 7060 DataTemplateSelectorList

### LINKED ISSUE #7060: [Enhancement] DataTemplateSelector - Support for defining several templates in XAML code.
Creating a DataTemplateSelector manually is a little boring. it would be nice to do it right in xaml.

``` xaml
<DataTemplateSelector>
    <DataTemplate ForType="{x:Type local:Foo}">
        <Entry Text="I am a Foo" />
    </DataTemplate >
    <DataTemplate ForType="{x:Type System:String}">
        <Label Text="I am a String" />
    </DataTemplate >
</DataTemplateSelector>
```

### PR DESCRIPTION
**Pull request by KSemenenko**
#### Create DataTemplate for types in XAML ####
It seems to me that now to create a DataTemplateSelector we need to do some work to create DataTemplateSelector manually.
I think it would be more convenient to be able to create a DataTemplateSelector in XAML.
And I suggest adding something like _DataTemplateSelectorList_ in which I can create the right amount of DataTemplate for the types I need.

``` xaml
<ListView>
    <ListView.ItemTemplate>
        <DataTemplateSelectorList>
            <DataTemplate TemplateDataType="{x:Type local:NamedColor}">
                <Label Text="I am a local:NamedColor" />
            </DataTemplate>
            <DataTemplate TemplateDataType="{x:Type System:String}">
                <Label Text="I am a String" />
            </DataTemplate>
        </DataTemplateSelectorList>
    </ListView.ItemTemplate>
</ListView>
```
like in WPF 
https://docs.microsoft.com/en-us/dotnet/framework/wpf/data/data-templating-overview#the-datatype-property
### Issues Resolved ### 

- fixes #7060

### Platforms Affected ### 

- Core/XAML (all platforms)

### PR Checklist ###

- [ ] Has automated tests 
- [ ] Rebased on top of the target branch at time of PR
- [ ] Changes adhere to coding standard

### CODE REVIEW

**Comment by KSemenenko** [comment]
I would like to know your opinion about this implementation. Of course this is very rough, but I just wanted to show an idea.
 And I also want to ask you @StephaneDelcroix is it a good idea to use x:DataType there?

**Comment by KSemenenko** [comment]
Also I found problem #3177 and I have the same. Although I do not have DynamicObject.

**Comment by KSemenenko** [comment]
perhaps I should add a property of the DataType type to the DataTemplate (as it is in WPF) which will determine what type this template is for.

**Comment by StephaneDelcroix** [comment]
@KSemenenko please provide a valid description for this PR first, then we'll start discussing :)

`x:DataType` is a bad idea, as it has a different meaning

your DataTemplateSelector implementation doesn't require any changes, and so far we tried to avoid including custom DTS in XF. if we add a DTS for target type, we'll have to add 12 of them, for the most common cases, and even the common cases might not cover everyone needs.

This is why I think this is best left out of XF core code...

**Comment by KSemenenko** [comment]
@StephaneDelcroix You are right, I forgot to add a description. done.
In my projects, I create heaps of DataTemplateSelectors, but still use them in one place.
And I thought, maybe this would be appropriate in XF, a way to create sectors in XAML.

**Comment by StephaneDelcroix** [comment]
I'm closing this for now, and the issue related, for the reasons stated earlier

**Pull request closed without merging**
