### PR TITLE
[XamlC] Resolve complex property type

### PR DESCRIPTION
**Pull request by akihikodaki**
### Description of Change ###

`Xamarin.Forms.Build.Tasks.PropertyDefinitionExtensions` couldn't resolve complex property types covered by #4061 and #4776 for `Xamarin.Forms.Build.Tasks.TypeReferenceExtensions.ResolveGenericParameters`. By contrast, `ResolveGenericParameters` cannot resolve a generic parameter given as an argument while `PropertyDefinitionExtensions`. It is actually not clear whether any caller gives `ResolveGenericParameters` such an argument or not.

This change lets `ResolveGenericParameters` consider about the case, and replaces the uses of `PropertyDefinitionExtensions` with `ResolveGenericParameters`.

### Issues Resolved ### 

None

### API Changes ###

 
 None

### Platforms Affected ### 

- Core/XAML (all platforms)

### Behavioral/Visual Changes ###

None

### Before/After Screenshots ### 

Not applicable

### PR Checklist ###

- [X] Has automated tests 
- [X] Rebased on top of the target branch at time of PR
- [X] Changes adhere to coding standard

### CODE REVIEW

**Comment by StephaneDelcroix** [comment]
doesn't build, apparently

**Comment by akihikodaki** [comment]
414b8d1250f1434aec4a7a0b1c2361940e09eea4 fixes the build failure.

**Comment by StephaneDelcroix** [comment]
@akihikodaki could rebase and retarget to 4.0.0 ? thanks

**Comment by akihikodaki** [comment]
8547486439a454b1698f487cd603bd7abecd4f19: rebased to `4.0.0`.

**Pull request merged**
