### PR TITLE
Marking exposed plumbing internal only in the docs.

### PR DESCRIPTION
**Pull request by MichaelNorman**
### Description of Change ###

Marked plumbing APIs internal only.

### Bugs Fixed ###

- Provide links to bugs here

### API Changes ###

None.

### Behavioral Changes ###

None. (Documentation only.)

### PR Checklist ###

- [ ] Has tests (if omitted, state reason in description)
- [x] Rebased on top of master at time of PR
- [ ] Changes adhere to coding standard
- [ ] Consolidate commits as makes sense

### CODE REVIEW

**Comment by rmarinho** [comment]
This is failing the docs step :/

**Comment by kingces95** [comment]
Rebased and pushed additional docs changes.

**Comment by MichaelNorman** [comment]
The "To be added." => "For internal use..." changes look good (and non-breaking).

**Comment by rmarinho** [comment]
@MichaelNorman @kingces95 needs rebase again :( sorry

**Pull request merged**
