### PR TITLE
[iOS] Cell.DefaultBackgroundColor iOS platform-specific only works for header cells

### LINKED ISSUE #5346: Forms 3.6: Cell.DefaultBackgroundColor iOS platform-specific only works for header cells
### Description

[This](https://github.com/xamarin/Xamarin.Forms/pull/4002#issuecomment-431049817) PR is included in Forms 3.6, and is used to set the background color of `Cell`s. It works fine when setting the background color of a header cell in a `ListView`. @AndreiMisiukevich tells me it should work for any cell, regardless of whether it's in a header or not. However, it doesn't.

```xaml
        <ListView ItemsSource="{Binding GroupedEmployees}"
                  IsGroupingEnabled="true">
            <ListView.GroupHeaderTemplate>
                <DataTemplate>
                    <ViewCell ios:Cell.DefaultBackgroundColor="Teal">
                        <Label Margin="10,10"
                               Text="{Binding Key}"
                               FontAttributes="Bold" /> 
                    </ViewCell>
                </DataTemplate>
            </ListView.GroupHeaderTemplate>
            <ListView.ItemTemplate>
                <DataTemplate>
                    <TextCell ios:Cell.DefaultBackgroundColor="Yellow"
                              Text="{Binding Name}"
                              Detail="{Binding Age}" />
                </DataTemplate>
            </ListView.ItemTemplate>
        </ListView>
```

### Steps to Reproduce

1. Run the attached sample on iOS.
2. Browse to the ListView/Cell Platform-Specifics page.

### Expected Behavior

Header cells should have a teal background color. Non-header cells should have a yellow background color.

### Actual Behavior

Header cells have a teal background color. Non-header cells have the default background color.

### Basic Information

- Version with issue: 3.6.0.135200-pre1
- IDE: VSMac
- Platform Target Frameworks: 
  - iOS:  12.1

### Screenshots

simulator screen shot - iphone x - 2019-02-22 at 11 59 06

### Reproduction Link

[PlatformSpecifics.zip](https://github.com/xamarin/Xamarin.Forms/files/2893804/PlatformSpecifics.zip)

### PR DESCRIPTION
**Pull request by AndreiMisiukevich**
### Description of Change ###

Modified SetBackgroundColor method

```csharp
public virtual void SetBackgroundColor(UITableViewCell tableViewCell, Cell cell, UIColor color)
{
    tableViewCell.TextLabel.BackgroundColor = color; // New line
    tableViewCell.ContentView.BackgroundColor = color; // New line
    tableViewCell.BackgroundColor = color;
}
```

### Issues Resolved ### 
- fixes #5346 

### API Changes ###
None

### Platforms Affected ### 

- iOS

### Behavioral/Visual Changes ###
Actual behavior: you cannot change background color of non-header cell by setting platform-specific property

### Testing Procedure ###

* Open original issue #5346 
* Run the attached sample on iOS.
* Browse to the ListView/Cell Platform-Specifics page.

### CODE REVIEW

**Comment by samhouts** [comment]
@AndreiMisiukevich Can you please rebase to 3.6? Thanks!

**Comment by hartez** [comment]
@AndreiMisiukevich Did something go wrong with the rebase? I see 91 files changed, and a lot of them seem to be in GTK, etc.

**Comment by AndreiMisiukevich** [comment]
@hartez yes, definitely.

What are the exact steps for achieving it?

I changes base branch in the header
image

What should i do after that? Or I have already break it?

**Comment by AndreiMisiukevich** [comment]
@hartez it would be better if i create new PR with 3.6.0 as target branch.
But i appreciate, if you explain steps how should i handle such cases in future.

**Comment by hartez** [comment]
@AndreiMisiukevich 
1. Rebase your changes, e.g.: `git rebase -i 3.6.0`
2. `git push --force`
3. Then change the target branch on GitHub (like you did).

**Comment by AndreiMisiukevich** [comment]
@hartez thank you very much

**Pull request closed without merging**
