### PR TITLE
Fixed NotImplementedException refreshing items in WPF ListView

### LINKED ISSUE #3309: [WPF] NotImplementedException When executing Clear and Remove methods on ObservableCollection
When executing Clear and Remove methods on ObservableCollection the exception is thrown: 'System.NotImplementedException' in Xamarin.Forms.Core.dll.
But if I cover it with try catch the result of the operation is correct.

Tested on
Xamarin latest 3.1 version
Platform WPF

### LINKED ISSUE #3648: Xamarin.Forms for WPF: cannot clear ListView selection
### Description

Cannot unselect items in a ListView under Xamarin.Forms.Platform.WPF. This results in a NotImplementedException being thrown here; 

https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Core/TemplatedItemsList.cs#L276

when you try to change the collection (either observable or straight changing ItemsSource). 

### Steps to Reproduce

1. Create a ListView with ItemsSource as ObservableCollection<string>
2. Add some items in the collection; works fine
3. Click on one of the items
4. listView.SelectedItem = null; 
(5. Clear the ObservableCollection<string>) 

### Expected Behavior

Item is no longer selected and the list is cleared. 

### Actual Behavior

Item is still selected, and when doing anything with the ObservableCollection that affects the selected item, the NotImplementedException pops up. 

### Basic Information

- Version with issue: 3.1.0.697729 Xamarin.Forms WPF
- Last known good version: never saw it work
- IDE: Visual Studio 15.6.0
- Platform Target Frameworks: 
 WPF: 3.1.0.697729
- Android Support Library Version: 
- Nuget Packages:
Xamarin.Forms
Xamarin.Forms.Platform.WPF
- Affected Devices:
Windows 10

### LINKED ISSUE #3737: [Feedback] System.NotImplementedException in Xamarin WPF
### Description

<p>When clearing a observablecollection or removing an item from it, we get a 

System.NotImplementedException: 'The method or operation is not implemented.'

error in the WPF implementation of Xamarin. In Android and UWP, the error does not occur.</p><p><br></p><p><span style="display:inline !important;float:none;background-color:rgba(255, 255, 255, 1);color:rgb(33, 33, 33);font-size:14px;font-style:normal;font-variant:normal;font-weight:400;letter-spacing:normal;orphans:2;text-align:left;text-decoration:none;text-indent:0px;text-transform:none;white-space:normal;word-spacing:0px;">We attach a mini solution with which you can reproduce the problem. We have noticed that if we enclose the Clear() method in a try / catch structure, the Exception is ignored and the program continues correctly (list clears and rebuilds).This exception only happens in WPF, UWP and Android work correctly.</span><b></b><i></i><u></u><sub></sub><sup></sup><strike></strike><br></p><p><b></b><i></i><u></u><sub></sub><sup></sup><strike></strike><br></p>
<a href="https://developercommunity.visualstudio.com/content/problem/272352/systemnotimplementedexception-in-xamarin-wpf.html">View on Developer Community</a>
<br>To find diagnostic information, see the <a href="https://devdiv.visualstudio.com/DevDiv/_workitems/edit/632874">original linked feedback ticket</a>.

### Source

[678647](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/678647)

### PR DESCRIPTION
**Pull request by jsuarezruiz**
### Description of Change ###

Fixed NotImplementedException refreshing items (addin, clear) in WPF ListView.

### Issues Resolved ### 
- fixes #3309 
- fixes #3737 
- fixes #3648 

### Platforms Affected ### 
- WPF

### Behavioral/Visual Changes ###
Now, can clear or change items in WPF ListView.

### Before/After Screenshots ### 

Before
wrong-3309

After

### PR Checklist ###

- [ ] Has automated tests 
- [ ] Rebased on top of the target branch at time of PR
- [ ] Changes adhere to coding standard

### CODE REVIEW

**Comment by samhouts** [comment]
@jsuarezruiz needs rebase! Thanks!

**Comment by jsuarezruiz** [comment]
Ok!

**Comment by rmarinho** [comment]
build

**Comment by petarkekez** [comment]
is this fix in one pre-release version? i have tried the XF v 3.3.0.893527-pre3 and i am still getting the same error

**Comment by rmarinho** [comment]
try a nightly this was merged on Master 11 days ago, it didn't got to the 3.3.0 branch so it shouldn't be on the release.

**Pull request merged**
