### PR TITLE
[Android] AndroidAppLinks.cs refactor to comply with Firebase's new packages

### PR DESCRIPTION
**Pull request by pabiagioli**
### Description of Change ###

I updated the packages to AndroidAppLinks project and removed old and deprecated packages following migration instructions from Google's Firebase docs: https://firebase.google.com/docs/app-indexing/android/migrate

### Bugs Fixed ###

- Bugzilla #54383: https://bugzilla.xamarin.com/show_bug.cgi?id=54383 

### API Changes ###

Added:
 - AndroidActionSuccessListener //internal class within AndroidAppLinks
 - AndroidActionFailureListener //internal class within AndroidAppLinks

Changed:
 - AndroidAppLinks.cs //refactored a few methods to upgrade to latest Firebase's instructions

### Behavioral Changes ###

None. The apps should work exactly the same

### PR Checklist ###

- [x] Has tests (if omitted, state reason in description)
- [x] Rebased on top of master at time of PR
- [x] Changes adhere to coding standard
- [x] Consolidate commits as makes sense

### CODE REVIEW

**Comment by petersondrew** [comment]
Anything the community can do to help move this PR along? We'd be willing to help test a pre-release of the AppLinks package at the very least.

**Comment by closetoyou293** [comment]
Hi guys, when will this issue be released via Nuget? I'm stuck because of it.

**Comment by rmarinho** [comment]
build

**Comment by rmarinho** [comment]
Needs nuspec updating, testing now the build

**Comment by rmarinho** [comment]
Build is faling 

```
:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1575, 5): error MSB4018: The "LinkAssemblies" task failed unexpectedly.
Java.Interop.Tools.Diagnostics.XamarinAndroidException: error XA2006: Could not resolve reference to 'Android.Gms.Common.Apis.GoogleApiClient' (defined in assembly 'Xamarin.Firebase.AppIndexing, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null') with scope 'Xamarin.GooglePlayServices.Base, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. When the scope is different from the defining assembly, it usually means that the type is forwarded. ---> Mono.Cecil.ResolutionException: Failed to resolve Android.Gms.Common.Apis.GoogleApiClient
   at Mono.Linker.Steps.MarkStep.MarkType(TypeReference reference)
   at MonoDroid.Tuner.MonoDroidMarkStep.MarkType(TypeReference reference)
   at Mono.Linker.Steps.MarkStep.MarkField(FieldReference reference)
   at Mono.Linker.Steps.MarkStep.MarkFields(TypeDefinition type, Boolean includeStatic)
   at Mono.Linker.Steps.MarkStep.MarkType(TypeReference reference)
   at MonoDroid.Tuner.MonoDroidMarkStep.MarkType(TypeReference reference)
   at Mono.Linker.Steps.MarkStep.InitializeType(TypeDefinition type)
   at Mono.Linker.Steps.MarkStep.InitializeType(TypeDefinition type)
   at Mono.Linker.Steps.MarkStep.InitializeAssembly(AssemblyDefinition assembly)
   at Mono.Linker.Steps.MarkStep.Initialize()
   at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
   at Mono.Linker.Pipeline.Process(LinkContext context)
   at MonoDroid.Tuner.Linker.Process(LinkerOptions options, LinkContext& context)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
   --- End of inner exception stack trace ---
   at Java.Interop.Tools.Diagnostics.Diagnostic.Error(Int32 code, Exception innerException, String message, Object[] args)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext() 
```

**Comment by pabiagioli** [comment]
Does the error have anything to do with the nuget dependencies? Can I do something from my side to fix this issue?
The whole point of this PR is to replace the use of GoogleApiClient for Firebase's new implementation, so I don't understand why is the error mentioning a class that is not being used...

**Comment by pabiagioli** [comment]
Does anyone know why is this merge failing?

**Comment by Nikdm46** [comment]
I got an error during the build when use Xamarin.Forms.AppLinks:

Could not load type of field 'Xamarin.Forms.Platform.Android.AppLinks.AndroidAppLinks:_client' (0) due to: Could not resolve type with token 01000013 (from typeref, class/assembly Android.Gms.Common.Apis.GoogleApiClient, Xamarin.GooglePlayServices.Basement, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null) assembly:Xamarin.GooglePlayServices.Basement, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null type:Android.Gms.Common.Apis.GoogleApiClient member:

 need help!

**Comment by rmarinho** [comment]
Working on this on #1107

**Pull request closed without merging**
