### PR TITLE
Bug unable to set title on date picker view 9673

### LINKED ISSUE #9673: [Bug] Unable to set Title on date picker view.
### Description
I am using the Material Visual library in my Xamarin forms application, I am able to set Title or Placeholder on other entry fields such as the regular picker and the entry fields etc. There is no property i am able to set for this on the date picker which results in non-uniform UI.

### Steps to Reproduce

1. Create a new Xamarin Forms project
2.  Update to the latest stable release
3.  Create a content page
4. Add a Date Picker control
5. Try to add a title or placeholder to the xml element

### Expected Behavior
I should be able to set the floating title via XAML or c sharp.
### Actual Behavior
There is no property to set

### PR DESCRIPTION
**Pull request by davidbuckleyni**
### Description of Change ###

This adds an important feature to the Date Picker XAML  for IOS and Android within Xamarin Forms. You can now set a hint style text item called PlaceHolder and also change the colour of this text as well.

**PlaceHolder**
**PlaceHolderColor**

### Issues Resolved ### 
- fixes #9673

Added code to following files iOS and Android
Date Picker.cs in Xamarin forms core.
   
Also within each platform the following was added
DatePickerRenderer.cs
UpdatePlaceholderColor
UpdatePlaceholder

### XAML Changes ###
Now when you create a date picker you can do the following.

###Syntax Example ###

    <DatePicker x:Name="Picker1" TextColor="Blue" BackgroundColor="White"                          
     Placeholder="Test" PlaceHolderColor="Aqua" /> 

### API Changes ###
None
**Platforms Affected**
**iOS**
**Android**

**Images**
image

### CODE REVIEW

**Comment by davidbuckleyni** [comment]
Hi @StephaneDelcroix  I added a new version here which as I forgot you mentioned to add PlaceHolderColor as well I hope this works but needs help with the Unit Tests to prove that it does its working in the mark-up as shown there.

**Comment by davidbuckleyni** [comment]
@PureWeen do u wanna track this into Maui or when will pull requests get merged into Maui.

**Comment by davidbuckleyni** [comment]
@PureWeen can u fire off a muster build for me and tell me how to access it so I can test it in an app properly and provide screen shots thanks.

**Comment by PureWeen** [comment]
@davidbuckleyni here is fine

We'll move things to Maui ourselves as needed

Kicked off a build

**Comment by davidbuckleyni** [comment]
See the way their two commits it’s really only the second one we need. Thanks is their a video on how to test the nuget ? Or do u send me a local copy

**Comment by davidbuckleyni** [comment]
@PureWeen only errors I had was those .net ones we said about before.

**Comment by davidbuckleyni** [comment]
@PureWeen How do I test the nuget do u give me a private url ? Or just the package.

**Comment by PureWeen** [comment]
https://dev.azure.com/xamarin/public/_build/results?buildId=18944&view=artifacts&type=publishedArtifacts

**Comment by davidbuckleyni** [comment]
Just install it as a local nuget?

**Comment by davidbuckleyni** [comment]
@PureWeen  it doesnt work because the null text value item is not in this build I need to be able to see the entry component without a date on launch can we please the null text bug fix in the other team memebers did ?

**Comment by davidbuckleyni** [comment]
@PureWeen I think we need this pull request in the same branch so can test when the text is empty?.

https://github.com/xamarin/Xamarin.Forms/pull/6947

**Comment by davidbuckleyni** [comment]
@PureWeen  can u stick the do not merge on this budy. 

I still have to have time to finish it off.

**Comment by PureWeen** [comment]
@davidbuckleyni 

> Just install it as a local nuget?

yes

>  DatePicker Nullable

Yea we need to revitalize that one :-/ I'll see if we can get that into the schedule somewhere

> can u stick the do not merge on this budy.

Added

**Comment by davidbuckleyni** [comment]
@PureWeen thanks how do we get that clear button into my merge or should I clear today’s date if their is a place holder value would that be best ?

**Comment by davidbuckleyni** [comment]
@PureWeen yesh I was able to do that for mine but if u look up I showed u a issue that is linked where it adds a clear button obv my fork doesn’t have that code in there yet so I don’t see the clear button when I use the date picker I think it was only added in that issue

**Comment by davidbuckleyni** [comment]
@PureWeen did u understand what I mean cause the way you set today date in the date property so it’s not null I don’t see a easy way to clear that value any hints or tips to get this sorted be great.

**Comment by samhouts** [comment]
We'll revisit this later in .NET MAUI. Closing now to do a little housekeeping. Thank you so much for the work you put into this! :)

**Pull request closed without merging**
