### PR TITLE
Put the child view underneath the Navigation Bar when translucent (iOS)

### PR DESCRIPTION
**Pull request by skaman**
### Description of Change ###

Under iOS, only if the Navigation Bar is translucent, the content is placed underneath the Navigation
Bar and not aligned to the bottom.

### Bugs Fixed ###

- https://forums.xamarin.com/discussion/27745/navigationrender-issue

### API Changes ###

None

### Behavioral Changes ###

Before this patch, if the Navagion Bar was setted to translucent, underneath the navigation bar the user see the background of the navigation controller. After the patch he'll see the child view (on iOS this should be the right behaviour for translucent navigation bar)

### PR Checklist ###

- [ ] Has tests (if omitted, state reason in description)
- [ ] Rebased on top of master at time of PR
- [ ] Changes adhere to coding standard
- [ ] Consolidate commits as makes sense

### CODE REVIEW

**Comment by jimmgarrido** [comment]
This is a similar fix as #621

**Comment by skaman** [comment]
True, the #621 maybe need also a fix for the container height. If the content go underneath the navigation bar, the height of the navigation bar should not be considered for the container height (it's like the navigation is invisibile and the container fit the screen).

**Comment by rmarinho** [comment]
@jimmgarrido can you check if this is covered by #621 if so we can close this one.

**Comment by jimmgarrido** [comment]
@rmarinho @skaman #621 does not adjust the container's size for this change and results in an empty area below the page content. #621 should be closed in favor of this pull request.

**Pull request merged**
