### PR TITLE
Fix OpenUri obsoletion message

### LINKED ISSUE #11433: Obsolete message for Device.OpenUri mentions non-existent APIs
`Device.OpenUri` is marked as obsolete with this message:

https://github.com/xamarin/Xamarin.Forms/blob/991f109df060cc33e79f6a61b71a64e49a8c11b8/Xamarin.Forms.Core/Device.cs#L227

But none of those APIs exist on `Launcher`. These are the APIs that exist:

* `OpenAsync`
* `TryOpenAsync`
* `CanOpenAsync`

The message should be updated to reflect the correct API names.

### PR DESCRIPTION
**Pull request by Eilon**
### Description of Change ###

Fix invalid message.

### Issues Resolved ### 
Fixes #11433

### API Changes ###
 
 None

### Platforms Affected ### 
All

### Behavioral/Visual Changes ###

None

### Before/After Screenshots ### 

Not applicable

### PR Checklist ###

- [ ] Targets the correct branch
- [x] Tests are passing (or failures are unrelated)

### CODE REVIEW

**Comment by Eilon** [comment]
cc @StephaneDelcroix because this is related to a PR you sent a while ago.

**Comment by StephaneDelcroix** [comment]
@Eilon could you rebase and retarget this on 4.8.0 ?

**Comment by Eilon** [comment]
I tried doing that in the GitHub UI and it brought in many other changes. I'll just send a new clean PR against 4.8.0.

**Comment by Eilon** [comment]
Closing this. Please see https://github.com/xamarin/Xamarin.Forms/pull/11436, which is based on 4.8.0.

**Comment by StephaneDelcroix** [comment]
> Closing this. Please see #11436, which is based on 4.8.0

thx. I usually rebase my branch locally, then force-push, and that updates the existing PR without the need to create a new one. ask me more if you're interested

**Comment by Eilon** [comment]
Oh I can do that, but that involves cloning the repo. I did all of this directly in the browser 😁

**Comment by StephaneDelcroix** [comment]
> Oh I can do that, but that involves cloning the repo. I did all of this directly in the browser 😁

🤪

**Pull request closed without merging**
