### PR TITLE
[Xaml[C]] Allow to connect to event handler with overloads

### PR DESCRIPTION
**Pull request by akihikodaki**
### Description of Change ###

`Xamarin.Forms.Xaml.ApplyPropertiesVisitor.TryConnectEvent` connects an event to an event handler with the following two steps:
1. Find a method by name
2. Try to connect the event to the method, and throw an exception saying the method handler has an incorrect signature if it fails

However, there actually can be several methods with the same name but different signatures. This change solves the issue by iterating methods with the same name.

### Issues Resolved ### 

None

### API Changes ###

 
 None

### Platforms Affected ### 

- Core/XAML (all platforms)

### Behavioral/Visual Changes ###

None

### Before/After Screenshots ### 

Not applicable

### Testing Procedure ###

Unfortunately it is impossible to write a reliable test because the order of methods returned by `System.Reflection.RuntimeReflectionExtensions.GetRuntimeMethods` is not defined.

### PR Checklist ###

- [ ] Has automated tests  (See "Testing Procedure" for the reason why tests are omitted.)
- [ ] Rebased on top of the target branch at time of PR
- [X] Changes adhere to coding standard

### CODE REVIEW

**Comment by akihikodaki** [comment]
> I think I understand why this does, and I'm ok with it, but I'd need some UnitTests. do you think you could come up with a xaml sample for this ? thanks

No, unfortunately.
> Unfortunately it is impossible to write a reliable test because the order of methods returned by `System.Reflection.RuntimeReflectionExtensions.GetRuntimeMethods` is not defined.

**Comment by StephaneDelcroix** [comment]
@akihikodaki could you rebase this on top of master ? thanks

**Comment by akihikodaki** [comment]
51258eca7e7b67b836d563a40c66c421aed74523: rebased to 6a92c858e555eb7b91eec22608b7eede24667f36.

**Comment by StephaneDelcroix** [comment]
@akihikodaki  Are you sure about the rebase ? it looks like the SetPropertyVisitor changes are gone

Did I merged or included those changes already in the past weeks ?

**Comment by StephaneDelcroix** [comment]
build

**Comment by akihikodaki** [comment]
> @akihikodaki Are you sure about the rebase ? it looks like the SetPropertyVisitor changes are gone

> Did I merged or included those changes already in the past weeks ?

It's my fault. I pushed it as commit 92790162d974768b152bcbdfd7693f4dbbb69bd4.

**Pull request merged**
