### PR TITLE
Fix Map ItemsSource bp name

### LINKED ISSUE #5498: Maps Binding - Possible typo in the bindable property
I was looking to see how the template binding was done in #4269  and noticed this line of code :

https://github.com/xamarin/Xamarin.Forms/blob/138791927206ef6c2f64243f8b991ee768ef4193/Xamarin.Forms.Maps/Map.cs#L21

Should this not have been nameof(ItemsSource):

`		public static readonly BindableProperty ItemsSourceProperty = BindableProperty.Create(nameof(ItemsSource), typeof(IEnumerable), typeof(Map), default(IEnumerable),`

### PR DESCRIPTION
**Pull request by andreinitescu**
### Issues Resolved ### 

- fixes #5498

### PR Checklist ###

- [ ] Has automated tests 
- [x] Rebased on top of the target branch at time of PR
- [x] Changes adhere to coding standard

### CODE REVIEW

**Comment by StephaneDelcroix** [comment]
@AndreiMisiukevich 🤪🤪🤪🤪🤪🤪🤪🤪🤪

could you please rebase and retarget this to the 3.6.0 branch ? thanks

**Comment by AndreiMisiukevich** [comment]
> @AndreiMisiukevich 🤪🤪🤪🤪🤪🤪🤪🤪🤪
> 
> could you please rebase and retarget this to the 3.6.0 branch ? thanks

@andreinitescu @StephaneDelcroix too many Andreis

**Comment by andreinitescu** [comment]
> @AndreiMisiukevich 🤪🤪🤪🤪🤪🤪🤪🤪🤪

@StephaneLebowski done!

**Comment by davidortinau** [comment]
> too many Andreis xD

Not enuf! We'll take as many as we can get if they all contribute like you two. :) @AndreiMisiukevich @andreinitescu

**Comment by StephaneDelcroix** [comment]
> > @AndreiMisiukevich 🤪🤪🤪🤪🤪🤪🤪🤪🤪
> 
> @StephaneLebowski done!

well done. that's proper trolling

**Comment by andreinitescu** [comment]
> well done. that's proper trolling

@StephaneLebowski, thanks!

**Pull request merged**
