### PR TITLE
[Android, Material] Fixes crash ProgressBar on Android 5.0

### LINKED ISSUE #5968: [Bug] ProgressBar with Visual=Material causing crash on Android 5.0
### Description

App crashes when using ProgressBar with Visual="Material" on android 5.0, I have also tested that on android 4.4 and 9.0 and it works fine there.

stack trace:
`
04-21 15:18:34.104 I/MonoDroid( 4152): UNHANDLED EXCEPTION:
04-21 15:18:34.124 I/MonoDroid( 4152): System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> Android.Content.Res.Resources+NotFoundException: File res/drawable/materialprogressbar.xml from drawable resource ID #0x7f020155 ---> Android.Content.Res.Resources+NotFoundException: File res/color/white_disabled_material.xml from color state list resource ID #0x7f0a00a5 ---> Java.Lang.RuntimeException: not a float!
04-21 15:18:34.124 I/MonoDroid( 4152):    --- End of inner exception stack trace ---
04-21 15:18:34.124 I/MonoDroid( 4152):    --- End of inner exception stack trace ---
04-21 15:18:34.124 I/MonoDroid( 4152):   at Java.Interop.JniEnvironment+InstanceMethods.CallNonvirtualVoidMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00089] in <286213b9e14c442ba8d8d94cc9dbec8e>:0 
04-21 15:18:34.124 I/MonoDroid( 4152):   at Java.Interop.JniPeerMembers+JniInstanceMethods.FinishCreateInstance (System.String constructorSignature, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x0004f] in <286213b9e14c442ba8d8d94cc9dbec8e>:0 
04-21 15:18:34.124 I/MonoDroid( 4152):   at Android.Widget.ProgressBar..ctor (Android.Content.Context context, Android.Util.IAttributeSet attrs, System.Int32 defStyleAttr) [0x000b7] in <95d915721ad748108ff096dce8f8f32c>:0 
04-21 15:18:34.124 I/MonoDroid( 4152):   at Xamarin.Forms.Material.Android.MaterialProgressBarRenderer..ctor (Android.Content.Context context) [0x00000] in D:\a\1\s\Xamarin.Forms.Material.Android\MaterialProgressBarRenderer.cs:30 
04-21 15:18:34.124 I/MonoDroid( 4152):   at (wrapper managed-to-native) System.Reflection.MonoCMethod.InternalInvoke(System.Reflection.MonoCMethod,object,object[],System.Exception&)
04-21 15:18:34.124 I/MonoDroid( 4152):   at System.Reflection.MonoCMethod.InternalInvoke (System.Object obj, System.Object[] parameters, System.Boolean wrapExceptions) [0x00005] in <d4a23bbd2f544c30a48c44dd622ce09f>:0 
04-21 15:18:34.124 I/MonoDroid( 4152):    --- End of inner exception stack trace ---
04-21 15:18:34.124 I/MonoDroid( 4152):   at System.Reflection.MonoCMethod.InternalInvoke (System.Object obj, System.Object[] parameters, System.Boolean wrapExceptions) [0x0001a] in <d4a23bbd2f544c30a48c44dd622ce09f>:0 
04-21 15:18:34.124 I/MonoDroid( 4152):   at System.Reflection.MonoCMethod.DoInvoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x0007a] in <d4a23bbd2f544c30a48c44dd622ce09f>:0 
04-21 15:18:34.134 I/MonoDroid( 4152):   at System.Reflection.MonoCMethod.Invoke (System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <d4a23bbd2f544c30a48c44dd622ce09f>:0 
04-21 15:18:34.134 I/MonoDroid( 4152):   at System.RuntimeType.CreateInstanceImpl (System.Reflection.BindingFlags bindingAttr, System.Reflection.Binder binder, System.Object[] args, System.Globalization.CultureInfo culture, System.Object[] activationAttributes, System.Threading.StackCrawlMark& stackMark) [0x0022b] in <d4a23bbd2f544c30a48c44dd622ce09f>:0 
04-21 15:18:34.134 I/MonoDroid( 4152):   at System.Activator.CreateInstance (System.Type type, System.Reflection.BindingFlags bindingAttr, System.Reflection.Binder binder, System.Object[] args, System.Globalization.CultureInfo culture, System.Object[] activationAttributes) [0x000a1] in <d4a23bbd2f544c30a48c44dd622ce09f>:0 
04-21 15:18:34.134 I/MonoDroid( 4152):   at System.Activator.CreateInstance (System.Type type, System.Object[] args) [0x00000] in <d4a23bbd2f544c30a48c44dd622ce09f>:0 
04-21 15:18:34.134 I/MonoDroid( 4152):   at Xamarin.Forms.Internals.DependencyResolver.ResolveOrCreate (System.Type type, System.Object source, System.Type visualType, System.Object[] args) [0x000af] in D:\a\1\s\Xamarin.Forms.Core\DependencyResolver.cs:58 
04-21 15:18:34.134 I/MonoDroid( 4152):   at Xamarin.Forms.Internals.Registrar`1[TRegistrable].GetHandler (System.Type type, System.Object source, Xamarin.Forms.IVisual visual, System.Object[] args) [0x00052] in D:\a\1\s\Xamarin.Forms.Core\Registrar.cs:71 
04-21 15:18:34.134 I/MonoDroid( 4152):   at Xamarin.Forms.Internals.Registrar`1[TRegistrable].GetHandlerForObject[TOut] (System.Object obj, System.Object[] args) [0x0002c] in D:\a\1\s\Xamarin.Forms.Core\Registrar.cs:103 
04-21 15:18:34.134 I/MonoDroid( 4152):   at Xamarin.Forms.Platform.Android.Platform.CreateRenderer (Xamarin.Forms.VisualElement element, Android.Content.Context context) [0x00000] in D:\a\1\s\Xamarin.Forms.Platform.Android\Platform.cs:339 
04-21 15:18:34.134 I/MonoDroid( 4152):   at Xamarin.Forms.Platform.Android.VisualElementPackager.AddChild (Xamarin.Forms.VisualElement view, Xamarin.Forms.Platform.Android.IVisualElementRenderer oldRenderer, Xamarin.Forms.Platform.Android.RendererPool pool, System.Boolean sameChildren) [0x000af] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:120 
04-21 15:18:34.134 I/MonoDroid( 4152):   at Xamarin.Forms.Platform.Android.VisualElementPackager.SetElement (Xamarin.Forms.VisualElement oldElement, Xamarin.Forms.VisualElement newElement) [0x00139] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:268 
04-21 15:18:34.134 I/MonoDroid( 4152):   at Xamarin.Forms.Platform.Android.VisualElementPackager.Load () [0x00000] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:92 
04-21 15:18:34.134 I/MonoDroid( 4152):   at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].SetPackager (Xamarin.Forms.Platform.Android.VisualElementPackager packager) [0x00007] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:414 
04-21 15:18:34.134 I/MonoDroid( 4152):   at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].SetElement (TElement element) [0x000e0] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:231 
04-21 15:18:34.134 I/MonoDroid( 4152):   at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].Xamarin.Forms.Platform.Android.IVisualElementRenderer.SetElement (Xamarin.Forms.VisualElement element) [0x00027] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:127 
04-21 15:18:34.134 I/MonoDroid( 4152):   at Xamarin.Forms.Platform.Android.Platform.CreateRenderer (Xamarin.Forms.VisualElement element, Android.Content.Context context) [0x0001f] in D:\a\1\s\Xamarin.Forms.Platform.Android\Platform.cs:341 
04-21 15:18:34.134 I/MonoDroid( 4152):   at Xamarin.Forms.Platform.Android.ViewCellRenderer.GetCellCore (Xamarin.Forms.Cell item, Android.Views.View convertView, Android.Views.ViewGroup parent, Android.Content.Context context) [0x0008f] in D:\a\1\s\Xamarin.Forms.Platform.Android\Cells\ViewCellRenderer.cs:41 
04-21 15:18:34.134 I/MonoDroid( 4152):   at Xamarin.Forms.Platform.Android.CellRenderer.GetCell (Xamarin.Forms.Cell item, Android.Views.View convertView, Android.Views.ViewGroup parent, Android.Content.Context context) [0x00075] in D:\a\1\s\Xamarin.Forms.Platform.Android\Cells\CellRenderer.cs:51 
04-21 15:18:34.134 I/MonoDroid( 4152):   at Xamarin.Forms.Platform.Android.CellFactory.GetCell (Xamarin.Forms.Cell item, Android.Views.View convertView, Android.Views.ViewGroup parent, Android.Content.Context context, Xamarin.Forms.View view) [0x0001e] in D:\a\1\s\Xamarin.Forms.Platform.Android\Cells\CellFactory.cs:20 
04-21 15:18:34.134 I/MonoDroid( 4152):   at Xamarin.Forms.Platform.Android.ListViewAdapter.GetView (System.Int32 position, Android.Views.View convertView, Android.Views.ViewGroup parent) [0x00200] in D:\a\1\s\Xamarin.Forms.Platform.Android\Renderers\ListViewAdapter.cs:299 
04-21 15:18:34.134 I/MonoDroid( 4152):   at Android.Widget.BaseAdapter.n_GetView_ILandroid_view_View_Landroid_view_ViewGroup_ (System.IntPtr jnienv, System.IntPtr native__this, System.Int32 position, System.IntPtr native_convertView, System.IntPtr native_parent) [0x0001a] in <95d915721ad748108ff096dce8f8f32c>:0 
04-21 15:18:34.134 I/MonoDroid( 4152):   at (wrapper dynamic-method) System.Object.102(intptr,intptr,int,intptr,intptr)

`

### Steps to Reproduce
Run app with Progress bar with Visual="Material"
### Expected Behavior
App should not crash, visual ProgressBar is displayed
### Actual Behavior
App crashes

### Basic Information

- Version with issue:
- Last known good version: not known
- IDE: VS2017
- Platform Target Frameworks:
  - Android: 9.1
- Android Support Library Version: 28.0.0.1
- Nuget Packages: Xamarin.Forms.Material
- Affected Devices: All those with android 5.0 I suppose

### PR DESCRIPTION
**Pull request by paymicro**
### Description of Change ###

on Android 5.0 attribute `disabledAlpha` isn't float type...

### Issues Resolved ### 

- fixes #5968

### API Changes ###
 
 None

### Platforms Affected ### 

- Android

### Behavioral/Visual Changes ###

None

### Testing Procedure ###

- run Visual Gallery on Android 5.0

### PR Checklist ###

- [ ] Has automated tests 
- [x] Rebased on top of the target branch at time of PR
- [ ] Changes adhere to coding standard

### CODE REVIEW

**Comment by hartez** [comment]
@paymicro What about versions below 22?

**Comment by PureWeen** [comment]
Also @paymicro just an FYI I rebased this one to 4.0.0 because I was having some issues getting it to compile on mac with some of the assembly version changes.

**Comment by samhouts** [comment]
@PureWeen Does this PR improve the situation? Or worsen it?

**Comment by PureWeen** [comment]
@samhouts slightly better for only API 21

@paymicro @hartez 

I submitted some additional changes which make it work on API 21 and 22

Let me know what you think.

**Comment by PureWeen** [comment]
@rmarinho PR rebased

**Comment by PureWeen** [comment]
@rmarinho should be fixed now

**Pull request merged**
