### PR TITLE
[iOS] CollectionView not applying "Selected" VisualState to pre-selected items

### LINKED ISSUE #9511: CollectionView not applying "selected" VisualState to pre-selected items (multi-select)
### Description
When using a customized VisualState on a CollectionView, items that passed to the "SelectedItems" property initially receive the "normal" styling until any item is (de)selected. Only then do all selected items (including pre-selected) receive the "selected" styling.

### Steps to Reproduce

1. Create CollectionView with populated SelectedItemsProperty.
2. Apply VisualState custom styling to "selected" items (or to "normal" items)
3. Reload page
4. Select or deselect any item

### Expected Behavior
Pre-selected items in CollectionView receive "selected" state immediately on page loading.
(Re: GIF: pre-selected items should immediately appear blue, not grey)

### Actual Behavior
Pre-selected items receive "normal" state until a selection event occurs.
(Re: GIF: pre-selected items remain grey until (de)selection occurs)

### Basic Information

- Version with issue: 4.4.0.991640
- Last known good version: N/A
- IDE: Visual Studio Community for Mac 2019
- Platform Target Frameworks:
  - iOS:  13.10.0.17
- Nuget Packages:
  - Xamarin.Essentials: 1.3.1
  - sqlite-net-pcl: 1.6.292
  - SQLiteNetExtensions: 2.1.0
  - SQLiteNetExtensions.Async: 2.1.0
- Affected Devices:
  - iPhone 8 (simulator)

### Screenshots

xambug

#### In ViewModel
```
public class TagEntry
{
    public string Name { get; set; }
}

TagEntry tag1 = new TagEntry { Name = "tag1";}
TagEntry tag2 = new TagEntry { Name = "tag2";}
TagEntry tag3 = new TagEntry { Name = "tag3";}

ObservableCollection<string> Tags = new ObservableCollection<string>
{ 
    tag1,
    tag2,
    tag3
};
List<object> SelectedTags = new List<object>
{ 
    tag1,
    tag3
};
```

#### In page XAML
```
    <ContentPage.Resources>
        <Style TargetType="StackLayout">
            <Setter Property="VisualStateManager.VisualStateGroups">
                <VisualStateGroupList>
                    <VisualStateGroup x:Name="CommonStates">
                        <VisualState x:Name="Normal"/>
                        <VisualState x:Name="Selected">
                            <VisualState.Setters>
                                <Setter Property="BackgroundColor"
                                        Value="LightSkyBlue" />
                            </VisualState.Setters>
                        </VisualState>
                    </VisualStateGroup>
                </VisualStateGroupList>
            </Setter>
        </Style>
    </ContentPage.Resources>
    <CollectionView Margin="20"
              SelectionMode="Multiple"
              ItemsSource="{Binding Tags}"
              SelectedItems="{Binding SelectedTags}">
        <CollectionView.ItemTemplate>
        <DataTemplate>
            <StackLayout Orientation="Horizontal">
                <Label Text="{Binding Name}"/>
            </StackLayout>
        </DataTemplate>
    </CollectionView.ItemTemplate>
    </CollectionView>
```

### Workaround

No workaround yet.

### LINKED ISSUE #14229: [Bug] VisualStateManager not working for CollectionView, CollectionView not considered as Selected
### Description
I want that my CollectionView highlights the selected item when user clicks it. For me it is just working fine on UWP

### Steps to Reproduce

1. Clone the reproduction repo https://github.com/nschoenberg/CollectionViewTest
2. Start Android or iOS to see the Problem, UWP is fine

### Expected Behavior

Highlighting selected item works for Android iOS and UWP.

### Actual Behavior

UWP (fine):

uwp

iOS:
iPhone 12_ios_14 5gif

Android:
Can't make gif, selection works the first time the item gets clicked. When user selects the Item a second time, its not working.

### Basic Information

- Version with issue: 5.0.0.2012
- Last known good version: n/a
- Platform Target Frameworks: 
  - iOS:  Deployment Target 10.0, Tested on iOS 14.5
  - Android: Target Framework Android 10, Tested on Android 8.1
  - UWP:  Target 16299, Min 16299

### Environment

<details><summary>Show/Hide Visual Studio info</summary>

```
Microsoft Visual Studio Enterprise 2019
Version 16.9.0
VisualStudio.16.Release/16.9.0+31025.194
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Enterprise

Visual C++ 2019   00435-60000-00000-AA545
Microsoft Visual C++ 2019

.NET Portability Analyzer   1.1.10808.0
Evaluates portability of assemblies across .NET platforms.

ASP.NET and Web Tools 2019   16.9.687.37626
ASP.NET and Web Tools 2019

ASP.NET Core Razor Language Services   16.1.0.2107702+c4adaa061f13292143de82a96c71341e50bc4032
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2019   16.9.687.37626
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.9.687.37626
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   16.9.687.37626
Azure Functions and Web Jobs Tools

C# Tools   3.9.0-6.21124.20+db94f4cc8c78a7cd8cf9cfdae091158d2ba9d974
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

DevExpress Reporting Extension   1.3
A Visual Studio extension that invokes the Report Designer editor for report definition VSREPX files.

DevExpress Reporting Tools Extension   1.0
Extends Visual Studio with tools required for the Report Designer editor.

DevExpress.DeploymentTool   1.0
A useful tool for deploying DevExpress assemblies.

DevExpress.Win.LayoutAssistant Extension   1.0
DevExpress.Win.LayoutAssistant Visual Studio Extension Detailed Info

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

GitHub.VisualStudio   2.11.102.28613
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

JetBrains ReSharper 2020.3.3   Build 203.0.20210128.162058
JetBrains ReSharper package for Microsoft Visual Studio. For more information about ReSharper, visit http://www.jetbrains.com/resharper. Copyright © 2021 JetBrains, Inc.

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2019 - v2.9.40218.1

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.113+g422d40002e.RR
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   16.9.7 (df23ba6)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   5.9.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Snapshot Debugging Extension   1.0
Snapshot Debugging Visual Studio Extension Detailed Info

SQL Server Data Tools   16.0.62102.01130
Microsoft SQL Server Data Tools

TypeScript Tools   16.0.30201.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.9.0-6.21124.20+db94f4cc8c78a7cd8cf9cfdae091158d2ba9d974
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   16.9.0-beta.21102.9+7ce7132f1459095e635194d09d6f73265352029a
Microsoft Visual F# Tools

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Foo   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

WakaTime   1.0


Xamarin   16.9.000.271 (d16-9@863670b)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.9.0.316 (remotes/origin/d16-9@fdbf64026)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.9.68 (8e9b569)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   11.2.0.21 (d16-9/93eab59)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: 5e9cb6d
    Java.Interop: xamarin/java.interop/d16-9@d6d86b2
    ProGuard: Guardsquare/proguard/v7.0.1@912d149
    SQLite: xamarin/sqlite/3.34.1@daff8f4
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-9@9d8924d


Xamarin.iOS and Xamarin.Mac SDK   14.14.2.5 (3836759d4)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
```

</details>

### Reproduction Link

https://github.com/nschoenberg/CollectionViewTest

### Workaround

iOS: 
1) When I remove the Gesture Recognizer it is working
2) When I keep the Gesture Recognizer and set the SelectedItem that is bound to the CollectionView via command, it is working as well

For me it seems that the Gesture Recognizer is blocking the SelectedItem Binding from View to ViewModel

Android: n/a

### Possibly related to

https://github.com/xamarin/Xamarin.Forms/issues/13141
https://github.com/xamarin/Xamarin.Forms/issues/14005
https://github.com/xamarin/Xamarin.Forms/issues/9511

### LINKED ISSUE #14513: [Bug] [iOS] SelectedItems custom image not displaying in iOS for CollectionView until tapped
### Description
Followed [this solution](https://social.msdn.microsoft.com/Forums/en-US/ccfa0ac4-5d9b-4c1e-be9e-12f865db903d/how-to-show-image-when-user-click-on-collection-view?forum=xamarinforms) to display checkbox images (check/uncheck) for CollectionView Items. Checked checkboxes do not show when loading my page with pre-selected items in iOS, but works fine in Android

### Steps to Reproduce

1. Create a Custom `ContentView` defining a CustomImageSource `BindableProperty` to define image as shown in article linked above
2. Refer to the Custom `ContentView` in the `CollectionView.DataTemplate`
```
        <CollectionView.ItemTemplate>
            <DataTemplate>
                <local:CustomView/>
            </DataTemplate>
        </CollectionView.ItemTemplate>
```
3. Define a `ResourceDictionary` to set the image sources for checked and unchecked checkbox images based on state as [shown in reproduction GitHub link](https://github.com/adolfo1981/MultiCollectionViewTest/blob/362121007e26e80ec82968074717851b46d6d5dc/MultiCollectionViewTest/MainPage.xaml#L7). 
4. Load CollectionView ItemsSource in the ViewModel and load SelectedItems for the CollectionView. See in [reproduction GitHub link](https://github.com/adolfo1981/MultiCollectionViewTest/blob/362121007e26e80ec82968074717851b46d6d5dc/MultiCollectionViewTest/ViewModel.cs#L93)

### Expected Behavior
Pre-selected `CollectionView` items show checked checkbox images.
### Actual Behavior
In iOS CollectionViews appear with default blank checkboxes until CollectionViews are tapped. That's when selection checkbox images are displayed
### Basic Information

- Platform Target Frameworks: Xamarin.Forms v 5.0.0.2012 
- Affected Devices: iPhone 6 to 13

### Environment

<details><summary>Show/Hide Visual Studio info</summary>

```
Microsoft Visual Studio Professional 2019
Version 16.10.4
VisualStudio.16.Release/16.10.4+31515.178
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Professional

.NET Core Debugging with WSL 2   1.0
.NET Core Debugging with WSL 2

ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools

ASA Service Provider   1.0

ASP.NET and Web Tools 2019   16.10.526.50910
ASP.NET and Web Tools 2019

ASP.NET Web Frameworks and Tools 2019   16.10.526.50910
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.10.526.50910
Azure App Service Tools v3.0.0

Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.

Azure Data Lake Tools for Visual Studio   2.6.1000.0
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools   16.10.526.50910
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio   2.6.1000.0
Microsoft Azure Stream Analytics Tools for Visual Studio

C# Tools   3.10.0-4.21329.37+246ce641f04b67ef017655275d850bf902a8e40f
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Fabric.DiagnosticEvents   1.0
Fabric Diagnostic Events

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Material icons generator   2.0.0
This extension helps you to add material design icons to your Android, iOS or UWP project

Microsoft Azure HDInsight Azure Node   2.6.1000.0
HDInsight Node under Azure Node

Microsoft Azure Hive Query Language Service   2.6.1000.0
Language service for Hive query

Microsoft Azure Service Fabric Tools for Visual Studio   16.10
Microsoft Azure Service Fabric Tools for Visual Studio

Microsoft Azure Stream Analytics Language Service   2.6.1000.0
Language service for Azure Stream Analytics

Microsoft Azure Stream Analytics Node   1.0
Azure Stream Analytics Node under Azure Node

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2019 - v2.9.40423.1

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.113+g422d40002e.RR
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual Studio Tools for Containers   1.2
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Mono Debugging for Visual Studio   16.10.15 (552afdf)
Support for debugging Mono processes with Visual Studio.

Node.js Tools   1.5.30310.1 Commit Hash:e550dd1b679956810ccace4368dbc7a64443213b
Adds support for developing and debugging Node.js apps in Visual Studio

NuGet Package Manager   5.10.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Open Command Line   2.4.236
2.4.236

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Razor (ASP.NET Core)   16.1.0.2122504+13c05c96ea6bdbe550bd88b0bf6cdddf8cde1725
Provides languages services for ASP.NET Core Razor.

SQL Server Data Tools   16.0.62106.24090
Microsoft SQL Server Data Tools

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   16.0.30429.2002
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.10.0-4.21329.37+246ce641f04b67ef017655275d850bf902a8e40f
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   16.10.0-beta.21262.7+1b23bbeda88ea3cb9be9af777f4c99fa8663df81
Microsoft Visual F# Tools

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

Visual Studio Tools for Kubernetes   1.0
Visual Studio Tools for Kubernetes

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   16.10.000.234 (d16-10@ecaf29b)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.10.0.115 (remotes/origin/c750fbf1bde3c720d077f51640fe197c6dac7cbe@c750fbf1b)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.10.5 (355b57a)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   11.3.0.4 (d16-10/ae14caf)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: b4a3858
    Java.Interop: xamarin/java.interop/d16-10@f39db25
    ProGuard: Guardsquare/proguard/v7.0.1@912d149
    SQLite: xamarin/sqlite/3.35.4@85460d3
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-10@c5732a0


Xamarin.iOS and Xamarin.Mac SDK   14.20.0.24 (c4b89cddb)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
```

</details>

### Reproduction Link

https://github.com/adolfo1981/MultiCollectionViewTest
### Workaround
I tried this workaround using a `CollectionView` Behavior and seems to be working: https://github.com/xamarin/Xamarin.Forms/issues/9511#issuecomment-757142935

### PR DESCRIPTION
**Pull request by jsuarezruiz**
### Description of Change ###

Fix issue where the CollectionView not applying "Selected" VisualState to pre-selected items (initial selection).

### Issues Resolved ### 

- fixes #14513
- fixes #14229
- fixes #9511

### API Changes ###
 
 None

### Platforms Affected ### 

- iOS

### Behavioral/Visual Changes ###

None

### Before/After Screenshots ### 

Not applicable

### Testing Procedure ###
Launch Core Gallery and navigate to the issue 14513. If the selected item have a Red background, the test has passed.

### PR Checklist ###

- [ ] Targets the correct branch
- [ ] Tests are passing (or failures are unrelated)

### CODE REVIEW

**Comment by danielcabral-code** [comment]
hey @jfversluis how would I go about implementing this fix? thanks!

**Comment by jfversluis** [comment]
Hey @danielcabral-code glad you found your way here, thank you! 

Would you be able to grab the NuGet [as described here](https://github.com/xamarin/Xamarin.Forms/wiki/Preview-Packages) and let us know if this fixes this issue? That will greatly speed up the review process. Make sure in this case you get the exact version of 5.0.0.7746

Besides verifying if this particular issue is fixed also be sure to check other scenarios in the same area to make sure that this fix doesn't accidentally has side-effects 🙂 

Thanks!

**Comment by jfversluis** [comment]
I did some additional testing and actually it seems to look good for me. Please still test whatever you can @danielcabral-code. In 24 hours this should now also be part of the nightly feed (find instructions in the README on the front page), so you could test that as well. Please open an issue if you still find anything.

**Comment by danielcabral-code** [comment]
Hey @jfversluis I finally got around to testing the fix. It worked a charm! Thanks!

**Comment by jfversluis** [comment]
Hooray, perfect, thanks for confirming @danielcabral-code !

**Pull request merged**
