### PR TITLE
[Android] Remove changes to IVisualElementRenderer so it remains backwards compatible

### PR DESCRIPTION
**Pull request by PureWeen**
### Description of Change ###
Added a new interface to handle LayoutChanges so that IVisualElementRenderer can stay the same and not break older libraries 

### Platforms Affected ### 
- Android

### PR Checklist ###

- [x] Has automated tests 
- [x] Rebased on top of the target branch at time of PR
- [x] Changes adhere to coding standard

### CODE REVIEW

**Comment by samhouts** [comment]
Master is where we introduced this problem? Or do we need to target a release branch?

**Comment by PureWeen** [comment]
@samhouts 3.4.0 is where it was introduced

I just targeted master because we hadn't seen issues about it and just didn't want to complicate the 3.6.0 release

But I can retarget

**Comment by samhouts** [comment]
Actually, I think if we do this now, we'll break them again. https://github.com/luberda-molinet/FFImageLoading/issues/1154

**Comment by PureWeen** [comment]
> Actually, I think if we do this now, we'll break them again. [luberda-molinet/FFImageLoading#1154](https://github.com/luberda-molinet/FFImageLoading/issues/1154)

So based on that I don't think we can merge this in

**Comment by daniel-luberda** [comment]
Regarding FFImageLoading, there are currently two versions: 

- stable nuget: old `IVisualElementRenderer` behaviour 
- prerelease nuget: new `IVisualElementRenderer` behaviour 

I'll adapt code to whichever implementation you choose.

**Comment by PureWeen** [comment]
@daniel-luberda  the plan is to roll it back to 

>     * stable nuget: old `IVisualElementRenderer` behaviour

There are probably other libraries out there that also broke from this change so we'd prefer to roll back changes

**Comment by PureWeen** [comment]
Alright @daniel-luberda  it's merged in so the fix should be available with the first release of 3.6

We're working on putting some better checks in place so we can avoid these unfortunate scenarios. That being said, if this does happen again please let us know and we'll get a service release out ASAP

**Pull request merged**
