### PR TITLE
[WPF] Platform and Maps nuget package

### PR DESCRIPTION
**Pull request by mohachouch**
### Description of Change ###

Add WPF related files (dll, pdb) to nuget packages.

- Xamarin.Forms.Platform.WPF.dll, .pdb --> (net45) Xamarin.Forms.Platform.WPF.nupkg
- Xamarin.Forms.Maps.WPF.dll,.pdb --> (net45) Xamarin.Forms.Maps.WPF.nupkg

Note : I downgraded the version of OpenTK to the latest stable (2.0.0 instead 3.0.0-pre)

### API Changes ###

None

### Behavioral Changes ###

You can use Xamarin Forms for WPF with nuget

### PR Checklist ###

- [ ] Has tests (if omitted, state reason in description)
- [ ] Rebased on top of master at time of PR
- [ ] Changes adhere to coding standard
- [ ] Consolidate commits as makes sense

### CODE REVIEW

**Comment by rmarinho** [comment]
Hi can you remove the .sln changes ? 

Thanks

**Comment by mohachouch** [comment]
It was to add both nuspec on Visual Studio. I restore it completely or I still add the two lines for nugets packages.

**Comment by rmarinho** [comment]
Please add the 2 lines, but remove changes not needed please. 

Thanks

**Comment by mohachouch** [comment]
Done

**Comment by flyingxu** [comment]
Question: Will Xamarin.Forms.Platform.WPF.nupkg be released to nuget.org? Currently, https://www.nuget.org/packages/Xamarin.Forms.Platform.WPF is very outdated (0.4.0.39324).

**Comment by flyingxu** [comment]
Oh, I found that I can use it from the nightly build https://www.myget.org/F/xamarinforms-ci/api/v2 (remember to check `include-prerelease`).

**Comment by mohachouch** [comment]
Yes, the WPF platform is available in nightly build. The name of the package will change next week for Xamarin.Forms.WPF.nupkg

Do not forget to report bugs or improvements :)

**Pull request merged**
