### PR TITLE
RefreshView: add new internal property IsRefreshAllowed to fix #14350

### LINKED ISSUE #14350: [Bug] RefreshView to completes instantly when using AsyncCommand or Command with CanExecute functionality
### Description
If you have a `RefreshView` to load some data asyncronsly on a pull to refresh the pull to refresh actions (`IsRefreshing = false`, animation goes away) will complete differently depending if you are using the normal Command vs Command with CanExecute functionality (Xamarin Community Toolkits AsyncCommand included).

This was discovered when I thought it was a problem with `AsyncCommand` (with `allowsMultipleExecutions` set to false) in Xamarin Community Toolkit (original issue is filed [here](https://github.com/xamarin/XamarinCommunityToolkit/issues/1388)), but the last changes to RefreshView by @PureWeen actually added this CanExecute functionality. So this may be by design.

IMO if I am using `AsyncCommand` (with allowsMultipleExecutions) I would expect the RefreshView to finish refreshing once the Task has finished executing. When using a regular command (with canExecute functionality setup) I would expect RefreshView to not finish refreshing early but instead wait for the Command to finish executing. It makes sense to not allow refreshing to start if the command `CanExecute = false`, but it shouldn't end it prematurely. 

### Steps to Reproduce

1. Add RefreshView and wire it up as per most tutorials
2. Implement CanExecute functionality in your command (or alternatively use AsyncCommand with allowsMultipleExecutions = false)

### Expected Behavior
When the user pulls to refresh the RefreshView will await for the specific method (ExecuteRefreshCommand in my sample) to finish before setting IsRefreshing to false and making the refresh animation go away.

### Actual Behavior
RefreshView completes refresh instantly when RefeshCommand has CanExecute functionality (or is AsyncCommand with allowsMultipleExecutions = false) .

### Basic Information

Xamarin.Forms: 5.0.0.2012
Xamarin Community Toolkit: 1.1.0

### Environment

<details><summary>Show/Hide Visual Studio info</summary>

```
=== Visual Studio Community 2019 for Mac ===

Version 8.10.1 (build 71)
Installation UUID: 0bad3465-09eb-41af-8e6c-ba3571637739
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000140

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.140 (2020-02/51d876a041e) (64-bit)
	Package version: 612000140

=== Roslyn (Language Service) ===

3.10.0-4.21269.26+029847714208ebe49668667c60ea5b0a294e0fcb

=== NuGet ===

Version: 5.9.0.7134

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/5.0.301/Sdks
SDK Versions:
	5.0.301
	5.0.203
	5.0.202
	5.0.201
	5.0.103
	5.0.102
	5.0.101
	3.1.410
	3.1.409
	3.1.408
	3.1.407
	3.1.406
	3.1.405
	3.1.404
MSBuild SDKs: /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	5.0.7
	5.0.6
	5.0.5
	5.0.4
	5.0.3
	5.0.2
	5.0.1
	3.1.16
	3.1.15
	3.1.14
	3.1.13
	3.1.12
	3.1.11
	3.1.10

=== .NET Core 3.1 SDK ===

SDK: 3.1.410

=== Xamarin.Profiler ===

Version: 1.6.15.68
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 12.5 (18205)
Build 12E262

=== Xamarin.Mac ===

Version: 7.14.0.3 (Visual Studio Community)
Hash: 17fdcf569
Branch: d16-10
Build date: 2021-05-20 15:46:14-0400

=== Xamarin.iOS ===

Version: 14.20.0.3 (Visual Studio Community)
Hash: 17fdcf569
Branch: d16-10
Build date: 2021-05-20 15:46:15-0400

=== Xamarin Designer ===

Version: 16.10.0.119
Hash: 36a2d986f
Branch: remotes/origin/d16-10
Build date: 2021-06-02 19:41:34 UTC

=== Xamarin.Android ===

Version: 11.3.0.1 (Visual Studio Community)
Commit: xamarin-android/d16-10/22fc2b3
Android SDK: /Users/bradmoore/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		None installed

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 30.0.4
SDK Build Tools Version: 30.0.2

Build Information: 
Mono: b4a3858
Java.Interop: xamarin/java.interop/d16-10@f39db25
ProGuard: Guardsquare/proguard/v7.0.1@912d149
SQLite: xamarin/sqlite/3.35.4@85460d3
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-10@c5732a0

=== Microsoft OpenJDK for Mobile ===

Java SDK: /Users/bradmoore/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.10.0.12
Hash: e240b8c
Branch: remotes/origin/d16-10
Build date: 2021-06-01 18:26:34 UTC

=== Android Device Manager ===

Version: 16.10.0.14
Hash: e340248
Branch: remotes/origin/d16-10
Build date: 2021-06-01 18:26:52 UTC

=== Build Information ===

Release ID: 810010071
Git revision: 3664adb3ec17b7a29476110bb1c6f7083d43b1ab
Build date: 2021-06-08 13:22:15-04
Build branch: release-8.10

=== Operating System ===

Mac OS X 10.16.0
Darwin 20.5.0 Darwin Kernel Version 20.5.0
    Sat May  8 05:10:33 PDT 2021
    root:xnu-7195.121.3~9/RELEASE_X86_64 x86_64

=== Enabled user installed extensions ===

MFractor 4.4.8

```

</details>

### Screenshots

Command (without canExecute): 
Command test

Command (with canExecute) or AsyncCommand
AsyncCommand test

### Reproduction Link

[AsyncCommandRefreshView.zip](https://github.com/xamarin/Xamarin.Forms/files/6652146/AsyncCommandRefreshView.zip)

### Workaround

Now that I understand the underlying issue I will go back to using a regular Command, not implement CanExecute, instead inside my method that is being called add extra checks to avoid it being called multiple times.

This workaround is fine, but IMO it feels the current implementation adds a nice got-ya that people may not be aware of.

### PR DESCRIPTION
**Pull request by cpraehaus**
### Description of Change ###
Add new internal property ``IsRefreshAllowed`` to ``RefreshView`` to avoid that change in ``Command.CanExecute`` cancels refresh animation.

Implementations of ``ICommand`` - like ``AsyncCommand`` - usually set CanExecute() based on command state. If command execution starts CanExecute() is often set to false to avoid that command is executed multiple times in parallel. If such a command is used for ``RefreshView.RefreshCommand`` then the refresh indication is stopped immediately - even if refresh command is still running.

``RefreshView`` sets its ``IsEnabled`` property depending on ``RefreshCommand.CanExecute()``. Two things happen regarding refresh indicator when ``IsEnabled`` is set to false:
1. ``RefreshView`` sets ``IsRefreshing`` to false, thereby stopping the refresh indicator
2. On Android, disabling the RefreshView (through ``IsEnabled = false``) also immediately stops the refresh indicator
 since the Android ``SwipeRefreshLayout`` is also disabled (this happens through standard XF view/renderer interactions). 

Idea is to introduce a new property ``RefreshView.IsRefreshAllowed`` instead of setting ``RefreshView.IsEnabled`` - similar to ``ListView``.
``RefreshView.IsRefreshAllowed`` is set depending on ``RefreshCommand.CanExecute()``. Platform renderers need to consider 
``IsRefreshAllowed`` and disable swipe to refresh AFTER finishing current refresh activity/indication.

### Issues Resolved ### 

- fixes #14350

### API Changes ###
Added:
 - bool RefreshView.IsRefreshAllowed { get; set; } // INTERNAL bindable Property

### Platforms Affected ### 
- iOS
- Android
- UWP

### Behavioral/Visual Changes ###
None

### Before/After Screenshots ### 
Not applicable

### Testing Procedure ###
Launch Xamarin.Forms.ControlGallery.Android and navigate to issue 14350. Follow the steps there to test the issue.

### PR Checklist ###

- [x] Targets the correct branch
- [x] Tests are passing (or failures are unrelated)

### CODE REVIEW

**Comment by jfversluis** [comment]
@cpraehaus could you have a look at the failing tests please? :)

**Comment by cpraehaus** [comment]
@jfversluis Thanks for the hint - fixed unit tests for ``RefreshView``.

**Review by PureWeen — CHANGES_REQUESTED** [review]
@jfversluis I don't know if this fix needs so many parts. This is fixed on MAUI so we could just back port that code. Unless my fix is being naive.

Unit Test
https://github.com/dotnet/maui/pull/2027/files#diff-01279e4d50b79e7507ba57cb5cf82e76b7d3c2f70892f863fcf1253a626d2113R57

Code Fix
https://github.com/dotnet/maui/pull/2027/files#diff-4ea8e3bcdd1fa32231c4d330c595279017142f8e67fbc71ff604b38b026e3f4bR130

**Comment by cpraehaus** [comment]
@PureWeen Wasn't aware the this is being worked in in MAUI already. I also had the feeling that my PR is bigger than needed, but more in the direction that I wanted the change to be localized in ``RefreshView`` core class without affecting platform renderers.

Your approach is simpler, which is good :-). However, I see two disadvantages (just took an overview, so maybe I overlooked something):
1. If Command remains disabled after refresh is done the RefreshControls' Pull-to-Refresh function will not be disabled. Although command will not be executed if user attempts to refresh its still strange for the user (s:he sees the usual PTR animation but is confused since nothing happens).
2. Its questionable if ``RefreshControl.IsDisabled`` is the right property for this task. It disables the entire View, potentially including child elements (there I'm not 100 % sure), see #13749. Don't know if this is by design or not. but I would assume the latter. In my opinion a new property ``IsRefreshAllowed`` make sense, since its clearer for the XF user, has less unwanted side-effects. and is consistent with the ``ListView`` control.

**Comment by cpraehaus** [comment]
@PureWeen Wasn't aware the this is being worked in in MAUI already. I also had the feeling that my PR is bigger than needed, but more in the direction that I wanted the change to be localized in ``RefreshView`` core class without affecting platform renderers.

Your approach is simpler, which is good :-). However, I see two disadvantages (just took an overview, so maybe I overlooked something):
1. If Command remains disabled after refresh is done the RefreshControls' Pull-to-Refresh function will not be disabled. Although command will not be executed if user attempts to refresh its still strange for the user (s:he sees the usual PTR animation but is confused since nothing happens).
2. Its questionable if ``RefreshControl.IsDisabled`` is the right property for this task. It disables the entire View, potentially including child elements (there I'm not 100 % sure), see #13749. Don't know if this is by design or not. but I would assume the latter. In my opinion a new property ``IsRefreshAllowed`` make sense, since its clearer for the XF user, has less unwanted side-effects. and is consistent with the ``ListView`` control.

**Comment by jfversluis** [comment]
Now that we're so close to the sunsetting of Xamarin.Forms unfortunately we won't be able to take this in anymore, we're really sorry about that. Nevertheless, thank you so much for your time and effort that you have put into this PR.

Please have a look at the evolution of Xamarin.Forms, [.NET MAUI](https://github.com/dotnet/maui). A lot of development has been going on there. Hopefully this issue was already fixed in that codebase. If not, feel free to port this over to there.

Again, thank you so much for being a contributor and Xamarin.Forms user!

**Pull request closed without merging**
