### PR TITLE
[Tizen] Enhancement WebView Renderer

### PR DESCRIPTION
**Pull request by myroot**
### Description of Change ###
Enhancement Tizen WebView Renderer
 - Support Focus
 - Support GestureRecognizers

### Bugs Fixed ###
 Fix focus issue
 Fix GestureRecognizer

### API Changes ###
 None

### Behavioral Changes ###
 None

### PR Checklist ###
- [ ] Has tests (if omitted, state reason in description)
- [x] Rebased on top of the target branch at time of PR
- [x] Changes adhere to coding standard
- [x] Consolidate commits as makes sense

### CODE REVIEW

**Comment by hadihashem** [comment]
fyi @samhouts

**Comment by myroot** [comment]
Hi, @hadihashem 
You can use CustomRenderer feature on Xamarin.forms to access Native controls
https://docs.microsoft.com/ko-kr/xamarin/xamarin-forms/app-fundamentals/custom-renderer/

**Comment by hadihashem** [comment]
Hi @myroot 
In this document it is described only for Android, iOS and UWP
There is nothing for Tizen unfortunately
Kind regards

**Comment by myroot** [comment]
@hadihashem 

It is a example for custom renderer on Tizen (but not WebView)
https://github.com/Samsung/Tizen-CSharp-Samples/tree/b5e089032a9dc917ad5e6ca2232fef5d32f91b08/Mobile/Calculator/Calculator/tizen/Calculator

**Comment by hadihashem** [comment]
Done !
Thank you for your help :-)

**Pull request merged**
