### PR TITLE
Fix default cancel button visibility on iOS SearchHandler

### LINKED ISSUE #6802: [Bug] Shell SearchHandler - Cancel is visible by default?
### Description

The cancel button from the search bar is visible by default (without focus to the search control). This is not the native behaviour. 

Simulator Screen Shot - iPhone Xʀ - 2019-07-06 at 18 58 58

### Steps to Reproduce

1. Create a fresh Xamarin.Forms Shell project
2. Add a seaerch handler

### Expected Behavior

The cancel button should only be visible when the search bar has content or the focus.

### Actual Behavior

Cancel button is visible when the app starts.

### Basic Information

- Version with issue: 4.1.0
- Last known good version: -
- IDE: VS2019 and VS for Mac
- Platform Target Frameworks: 
  - iOS:  Tested with iOS 12 Simulator

### Screenshots

Already added above in the description.

### Reproduction Link

Reproduction can be done with the VS template within a minute.

### PR DESCRIPTION
**Pull request by joepgrooten**
### Description of Change ###

The cancel button on the search bar is now hidden initially.

### Issues Resolved ### 
- fixes #6802

### API Changes ###
None

### Platforms Affected ### 
- iOS

### Behavioral/Visual Changes ###
When the search bar was shown on an iOS device it initially had a cancel button even in the initial state.

Now the cancel button is not visible on a new search bar, it will only be shown when user selects the search entry field.

### Before/After Screenshots ### 
Before:
image

After:
image

### Testing Procedure ###
Add a SearchHandler to a page, the fixed version won't have a cancel button by default.

### PR Checklist ###

- [ ] Has automated tests (No automated tests, i don't know how to test this)
- [X] Rebased on top of the target branch at time of PR
- [X] Changes adhere to coding standard

### CODE REVIEW

**Comment by Bronson15** [comment]
Yes please!

**Comment by aodegov** [comment]
in iOS, now it's just collapses shell navigation bar once search bar is focused (regardless the  SearchBoxVisibility settings).
And there is no any option like in Android to get back the shell navigation bar since it hides all buttons from header.
Very odd behaviour.
Any options to fix this for iOS shell Search control?

**Comment by scicom02** [comment]
> in iOS, now it's just collapses shell navigation bar once shell search handler control is focused (regardless the SearchBoxVisibility settings). And there is no any option like in Android to get back the shell navigation bar since it hides all buttons from header. Very odd and unexpected behaviour for users. Where they can't get back from Shell search input if it's focused. There is no more 'Cancel' iOS button to do this, like in Search bar. Any options to fix this for iOS shell SearchHandler control?

Hello, Did you find a solution ? am stuck at this too

**Comment by aodegov** [comment]
> > in iOS, now it's just collapses shell navigation bar once shell search handler control is focused (regardless the SearchBoxVisibility settings). And there is no any option like in Android to get back the shell navigation bar since it hides all buttons from header. Very odd and unexpected behaviour for users. Where they can't get back from Shell search input if it's focused. There is no more 'Cancel' iOS button to do this, like in Search bar. Any options to fix this for iOS shell SearchHandler control?
> 
> Hello, Did you find a solution ? am stuck at this too

Hi there.
I decided to use SearchBar instead of SearchHandler, which is not working correctly.

**Pull request merged**
