### PR TITLE
On requested theme changed android

### PR DESCRIPTION
**Pull request by fredyadriano90**
### Description of Change ###

The event `Xamarin.Forms.Application.RequestedThemeChanged` is fired when the device rotates. 

### Issues Resolved ### 

Fire the event `Xamarin.Forms.Application.RequestedThemeChanged` only when the theme change

- fixes #

### API Changes ###

none

### Platforms Affected ### 

- Android

### Behavioral/Visual Changes ###

None

### Before/After Screenshots ### 

Not applicable

### Testing Procedure ###

- On the App.cs subscribe to the event `Xamarin.Forms.Application.RequestedThemeChanged`
- Rotate the device
- The event will be fired

### PR Checklist ###

- [x] Targets the correct branch
- [x] Tests are passing (or failures are unrelated)

### CODE REVIEW

**Comment by fredyadriano90** [comment]
I would like to keep LastAppTheme public property to check that value from Android and do not fire the RequestTheme event without need.

**Comment by fredyadriano90** [comment]
@jfversluis the idea of `LastAppTheme` public is to not dispatch the event

**Comment by jfversluis** [comment]
I see why you are doing it! But as a side-effect we're exposing a new API to our users that will then have to maintain. And yes, this one is not very exciting but also not very useful to the end-user IMO.

My preference would be to keep it private.

**Comment by fredyadriano90** [comment]
@jfversluis  I got your point, and I think that you are right. The only thing that I would like to add is the initialization to lastAppTheme on the ctor

**Comment by fredyadriano90** [comment]
@jfversluis Hi, I was testing XF vs 4.6.0.800 and if you don't initialize the _lastAppTheme on the ctor the RequestedThemeChanged event is invoked as soon as you rotate the device

**Pull request merged**
