### PR TITLE
[Tizen] Add indicator to CarouselPage

### PR DESCRIPTION
**Pull request by sung-su**
### Description of Change ###

This patch for using an indicator to `CarouselPage`.
It provides views such as a combination of `CarouselView` and `IndicatorView`.

### Issues Resolved ### 

- fixes #

### API Changes ###

None

### Platforms Affected ### 

- Tizen

### Behavioral/Visual Changes ###

None

### Before/After Screenshots ### 

caro-ind-mob
caro-ind-w

### PR Checklist ###

- [ ] Targets the correct branch
- [ ] Tests are passing (or failures are unrelated)

### CODE REVIEW

**Comment by rookiejava** [comment]
> Because IndicatorView is Experimental Feature

IndicatorView is not experimental feature since  4.7.0.937-pre4. (#10998)

**Review by rookiejava — APPROVED** [review]

**Comment by rookiejava** [comment]
Can you rebase onto `4.8.0`?

**Comment by sung-su** [comment]
rebased

**Review by rmarinho — APPROVED** [review]

**Pull request merged**
