### PR TITLE
[iOS] ImageButton border radius issue

### LINKED ISSUE #4511: ImageButton CornerRadius doesn't work on iOS
### Description
I'm using the new ImageButton control introduced with XF 3.4 to create circular image button. Unfortunately it doesn't work on iOS. I haven't checked/tested on Android but on UWP it works.

### Steps to Reproduce

`<ImageButton Grid.Row="0" Grid.Column="0" 
             Source="{Binding ProfileImage, Converter={StaticResource PathToImageConverter}}"
             CornerRadius="50"
             HorizontalOptions="Center" VerticalOptions="Center"
             HeightRequest="100" WidthRequest="100">
</ImageButton>`

### Expected Behavior

See a circular image

### Actual Behavior

Image is rectangular

### Basic Information

- Version with issue: 3.4.0.1008975
- Last known good version: N/A
- IDE: VS 2017 Professional 15.9.2
- Platform Target Frameworks: 
  - iOS:  12.0 (16A366)
  - UWP:  16299
- Nuget Packages:
- Affected Devices:

### Screenshots

iOS
profile_ios

UWP
profile_uwp

### PR DESCRIPTION
**Pull request by AndreiMisiukevich**
### Description of Change ###

ClipsToBounds missing for ImageButton - that's the reason of bug.

### Issues Resolved ### 
- fixes #4511

### API Changes ###
None

### Platforms Affected ### 
- iOS

### Behavioral/Visual Changes ###
CornerRadius works

### Before/After Screenshots ### 
BEFORE:
image

AFTER:
image

### Testing Procedure ###
```csharp
MainPage = new ContentPage
{
	Content = new StackLayout
	{
		Children = {
			new ImageButton
			{
				VerticalOptions = LayoutOptions.CenterAndExpand,
				HorizontalOptions = LayoutOptions.CenterAndExpand,
				HeightRequest = 200,
				WidthRequest = 200,
				Source = "xamarinlogo",
				BackgroundColor = Color.Red,
				CornerRadius = 100
			}
		}
	}
};	
```

### CODE REVIEW

**Comment by PureWeen** [comment]
@AndreiMisiukevich  can you add the this scenario to the ImageButton gallery page?

https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Controls/CoreGalleryPages/ImageButtonCoreGalleryPage.cs

**Comment by AndreiMisiukevich** [comment]
@PureWeen should I create an issue-class in Controls Gallery?

BTW, I noted, that in original ticket there's android attribute.
Indeed this issue reproduces on Android as well, but I haven't found the solution yet. Have you any advises. I checked code, everything looks well..

**Comment by PureWeen** [comment]
@AndreiMisiukevich   Since it's a new control and the issue would just be a visual test not automated, I would say just add it to the Core Gallery Page. This way someone can witness and validate all the ImageButton behaviors on one single page. 

Not sure off hand with android :-/ I'll have to poke it a bit next week and see if I get any ideas.  Probably something similar with Clipping the bounds

**Comment by PureWeen** [comment]
@AndreiMisiukevich it looks like the rounding on Android will need to be achieved by utilizing *canvas.drawcircle* inside the Draw method.  So the paint object and all the parameters for that will need to be setup and used instead of *base.draw*

Which is just based on some quick research.

**Comment by PureWeen** [comment]
@AndreiMisiukevich  for now can you just add a case to

https://github.com/xamarin/Xamarin.Forms/blob/494b9137fd7c29a61fac555405060f329cce7c1f/Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue1724.cs

that demonstrates the issue this is fixing?

Then we'll just merge what you have here and create a new issue for Android

**Comment by AndreiMisiukevich** [comment]
@PureWeen done
I added red border as test image has white background for better visibility

**Comment by PureWeen** [comment]
@AndreiMisiukevich  looks great thank you. If only Android was so easy :-/

**Comment by PureWeen** [comment]
Android version of issue
https://github.com/xamarin/Xamarin.Forms/issues/4606

**Pull request merged**
