### PR TITLE
Shapes do not work with StaticResource Fill Colour

### LINKED ISSUE #12538: [Bug] Shapes do not work with StaticResource Fill Colour
### Description

As soon as you set Fill to a StaticResource then the shape disappears. Only tested on UWP so far..

**This line works**

`<Ellipse Fill="Blue" StrokeThickness="0" WidthRequest="10" HeightRequest="10" HorizontalOptions="End" VerticalOptions="End" Margin="0,0,2,2" />`

**This line doesnt**

`<Ellipse Fill="{StaticResource CompleteColour}" StrokeThickness="0" WidthRequest="10" HeightRequest="10" HorizontalOptions="End" VerticalOptions="End" Margin="0,0,2,2" >`

XF 4.8.0.1560 - latest release

### PR DESCRIPTION
**Pull request by jsuarezruiz**
### Description of Change ###

The issue have been fixed by https://github.com/xamarin/Xamarin.Forms/pull/12761 (already merged). For that reason, this PR only include a test to validate that the issue is fixed.

### Issues Resolved ### 

- fixes #12538

### API Changes ###
 
 None

### Platforms Affected ### 

- Core/XAML (all platforms)

### Behavioral/Visual Changes ###

None

### Before/After Screenshots ### 
Captura de pantalla 2020-11-13 a las 13 08 41

### Testing Procedure ###
Launch Core Gallery and navigate to the issue 12538. If an Ellipse is rendered below using am static SolidColorBrush, the test has passed.

### PR Checklist ###

- [ ] Targets the correct branch
- [ ] Tests are passing (or failures are unrelated)

### CODE REVIEW

**Comment by BurkusCat** [comment]
Shapes now can have a colour when using a dynamic resource, however, those shapes cannot change colour dynamically like other things can. Example shape and text that both should be changing to the primary colour:
image
image
image

On the page:
``` xaml
                <Polygon
                    Fill="{DynamicResource PrimaryColorBrush}"
                    HeightRequest="250"
                    Points="5,2 65,37 103,16 141,37 202,2 203,73 204,74 205,190 103,248 2,190 2,74 4,73 5,2" />
```

In `app.xaml`:
``` xaml
        <SolidColorBrush
            x:Key="PrimaryColorBrush"
            Color="{DynamicResource PrimaryColor}" />
```

Color defined in a resource dictionary that is merged into the main one programatically when the user picks a different color:
``` xaml
    <Color x:Key="PrimaryColor">#2196F3</Color>
```

I don't think shapes and dynamic colours are fixed yet in `5.0.0.1709-pre4`. I believe the very first previous of Shapes (when you could use colours) worked perfectly. Another version broke any colour from showing at all and currently it seems like it will show a colour but not dynamically change.

**Comment by jsuarezruiz** [comment]
@BurkusCat Could you attach a sample where reproduce the issue?

**Comment by BurkusCat** [comment]
@jsuarezruiz Sure, here is a minimal one: 
[DynamicResourceShape.zip](https://github.com/xamarin/Xamarin.Forms/files/5609152/DynamicResourceShape.zip)

image
image

**Comment by jfversluis** [comment]
I think at this point it's safe to say this won't be happening for Xamarin.Forms anymore. Let's make it happen for .NET MAUI!

**Pull request closed without merging**
