### PR TITLE
Set AccessibilityValue regardings check state

### PR DESCRIPTION
**Pull request by magoolation**
### Issues Resolved ### 

- fixes #

### API Changes ###

 
 None

### Platforms Affected ### 

- Core/XAML (all platforms)
- iOS
- Android
- UWP

### Behavioral/Visual Changes ###

None

### Before/After Screenshots ### 

Not applicable

### PR Checklist ###

- [ ] Targets the correct branch
- [ ] Tests are passing (or failures are unrelated)

### CODE REVIEW

**Comment by jsuarezruiz** [comment]
@magoolation Is this PR still a Draft? or can we review it?

**Comment by magoolation** [comment]
I really need help to get the localized string for the checked and unchecked state. In the current implementation the stirng on and off are announced what is not the expected behavior for localized apps. Is there any Xamarin.iOS team member that can help me find out the Apple's resource string name for that values?

**Comment by jfversluis** [comment]
Hey @magoolation so sorry that this didn't get the attention it deserved. Do you still feel that we can make this happen? Or are you OK with this being fixed in .NET MAUI?

**Comment by jfversluis** [comment]
No response unfortunately. If this is still an issue, please make sure to open something on the .NET MAUI repo so we can address it there. Or let me know if this can still improve accessibility for Xamarin.Forms. Either way, thank you for your time and effort here!

**Pull request closed without merging**
