### PR TITLE
[Android] Remove and add view while being reused in a ListView

### PR DESCRIPTION
**Pull request by adrianknight89**
### Description of Change

If you have a list view of entries with a custom renderer where `SelectAllOnFocus` is set to true, cells shown into reusable positions won't honor this request. I do not know why this is the case, but the only solution I could find was removing `convertView` and adding `view` even if they are the same. There seems to be something about convertView (recycled cell) that breaks focusability. Note that this causes `OnElementChanged()` to be fired in `Recycle` mode. `Retain` raises element changed regardless of my changes.

If somebody has a proper/different fix, I'd like to see.

P.S. I created a new folder in the Android control gallery app for current and future renderers.

### Bugs Fixed
- https://bugzilla.xamarin.com/show_bug.cgi?id=42534
### PR Checklist
- [ ] Has tests (if omitted, state reason in description)
- [x] Rebased on top of master at time of PR
- [x] Changes adhere to coding standard
- [x] Consolidate commits as makes sense

### CODE REVIEW

**Comment by dazinator** [comment]
+1 - When can we expect this bug to be fixed? It's presently affecting our application, but we don't want to have to switch to a custom build of Xamarin.Forms assemblies if we can help it!

**Comment by whit0489** [comment]
@adrianknight89  When can we expect this bug to be fixed?  We to don't want to have to switch to a custom build of Xamarin.Forms assemblies.

**Comment by adrianknight89** [comment]
@whit0489 This isn't something I have control over. 

@jassmith

**Comment by adrianknight89** [comment]
@rmarinho Can you expand on "how" it breaks cell reuse?

**Comment by rmarinho** [comment]
IF we are always adding the view, we aren't reusing the cell.. 
The idea of cell reuse is we just set a new context and use all the same layout.

**Comment by adrianknight89** [comment]
I'm going to close this for now so we can find another solution. If anybody knows how we might fix this, let us know.

**Comment by dazinator** [comment]
I "fixed this" by switching to Telerik's RadListView control for Xamarin Forms which doesn't appear to have this issue!

**Pull request closed without merging**
