### PR TITLE
[WPF] Fix FontFamily Assignment in platform specific project

### LINKED ISSUE #2187: [WPF] FontFamily Assignment in platform specific project don't work
Bug report best practices: https://github.com/xamarin/Xamarin.Forms/wiki/Submitting-Issues

### Description

For all controls with FontFamily - setting it to a CUSTOM font   defined in the platform specific project does not work in Xamarin.Forms.WPF

### Steps to Reproduce

1. Set a custom FontFamily in Xamarin.Forms.WPF project 

### Expected Behavior
Custom FontFamily will take effect 

### Actual Behavior
Ignored 

### Basic Information

- Version with issue: Xamarin.Forms.WPF
- Last known good version:
- IDE: VS 2017
- Platform Target Frameworks: 
  - WPF

### PR DESCRIPTION
**Pull request by mohachouch**
### Description of Change ###

Fix FontFamily Assignment in platform specific project

Font in current project with namespace : 

- FontFamily = "/Xamarin.Forms.ControlGallery.WPF;component/Assets/#FontAwesome"

Font in current project without namespace : 

- FontFamily = "/Assets/#FontAwesome"

Font in other project : 

- FontFamily = "/Meziantou.WpfFontAwesome;component/Resources/#FontAwesome"

### Issues Resolved ###

- fixes #2187

### Platforms Affected ###

- WPF

### Image ###

image

### PR Checklist ###

- [ ] Has automated tests 
- [x] Rebased on top of the target branch at time of PR
- [x] Changes adhere to coding standard

### CODE REVIEW

**Comment by maxim-saplin** [comment]
I believe the same fix (self.FontFamily = new FontFamily(new Uri("pack://application:,,,/"), font.FontFamily);) must be applied to all 4 ApplyFont overloads in https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Platform.WPF/Extensions/FontExtensions.cs

I see the issue with custom font fixed for Label, though it doesn't work for Spans (setting custom fonts for individual spans) in Label.
Same issue for buttons.

**Comment by mohachouch** [comment]
Thanks @maxim-saplin

PR soon

**Comment by mohachouch** [comment]
@maxim-saplin  

PR #3905

**Comment by mohachouch** [comment]
@maxim-saplin

PR #3907

**Pull request merged**
