### PR TITLE
Embedded fonts fix

### LINKED ISSUE #9190: [Bug] Embedded Fonts Not Recognized
### Description

Using the Embedded Fonts in Xamarin.Forms 4.5 preview 1, a general TTF font seems to be working fine(*), however when using an OTF font such as Font Awesome it does not get rendered on iOS.

\* NOTE that neither font works on Android

Also related to this... the Font Alias does not work.

### Steps to Reproduce

1. Embed 1:* Fonts 
2. Add the appropriate ExportFont Attribute(s) to the assembly
3. Use the PostScript Name for the font

### Expected Behavior

The specified font should be used

### Actual Behavior

The TTF font works on iOS but not Android. 
The OTF font doesn't work on iOS or Android... 

didn't check UWP.

### Basic Information

- Version with issue: 4.5-pre1
- Last known good version: n/a
- Nuget Packages:

### Screenshots

You can see the recorded stream https://twitch.tv/dansiegel

### Reproduction Link

[App5.zip](https://github.com/xamarin/Xamarin.Forms/files/4055967/App5.zip)

### Workaround

n/a

### LINKED ISSUE #9255: [Bug] ExportFontAttribute has unused properties
### Description

The `ExportFontAttribute` class has three properties. However, the `Alias` and `EmbeddedFontResourceId` properties are unused.

### Basic Information

- Version with issue: 4.5-pre1

### PR DESCRIPTION
**Pull request by Clancey**
### Description of Change ###

iOS and android had times when the emebedded font's were not loaded

### Issues Resolved ### 

- fixes #9190
- fixes #9255

### API Changes ###
 
 None

### Platforms Affected ### 

- iOS
- Android

### PR Checklist ###

- [x] Targets the correct branch
- [x] Tests are passing (or failures are unrelated)

### CODE REVIEW

**Comment by jfversluis** [comment]
Installed the NuGets associated with this on my test project and the ExportFont attribute can't seem to be found after installation.

image

**Comment by dansiegel** [comment]
the last build seems to almost work... but I'm not getting FontAwesome to show up using the file name like @Clancey indicated should work.

**Comment by jfversluis** [comment]
I have been playing with this some more. It seems inconsistent atm across iOS and Android. It seems like Android looks at the filename, while iOS looks at the postscript name.

When running the attached sample, notice how there is one font in there named `Samantha1.ttf` the postscript name is `Samantha`. When using `FontFamily="Samantha"` on iOS it works, while on Android using `FontFamily="Samantha1"` works. In both cases I included the font with `[assembly: ExportFont("Samantha1.ttf")]`

Same goes for the Font Awesome one included in the project.

[EmbeddedFontsSample.zip](https://github.com/xamarin/Xamarin.Forms/files/4061538/EmbeddedFontsSample.zip)

**Comment by samhouts** [comment]
Why am I getting so many pings on this PR 😂😂😂

**Comment by dansiegel** [comment]
I was more confused why @samhouts is getting used as a font... haha

**Comment by dansiegel** [comment]
@samhouts just curious where this stands... as I understand it... pre4 was supposed to be the last pre release for 4.5

**Comment by jrahma** [comment]
I have the same problem:

[](https://github.com/xamarin/Xamarin.Forms/pull/6013#issuecomment-585330314)

**Comment by groege** [comment]
any news on this?

**Comment by ahmad-crossplatform** [comment]
For me this works on iOS but not Android 

image

**Comment by Clancey** [comment]
You can now use FontFamily="FontFileName.ttf", or you can use the Alias specified when registering the font!

**Pull request merged**
