### PR TITLE
[Android] Enables custom images (especially SVG) through the new IImageSourceHandler

### PR DESCRIPTION
**Pull request by softlion**
### Description of Change ###

Enables custom images (especially SVG) through the new IImageSourceHandler to work with tab bar icons on Android (like it does on iOS). And also on cell adapters and navigation page menu.

No test: there is no existing test for IImageSourceHandler (or can't find where).

### API Changes ###

None

### Behavioral Changes ###

None

### PR Checklist ###

- [ ] Has tests (if omitted, state reason in description)
- [X] Rebased on top of master at time of PR
- [X] Changes adhere to coding standard
- [X] Consolidate commits as makes sense

### CODE REVIEW

**Comment by softlion** [comment]
Note that another good addition would be a new IDrawableImageSourceHandler which would returns drawable from image source. For Android only at first. And after on all platforms in order to extend those to accept the notion of drawable images.

**Comment by softlion** [comment]
Tell me if you want the push on the master instead of this branch

**Comment by rmarinho** [comment]
yap please target master

**Comment by rmarinho** [comment]
reopen when you target master

**Comment by softlion** [comment]
Done https://github.com/xamarin/Xamarin.Forms/pull/1130

**Pull request closed without merging**
