### PR TITLE
[iOS] Clear prototype cell on UnevenRows

### LINKED ISSUE #1567: NRE using TapGestureRecognizer on cell with HasUnevenRows
### Description

When using a Listivew where the viewcell uses a GestureRecognizer we get a NRE when updating the list source.

### Steps to Reproduce
Click Filldata on the sample 

### Expected Behavior
Should not crash

### Actual Behavior
Crash with NRE

### Basic Information

failing with 2.4 and above includes nightly and master 

### Reproduction Link

[ProjError01.zip](https://github.com/xamarin/Xamarin.Forms/files/1626464/ProjError01.zip)

### PR DESCRIPTION
**Pull request by rmarinho**
### Description of Change ###

We were disposing our renderers of the prototype cell so we should also just clear our prototypecell 

### Bugs Fixed ###

- fixes #1567

### PR Checklist ###

- [x] Has tests (if omitted, state reason in description)
- [x] Rebased on top of master at time of PR
- [x] Changes adhere to coding standard
- [x] Consolidate commits as makes sense

### CODE REVIEW

**Comment by samhouts** [comment]
Should this be pointed at 15-5 instead of master? It's on the vCurrent board.

**Comment by rmarinho** [comment]
build

**Comment by StephaneDelcroix** [comment]
please make sure one of your commit says "fixes #xxx" so the squashed merge commit contains it.

**Comment by kingces95** [comment]
@rmarinho Expect launch iOS gallery and tapping "Go to Test Cases" works but actually fails with exception "Please provide unique tracker + issue number combo" due to existing test test case with matching issue repository and number:  https://github.com/xamarin/Xamarin.Forms/blob/74cb5c4a97dcb123eb471f6b1dffa1267d0305aa/Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue1567.cs#L13. .

**Comment by jassmith** [comment]
Approved once test is fixed :)

**Pull request merged**
