### PR TITLE
[IOS] label not rendering in BOLD when using a STYLE

### LINKED ISSUE #2831: [IOS] label not rendering in BOLD when using a STYLE, Droid however works
### Description

Label titleLabel = new Label
            {
                Text = title,
                //BackgroundColor = Color.Transparent,
                BackgroundColor = Color.White,
                WidthRequest = (Constants.DeviceWidth * 0.85) - 30,
                Style = Device.Styles.ListItemDetailTextStyle,
                HorizontalTextAlignment = TextAlignment.Center,
                FontAttributes = FontAttributes.Bold,
                TextColor = Color.Black
            };

in IOS does not render in bold but does in Android

### Steps to Reproduce

1. add label to a content page

### Expected Behavior

Both Droid and IOS should render text in bold

I believe that this only started to happen when I moved from a named size of font to a style (which I require to do for accessibility reasons).

### Actual Behavior

Droid renders text in bold, IOS does not

### Basic Information

- Version with issue: 30.0
- Last known good version: none, 2.5 had issue as well
- IDE: Visual Studio 15.7.2
- Platform Target Frameworks: 
  - iOS:  11.10.1.178
  - Android: 8.3.0.19
  - UWP:  N/A 
- Android Support Library Version: N/A
- Nuget Packages:
- Affected Devices:

### PR DESCRIPTION
**Pull request by AndreiMisiukevich**
### Description of Change ###

UIFont.FamilyNames method doesn't return default font name

### Issues Resolved ### 

- fixes #2831

### API Changes ###

Changed: _ToUIFont fontFamily check

### Platforms Affected ### 
- iOS

### Behavioral/Visual Changes ###

Now we can use Bold fontAttribute with style

### Testing Procedure ###
Check Issue2831 test case

### CODE REVIEW

**Review by StephaneDelcroix — APPROVED** [review]

**Review by hartez — APPROVED** [review]

**Comment by PureWeen** [comment]
@AndreiMisiukevich  can you rebase this with master so it gets the commits that fix the build

**Comment by AndreiMisiukevich** [comment]
@PureWeen done

**Comment by AndreiMisiukevich** [comment]
@PureWeen should I do anything else?

**Comment by StephaneDelcroix** [comment]
build --uitests

**Comment by isax5** [comment]
This problem is back!

**Pull request merged**
