### PR TITLE
Fix input for decimal/float/double and nullable

### LINKED ISSUE #7996: [Bug] Xamarin.Forms.Entry does not enter decimal when binding a float/double and decimal to it
### Description
[Bug] Xamarin.Forms.Entry does not enter decimal when binding a float/double and decimal to it
### Steps to Reproduce

1. Take Entry. 
2.  Binding decimal variable to it. 
3.  if enter with one number and the enter decimal.
4. it not taking decimal after any number but first decimal then number it taking. 

### Basic Information
not working on Android and IOS

- Version with issue: XF-4.2.0.778463
- Last known good version:XF 3.6
- IDE:VS2017
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### PR DESCRIPTION
**Pull request by jonkas2211**
### Description of Change ###

The input for floating numbers had some errors in different cultures.
When using german for example, the decimal seperator is a ',' and not a dot.

You can also use Nullable Types now. Before the Decimal Seperator would be cut off for Nullables.

### Issues Resolved ### 

- fixes #7996 

### API Changes ###
 
 None

### Platforms Affected ### 

- Core/XAML (all platforms)

### Behavioral/Visual Changes ###
The user of an app can now use the correct decimal sperator for his language.

### Before/After Screenshots ### 

Not applicable

### Testing Procedure ###
I have tested this on android.
I added a UI Test to the Gallery (G7996).
Unfortunately i cant test this on other platforms right now.
I also added a new Unit Test to prove the behaviour.

### PR Checklist ###

- [ ] Targets the correct branch
- [ ] Tests are passing (or failures are unrelated)

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/xamarin/Xamarin.Forms?pullRequest=11815) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/xamarin/Xamarin.Forms?pullRequest=11815) before we can accept your contribution.<br/><br/>:x: jonkas2211 [sign now](https://cla.dotnetfoundation.org/xamarin/Xamarin.Forms?pullRequest=11815)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/xamarin/Xamarin.Forms?pullRequest=11815) it.</sub>

**Comment by rmarinho** [comment]
Failing unit tests.

image

https://dev.azure.com/xamarin/public/_build/results?buildId=24368&view=ms.vss-test-web.build-test-results-tab

**Comment by jonkas2211** [comment]
Hello @rmarinho,

may this caused by this line `CultureInfo.CurrentUICulture = culture;` of the Unit Test?

**Comment by memu8** [comment]
In your UI tests, there's currently no way to know see the binding value or recognise if there was a binding error. You might want to add another control (maybe a label) that the displays the current value of my decimal so users can see what the entry is converting to and from in the tests.

**Comment by jonkas2211** [comment]
Hello @memu8,
please correct me, if i undestood you wrong, but you can see the value in the entry or not?

If I would add a label, that will also bind to the decimal in from the ViewModel the conversion would be the same of the entry.
Or do you mean this as a static string value for the initial value?

**Comment by jonkas2211** [comment]
I have made an update to the UI Test.

**Comment by EmilAlipiev** [comment]
Can we get that merged in one of the next release 4.8 or 5 pre? it is such blocking issue as we need to support non-English cultures.

**Comment by jonkas2211** [comment]
So whats the status on this PR?

**Comment by jfversluis** [comment]
Hey @jonkas2211 I'm truly sorry this was kept around for so long. Just updated this to work with our latest code and see if I can get it to work. If you're still around and interested please let me know, if not, I will take over and see to get this merged.

In either case: thank you so much for your time and effort on this. Although it doesn't show, I know I and all of use appreciate this.

**Comment by jonkas2211** [comment]
Hello @jfversluis,
thanks for finally looking at his PR!
If there is any thing open let me know, but i think there shouldnt be anymore work here.
We need to make sure, that apps that are arround are not breaking by this change since they might expect the old behaviour.

**Comment by jfversluis** [comment]
Yeah from some quick testing it seems that the code looks alright, I had to fix up some old tests to take into account this new behavior.

If you want, you could test this functionality on your own scenarios by downloading the NuGets that resulted from this build [as described here](https://github.com/xamarin/Xamarin.Forms/wiki/Preview-Packages). If you decide to do so, please let me know what you find, thanks!

**Pull request merged**
