### PR TITLE
[iOS] Remove suggestion bar in iOS picker, datepicker,timepicker for iPAD

### LINKED ISSUE #4629: Picker/DatePicker/TimePicker on iOS iPad should NOT have word suggestions
This is an easy one.  Any of the 3 types of pickers render on iOS iPad with word suggestions toolbar.  iPhone does NOT do this.  Since pickers should only allow values from the picker, there should NOT be any word suggestions available.  I propose that all 3 pickers have their iOS renderers updated to include:

                Control.SpellCheckingType = UITextSpellCheckingType.No;
                Control.AutocorrectionType = UITextAutocorrectionType.No;
                Control.AutocapitalizationType = UITextAutocapitalizationType.None;

### PR DESCRIPTION
**Pull request by masonyc**
### Description of Change ###

Set LeadingBarButtonGroups and TrailingBarButtonGroups to null  in picker renderer, datepicker renderer , timepicker renderer for iOS to prevent suggestion bar in iPAD

### Issues Resolved ### 
fixes #4629 

### API Changes ###
None

### Platforms Affected ### 
- iOS (iPad only)

### Behavioral/Visual Changes ###
Now in picker, datepicker, timepicker, suggestion bar is not displayed anymore on iPAD.

### Before/After Screenshots ### 
Before:
before

after:
after

### Testing Procedure ###
Start ControlGallery.iOS on iPAD device, Search and go to G4629 Page in tests screen, tap the picker to verify suggestion bar not exist anymore.

### PR Checklist ###

- [ ] Has automated tests 
- [x] Rebased on top of the target branch at time of PR
- [x] Changes adhere to coding standard

### CODE REVIEW

**Comment by masonyc** [comment]
@paymicro done

**Comment by samhouts** [comment]
@masonyc I think that didn't work so well! You might need to try again. Make a new branch from the 3.5.0 branch and then cherry-pick just your commits to that branch. Then force push that to this branch.

**Comment by masonyc** [comment]
> @masonyc I think that didn't work so well! You might need to try again. Make a new branch from the 3.5.0 branch and then cherry-pick just your commits to that branch. Then force push that to this branch.

Hi, does it seem right now?

**Comment by kingces95** [comment]
Hm, fairly sure the change is fine if it's just want's suggested in the bug. Just gotta get the merge right. You can tell there's an issue because there are 100+ files touched. Try rebasing instead of merging. And if reusing this branch be sure to push -f.

**Comment by masonyc** [comment]
> Hm, fairly sure the change is fine if it's just want's suggested in the bug. Just gotta get the merge right. You can tell there's an issue because there are 100+ files touched. Try rebasing instead of merging. And if reusing this branch be sure to push -f.

@samhouts @kingces95  sorry, does the merge look correctly now?

**Pull request merged**
