### PR TITLE
Correct Grid Height When Aspect Fit Image Gets Shrinked [issue #4933]

### LINKED ISSUE #4933: Grid size incorrect when using with Image
## Grid size incorrect when using with Image

When Grid.VerticalOption is not fill to parent, and Grid has an Image view, Grid.Height is incorrect. 

Grid should use scaled image size as row height, but it use original image height.

for example like this
```
<Grid HorizontalOptions="FillAndExpand" VerticalOptions="Center" BackgroundColor="Maroon" RowSpacing="0" \>
    <Grid.RowDefinitions>
        <RowDefinition Height="Auto" />
        <RowDefinition Height="Auto" />
    </Grid.RowDefinitions>
    <Image Source="logo.jpg" Grid.Row="0" />
    <Label Grid.Row="1" Text="test message" BackgroundColor="Blue" />
</Grid\>
```
* * *
There are reproduction steps and screenshots in Bugzilla. I am not the original author of the bug but would also like to see this fixed and don't see this bug in GitHub. I am on Xamarin.Forms 3.4.0 and it is still an issue.
 
Submitted by a community member on 2017-04-17 16:35 UTC on Bugzilla and has a Confirmed Status. 

_Reference: <https://bugzilla.xamarin.com/show_bug.cgi?id=55294>_

### PR DESCRIPTION
**Pull request by spruceDevelopment**
### Description of Change ###

There was an issue in GridCalc class where in one case there weren't passed width and height constraints, so the whole grid size calculation gone wrong.

### Issues Resolved ### 

- fixes #4933 

### Platforms Affected ### 

- Core/XAML (all platforms)

### Behavioral/Visual Changes ###

Grid sizing when using images with aspect fit will now work correctly

### Before/After Screenshots ### 

image
image

### PR Checklist ###

- [Yes] Has automated tests 
- [Yes] Rebased on top of the target branch at time of PR
- [Yes] Changes adhere to coding standard

### CODE REVIEW

**Comment by rmarinho** [comment]
Hi @spruceDevelopment you mind rebase ? 

Thanks

**Comment by spruceDevelopment** [comment]
Ok, @rmarinho i will try today

**Comment by spruceDevelopment** [comment]
@rmarinho is this ok or did i just broke everything? :P

**Comment by samhouts** [comment]
@spruceDevelopment Looks like that didn't work properly. You might want to try again. Thanks! :)

**Comment by spruceDevelopment** [comment]
@samhouts ok, now there are no conflicts :)

**Pull request merged**
