### PR TITLE
[Core] Shapes not rendering changing Shell tabs

### LINKED ISSUE #11656: [Bug] Android Shapes drawing Line disappears on page pop and returning back to the page won't draw again
### Steps to Reproduce

1. When I draw a simple line using like code below on contentview inside a contentpage (it could be the problem on contentview)
2. I simply click backbutton to pop the page
3. if I navigate to the page again Line is not drawn. 

```
 <Line
                    x:Name="Line"
                    Stroke="#FF707070"
                    X1="55"
                    X2="150"
                    Y1="90"
                    Y2="120" />
```

 
### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
 
  - Android:  Android 10
 
- Android Support Library Version: 
- Nuget Packages: XF 4.7 
- Affected Devices: tested on emulator

### LINKED ISSUE #11924: [Bug] Shapes not loading in Xamarin ShellContent Tab once it is navigated back from other Tab
### Steps to Reproduce

1.  Create a Sample Xamarin Shell application with 2 tabs
2.  In one of shell content Page Create an Ellipse shape
 [ <Ellipse  Fill="#fff" HorizontalOptions="Center"   VerticalOptions="Center"  Margin="20,0,20,0"  WidthRequest="90"      HeightRequest="90" 
                               />]
3.  Navigate between Pages-- Shape will not render for second time. 

### Expected Behavior
 Shape Should render

### Actual Behavior
 Shape is not rendering

### Basic Information
 Shape is  rendering Xamarin Shell only by  InitializeComponent()

- Version with issue: Xamarin Forms 4.8.0.1269
- Last known good version:
- IDE: Visual Studio 2019
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Workaround
Create Shape from Code Behind and insert it into layout OnAppearing()
public partial class HomePage : ContentPage
    {
        Int16 init  = 0;
        public HomePage()
        {

            InitializeComponent();

            BindingContext = new Empower.ViewModel.HomePageModel();
            // var point = new Point(0,0);
            // pancakecolors.BackgroundGradientStartPoint = point;
            // pancakecolors.BackgroundGradientEndPoint = new Point(1, 1);

            init = 1;

        }

        protected override void OnAppearing()
        {
            if (init == 0)
            {

                Ellipse _elpseShape = new Ellipse();
                _elpseShape.Fill = Brush.White;
                _elpseShape.HorizontalOptions = LayoutOptions.Center;
                _elpseShape.VerticalOptions = LayoutOptions.Center;
                _elpseShape.WidthRequest = 80;
                _elpseShape.HeightRequest = 80;

                grdmyaccount.Children.RemoveAt(0);
                grdmyaccount.Children.Insert(0, _elpseShape);
            }

            init = 0;

        }

    }
martin_community

### LINKED ISSUE #12844: [Bug] Path not rendered on page reload
### Description

Using a Path to provide a shaped background on a page in a Shell app. The Path is correctly rendered on the initial page load but when you switch to another page then back to that page the Path is not rendered.

### Steps to Reproduce

1. Create a new project from the Mobile App (Xamarin Forms) template.
2. Update the project to the Xamarin Forms v5 Nuget package and change Android Target Framework to 10.
3. Replace the contents of the ItemsPage.xaml with the Path as below.

<?xml version="1.0" encoding="utf-8" ?>
<ContentPage
    x:Class="TestApp.Views.ItemsPage"
    xmlns="http://xamarin.com/schemas/2014/forms"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    xmlns:local="clr-namespace:TestApp.ViewModels"
    xmlns:model="clr-namespace:TestApp.Models"
    x:Name="BrowseItemsPage"
    Title="{Binding Title}">

    <Path
        Aspect="Fill"
        Data="m 0,0 h 100 v 41.910828 c 0,0 -14.861996,6.878981 -50,0 -35.138004,-6.878981 -50,0 -50,0 z"
        StrokeThickness="0">
        <Path.Fill>
            <SolidColorBrush Color="DarkBlue" />
        </Path.Fill>
    </Path>

</ContentPage>

### Expected Behavior

Path is displayed on the page.

### Actual Behavior

Path is displayed on initial page load but when you navigate to the About page and back to the Browse page it is not rendered.

### Basic Information

- Version with issue: 5.0.0.1558-pre3
- Last known good version: ?
- IDE: Visual Studio 2019
- Platform Target Frameworks: 
  - iOS:  not tested
  - Android: v10
  - UWP:  not tested
- Android Support Library Version: 
- Nuget Packages: Xamarin.Forms (5.0.0.1558-pre3), NETStandard.Library (2.0.3)
- Affected Devices:

### Screenshots

Initial load of page:
Screenshot_1605302650

After navigating away from page and back to it:
Screenshot_1605302657

### PR DESCRIPTION
**Pull request by jsuarezruiz**
### Description of Change ###

Shapes not rendering changing Shell tabs. 

### Issues Resolved ### 

- fixes #11924 
- fixes #11656
- fixes #12844

### API Changes ###
 
 None

### Platforms Affected ### 

- Core/XAML (all platforms)

### Behavioral/Visual Changes ###

None

### Before/After Screenshots ### 

fix11924-ios
fix11924-droid

### Testing Procedure ###
Launch Core Gallery and navigate to the issue 11924. Navigate to the second Tab and then navigate back to the first tab, and verify if the Ellipse is rendering.

### PR Checklist ###

- [ ] Targets the correct branch
- [ ] Tests are passing (or failures are unrelated)

### CODE REVIEW

**Comment by martinkabraham** [comment]
@jsuarezruiz .Tried with Nuget 4.8.0.1269 pre-release  in Xamarin Shell.  Not Working while Tab is selected from second time. First time it is working.

Below shape I placed in second tab ShapePage when I navigate to AboutPage and again back to ShapePage ellipse not rendering.

`  <FlyoutItem FlyoutDisplayOptions="AsMultipleItems">
        <ShellContent Title="About" Icon="tab_about.png" Route="AboutPage" ContentTemplate="{DataTemplate local:AboutPage}" />
        <ShellContent Title="Browse" Icon="tab_feed.png" ContentTemplate="{DataTemplate local:ShapePage}" />
    </FlyoutItem>
`

`    <Ellipse Fill="DarkBlue"
         Stroke="Red"
         StrokeThickness="4"
         WidthRequest="150"
         HeightRequest="50"
         HorizontalOptions="Start" />
`

**Comment by martinkabraham** [comment]
xamarin

**Comment by jsuarezruiz** [comment]
Thanks for the feedback @martinkabraham. Will do more tests. Testing with https://github.com/xamarin/Xamarin.Forms/blob/34bbf5d6fbf920a16717686766f220e13348cf0b/Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue11924.cs the Ellipse is always rendering (I did the change of tabs more than 10 times).

**Comment by Cfun1** [comment]
There is a case where it is still happening, the case where you have 3 pages inside a `Tab` with condition that the shapes are contained in `Page3:`

### Steps to reproduce:
1- Define the below Shell pages structure.
2- Navigate from `Page1 `to `Page3`.
3- Navigate to `Page1 `then come back to `Page3`

Version with issue: 5.0.0-pre4

```
  <FlyoutItem FlyoutDisplayOptions="AsMultipleItems">
        <Tab Title="Tab1">
            <ShellContent Title="Page1"
                          ContentTemplate="{DataTemplate local:Parent}"/>

            <ShellContent Title="Page2"
                          ContentTemplate="{DataTemplate local:Page2}"/>

            <ShellContent Title="Page3"
                          ContentTemplate="{DataTemplate local:Page3}"/> <!-- Contains shapes -->
        </Tab>
    </FlyoutItem>
```

**Comment by jsuarezruiz** [comment]
I'm going to close this PR because this fix is now in https://github.com/xamarin/Xamarin.Forms/pull/13284/

**Pull request closed without merging**
