### PR TITLE
[Android] AppCompat version of EntryRenderer

### LINKED ISSUE #1549: [Feature Request] Add AppCompat version of EntryRenderer
### Summary
There isn't a AppCompat version of the EntryRenderer, there should be.

### API Changes
Create a AppCompat version of the EntryRenderer, so that the native control is set as a AppCompatEditText.

### Intended Use Case
Having a AppCompat version of controls makes it easier to style it the same for all Android Versions

### PR DESCRIPTION
**Pull request by ravinderjangra**
### Description of Change ###

Ported EntryRenderer
fixes #1549

### Bugs Fixed ###

- No Bug Fix

### API Changes ###

List all API changes here (or just put None), example:

Added:
 - string ListView.GroupName { get; set; } //Bindable Property
 - int ListView.GroupId { get; set; } // Bindable Property
 - void ListView.Clear ();

### PR Checklist ###

- [ ] Has tests (if omitted, state reason in description)
- [x] Rebased on top of master at time of PR
- [x] Changes adhere to coding standard
- [ ] Consolidate commits as makes sense

### CODE REVIEW

**Comment by rmarinho** [comment]
Can you add some screenshots so we can check the difference ? @jassmith is this something we need? was requested ?

**Comment by ravinderjangra** [comment]
any update on this?

**Comment by rmarinho** [comment]
@ravinderjangra can you put some screenshots? 

Thanks

**Comment by adrianknight89** [comment]
I think this needs to be rebased since the original renderer has more to copy from. Also, we might need to wrap `AppCompatEditText` in `FormsAppCompatEditText` to add the missing code with respect to selection change, keyboard, and focusability stuff, but I suspect the original `FormsEditText` has something to do with #3647.

**Comment by samhouts** [comment]
Since we have an updated PR (#4241), I will close this one for now. Thank you!

**Pull request closed without merging**
