### PR TITLE
Drop AppTheme flag

### PR DESCRIPTION
**Pull request by StephaneDelcroix**
### Description of Change ###

Drop the AppTheme Flag

### Issues Resolved ### 

none

### API Changes ###

 
 None

### Platforms Affected ### 

- Core/XAML (all platforms)
- iOS
- Android
- UWP

### Behavioral/Visual Changes ###

None

### Before/After Screenshots ### 

Not applicable

### PR Checklist ###

- [ ] Targets the correct branch
- [ ] Tests are passing (or failures are unrelated)

### CODE REVIEW

**Comment by samhouts** [comment]
@StephaneDelcroix Can you please resolve the conflicts? Thanks!

**Comment by vniehues** [comment]
This right here might be needed for it to work properly:


```
//Dark mode
UIApplication.SharedApplication.SetStatusBarStyle(UIStatusBarStyle.LightContent, true);

//Light mode
UIApplication.SharedApplication.SetStatusBarStyle(UIStatusBarStyle.DarkContent, true);
```

**Comment by mikebikerider** [comment]
Thank you for the suggestion, but it is not a solution.

I slightly modified the test app to better illustrate the issue.

The code of a test page producing the screenshot that follows:
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="AppThemeTest.Page1">
    <Grid  ColumnDefinitions="*" RowDefinitions="*,*,*">
        <BoxView Grid.Row="1" Color="{AppThemeBinding Light=Wheat,Dark=DarkSlateGray}"/>
        <Label x:Name="label1" Grid.Row="1" FontSize="28" TextColor="{AppThemeBinding Light=DarkBlue, Dark=White}"  VerticalTextAlignment="Center" HorizontalTextAlignment="Center" LineBreakMode="WordWrap"/>
    </Grid>
</ContentPage>
The page has a grid with no background set. One column, three rows. The middle row holds a BoxView and a Label to show the selected Theme and the Xamarin.Forms version.
The issue affects iOS only. I deliberately did not apply UseSafeArea.

IMG_0467

Grid rows 0 and 2 are rendered on the white background while the selected Theme is Dark. The status bar text is not visible because the status bar TextColor is White, as it should be in the Dark mode.
 
Xamarin Forms 4.7 and prior do render page background according to the current Theme.
Xamarin.Forms 4.8.0.1269 renders page background White regardless of the selected Theme.

A simple but silly looking 'solution' is to put following line into the ContentPage XAML section:
 BackgroundColor="{AppThemeBinding Light=White, Dark=Black}"

The below code will produce a correctly rendered page:

<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="AppThemeTest.Page1"
             BackgroundColor="{AppThemeBinding Light=White, Dark=Black}">
    <Grid  ColumnDefinitions="*" RowDefinitions="*,*,*">
        <BoxView Grid.Row="1" Color="{AppThemeBinding Light=Wheat,Dark=DarkSlateGray}"/>
        <Label x:Name="label1" Grid.Row="1" FontSize="28" TextColor="{AppThemeBinding Light=DarkBlue, Dark=White}"  VerticalTextAlignment="Center" HorizontalTextAlignment="Center" LineBreakMode="WordWrap"/>
     </Grid>
</ContentPage>

IMG_0468

I don't recall ever applying the background to the whole page. Prior to Xamarin.Forms 4.8 there was no need for this.

Looking closely at the recently updated Xamarin documentation   https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/theming/system-theme-changes August 6, 2020:
Xamarin.Forms 4.6.0.967 or greater... 
I don't think code snippets offered there will produce dark mode screenshots as shown if rebuilt with Xamarin.Forms 4.8.
 
I did not formally report this as an issue.

**Comment by mikebikerider** [comment]
Stefan, I can't tell from your screenshot if it is from iPhone or Android phone.
The issue I described affects iOS only. It is easily fixed in XAML by setting ContentPage BackgroundColor :
BackgroundColor="{AppThemeBinding Light=White, Dark=Black}"

Xamarin.Forms 4.7 with the experimental AppTheme flag loads Page with the background color matching the selected theme.
In August I updated two existing apps to Xamarin.Forms 4.8 and didn't even notice until the next day that the system notification area in Dark Mode is rendered white and no text visible because text is correctly rendered in white and not visible on the white background.
Easy to fix in XAML, but is inconsistent.

**Comment by stefanhk31** [comment]
> Stefan, I can't tell from your screenshot if it is from iPhone or Android phone.
> The issue I described affects iOS only. It is easily fixed in XAML by setting ContentPage BackgroundColor :
> BackgroundColor="{AppThemeBinding Light=White, Dark=Black}"
> 
> Xamarin.Forms 4.7 with the experimental AppTheme flag loads Page with the background color matching the selected theme.
> In August I updated two existing apps to Xamarin.Forms 4.8 and didn't even notice until the next day that the system notification area in Dark Mode is rendered white and no text visible because text is correctly rendered in white and not visible on the white background.
> Easy to fix in XAML, but is inconsistent.

Sorry, should have clarified. The screenshot above is on iOS. I set the code in XAML exactly as you describe. Background appears as black with the flag on 4.7, but the white screen shows when upgrading to 4.8.

I can give specific more specific code when I'm at my workstation next, but the issue only appeared after I upgraded to 4.8.

**Pull request merged**
