### PR TITLE
Fix 9052 - restore style with no extra width for Switch / ToggleSwitch [UWP]

### LINKED ISSUE #9052: [Bug] [UWP] Switch takes up more horizontal space then before
### Description
Switch seems to take up more horizontal space in XF 4.3+.

### Steps to Reproduce

Add a Switch to a StackLayout with Horizontal orientation

### Expected Behavior
Switch only takes the horizontal space it needs

### Actual Behavior
It's taking more space then needed

### Basic Information

- Version with issue:
- Last known good version: 4.2
- IDE: VS2019 16.4.2
- Platform Target Frameworks: 
  - UWP: 16299   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Screenshots
Yellow is the background color of the switch

UWP (Win 10 1903)
image

Android
image

iOS
image

### Reproduction Link
[SwitchRepro.zip](https://github.com/xamarin/Xamarin.Forms/files/4011326/SwitchRepro.zip)

### PR DESCRIPTION
**Pull request by WayaFlyfeather**
### Description of Change ###

By using a new dedicated style, FormsToggleSwitchStyle, the UWP SwitchRenderer now shows a switch with no extra-margin, as before 4.3.0; previously it relied on a default style, overwritten by changes in #7319; basically the cause and fix is the same as in #8743. The fact that the previous default style is hidden is the cause of #9052.

### Issues Resolved ### 

- fixes #9052

### API Changes ###
 
 None

### Platforms Affected ### 

- UWP

### Behavioral/Visual Changes ###

Switches will have no extra width, as before 4.3. There is one possible problem for UWP developers: if they have implemented their own default ToggleSwitch style, then Xamarin Switches will no longer use that; they will have to implement their own version of FormsToggleSwitchStyle in that case.

### Before/After Screenshots ### 
Before:
fix-9052-before

After:
fix-9052-after

### Testing Procedure ###

Go to test case 9052; Check that the yellow background of the Switch has no extra width.

### Todo(?) ###

As the previous (pre 4.3) default ToggleSwitch is now no longer default, other uses of ToggleSwitch will probably have the extra width; this may possibly cause problems. One fix would be to have them use the new FormsToggleSwitchStyle. One such possible problem (perhaps the only one), is in DataTemplate for the SwitchCell (in Resources).

Also, in Resources, is a default style for TextBox. This is most likely also hidden now, and it would probably be prudent to delete it from Resources, as it has no effect beyond being confusing. I'm not sure whether it may be a problem that it has been hidden, as the FormsTextBox already uses it's own style.

I have not at this point done any of these as part of this PR, as they had nothing to do with fixing #9052, as such.

### PR Checklist ###

- [ ] Targets the correct branch
- [ ] Tests are passing (or failures are unrelated)

### CODE REVIEW

**Comment by PureWeen** [comment]
Here's a Xamarin.Forms app against XF 4.2 with the TPV set to 18632

image

Here's the same app with TPV set to 16299

image

**Comment by PureWeen** [comment]
I'm thinking to fix this we'll need to just break out the entire control template and hard code

ToggleSwitchThemeMinWidth

to Zero

**Comment by WayaFlyfeather** [comment]
Right - nice catch, @PureWeen.

So, to sum up: this fix brought the Switch on UWP back to the state it was in before #7319. However, that state isn't really good enough, as it is susceptible to changes in the default ControlTemplate.

So we also need to provide our own ControlTemplate, for us to be sure what it looks like, and doesn't add spacing as per the Theme.

Luckily, that's is pretty easy to do, now we have a FormsToggleSwitchStyle. In my recent commit I have added a copy of the default ControlTemplate from 16299 to the style - it doesn't use ToggleSwitchMinWidth, so is not affected by changes to that.

With TPV 16299:
fix-9052-after-16299

With TPV 18632:
fix-9052-after-18632

**Comment by WayaFlyfeather** [comment]
Note, this of course also means that the notes in the PR for Behavioral/Visual changes are not complete. There will also be a change where the extra width on are removed from Switches for clients with Target Platform Version > 16299.

**Comment by samhouts** [comment]
@WayaFlyfeather Are you able to address @PureWeen's comments? Thanks!

**Comment by samhouts** [comment]
I'm going to close this one for now until we're ready to return to it. Thanks, @WayaFlyfeather !

**Pull request closed without merging**
