### PR TITLE
[iOS/Droid] Fix Shell SearchHandler - Search text getting lost on execute search

### LINKED ISSUE #6804: [Bug] Shell SearchHandler - Search text getting lost on execute search
### Description

When using the Xamarin.Forms Shell template and upgrade to Xamarin.Forms 4.1 (I did not test with 4.0 yet), the SearchHandler is removing the search term on enter/search execution. 

SearchHandlerBug

### Steps to Reproduce

1. Create a fresh Xamarin.Forms Shell project
2. Add a search handler

### Expected Behavior

It should keep the searched term.

### Actual Behavior

It losts the content.

### Basic Information

- Version with issue: 4.1.0
- Last known good version: -
- IDE: VS2019 and VS for Mac
- Platform Target Frameworks: 
  - iOS:  Tested with iOS 12 Simulator

### Screenshots

Already added above in the description.

### Reproduction Link

Reproduction can be done with the VS template within a minute.

### PR DESCRIPTION
**Pull request by dmariogatto**
### Description of Change ###

Stop the clearing of the search box text when executing a search using a SearchHandler (Shell).

### Issues Resolved ### 

- fixes #6804

### API Changes ###
 
 None

### Platforms Affected ### 

- iOS
- Android

### Behavioral/Visual Changes ###

Do not clear search text on execute.

#### iOS ####

ios_broken
ios_fix

#### Android ####

droid_broken
droid_fix

### Testing Procedure ###

Manual, enter a search query and execute the text should remain.

### PR Checklist ###

- [x] Targets the correct branch
- [ ] Tests are passing (or failures are unrelated)

### CODE REVIEW

**Comment by rmarinho** [comment]
this is a breaking change on the ux no? I wonder if this was done liek this for a reason.

**Comment by dmariogatto** [comment]
If it was done for an UX reason there needs to be a way to override this behaviour, as currently it does not match what the native platforms do by default.

**Comment by Bronson15** [comment]
Any movement on this PR?

**Comment by GeorgeVelikov** [comment]
I probably should have posted [this](https://github.com/xamarin/Xamarin.Forms/issues/6804#issuecomment-591880010) in here

**Pull request merged**
