### PR TITLE
Revert "[GTK] Fix visibility of hidden pages in the stack (#3904)"

### PR DESCRIPTION
**Pull request by mfkl**
This reverts commit b5b9404bda761e7e5941da7ff26f1d42dd62d1b2.

### Description of Change ###

Regression introduced in https://github.com/xamarin/Xamarin.Forms/pull/3904 

### Issues Resolved ### 

- fixes https://github.com/xamarin/Xamarin.Forms/issues/6663

### API Changes ###

 None

### Platforms Affected ### 

- GTK

### Behavioral/Visual Changes ###

Fixes navigation issues.

### Testing Procedure ###

Try running https://gitlab.com/knocte/geewallet/commits/bugreport/gtk-navgoback2 with last 3.3 (good) or first 3.4 (bad) to see the issue.

### PR Checklist ###

- [x] Targets the correct branch
- [ ] Tests are passing (or failures are unrelated)

/cc @knocte

### CODE REVIEW

**Comment by mfkl** [comment]
> I can add it if to your branch if it's ok for you.

Yes please, I'm having some trouble running the existing tests locally.

**Comment by jsuarezruiz** [comment]
Updated the branch adding the sample.

**Comment by mfkl** [comment]
>  mfkl requested a review from StephaneDelcroix as a code owner 10 minutes ago 

hmm I think I mis-clicked or something...

**Comment by knocte** [comment]
>  samhouts changed the base branch from 4.3.0 to master 12 hours ago
> [This branch has conflicts that must be resolved]

Oh, seems like this needs a rebase now?

**Comment by knocte** [comment]
In case you request a rebase, I've done one here: https://github.com/xamarin/Xamarin.Forms/pull/8096

**Comment by knocte** [comment]
#8096 was merged to master (thanks). @samhouts would you authorize backporting this to 4.3.x?

**Comment by samhouts** [comment]
@knocte This has been cherry-picked to 4.3.0, and it'll be in service release 2. Thanks!

**Pull request closed without merging**
