### PR TITLE
Implements ListView Header and Footer for WPF

### LINKED ISSUE #3770: [WPF] ListView.Header not being rendered
### Description
ListView.Header does not render with Xamarin.Forms.Platform.WPF.

### Steps to Reproduce

1. Download attached reproduction project
2. Build and run ListViewBug.WPF (can compare with ListViewBug.UWP to see difference)

### Expected Behavior
ListView header should show two columns named "Column1" and "Column2". Nothing shows up.

### Actual Behavior
ListView header does not show at all on WPF project.

### Basic Information

- Version with issue: 3.2.0.809874-pre (and 3.1.0.697729)
- Last known good version: N/A
- IDE: VS2017 Community
- Platform Target Frameworks: 
  - UWP:  16299
  - WPF
- Affected Devices: Windows Classic Desktop

### Screenshots
WPF:
image

UWP:
image

### Reproduction Link
[ListViewBug.zip](https://github.com/xamarin/Xamarin.Forms/files/2376261/ListViewBug.zip)

### LINKED ISSUE #3947: [Error] ListView's Header and Footer is not working in WPF
### Steps to Reproduce
1. Add ListView with Header
```
                <ListView Grid.Row="2"
                          ItemsSource="{Binding KeyPoints}">
                    <ListView.Header>
                        <StackLayout>
                            <Label Text="TEST" />
                        </StackLayout>
                    </ListView.Header>
                </ListView>
```
2. Build and Debug
3. Have no result in Header

### Expected Behavior
ListView's Header and Footer is working properly

- Version with issue: 3.2.0.839982
- IDE: Visual Studio 2017, 15.8
- Platform Target Frameworks: WPF

### PR DESCRIPTION
**Pull request by BarryNolte**
### Description of Change ###
Wrapped the ListView in a Grid that allows for the insert/delete of headers and footers.

### Issues Resolved ### 
- fixes #3947 
- fixes #3770

### API Changes ###
None

Added:
No public changes.

### Platforms Affected ### 
-WPF

### Behavioral/Visual Changes ###
Headers and footers will not show on Platform.WPF

### CODE REVIEW

**Comment by melimion** [comment]
@BarryNolte @jsuarezruiz
Maybe it's better to add Footer as last cell to Control.ItemsSource

**Comment by VladislavAntonyuk** [comment]
> @BarryNolte @jsuarezruiz
> Maybe it's better to add Footer as last cell to Control.ItemsSource

@melimion Header and Footer are not a part of ItemsSource. They shouldn't be clickable as cells and shouldn't increase Items.Count.

**Comment by BarryNolte** [comment]
The fixed headers are the same behavior as on MacOS FWIW.  This appears to be more of a desktop behavior than a mobile behavior.  I thought about the ItemSource solution, but then you have to keep track of way too many things creating a bug factory in something that should be as easy as setting a property to a collection source.  Header/ListView/Footer could also be put on a ScrollView, but then you have to determine when to scroll the header and footer off the screen and you might lose any ability to optimize/virtualize the ListView and you have two scrollbars to deal with.  Just my $.02.

**Comment by melimion** [comment]
> Header and Footer are not a part of ItemsSource. They shouldn't be clickable as cells and shouldn't increase Items.Count.
@VladislavAntonyuk group headers already work that way. WPF native ListView Items are not available from XF layer, so ItemsSource.Count wouldn't be a problem. Click can also be prevented in renderer.

>Probably we have to add 2 properties: IsFooterFixed and IsHeaderFixed.
That's good idea.

> The fixed headers are the same behavior as on MacOS
@BarryNolte I think behaviour should be same on all platforms, so MacOS needs to be fixed. But idea with IsFooterFixed/IsHeaderFixed resolves this.

**Comment by amirvenus** [comment]
+1 for `IsFooterFixed` and `IsHeaderFixed`.

**Comment by BarryNolte** [comment]
Any progress on the review?  The suggestions to add the IsFooterFixed/IsHeaderFixed is sound, but causes a change to the underling ListView API instead of isolating this to the WPF renderer which creates changes to docs as well as tests, etc.

**Pull request merged**
