### PR TITLE
[Android] CarouselView position resets when visibility toggled

### LINKED ISSUE #12848: [Bug] CarouselView position resets when visibility toggled.
### Description

CarouselView resets its position when its visibility is changed. It appears from the CarouselViewRenderer code that it is trying to restore the position, but for some reason is not.

### Steps to Reproduce

1. Move CarouselView to another position.
2. Set CarouselView IsVisible=false
3. Set CarouselView IsVisible=true
4. Observe that the CarouselView position has been lost

### Expected Behavior

CarouselView should retain its set position.

### Actual Behavior

CarouselView resets to the 0 position.

### Basic Information

- Version with issue: 4.8.0.1687, 5.0.0.1558-pre-3
- Last known good version: 4.7
- IDE: VS 2019 16.8.1
- Platform Target Frameworks: 
  - Android: 11.0 

### Reproduction Link

[CarouselVisibilityReset.zip](https://github.com/xamarin/Xamarin.Forms/files/5540277/CarouselVisibilityReset.zip)

### PR DESCRIPTION
**Pull request by jsuarezruiz**
### Description of Change ###

Fix CarouselView position issue resets when visibility toggled on Android.

### Issues Resolved ### 

- fixes #12848 

### API Changes ###

 None

### Platforms Affected ### 

- Android

### Before/After Screenshots ### 
fix12848

### Testing Procedure ###
Launch Core Gallery and navigate to the issue 12848. Swipe the Carousel to select the item numbered 2. Then, tap the Hide Button to hide the Carousel and then the Show Button to show the Carousel again. If the position of the Carousel is the same as before hiding, the test has passed.

### PR Checklist ###

- [ ] Targets the correct branch
- [ ] Tests are passing (or failures are unrelated)

### CODE REVIEW

**Review by rmarinho — COMMENTED** [review]
Can we add a UITest please? :)

**Comment by jsuarezruiz** [comment]
@rmarinho Sure, added the related UITest.

**Comment by rmarinho** [comment]
Seems tests were failing on Android , can you confirm @jsuarezruiz  ?

**Comment by jsuarezruiz** [comment]
The build seems to be correct.

**Review by hartez — APPROVED** [review]

**Review by rmarinho — CHANGES_REQUESTED** [review]
Tests are failing on Android

**Comment by jsuarezruiz** [comment]
Updated the PR merging the latest changes added to `CarouselViewRenderer` and validated that the fix is still valid.

**Review by rmarinho — APPROVED** [review]

**Pull request merged**
