### PR TITLE
Minimum width and height should work

### PR DESCRIPTION
**Pull request by adrianknight89**
### Description of Change ###

`VisualElement` incorrectly sized minimum dimensions due to these lines:

```
minimum.Height = Math.Min(request.Height, minimum.Height);
minimum.Width = Math.Min(request.Width, minimum.Width);
```

If request is 100x100 and minimum is 300x300, Math.Min always sets minimum to 100x100; thus, ignoring user-set minimum dimensions. `GetSizeRequest()` should return the correct size object.

`Layout` then should account for minimum size request while positioning visual elements.

The unit test is there to make sure setting minimum dimensions does not inadvertently change request.

### Bugs Fixed ###

I have not verified all, but since they are related to minimum dimensions, they might all be fixed.

- https://bugzilla.xamarin.com/show_bug.cgi?id=37614
- https://bugzilla.xamarin.com/show_bug.cgi?id=41740
- https://bugzilla.xamarin.com/show_bug.cgi?id=38535
- https://bugzilla.xamarin.com/show_bug.cgi?id=44738

### CODE REVIEW

**Comment by jassmith** [comment]
This would present a breaking change to current apps unfortuantely.

**Comment by adrianknight89** [comment]
@jassmith How do you hope to fix those issues then? Will `MinimumWidthRequest` and `MinimumHeightRequest` never work?

Can we add a check to look at XF version ID so that new apps use the fixed version? I know this would create clutter in the code base. Just an idea.

**Comment by rogihee** [comment]
People are clearly expecting a different behavior, looking at all the bugs. Is it not better to do the breaking change in a new point release, say 2.4?

Why reject a fix?

**Comment by adrianknight89** [comment]
@jassmith  I ran 10 different tests on an Android button with my code changes:

image

Only one produces incorrect result. This is because of the way GetSizeRequest works. Instead of measuring once for width/height request and once for minimum width/height request, it measures only once and tries to update minimum. Unfortunately, minimum gets 55.5 units for height instead of 48.

All unit tests pass.

I'd still test my code on your end unless you have a strong reason (please explain) not to do so. Right now, minimum size request does not work at all.

**Pull request closed without merging**
