### PR TITLE
[iOS] Fix incorrect refresh indicador position using RefreshView with CollectionView Header

### LINKED ISSUE #8282: [Bug] [iOS] RefreshView draws behind CollectionView Header
### Description

When using a `RefreshView` and wrap a `CollectionView` with header in it, the `RefreshView` draws behind the `CollectionView` header on iOS.
This leads to unwanted behaviour, for instance: `CollectionView` in some cases scrolls out of screen bounds (as it scrolls up too far after refreshing).

### Steps to Reproduce
I just re-used and adjusted the Xamarin.Forms `CollectionView` Demo to reproduce the issue.

1. Open the attached Solution
2. Navigate to "Pull to Refresh using RefreshView -> Vertical List"
3. Pull the CollectionView down to refresh

### Expected Behavior

The `RefreshView` should draw above the `CollectionView` header.

### Actual Behavior

The `RefreshView` draws behind the `CollectionView` header on iOS.

### Basic Information

- Version with issue: Tested on Xamarin.Forms 4.3.0.908675
- Last known good version: N/A
- IDE: Tested on Visual Studio Professional 2019
- Platform Target Frameworks:
  - iOS: 11.0
  - Android: 9.0
  - UWP:  N/A
- Android Support Library Version: N/A
- Nuget Packages: Xamarin.Forms 4.3.0.908675
- Affected Devices: Tested on iPhone 8 running iOS 13.1.3 and Huawei P Smart + (2019) running Android 8.1. 

### Screenshots

The screencasts were made on Emulators (iPhone 8 iOS13, Google Nexus 5X Android 8.1).

**iOS**

OMMZ7DvVCg

**Android**

fmULH9FL7K

### Reproduction Link

[CollectionViewHeader.zip](https://github.com/xamarin/Xamarin.Forms/files/3783031/CollectionViewHeader.zip)

### PR DESCRIPTION
**Pull request by jsuarezruiz**
### Description of Change ###

Fix incorrect refresh indicador position using RefreshView with CollectionView with Header on iOS.

### Issues Resolved ### 

- fixes #8282

### API Changes ###
 
 None

### Platforms Affected ### 

- iOS

### Behavioral/Visual Changes ###

None

#### Before
issue82822

#### After
fix8282

### Testing Procedure ###
Launch Core Gallery and navigate to the issue 8282. Pull to Refresh. If the loading indicator appears above the CollectionView header, the test has passed.

### PR Checklist ###

- [ ] Targets the correct branch
- [ ] Tests are passing (or failures are unrelated)

### CODE REVIEW

**Comment by xleon** [comment]
why is this not merged yet?

**Comment by thecuong064** [comment]
Looking forward to seeing this in the next release of Xamarin Forms !!!

**Comment by TingtingAn** [comment]
please merge it asap

**Review by rachelkang — APPROVED** [review]

**Comment by matteovelati** [comment]
Where can I get the Xamarin.Forms version with this fix? On Nuget I can only find the 5.0.0.2012 where this issue is still present..
Thanks

**Comment by argentini** [comment]
@jsuarezruiz do you know when we can expect the next service release to be available (with this fix)?

**Comment by rdeveen** [comment]
Releases in https://github.com/xamarin/Xamarin.Forms/releases/tag/release-5.0.0-sr4

**Pull request merged**
