### PR TITLE
Fixed NullReferenceException in Dual Screen Android GetHinge() function

### PR DESCRIPTION
**Pull request by mscherotter**
### Description of Change ###
Added check for null value before using it in the GetHinge() function

### Issues Resolved ### 

- fixes #0001 Added check for null to code.

### API Changes ###
None

### Platforms Affected ### 
- Android
### Behavioral/Visual Changes ###
None
### Before/After Screenshots ### 
Not applicable
### PR Checklist ###

- [ ] Targets the correct branch
- [ ] Tests are passing (or failures are unrelated)

### CODE REVIEW

**Comment by mscherotter** [comment]
Added a null check to the hinge rectangle returned from a previous API call.

**Comment by PureWeen** [comment]
@mscherotter 

Yay! Dual Screen PRs!!

Looks like something is messed up here with the commits? 

Do you need to rebase the original to 4.5.0?

**Comment by mscherotter** [comment]
Possibly – how should I do that?

**Comment by PureWeen** [comment]
Let's see.. Looking at your setup this should work

git rebase --onto 4.5.0 master 85403e5ced1a5e1d1292f5b4f738b2cc10461f9a

But if that doesn't work I'd say just checkout the `4.5.0` branch locally, make the changes there, and then force push to this branch

**Comment by mscherotter** [comment]
Just did that with a new PR.

**Pull request closed without merging**
