### PR TITLE
[Android] Add IsSmoothScrollEnabled platform specific to control tab change animation

### LINKED ISSUE #2948: [Android] Create a platform specific for UseAnimations in TabbedPageRenderer
Through a platform specific, please let us control whether the new current page should have a transition animation.

```
internal bool UseAnimations
{
	get { return _useAnimations; }
	set
	{
		FormsViewPager pager = _viewPager;

		_useAnimations = value;
		if (pager != null)
			pager.EnableGesture = value;
	}
}
```

This property is used when `_viewPager` is being constructed:

```
FormsViewPager CreateFormsViewPager(Context context, TabbedPage tabbedPage)
{
	return new FormsViewPager(context)
	{
		OverScrollMode = OverScrollMode.Never,
		EnableGesture = UseAnimations,
		LayoutParameters = new LayoutParams(LayoutParams.MatchParent, LayoutParams.MatchParent),
		Adapter = new FormsFragmentPagerAdapter<Page>(tabbedPage, FragmentManager) { CountOverride = tabbedPage.Children.Count }
	};
}
```

As you can see, it's setting `EnableGesture` which is also being set by the platform specific `IsSwipePagingEnabled` to control swiping on the page:

```
void UpdateSwipePaging()
{
	_viewPager.EnableGesture = Element.OnThisPlatform().IsSwipePagingEnabled();
}
```

This is a conflict of interest. In my opinion, `IsSwipePagingEnabled` should control `EnableGesture` everywhere and a platform specific should be created which controls the second parameter when invoking `_viewPager.SetCurrentItem()`.

Right now, we can disable swiping on a `TabbedPage`, but we cannot control transition animations when we programmatically change current page or use the tab bar.

### PR DESCRIPTION
**Pull request by adrianknight89**
### Description of Change ###

This adds `IsSmoothScrollEnabled` platform specific to Android's `TabbedPage` to enable/disable scroll animation as the user navigates from one tab to another manually or programmatically. Previously, a user sitting on the last tab and tapping the first one would see a flipbook-like animation visiting every tab in between which may not be ideal for some use cases. This platform-specific controls this behavior.

Also, `EnableGesture` property should not be set by `IsSmoothScrollEnabled` (previously `UseAnimations`). This property is being controlled by `IsSwipePagingEnabled` and initially should be set by that platform specific instead.

Please let me know how to update docs.

### Bugs Fixed ###

- fixes #2948 

### API Changes ###

Added:
 - `IsSmoothScrollEnabled`  boolean and its platform specific methods

### PR Checklist ###

- [x] Has tests (if omitted, state reason in description)
- [x] Rebased on top of the target branch at time of PR
- [x] Changes adhere to coding standard
- [x] Consolidate commits as makes sense

### CODE REVIEW

**Comment by samhouts** [comment]
HI @adrianknight89! No need to update docs anymore. It's now a separate process handled by a separate team. Thanks!

**Comment by adrianknight89** [comment]
Awesome. Much less work on our part. :)

**Comment by rmarinho** [comment]
hey @adrianknight89 you mind rebase to run tests again to see if we get better results?! thanks

**Comment by adrianknight89** [comment]
I’m on vacation till August and don’t have access to my workspace. Feel free to take ownership or else I’ll rebase when I’m back.

**Comment by PureWeen** [comment]
build --uitests

**Pull request merged**
