### PR TITLE
[UWP] Fixes image scale

### LINKED ISSUE #3169: Image Scale ignored on UWP apps
### Description

I have a few images with a scale set to .3.  They were showing up correctly on UWP, but I recently updated the xamarin.forms packages and now on UWP only, the scale seems to be ignored.

### Steps to Reproduce

1.  Create blank Xamarin.Forms standard.net app
2. Updage Xamarin.Forms package to 3.1.0.583944
3. Add this to XAML
```xaml
          <Image Source="MetroIcon.png" Scale=".3"/>
```
4.  Run on UWP and Android and see that UWP is large and ignores scale

### Expected Behavior
Used to scale correctly before ???

- Version with issue:
Xamarin.Forms 3.1.0.583944

- Last known good version:
Xamarin.Forms 3.1.0.482410
- IDE:
Visual Studio 2017 community version

### PR DESCRIPTION
**Pull request by paymicro**
### Description of Change ###

Fixes image scale

### Issues Resolved ###

- fixes #3169

### API Changes ###

None

### Platforms Affected ###

- UWP

### Behavioral/Visual Changes ###

image scale works correctly

### PR Checklist ###

- [ ] Has automated tests 
- [x] Rebased on top of the target branch at time of PR
- [x] Changes adhere to coding standard

### CODE REVIEW

**Comment by samhouts** [comment]
Can you post before and after screenshots? Thanks!

**Comment by paymicro** [comment]
**Screenshots**
Before http://prntscr.com/k2zdxf
After https://prnt.sc/k2zfi7

**Comment by deakjahn** [comment]
Was this supposed to be fixed in the new 3.1.697729? It still isn't working.

**Comment by deakjahn** [comment]
Put something as simple as

      Root.Scale = 0.2; // Root is the outermost container on the page

into the `OnAppearing` of a page you navigate to, and the size will stay 1. Consequently, a following `ScaleTo()` animation has no effect whatsoever.

**Comment by samhouts** [comment]
This will probably land in 3.3. It was not included in 3.1. Thank you!

**Comment by deakjahn** [comment]
But really, why? A rather serious error, corrected, supposed to be all right now, and we're forced to wait a long time to get it? What could be the reason? This just doesn't make sense.

**Pull request merged**
