### PR TITLE
Change known colors to public properties

### PR DESCRIPTION
**Pull request by kzu**
The XAML completion only picks up public properties, not fields, 
so change the known color fields to properties.

Before:

image

After:

image

### CODE REVIEW

**Comment by StephaneDelcroix** [comment]
Thanks for this @kzu. Unfortunately this is a major breaking change that we can't take.

**Comment by kzu** [comment]
Would you care to elaborate? I'm sure I'm missing something, because unless someone is doing 
useless reflection (hardcoding to filter out for *fields only*, in addition) to get at these values, 
this should totally work without changing customer's code.

@mgoertz-msft is there an easy fix to light up the XAML completion also for static fields?

**Comment by StephaneDelcroix** [comment]
customer code will compile just fine. Already compiled code against previous version won't work without recompiling against this

**Comment by kzu** [comment]
So, given that customers explicitly opt-in to newer versions by bumping a nuget package, wouldn't that be an acceptable change for (say) a major version? i.e. do it in v4?

I find it hard to believe that we're not going to even evaluate improvements even if they are source compatible, like, ever.

**Pull request closed without merging**
