### PR TITLE
fix the calculations of the needed size of a ScollView on Android (Issue 15100)

### LINKED ISSUE #15100: [Bug] ScrollView's size does not consider all Margins and Paddings on Android
### Description

The calculation of the render size (width and height) of a ScrollView does not consider all Paddings of the ScrollView and all Margins of the child view. Affected are ScrollViews with Orientation Vertical, Horizontal or Both.
It works as expected on UWP.

### Steps to Reproduce

1. create a page with a ScrollView with a Padding > 0 as content
2. add a child view with a Margin > 0 to the ScrollView

### Expected Behavior

The ScrollView takes up the space needed by the size of its child view, the Margins of the child view and the Paddings of the ScrollView.

### Actual Behavior

The size of the ScrollView does not consider all Margins of the child view and all Paddings of the ScrollView.
It is not possible to see the complete child view or the Margin/Padding space at the end or the right side of the page.

### Basic Information

- Version with issue: 5.0.0.2337
- Last known good version: None?
- Platform Target Frameworks:
  - iOS: not able to execute
  - Android: 4.4 and 10.0
  - UWP: TargetPlatformVersion: 10.0.19041.0, TargetPlatformMinVersion: 10.0.16299.0
- Android Support Library / AndroidX Version: –
- NuGet Packages: NETStandard.Library 2.0.3, Microsoft.NETCore.UniversalWindowsPlatform 6.2.13 (UWP)
- Affected Devices: HTC device with Android 4.4 and HUAWEI device with Android 10.0

### Environment

<details><summary>Show/Hide Visual Studio info</summary>

```
Microsoft Visual Studio Community 2019
Version 16.11.9
VisualStudio.16.Release/16.11.9+32106.194
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Community

Visual C++ 2019   00435-60000-00000-AA396
Microsoft Visual C++ 2019

ASP.NET and Web Tools 2019   16.11.94.52318
ASP.NET and Web Tools 2019

ASP.NET Web Frameworks and Tools 2019   16.11.94.52318
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.11.94.52318
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   16.11.94.52318
Azure Functions and Web Jobs Tools

C# Code Analyzer   1.0
C# Code Analyzer ist eine Visual-Studio-Erweiterung zum Analysieren von C#-Code, um Dokumentationsfehler, Rechtschreibfehler, Formatierungsfehler, TODOs und Kodierungsfehler zu finden.

C# Tools   3.11.0-4.21602.3+fc14a1355c0461af5110b74b26f6478f22d26565
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Clear MEF Component Cache   1.4
Clears the Visual Studio MEF component cache to fix issues with cache corruption.

CodeMaid   12.0.300
CodeMaid is an open source Visual Studio extension to cleanup and simplify our C#, C++, F#, VB, PHP, PowerShell, R, JSON, XAML, XML, ASP, HTML, CSS, LESS, SCSS, JavaScript and TypeScript coding.

Command Explorer   1.0.9999
Provides a tool window to explorer all commands, groups and menus to help extension authors place commands/buttons in the desired location

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Essentials 2019   1.1.10
A collection of extensions that makes it much easier to write Visual Studio extensions

Extensibility Logs   1.6
Quickest & easiest way to view extensibility logs!

Extensibility Margin   1.0.9
Shows relevant information about the current file and language to extensibility authors

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Image Manifest Tools   1.0.9
Makes it easier to create and maintain .imagemanifest files for Visual Studio extension

Image Optimizer   4.0.143
Uses industry standard tools to optimize any JPEG, PNG and Gifs - including animated Gifs. Can do both lossy and lossless optimization.

KnownMonikers Explorer 2019   1.2.42
A tool window for Visual Studio extension authors to explore the KnownMonikers image collection

Microsoft Azure Tools for Visual Studio   2.9
Support for Azure Cloud Services projects

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.113+g422d40002e.RR
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.2
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   16.10.15 (552afdf)
Support for debugging Mono processes with Visual Studio.

MySQL for Visual Studio   1.2.9
Data design and management tools for MySQL. Copyright (c) 2007, 2019, Oracle and/or its affiliates. All rights reserved.

NuGet Package Manager   5.11.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Productivity Power Tools 2017/2019   16.0
Installs the individual extensions of Productivity Power Tools 2017/2019

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Razor (ASP.NET Core)   16.1.0.2122504+13c05c96ea6bdbe550bd88b0bf6cdddf8cde1725
Provides languages services for ASP.NET Core Razor.

SQL Server Data Tools   16.0.62111.25150
Microsoft SQL Server Data Tools

TypeScript Tools   16.0.30526.2002
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.11.0-4.21602.3+fc14a1355c0461af5110b74b26f6478f22d26565
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   16.11.0-beta.21514.6+b6c2c4f53ea3a08fa603ea93d6d2f808a62a21d1
Microsoft Visual F# Tools

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio Spell Check Everywhere   VSSpellCheckEverywhere
An extension that enables spell checking within any Visual Studio file editor or tool window that uses WPF text boxes.
https://GitHub.com/EWSoftware/VSSpellChecker

Visual Studio Spell Checker   VSSpellChecker
An editor extension that checks the spelling of comments, strings, and plain text as you type or interactively with tool windows.
https://GitHub.com/EWSoftware/VSSpellChecker

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Foo   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

VS Theme Colors 2019   1.0.9
Makes it easy to browse all the brushes and select the right theme color for your Visual Studio extension UI.

VSIX Synchronizer   1.0.26
Provides the ability to generate code-behind files for .vsixmanfiest and .vsct files in managed code to make the information easy to consume from the rest of the extension.

Xamarin   16.11.000.197 (d16-11@6934992)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.11.0.47 (remotes/origin/d16-11@e0d612363)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.10.5 (355b57a)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   12.0.0.3 (d16-11/f0e3c2d)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: c633fe9
    Java.Interop: xamarin/java.interop/d16-11@476bb5b
    ProGuard: Guardsquare/proguard/v7.0.1@912d149
    SQLite: xamarin/sqlite/3.35.4@85460d3
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-11@87af37b


Xamarin.iOS and Xamarin.Mac SDK   15.2.0.17 (738fde344)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
```

</details>

### Build Logs

–

### Screenshots

Android device (10.0 - API 29):
Screenshot_20220127_142147_com companyname xamarinformsscrollviewsizebug_shrinked

### Reproduction Link

https://github.com/heikow10/XamarinFormsScrollViewSizeBug

### Workaround

No.

### PR DESCRIPTION
**Pull request by heikow10**
### Description of Change ###

The calculations of the needed size of a ScollView on Android do now always consider all Margins of its child view and all Paddings of the ScrollView.

### Issues Resolved ### 

- fixes #15100 

### API Changes ###
 
 None

### Platforms Affected ### 

- Android

### Behavioral/Visual Changes ###

Now a ScrollView takes up all the space needed by the size of its child view, the Margins of the child view and the Paddings of the ScrollView.
So it is possible to see the complete child view and the complete Padding/Margin surrounding the child view.

### Before/After Screenshots ### 

Screenshot_20220127_142147_com companyname xamarinformsscrollviewsizebug_shrinked
Screenshot_20220127_144226_com companyname xamarinformsscrollviewsizebug_shrinked

### Testing Procedure ###

- Android: description can be seen in Issue15100.cs
- iOS: not able to test this
- UWP: bug is not present

### PR Checklist ###

- [ ] Targets the correct branch
- [ ] Tests are passing (or failures are unrelated)

### CODE REVIEW

**Comment by jfversluis** [comment]
@heikow10 would you be able to confirm that this is still necessary in the latest version of Xamarin.Forms? I know we did some fix(es) in the meanwhile for the `ScrollView`

**Comment by jfversluis** [comment]
Yep, this seems still needed. Verified that this issue doesn't exist in .NET MAUI.

Thanks for another great contribution @heikow10 !

**Comment by heikow10** [comment]
@jfversluis My response is a little bit late. But I can confirm that the fix was still relevant. So thanks for merging!

**Pull request merged**
