### PR TITLE
Fixed ScrollY when ItemsSource reloaded or row height changed

### LINKED ISSUE #8305: [Bug] ListView Scrolled event doesn't reset ScrollY when clearing ItemsSource
### Description
Not sure if this is a bug or what, but when you clear the listview's ItemsSource, the `Scrolled` event's coordinate doesn't reset to 0
### Steps to Reproduce
Referring to the enclosed project:
1.  Scroll down the list view and take note of the `ScrollY` value
InShot_20191030_213157753

2.  Click on the `Clear` button to clear the `ItemsSource`
3.  Click on the `Add` button to add items to the `ItemsSource`

### Expected Behavior
The `ScrollY` should be reset to 0 when `ItemsSource` is cleared

### Actual Behavior
The `ScrollY` resume from the previous value

### Basic Information

- Version with issue:
- IDE: Visual Studio 2019 Community 16.3.4
- Platform Target Frameworks: 
  - Android: 10.0.3.0 
- Nuget Packages: Xamarin Form 4.3.0.947036

### Reproduction Link
[App3.zip](https://github.com/xamarin/Xamarin.Forms/files/3789072/App3.zip)

### LINKED ISSUE #9370: [Android] Increasing ListView header height modifies ScrollY value reported by Scrolled event
### Description

On Android, when the header of a ListView changes its height after its containing page has been laid out, the Scrolled event from the ListView will report a value with and offset equal to the height change of the header.

The Scrolled event is triggered too when the header changes its height.

This doesn't happen on iOS.

### Steps to Reproduce

1. Run the sample project.
2. Click on the header button to increase its height.
3. The label at the bottom of the screen shows the ScrollY reported by the ListView.Scrolled event.

### Expected Behavior

After increasing the header height, the reported scroll from the ListView starts at 0.

### Actual Behavior

After increasing the header height, the reported scroll from the ListView starts at a diffrent point from 0.

### Basic Information

- Version with issue: 4.3.0.908675
- Last known good version: -
- IDE: Visual Studio 2019 16.2.4
- Platform Target Frameworks:
  - Android: 9.0

### Reproduction Link

[HeaderScrollBug.zip](https://github.com/xamarin/Xamarin.Forms/files/4134723/HeaderScrollBug.zip)

### PR DESCRIPTION
**Pull request by rihadavid**
**EDIT: seems like I did some bad branching here, sorry, my first PR here 😁 this was supposed to be a single file commit (Xamarin.Forms.Platform.Android/Renderers/ListViewRenderer.cs). Can someone make it right?**

Fixes two issues with ListView scroll event ScrollY value that were making it pretty unreliable and buggy.

Original code was commited in [this commit](https://github.com/xamarin/Xamarin.Forms/commit/e85fcbcb87c5455b312ac46079c1b2cda34b6fe0#diff-ef4e030a3614a0c4819c7bffc5fd7b03)

_I'm not 100% sure if there can't be any other situation when the scroll fails to be tracked (maybe some fast scroll?), for which setting the  `_contentOffset` to `0` might not be correct, but it fixes the "reloaded ItemsSource" issue, which seems to be the most common. When we are not able to track the offset at all, it's a bug anyway, so setting the offset to 0 seems good because it solves this issue at least._

### Issues Resolved ### 
- fixes #8305
- fixes #9370

### API Changes ###
None

### Platforms Affected ### 
- Android

### Behavioral/Visual Changes ###
ScrollY value in Scrolled event might sometimes be different than before, because it's now fixed.

### Testing Procedure ###
I tested the sample project in #8305 and #9370 and confirmed it is fixed. However, it might be good to test that setting the  `_contentOffset` to `0` doesn't create any side effects in different situations.

### PR Checklist ###

- [ ] Targets the correct branch
- [ ] Tests are passing (or failures are unrelated)

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/xamarin/Xamarin.Forms?pullRequest=12047) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/xamarin/Xamarin.Forms?pullRequest=12047) before we can accept your contribution.<br/><br/>:x: rihadavid [sign now](https://cla.dotnetfoundation.org/xamarin/Xamarin.Forms?pullRequest=12047)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/xamarin/Xamarin.Forms?pullRequest=12047) it.</sub>

**Comment by pictos** [comment]
Hey @rihadavid thanks for your contribution! Try to rebase your branch against the 5.0.0. If you need any help, please let me know

**Comment by rihadavid** [comment]
I did that, in the web GUI, but it didn't change the pull request. I am not friend with git commands, so it might be easier to close this and create a new PR, right?

**Comment by pictos** [comment]
@rihadavid if you don't want to try you can open a new. Be aware to create a branch based on the 5.0 branch

**Comment by rihadavid** [comment]
Closing due to bad branching, moved to #12053

**Pull request closed without merging**
