### PR TITLE
Do not use the same embedded font path in WPF

### LINKED ISSUE #11687: [Bug] Open the same WPF application with EmbeddedFont may throw IOException
### Steps to Reproduce

1. Create a WPF application that will use EmbeddedFont in startup
2. Build the project and open the application twice

### Expected Behavior

We can use the EmbeddedFont 

### Actual Behavior

Sometime the `Xamarin.Forms.Platform.WPF.EmbeddedFontLoader` will throw IOException, because it will write the same font file.

### LINKED ISSUE #11689: [Bug] WPF can not update the embedded font
### Steps to Reproduce

1. Create a WPF application that use the font1(Arial) as embedded font
2. Run the WPF application
3. Replace the font1 as font2(Constan)
1. Rerun the WPF application

### Expected Behavior

The WPF application use the old font(font1)

### Actual Behavior

The WPF application use the font2

### PR DESCRIPTION
**Pull request by lindexi**
### Description of Change ###

I use the different file path to save the embedded font in WPF to fix https://github.com/xamarin/Xamarin.Forms/issues/11687

### Issues Resolved ### 

- fixes #11687
- fixes #11689

### API Changes ###

 
 None

### Platforms Affected ### 

- WPF

### Behavioral/Visual Changes ###

None

### Before/After Screenshots ### 

Not applicable

### PR Checklist ###

- [ ] Targets the correct branch
- [ ] Tests are passing (or failures are unrelated)

### CODE REVIEW

**Comment by Clancey** [comment]
I actually wonder if it’s better to store it in an app user folder. So we don’t have to copy it out each launch. Using temp could cause it to create a ton of duplicates until the machine restarts and clears temp. Or if temp is cleared while running it will no longer exist.

**Comment by lindexi** [comment]
> I actually wonder if it’s better to store it in an app user folder. So we don’t have to copy it out each launch. Using temp could cause it to create a ton of duplicates until the machine restarts and clears temp. Or if temp is cleared while running it will no longer exist. 

But how do I know that the font of the application has changed when the application is upgraded. If my app uses the same copy every time it starts, it means that my app’s fonts will never be updated.

**Comment by Clancey** [comment]
It only copies uses the same if the name is the same. Fonts don’t usually update. If so v.1. The other option would be put it in a font folder in the user folder and delete the folder on upgrading. But that’s a bit more code.

**Comment by lindexi** [comment]
> The other option would be put it in a font folder in the user folder and delete the folder on upgrading. But that’s a bit more code.

I think it is a good idea.

But how can we know the application updated?

**Comment by lindexi** [comment]
> Fonts don’t usually update.

I don't agree with that. If developers really need to update fonts, then this design will make upgrading very difficult.

**Comment by samhouts** [comment]
@lindexi Can you please rebase this to 5.0.0 or give me access to push to your fork? Thanks!

**Comment by lindexi** [comment]
> @lindexi Can you please rebase this to 5.0.0 or give me access to push to your fork? Thanks!

Thank you. I will do it after I eat breakfast.

**Comment by lindexi** [comment]
@samhouts I have invited you to join my repo

**Comment by lindexi** [comment]
@samhouts Any update?

**Comment by jsuarezruiz** [comment]
Retarget to 5.0.0 branch.

**Comment by lindexi** [comment]
@jsuarezruiz  Any update?

**Pull request closed without merging**
