### PR TITLE
[Android] Fix Animations not animating in 4.2

### LINKED ISSUE #7255: [Bug] Animations not working
# Description

Custom animation not working on latest version of Xamarin Forms

### Steps to Reproduce

1. Use code from official Microsoft docs for custom animations
`var animation = new Animation (v => image.Scale = v, 0, 1);`
`animation.Commit (this, "SimpleAnimation", 16, 2000, Easing.Linear, (v, c) => image.Scale = 1, () => true);`
2. Trigger code from a button or somewhere else

### Expected Behavior
Animation working

### Actual Behavior
Animation hot working. The value passed to the callback function goes from 0 to 1 directly with
no intermediate values (0.1, 0.2...)

### Basic Information

- Version with issue: 4.2.0.709249
- Last known good version: 4.1.0.109244
- IDE: VS 2019
- Platform Target Frameworks: 
  - Android: 6.0
- Android Support Library Version: 28.0.0.1
- Nuget Packages:
- Affected Devices:

### LINKED ISSUE #7278: [Bug] ViewExtensions.RotateTo not working with Xamarin.Forms 4.2
### Description

ViewExtensions.RotateTo does not work anymore on version 4.2.0709249.

### Steps to Reproduce

1. Create a project where you have an Image object in XAML code. Add an image to the android project in resources/drawable and add the name of the image as source in the XAML code.
2. Add a button in page and in its event handler try RotateTo on the image object; e.g.
                await ViewExtensions.RotateTo(image, 360, 800, Easing.Linear);
		await ViewExtensions.RotateTo(image, 0, 0);
3. Run project. You can directly run the projects from attachment (1 project with version 3.4 and one with version 4.2).

### Expected Behavior

Image should be rotated.

### Actual Behavior

Image does not rotate at all, even if code is executed.

### Basic Information

- Version with issue: 4.2.0709249
- Last known good version: 3.4.0.1008975
- IDE: Visual Studio 2017 Windows
- Platform Target Frameworks: 
  - iOS: 
  - Android: Android 8.1 and 9.0
  - UWP:  
- Nuget Packages: Xamarin.Forms
- Affected Devices: all

See attachment below for project samples.
[Desktop.zip](https://github.com/xamarin/Xamarin.Forms/files/3540215/Desktop.zip)

### LINKED ISSUE #7291: [Bug] Animations are not working in 4.2.0.709249
### Description
I have some part of my apps that animates. Fading in and out and translating from A to B. They are all working in 4.1.0.673156 but after upgrading to 4.2.0.709249, animations are not working anymore. FadeTo and TranslateTo are getting called when debugging. But no animations are happening. 

### Steps to Reproduce
Use Xamarin.Forms version 4.1.0.673156 and have some small animations like FadeTo and TranslateTo then upgrade to the latest version: 4.2.0.709249

### Expected Behavior
It should animate

### Actual Behavior
It's not animating

### Basic Information

- Version with issue:
- Last known good version: 4.1.0.673156
- IDE: Visual Studio 2019 Preview 2
- Platform Target Frameworks: 
  - iOS:  _I have only tested in Android_
  - Android: 8.1
  - UWP:  _I have only tested in Android_
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:
Emulator and Xiaomi Redmi 5 Plus

### Screenshots
n/a

### Reproduction Link
n/a

### PR DESCRIPTION
**Pull request by bentmar**
fixes #7255
fixes #7291
fixes #7278

I found that if the Animation duration scale setting has never been changed in the developer settings, the scale we get will allways be 0. So instead of defaulting to 0 we default to 1. This means if i havent touched the setting it will behave as it did pre 4.2.

Also if somehow the context is null, we should default to enabling animations since this is far more "normal" than disabling animations.

### CODE REVIEW

**Comment by Nullstr1ng** [comment]
awesome! I hope this works now

**Comment by bergeling** [comment]
Wow! That bentmar dude is epic ;)

**Comment by bentmar** [comment]
@samhouts  i did this PR in the browser, I think il just create a new one on the correct branch.

**Comment by jfversluis** [comment]
Please just retarget this one. It shouldn't be that hard to do :)

**Comment by bentmar** [comment]
Aaaanyhow https://github.com/xamarin/Xamarin.Forms/pull/7298 :)

**Comment by jsuarezruiz** [comment]
Hey @bentmar, I am going to close this one now that we have https://github.com/xamarin/Xamarin.Forms/pull/7292, ¿ok?.

**Pull request closed without merging**
