### PR TITLE
[iOS] Allow observable source update while CollectionView is not visible

### LINKED ISSUE #13126: [Bug] Regression: 5.0.0-pre5 often fails to draw dynamically loaded collection view content
### Description

After updating to 5.0.0-pre5 some of my collection views don't show up the first time they are loaded.

I often employ the following pattern:

1) Have content (collection view in this case) where its IsVisible property is set to something like `IsVisible="{Binding ChatRooms.Count, Converter={StaticResource IsNotZeroConverter}}"`, where the same ObservableCollection is used as its content.
2) Have some text saying "You don't have any xxx yet, please do yyy" where its IsVisible property is true when the collection view's content count is zero.

The intent is to show an informational message if there's no content in the collection view, or else show the collection view's contents.

This has worked flawlessly until updating to pre5. What happens now is that collection views content is *never* made visible when the content has finished loading (IsVisible goes to true by the ChatRooms collection filling up after loading). The collection view's headers are shown so the view itself does get drawn, but the content inside it does not, it is drawn as if it had zero items.

If I load the page again then it displays fine, but safe to say I can't have an app where the default is to show blank content. On consecutive loads the data is cached on the client so it's instantly available to the content view.

I suspect this is caused https://github.com/xamarin/Xamarin.Forms/pull/12017, which definitely takes XF to a better direction but I think it has a bug in it.

If I remove the IsVisible=xxx on the collection view it does draw its contents properly, but this I can't do as it breaks the logic of the page. Is this some kind of race condition with drawing the items when IsVisible toggles to true?
Nevertheless this is pretty fatal as most of my pages are now empty.

Thank you.

**EDIT: please read my follow up reply**

### Basic Information

- Version with issue: XF 5.0.0-pre5
- Last known good version: XF 5.0.0-pre4
- Affected Devices: iOS. Didn't test on Android.

### Environment

<details><summary>Show/Hide Visual Studio info</summary>

```
=== Visual Studio Community 2019 for Mac (Preview) ===

Version 8.9 Preview (8.9 build 947)
Installation UUID: 2a591afe-0a7f-4f19-8e9f-143b723bd49f
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000107

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.107 (2020-02/a22ed3f094e) (64-bit)
	Package version: 612000107

=== Roslyn (Language Service) ===

3.9.0-2.20573.18+bc20ce579f9b17c9153f3f54a0690d23c482d899

=== NuGet ===

Version: 5.8.0.6860

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/5.0.100/Sdks
SDK Versions:
	5.0.100
	3.1.404
	3.1.403
MSBuild SDKs: /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	5.0.0
	3.1.10
	3.1.9

=== .NET Core 3.1 SDK ===

SDK: 3.1.404

=== Xamarin.Profiler ===

Version: 1.6.15.68
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Xamarin.Android ===

Version: 11.1.99.218 (Visual Studio Community)
Commit: xamarin-android/master/9bc0003
Android SDK: /Users/tommikiviniemi/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		None installed

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 30.0.4
SDK Build Tools Version: 30.0.2

Build Information: 
Mono: ac59637
Java.Interop: xamarin/java.interop/master@99897b2
ProGuard: Guardsquare/proguard/v7.0.0@84e8560
SQLite: xamarin/sqlite/3.32.1@1a3276b
Xamarin.Android Tools: xamarin/xamarin-android-tools/main@ab650f5

=== Microsoft OpenJDK for Mobile ===

Java SDK: /Users/tommikiviniemi/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.9.0.19
Hash: 9771026
Branch: remotes/origin/HEAD
Build date: 2020-11-21 02:03:08 UTC

=== Android Device Manager ===

Version: 16.9.0.13
Hash: bbbb387
Branch: remotes/origin/main
Build date: 2020-11-21 02:03:28 UTC

=== Apple Developer Tools ===

Xcode 12.2 (17535)
Build 12B45b

=== Xamarin.Mac ===

Xamarin.Mac not installed. Can't find /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/Version.

=== Xamarin.iOS ===

Version: 14.9.0.27 (Visual Studio Community)
Hash: f4c9327fa
Branch: main
Build date: 2020-11-19 10:57:31-0500

=== Xamarin Designer ===

Version: 16.9.0.105
Hash: f693266a2
Branch: remotes/origin/main
Build date: 2020-12-02 05:56:40 UTC

=== Build Information ===

Release ID: 809000947
Git revision: 95291d4f910c26f21816bf2bd51937ef46b99c4f
Build date: 2020-12-03 14:19:22-05
Build branch: release-8.9
Xamarin extensions: 95291d4f910c26f21816bf2bd51937ef46b99c4f

=== Operating System ===

Mac OS X 10.16.0
Darwin 20.1.0 Darwin Kernel Version 20.1.0
    Sat Oct 31 00:07:11 PDT 2020
    root:xnu-7195.50.7~2/RELEASE_X86_64 x86_64

```

</details>

### Workaround

None. Can't just have it visible at all times as it contains headers and stuff that break the layout.

### PR DESCRIPTION
**Pull request by hartez**
### Description of Change ###

Fix timing issue where CollectionView items are added to ObservableSource before CollectionView is visible, and CollectionView is later made visible via Binding.

### Issues Resolved ### 

- fixes #13126

### API Changes ###
 
None

### Platforms Affected ### 

- iOS

### Behavioral/Visual Changes ###

None

### Before/After Screenshots ### 

Not applicable

### Testing Procedure ###

Automated UI test.

### PR Checklist ###

- [ ] Targets the correct branch
- [ ] Tests are passing (or failures are unrelated)

### CODE REVIEW

**Comment by Tommigun1980** [comment]
Fantastic @hartez! Is there a package with this fix I could test?
Thank you so much!

**Comment by rmarinho** [comment]
@Tommigun1980  you can try the packages inside the artifacts folder / Nuget 

https://dev.azure.com/xamarin/public/_build/results?buildId=34759&view=artifacts&pathAsName=false&type=publishedArtifacts

**Comment by hartez** [comment]
UWP and Android test failures are utterly unrelated. iOS 14 failures are the know ListView issues.

**Comment by Tommigun1980** [comment]
> @Tommigun1980 you can try the packages inside the artifacts folder / Nuget
> 
> https://dev.azure.com/xamarin/public/_build/results?buildId=34759&view=artifacts&pathAsName=false&type=publishedArtifacts
> 
> https://dev.azure.com/xamarin/6fd3d886-57a5-4e31-8db7-52a1b47c07a8/_apis/build/builds/34759/artifacts?artifactName=nuget&api-version=6.0&%24format=zip

Thank you.

Tested with this package and the issue was unfortunately not fixed in my app.

**Comment by timvandenhof** [comment]
> > @Tommigun1980 you can try the packages inside the artifacts folder / Nuget
> > https://dev.azure.com/xamarin/public/_build/results?buildId=34759&view=artifacts&pathAsName=false&type=publishedArtifacts
> > https://dev.azure.com/xamarin/6fd3d886-57a5-4e31-8db7-52a1b47c07a8/_apis/build/builds/34759/artifacts?artifactName=nuget&api-version=6.0&%24format=zip
> 
> Thank you.
> 
> Tested with this package and the issue was unfortunately not fixed in my app.
> 
> I still have to do the following after populating the CollectionView in order for its items to become visible:
> 
> ```cs
> var items = this.myCollectionView.ItemsSource;
> this.myCollectionView.ItemsSource = null;
> this.myCollectionView.ItemsSource = items;
> ```
> 
> If I don't do the above, it will display the EmptyView. A hot reload also makes the contents draw properly.

We are experiencing the same (or similar) issue, with the same exception. We are using a view with two tabs, where each tabs has a separate view model with separate ObservableCollection. Collection view has grouped items, with sticky list header behaviour disabled.

Downloaded the above NuGet packages and updated locally to verify this issue has been resolved.
This appears not to be the case for us:
```
Foundation.MonoTouchException: Objective-C exception thrown.  Name: NSInternalInconsistencyException Reason: Invalid update: invalid number of sections.  The number of sections contained in the collection view after the update (12) must be equal to the number of sections contained in the collection view before the update (12), plus or minus the number of sections inserted or deleted (1 inserted, 0 deleted).
Native stack trace:
	0   CoreFoundation                      0x00007fff20421af6 __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00007fff20177e78 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff2042191f +[NSException raise:format:] + 0
	3   Foundation                          0x00007fff2077156a -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 191
	4   UIKitCore                           0x00007fff23d92d24 -[UICollectionView _endItemAnimationsWithInvalidationContext:tentativelyForReordering:animator:collectionViewAnimator:] + 15731
	5   UIKitCore                           0x00007fff23d8efa0 -[UICollectionView _endItemAnimationsWithInvalidationContext:tentativelyForReordering:animator:] + 60
	6   UIKitCore                           0x00007fff23d8e58e -[UICollectionView _updateSections:updateAction:] + 454
	7   UIKitCore                           0x00007fff23d8e65e -[UICollectionView insertSections:] + 64
	8   UIKit                               0x0000000108ebd4e4 -[UICollectionViewAccessibility insertSections:] + 42
	9   MyApp.iOS                   0x00000001012df489 xamarin_dyn_objc_msgSend + 217
	10  ???                                 0x0000000109a444f0 0x0 + 4456727792

  at ObjCRuntime.Runtime.ThrowNSException (System.IntPtr ns_exception) [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/14.8.0.3/src/Xamarin.iOS/ObjCRuntime/Runtime.cs:407
  at ObjCRuntime.Runtime.throw_ns_exception (System.IntPtr exc) [0x00000] in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/runtime/Delegates.generated.cs:126
  at at (wrapper native-to-managed) ObjCRuntime.Runtime.throw_ns_exception(intptr)
  at at (wrapper managed-to-native) ObjCRuntime.Messaging.void_objc_msgSend_IntPtr(intptr,intptr,intptr)
  at UIKit.UICollectionView.InsertSections (Foundation.NSIndexSet sections) [0x0001b] in /Library/Frameworks/Xamarin.iOS.framework/Versions/14.8.0.3/src/Xamarin.iOS/UIKit/UICollectionView.g.cs:537
  at Xamarin.Forms.Platform.iOS.ObservableGroupedSource+<>c__DisplayClass24_0.<Add>b__0 () [0x00000] in D:\agent\1\s\Xamarin.Forms.Platform.iOS\CollectionView\ObservableGroupedSource.cs:207
  at Xamarin.Forms.Platform.iOS.ObservableGroupedSource.Update (System.Action update) [0x00013] in D:\agent\1\s\Xamarin.Forms.Platform.iOS\CollectionView\ObservableGroupedSource.cs:358
  at Xamarin.Forms.Platform.iOS.ObservableGroupedSource.Add (System.Collections.Specialized.NotifyCollectionChangedEventArgs args) [0x00068] in D:\agent\1\s\Xamarin.Forms.Platform.iOS\CollectionView\ObservableGroupedSource.cs:207
  at Xamarin.Forms.Platform.iOS.ObservableGroupedSource.CollectionChanged (System.Collections.Specialized.NotifyCollectionChangedEventArgs args) [0x00026] in D:\agent\1\s\Xamarin.Forms.Platform.iOS\CollectionView\ObservableGroupedSource.cs:147
  at Xamarin.Forms.Platform.iOS.ObservableGroupedSource+<>c__DisplayClass19_0.<CollectionChanged>b__0 () [0x00000] in D:\agent\1\s\Xamarin.Forms.Platform.iOS\CollectionView\ObservableGroupedSource.cs:134
  at Foundation.NSAsyncActionDispatcher.Apply () [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/14.8.0.3/src/Xamarin.iOS/Foundation/NSAction.cs:152
  at at (wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
  at UIKit.UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate) [0x00005] in /Library/Frameworks/Xamarin.iOS.framework/Versions/14.8.0.3/src/Xamarin.iOS/UIKit/UIApplication.cs:86
  at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) [0x0000e] in /Library/Frameworks/Xamarin.iOS.framework/Versions/14.8.0.3/src/Xamarin.iOS/UIKit/UIApplication.cs:65
  at MyApp.iOS.Application.Main (System.String[] args) [0x00001] in /Users/MyUsername/Projects/MyApp/MyApp.iOS/Main.cs:16
```

Tried workarounds:
- Make sure update on collection took place on UI thread.
- In stead of `.Clear()`, use a while loop to remove items one by one before adding all new retrieved data.

Maybe the above information is useful for further troubleshooting.

**Comment by hartez** [comment]
@Tommigun1980 I thought it was odd that it didn't work, because I basically just copied your repro project from 13126 as my test case for this. But you're right - applying this nuget package to the repro project does not work.

However, if I apply the nuget package to your repro project and then comment out the `using (this.Models.BeginMassUpdate())` in MyViewModel.cs, it _does_ work. 

So now I need to figure out what the XamarinUniversity.Infrastructure package's "OptimizedObservableCollection" is doing that's thwarting the ObservableItemsSource.

**Comment by hartez** [comment]
@timvandenhof Your issue sounds like a different problem; your situation is crashing (not just remaining blank) and you're using a grouped collection. Can you open an issue? And if you can provide a small repro project, that would help a lot. It sounds like your problem might be a grouped version of issue #7700.

**Comment by hartez** [comment]
@Tommigun1980 Okay, looking at OptimizedObservableCollection, it looks like when the mass update object is Disposed the collection raises a Reset event. Which should just trigger a full UICollectionView.ReloadData(), but I'm guessing there's a timing/race condition we're not accounting for. I'll add another test case for a reset and see what I can find.

**Comment by Tommigun1980** [comment]
> @Tommigun1980 Okay, looking at OptimizedObservableCollection, it looks like when the mass update object is Disposed the collection raises a Reset event. Which should just trigger a full UICollectionView.ReloadData(), but I'm guessing there's a timing/race condition we're not accounting for. I'll add another test case for a reset and see what I can find.

Thank you @hartez.

Yeah the OptimizedObservableCollection suspends the updates when it is populated, and only sends out one Reset when done.
It’s effectively a “batch add”.

Thank you so much for fixing these!!

**Review by rmarinho — APPROVED** [review]

**Review by jsuarezruiz — APPROVED** [review]

**Pull request merged**
