### PR TITLE
Make SetElement of VisualElementRenderer smarter

### PR DESCRIPTION
**Pull request by adrianknight89**
### Description of Change ###

`SetElement` of `VisualElementRenderer` is not check if the new element is the same as the old. If this method is, for whatever reason, called with the same `Element`, then `OnElementChanged()` among others will be invoked.

### Bugs Fixed ###

- N/A

### PR Checklist ###

- [ ] Has tests (if omitted, state reason in description)
- [ ] Rebased on top of master at time of PR
- [ ] Changes adhere to coding standard
- [ ] Consolidate commits as makes sense

### CODE REVIEW

**Comment by StephaneDelcroix** [comment]
If there's a possibility for this to happen, it will, and it will -- randomly or not -- crash existing apps.
If this never happens, the extra check is not required.

Any way, this is a 👎 from me :(

**Comment by adrianknight89** [comment]
My line of thought was that there are 3 ways to look at this. First, as you said, it will crash apps and we will find out about the root cause. Second, it will produce incorrect results without a crash. If this happens, eventually somebody will file a bug report. Third, even if no crash or no incorrect result occurs, you still don't want to raise `OnElementChanged` or `ViewInitialized` or any of the other methods on the call stack because the element has not changed.

Sorry, yesterday I was looking at #458 and thinking about different combinations of values event args can have in `protected override void OnElementChanged(ElementChangedEventArgs<TView> e)`.

**Comment by adrianknight89** [comment]
Well, looks like this is already breaking. If you have a `ListView` with `RetainElement` and you scroll up and down, eventually `SetElement` will be called with the same view. Was this on purpose? I changed exception throws to return statements for now.

**Comment by jassmith** [comment]
This is a breaking change. Unfortunately we have decided not to take this change.

**Comment by adrianknight89** [comment]
@jassmith Can you tell me why this is a breaking change?

**Pull request closed without merging**
