### PR TITLE
Change appearance of NSTabView

### PR DESCRIPTION
**Pull request by ailen0ada**
### Description of Change ###

`Image` property of `NSSegmentedControl` requests 19x19 pixels image **strictly**. 
Control won't resize the image whether small or large.
https://developer.apple.com/library/content/documentation/UserExperience/Conceptual/OSXHIGuidelines/ToolbarIcons.html#//apple_ref/doc/uid/20000957-CH89-SW1 

This is differ from behavior and image specification of `UITabBar` in iOS.

### Bugs Fixed ###

- None

### API Changes ###

- None

### Behavioral Changes ###

Appearance of page items placed on the top of TabbedPage will change from segmented button to toolbar.

Before:
before
After:
after

### PR Checklist ###

- [ ] Has tests (if omitted, state reason in description)
- [ ] Rebased on top of master at time of PR
- [x] Changes adhere to coding standard
- [x] Consolidate commits as makes sense

### CODE REVIEW

**Comment by rmarinho** [comment]
Thanks for the PR, i changed because of issues with the NavigationPage where we need to add and manage a NSToolbar, Also i checked some applications and they most use the segmented control version.

@jassmith what do you like more ?

My idea is this is a virtual method one could override in a custom renderer if they want.

**Comment by rmarinho** [comment]
what if we resize the image ?

**Comment by ailen0ada** [comment]
Resize the image before control appears would be nice.
I'm not enough thought about NavigationPage.
Thank you for considering.

**Comment by rmarinho** [comment]
I added the resize of the icon image, it now looks fine, you can override in a custom renderer if you want.

**Pull request closed without merging**
