### PR TITLE
fix-8284 - [Bug] [Android] Cannot add/remove menuitems at runtime to contextActions of a ViewCell

### LINKED ISSUE #8284: [Bug] [Android] Cannot add/remove menuitems at runtime to contextActions of a ViewCell
### Description
It is not possible to add or remove menuitems to a viewcell at runtime. This actually only does not work for Android.

### Steps to Reproduce

1. Clone this repository: https://github.com/BrayanKhosravian/AddMenuItemAtRuntime
2. Select Android as startup project
3. long press on one of the `ViewCell` which are visible inside the `ListView` (just to verify that there is only 1 `MenuItem`)
4. Click the `"Add"`- Button to add a `MenuItem` at runtime
5. Long click the same `ViewCell`
6. result: no  `MenuItem` was added
7. try the same with remove

8. to verify the behavior check the same steps for uwp and ios (result: MenuItems get added) 

### Expected Behavior
It should be able to add/remove  `MenuItem`´s at runtime to a `ViewCell`. This works for Ios and UWP.

### Actual Behavior
It is not possible to add/remove  `MenuItem`´s at runtime to a `ViewCell`. This works for Ios and UWP.

### Basic Information

- Version with issue: v4.3.0908675 (lower versions as well)
- Last known good version: -
- IDE: Visual Studio 2019 v16.3.2
- Platform Target Frameworks: 
  - Android: 9.0  
- Android Support Library Version: 
- Nuget Packages: no external nugets
- Affected Devices: tested with Huawei p20, but this is a generic issue

### Reproduction Link

https://github.com/BrayanKhosravian/AddMenuItemAtRuntime

### Screenshots

**Not working on android**
droid_menuitem

**Working on IOS**

ios_menuitem

**Working on UWP**
uwp_menuitem

### PR DESCRIPTION
**Pull request by BrayanKhosravian**
### Description of Change ###

When the `ListView` uses a `ListViewCachingStrategy.RecycleElement` then it was not able to add or remove contextations during runtime.

When using this CachingStrategy the ViewCells are not cached in `Xamarin.Forms.TemplatedItemsList`.
The android ContextActionMenu is created when long pressing a ViewCell.
During this process we try to get the ViewCell from the `TemplatedItemsList` but when the ViewCell is not cached it is created using reflection (`Activator.CreateInstance`).

The ContextActions of the activated ViewCell are used for the MenuItems when the Android ContextActionMenu is created.
Which means that the initial ContextActions are used and not the runtime changed context actions.

I tried to code as defensive as possible.
This solution could include some design smells.
However, I want to ask for a feedback before changing too much of the codebase.

### Issues Resolved ### 
- fixes #8284

### API Changes ###

 
 None

### Platforms Affected ### 

- Android

### Behavioral/Visual Changes ###

It's possible to add ContextActions to the ViewCell/ListView during runtime on Android.

### Before/After Screenshots ### 

Before: (this is the gif from the Issue)
image

After:

### Testing Procedure ###
1.) switch to my branch
2.) start the android control galery
3.) go to issues
4.) search for 8284

5.) open all 3 pages (all pages use a different ListViewCachingStrategy)
6.) try to add and remove contextactions 

### PR Checklist ###

- [ ] Targets the correct branch
- [ ] Tests are passing (or failures are unrelated)

### CODE REVIEW

**Comment by BrayanKhosravian** [comment]
It is not possible to add a sensible ui test as the ContexActions were added to the "ContextActionList" in Xamarin.Forms before the fix.
The contextactions were just not added on the native side.

**Comment by BrayanKhosravian** [comment]
I'll check this issue as well #9998

**Comment by jsuarezruiz** [comment]
@BrayanKhosravian Could you rebase 5.0.0 to fix the current conflict?. Thanks!.

**Comment by jsuarezruiz** [comment]
Seems like the is a merge issue, there are many unnecessary modified files here. Could you take a look?. Let me know if need help.

**Comment by BrayanKhosravian** [comment]
@jsuarezruiz I do not know how exactly this happened, but I resolved it by using "git reflog".
There is still one merge issue. Not sure if I could fix it on my side. 
If I can do something about it, then please inform me.

**Comment by BrayanKhosravian** [comment]
And all the `internal` access modifiers I used is an awful solution imo.
Also I only added but not deleted code.
Someone should probably checkout this branch and have a look.
Or even implement that fix in a clean way, make a new pr and close mine.
My intent was to provide a solution which has no impact on something else but describes the issue.

**Comment by jfversluis** [comment]
Looks like this needed some work that we never got to put in. Thank you so much for your time and effort on this! If this is still something you'd like to see for .NET MAUI, make sure to open an issue there to discuss further options. Thanks!

**Pull request closed without merging**
