### PR TITLE
[UI Test] Revert 56771 test

### PR DESCRIPTION
**Pull request by samhouts**
### Description of Change ###

New test added in #2512 caused 56771 to start failing.

### PR Checklist ###

- [x] Has tests (if omitted, state reason in description)
- [x] Rebased on top of the target branch at time of PR
- [x] Changes adhere to coding standard
- [x] Consolidate commits as makes sense

### CODE REVIEW

**Comment by samhouts** [comment]
build --uitests

**Comment by rmarinho** [comment]
nop :( 

https://devdiv.visualstudio.com/DevDiv/Xamarin%20Forms/_releaseProgress?releaseId=108003&environmentId=345944&extensionId=ms.vss-test-web.test-result-in-release-environment-editor-tab&_a=release-environment-extension

**Comment by rmarinho** [comment]
build --uitests

**Comment by samhouts** [comment]
build --uitests

**Pull request merged**
