### PR TITLE
[shell] Fix show DisplayAlert

### LINKED ISSUE #5466: [Shell] Cannot navigate to a route
### Description

No matter what I try to navigate to by URI, I get this error:

```
System.NotImplementedException: The method or operation is not implemented.
  at Xamarin.Forms.Shell.GoToAsync (Xamarin.Forms.ShellNavigationState state, System.Boolean animate) [0x000d8] in D:\a\1\s\Xamarin.Forms.Core\Shell\Shell.cs:382 
  at Demos.ViewModels.DemoViewModel.HandleVisualNav (System.String page) [0x00035] in /work/TheLittleThingsPlayground/TheLittleThingsPlayground/ViewModels/DemoViewModel.cs:35 
```

In AppShell.xaml.cs I register the route like this:

```
Routing.RegisterRoute("buttons", typeof(ButtonsPage));
```

And then in the VM call the `GoToAsync` (page is "buttons"):

```
await Shell.CurrentShell.GoToAsync($"{page}", true);
```

I've also tried:

```
await Shell.CurrentShell.GoToAsync($"app://root/ShellItem14/three_six/{page}", true);
await Shell.CurrentShell.GoToAsync($"app:///ShellItem14/three_six/{page}", true);
await Shell.CurrentShell.GoToAsync($"/{page}", true);
```

Thinking I could use the relative navigation that @paymicro added in #4977 . 

### Basic Information

- Version with issue: 3.6.0.220655

### Reproduction

https://github.com/davidortinau/TheLittleThingsPlayground/blob/3.6.0/TheLittleThingsPlayground/ViewModels/DemoViewModel.cs#L35

### LINKED ISSUE #5504: [Shell] DisplayAlert crashes
### Description

In this app, go the About and tap Learn More button to launch an alert. iOS crashes.

```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidCastException: Specified cast is not valid.
  at Xamarin.Forms.Platform.iOS.Platform.PageIsChildOfPlatform (Xamarin.Forms.Page page) [0x00002] in D:\a\1\s\Xamarin.Forms.Platform.iOS\Platform.cs:317 
  at Xamarin.Forms.Platform.iOS.Platform.<.ctor>b__7_1 (Xamarin.Forms.Page sender, Xamarin.Forms.Internals.AlertArguments arguments) [0x00000] in D:\a\1\s\Xamarin.Forms.Platform.iOS\Platform.cs:51 
  at (wrapper managed-to-native) System.Reflection.MonoMethod.InternalInvoke(System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x0003b] in /Library/Frameworks/Xamarin.iOS.framework/Ver
sions/12.6.0.23/src/Xamarin.iOS/mcs/class/corlib/System.Reflection/MonoMethod.cs:305 
```

### Basic Information

- Version with issue: 3.5.x, 3.6.0 (and probably all the 4.0.x)

### Reproduction Link

[ShellAlerty.zip](https://github.com/xamarin/Xamarin.Forms/files/2948530/ShellAlerty.zip)

### PR DESCRIPTION
**Pull request by paymicro**
### Description of Change ###

Fix show alert

### Issues Resolved ### 

- fixes #5504

### API Changes ###
 
 None

### Platforms Affected ### 

- Core/XAML (all platforms)

### Before/After Screenshots ### 

Not applicable

### PR Checklist ###

- [ ] Has automated tests 
- [ ] Rebased on top of the target branch at time of PR
- [ ] Changes adhere to coding standard

### CODE REVIEW

**Comment by rmarinho** [comment]
it doesn't fix the problem but it's a start.

**Comment by PureWeen** [comment]
@paymicro I know @rmarinho said this is a start so maybe I'm not testing this quite right but when I run the store shell I'm getting an exception with all the navigations that seem to match up to the original issue

If I click on any of these
```
			AddChild(MakeButton("GoTo Games",
				async () => await Shell.CurrentShell.GoToAsync($"../IMPL_games", true)));

			AddChild(MakeButton("GoTo Home",
				async () => await Shell.CurrentShell.GoToAsync($"../IMPL_home", true)));

			AddChild(MakeButton("GoTo Books",
				async () => await Shell.CurrentShell.GoToAsync($"app:///xamstore/store/IMPL_books", true)));
```

I get an exception here

image

What should I click inside the shell store in order to test the behavior from this PR?

**Comment by rmarinho** [comment]
@paymicro let's leave just the DisplayAlert fix here? and work routing on the other PR ?

**Comment by paymicro** [comment]
@rmarinho done

**Comment by paymicro** [comment]
@PureWeen I guess so. Adding a shell broke the logic of _**parent page = page or app**_, because between the pages added Shell elements.

**Comment by PureWeen** [comment]
@paymicro yea I'm not sure how possible or relevant my comments are. Just observations. If you think they don't necessarily apply then I'd say just merge

The comments on NavigationModel was more for future proofing. Does it make since to change that case from Page to Element? or should that code be expected to crash if RealParent isn't a page?

**Pull request merged**
