### PR TITLE
Add convenience GridLength.Star

### PR DESCRIPTION
**Pull request by scastria**
### Description of Change ###

When writing UI in code, it should be as convenient as possible, like XAML.  When configuring Row and Column Definitions in a Grid, the majority of the time only (1,Auto) and (1,Star) are needed.  There is already a convenience value for (1,Auto) with GridLength.Auto, but there is not one for (1,Star) with GridLength.Star.  This adds that allowing this:

				RowDefinitions = {
					new RowDefinition { Height = GridLength.Auto },
					new RowDefinition { Height = new GridLength (1, GridUnitType.Star) },
					new RowDefinition { Height = new GridLength (1, GridUnitType.Star) }
				}

to become this:

				RowDefinitions = {
					new RowDefinition { Height = GridLength.Auto },
					new RowDefinition { Height = GridLength.Star },
					new RowDefinition { Height = GridLength.Star }
				}

### API Changes ###

Added convenience static value GridLength.Star

### PR Checklist ###

- [ ] Has tests (if omitted, state reason in description)
- [ ] Rebased on top of master at time of PR
- [ ] Changes adhere to coding standard
- [ ] Consolidate commits as makes sense

### CODE REVIEW

**Comment by StephaneDelcroix** [comment]
Changing this hides the fact that stars are meant to be multiplied by some factors. It could be misleading to some users.

**Comment by scastria** [comment]
I don't think it hides anything. it is just an additional convenience.

**Comment by scastria** [comment]
Updated docs

**Comment by adrianknight89** [comment]
great addition

**Pull request merged**
