### PR TITLE
[macOS] Fix Image Rotation issue

### LINKED ISSUE #5395: [macOs] Image Rotation issue
### Description

I'd like to animate image with **Scale up**, **Rotate** and **Scale down** animations.
Scaling works fine while rotating has wrong behavior.

### Steps to Reproduce

Xaml:
```xaml
<ContentPage>
    <AbsoluteLayout>
        <Image x:Name="logoImage" 
               source="YOUR_TEST_IMAGE_HERE.png"
               AbsoluteLayout.LayoutBounds=".5, .5, 60, 60"
               AbsoluteLayout.LayoutFlags="PositionProportional" />
    </AbsoluteLayout>
</ContentPage>
```
F# code behind (create cycling animation on appearing)
``` fsharp
    override this.OnAppearing () =
        let scaleUpAction = Action<float>(fun v -> logoImage.Scale <- v)
        let scaleDownAction = Action<float>(fun v -> logoImage.Scale <- v)
        let rotateAction = Action<float>(fun v -> logoImage.Rotation <- v)


        let parentAnim = Animation()
        parentAnim.Add(0.0, 0.5, Animation(scaleUpAction, 1., imageScale, Easing.Linear, Action UpdateDotsLabel))
        parentAnim.Add(0.5, 1., Animation(scaleDownAction, imageScale, 1., Easing.Linear, Action UpdateDotsLabel))
        parentAnim.Add(0.9, 1., Animation(rotateAction, 0.0, 360., Easing.Linear, fun _ -> logoImage.Rotation <- 0.0))
        parentAnim.Commit(logoImage, animId, dummyFrequencyRate, animLengthInMilliseconds, Easing.Linear, null, fun _ -> true)

    override this.OnDisappearing() =
        logoImage.AbortAnimation animId |> ignore
```

### Expected Behavior

Should work like on iOS:
ios_gif

### Actual Behavior

mac_gif

### Basic Information

- Version with issue: 3.5.0.169047
- Last known good version: None
- IDE: VS for Mac

### PR DESCRIPTION
**Pull request by melimion**
### Description of Change ###

Fixes anchor point for macOS.
Rotation, scaling and translation work as expected.

### Issues Resolved ### 

- fixes #5395

### API Changes ###
 
 None

### Platforms Affected ### 
- MacOS

### Behavioral/Visual Changes ###

Rotation, scaling and translation work as expected

### Before/After Screenshots ### 

Not applicable

### PR Checklist ###

- [ ] Targets the correct branch
- [ ] Tests are passing (or failures are unrelated)

### CODE REVIEW

**Comment by rmarinho** [comment]
Thank you very much @melimion

**Comment by SeRgI1982** [comment]
Hi @melimion,

Is this change is in the latest version of XF (4.3.0.908675) ?

I would like to rotate a StackLayout with two labels on macOS.

**Comment by melimion** [comment]
Hi @SeRgI1982,

Yes, it's included

**Comment by SeRgI1982** [comment]
@melimion, as you can see on linked image - it doesn't work.

[Rotation image](https://drive.google.com/open?id=14Xmfomv0nSuRjiKhnvfv-lVHXtvrrUwB)

**Comment by melimion** [comment]
Try to add button and rotate on button click, it should work.

My PR only fixed #5395 - anchor points and axis directions.
Looks like there is another issues #4277 #5393 and initial transforms have no effect.

**Pull request merged**
