### PR TITLE
[Android] Internal keyboard hide/show should handle null views

### PR DESCRIPTION
**Pull request by adrianknight89**
### Description of Change ###

Internal `HideKeyboard` throws an NRE when the view passed is null. In most cases, the view should be set, but I've run into situations where this wasn't true (extension methods do not care if the owner is null or not). The method should be able to handle null references. At the moment, I'm not sure if it should return immediately or throw a `NullReferenceException`.

The same can be said of `ShowKeyboard`.

No tests provided since the methods are internal.

### PR Checklist ###

- [ ] Has tests (if omitted, state reason in description)
- [x] Rebased on top of master at time of PR
- [x] Changes adhere to coding standard
- [ ] Consolidate commits as makes sense

### CODE REVIEW

**Comment by jassmith** [comment]
Yeah it should throw an ArgumentNullException

**Comment by kingces95** [comment]
Will change `return` to throw `ArgumentNullException` and submit new PR and close this one.

**Comment by adrianknight89** [comment]
I can update this one here. Why create a new PR?

**Comment by kingces95** [comment]
Thanks, we we're gonna do it for you but you beat us to it.

**Comment by kingces95** [comment]
:+1:

**Pull request merged**
