### PR TITLE
Notify child added to CollectionView

### LINKED ISSUE #10454: [Bug] CollectionView ChildAdded
### Description
Event ChildAdded on CollectionView don`t fire.

### Steps to Reproduce

1. CollectionView with an ItemSource from ViewModel.
2. Add ChildAdded Event
3. On ChildAdded put a DisplayAlert.

### Expected Behavior
Display alert on new item added on collectionview.
### Actual Behavior
Do notting
### Basic Information

- Version with issue: Xamarin.Forms v4.5.0.617
- IDE: Visual Studio 2019
- Platform Target Frameworks: 
  - Android: 9

- Nuget Packages: Sharpnado.Presentation.Forms 1.5.1
- Affected Devices: All

### GitHub Project

https://github.com/andrewBezerra/Xamarin_TODO 

-> MyTasksView.xaml
-> MyTasksView.xaml.cs

### PR DESCRIPTION
**Pull request by jsuarezruiz**
### Description of Change ###

Notify child added/removed to CollectionView:
- ChildAdded
- ChildRemoved

### Issues Resolved ### 

- fixes #10454 

### API Changes ###
 
 None

### Platforms Affected ### 

- Core/XAML (all platforms)
- iOS
- Android
- UWP

### Behavioral/Visual Changes ###

None

### Before/After Screenshots ### 

Not applicable

### Testing Procedure ###
Launch Core Gallery and navigate to the Issue 10454. Verify that the Label above CollectionView have text (updated using `ChildAdded` event).

### PR Checklist ###
- [ ] Targets the correct branch
- [ ] Tests are passing (or failures are unrelated)

### CODE REVIEW

**Comment by rmarinho** [comment]
Can we add a UITest ?

**Comment by rmarinho** [comment]
Seems we have a failing test on iOS

**Comment by samhouts** [comment]
@jsuarezruiz Looks like new tests are failing. Can you investigate, please? Thanks!

**Comment by jsuarezruiz** [comment]
Fixed conflicts and I have tried UITest in local:
Captura de pantalla 2020-09-17 a las 14 33 39
Waiting for the build results!

**Comment by vniehues** [comment]
This was already merged in 5.0 but it is still not working for me.
Either this fix was not successful or i fail at implementing the ChildAdded Event :D 
I have this in my ctor where _BookingStack_ is my CollectionView

`BookingStack.ChildAdded += BookingStack_ChildAdded;`

Is this still WIP somehow?

**Pull request merged**
