### PR TITLE
revert [Android] Fix BottomNavigationItemView issue with MasterDetailPage

### PR DESCRIPTION
**Pull request by PureWeen**
### Description of Change ###

#9187 broke the following UI tests on master

TabBottomIconsAndTitlesChange_google_pixel_2
AddAndRemovePages_google_pixel_2-8_1_0
BottomTabbedPageWithModalIssueTestsPopFromSecondTab_google_pixel_2-8_1_0

### Testing Procedure ###
- All Green on Master

### PR Checklist ###

- [ ] Targets the correct branch
- [ ] Tests are passing (or failures are unrelated)

### CODE REVIEW

**Comment by PureWeen** [comment]
FYI @kvpt

**Comment by kvpt** [comment]
Oh, sorry for that.

In the code you referenced
```cs
Element.Children.Count > item.ItemId
```
With autogenerated id this condition will never be true.
But what is the purpose of this condition ?

**Comment by PureWeen** [comment]
item.ItemId typically mapped to the index in the array

The following line uses the ItemId to retrieve the Page
https://github.com/xamarin/Xamarin.Forms/blob/7a52542d50797ccc69ae1d8dd84259190d96bdb4/Xamarin.Forms.Platform.Android/AppCompat/TabbedPageRenderer.cs#L875

so that check is just guarded programming but it's debatable if it makes sense to guard there.

Like if the index is wrong something is wrong and it should probably throw an exception

**Comment by kvpt** [comment]
We can't use the item id anymore but we can retrieve the item index in the menu.

```cs
				var itemIndex = -1;

				for (int i = 0; i < _bottomNavigationView.Menu.Size(); i++)
				{
					if (_bottomNavigationView.Menu.GetItem(i) == item)
					{
						itemIndex = i;
						break;
					}
				}

				if (itemIndex != -1 && _bottomNavigationView.SelectedItemId != item.ItemId && Element.Children.Count > itemIndex)
					Element.CurrentPage = Element.Children[itemIndex];
```
I tested with BottomTabbedPageTests and it seem to work.

@PureWeen What do you think about this approach, did I miss something ?

**Comment by PureWeen** [comment]
@kvpt that makes sense

What are your thoughts on this?
> I'm wondering if your change should be applied everywhere that we add menus so that all MenuItems always have a unique id?

There are a couple places where we use menu items (ToolBarItems)

It feels like we should apply this same fix to those to future proof against future possible weirdness.

Just give everyone their own ID

**Comment by kvpt** [comment]
Yes, on the pure Android side, it shouldn't break anything and protect us of some weird cases like the one in #9143. 
We just have to be sure that we don't rely on them as index, like here.

Not sure, but I think this place also need to be fixed :
https://github.com/xamarin/Xamarin.Forms/blob/efb4779bc2dd119a87e375ee4a9f7efe94abba4f/Xamarin.Forms.Platform.Android/Renderers/BottomNavigationViewUtils.cs#L77

**Pull request merged**
