### PR TITLE
Add GetNamedColor for platform specific colors

### PR DESCRIPTION
**Pull request by jfversluis**
### Description of Change ###

Adds an API to retrieve "named colors" on iOS and UWP.

For iOS you can retrieve the [system colors](https://developer.apple.com/design/human-interface-guidelines/ios/visual-design/color/#system-colors) like this, for UWP the [theme resources](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/xaml-theme-resources). From what I can tell Android has no such color system in place atm.

To gracefully fallback, not supported platforms _or_ whenever the name is not found, it will return `Color.Default`

### Issues Resolved ### 

- related to #9804

### API Changes ###

Added:
 - Color Device.GetNamedColor(string name);
 - public static class NamedPlatformColor // contains the const string names for the platforms as a reference

### Platforms Affected ### 

- Core/XAML (all platforms)
- iOS
- Android
- UWP

### Behavioral/Visual Changes ###

None

### Before/After Screenshots ### 

Not applicable

### PR Checklist ###

- [ ] Targets the correct branch
- [ ] Tests are passing (or failures are unrelated)

### CODE REVIEW

**Comment by jsuarezruiz** [comment]
In Android, could be the list of constant colors https://developer.android.com/reference/android/R.color#constants_2?

- background_dark
- background_light
- black
- darker_gray
- holo_blue_bright
- holo_blue_dark
- holo_blue_light
- holo_green_dark
- holo_green_light
- holo_orange_dark
- holo_orange_light
- holo_purple
- holo_red_dark
- holo_red_light
- primary_text_dark
- primary_text_dark_nodisable
- primary_text_light
- primary_text_lignt_nodisable
- secondary_text_dark
- secondary_text_dark_nodisable
- secondaryy_text_light
- secondary_text_lignt_nodisable
- tab_indicator_text
- tertiary_text_dark
- tertiary_text_light
- transparent
- white
- widget_edittext_dark

**Comment by jfversluis** [comment]
@jsuarezruiz yeah that might be at least something. But these are just fixed colors, right? They are not different per theme

**Comment by kefyru** [comment]
[Xamarin.Forms 4.7.0.1080]
On iOS, Device.GetNamedColor("systemBackground") returns Color.Default.

**Comment by jfversluis** [comment]
Could you please open an issue for that? And check if you can find more colors that are missing? Thanks!

**Pull request merged**
