### PR TITLE
[Core] FIX RelativeLayout layout error when only width or height specified

### LINKED ISSUE #5581: [Forms] Containers of word-wrappable Text controls don't set their height correctly with RelativeLayout.WidthConstraint
### Description

Containers of word-wrappable Text controls don't set their height correctly with RelativeLayout.WidthConstraint.

If the width of the control is controlled with StackLayout.WidthRequest the problem disappears. (see the attached example)

Happens on both Android and iOS, so i guess it is a Forms issue.

maybe related to #4950 #4875

### Steps to Reproduce

1. Use a Label (with LineBreakMode set to WordWrap) or Editor (wordwraps by default)
2. Put it inside a StackLayout with fixed RelativeLayout.WidthContraint (and no HeightContraint!)
3. If the Text is wrapped, the container height doesn't accomodate accordingly. (But eventually it does grow)

### Expected Behavior

When the Label/Editor changes in vertical size, its container should adapt in height aswell.
Container height should always be greater (or equal with no margins) than content height.

### Actual Behavior

Mostly the container height is smaller than content height!

### Basic Information

- Version with issue: 3.6.0
- Last known good version: never?
- IDE: VS 15.9.8
- Platform Target Frameworks: 
  - iOS:  12.1.4
  - Android: 29

### Screenshots

Container has green background, content has red background, thus the red rectangles should always be surrounded by a green "border".
Size info is referencing the left Label and its container StackLayout.

nowrap
wrap_incorrect1
wrap_incorrect2
wrap_incorrect3
wrap_incorrect4

### Reproduction Link

[FormsTest.zip](https://github.com/xamarin/Xamarin.Forms/files/2971446/FormsTest.zip)

keep clicking the grow button!

### PR DESCRIPTION
**Pull request by kicsiede**
### Description of Change ###

This change lets RelativeLayout to size width and height independently. For example if height constraint is unset, it will adapt to content height automatically. This is neccessary when constraining width for label with text wrapping enabled. (See screenshots in #5581)

### Issues Resolved ### 

- fixes #5581

 None

### Platforms Affected ### 

- Core/XAML (all platforms)

### Before/After Screenshots ### 

no wrap:
nowrap

incorrect:

wrap_incorrect1
wrap_incorrect2
wrap_incorrect3
wrap_incorrect4

correct:

wrap_correct1
wrap_correct2
wrap_correct3
wrap_correct4

### Testing Procedure ###

see #5581

### PR Checklist ###

- [ ] Has automated tests
- [x] Rebased on top of the target branch at time of PR
- [x] Changes adhere to coding standard

### CODE REVIEW

**Comment by kicsiede** [comment]
@StephaneDelcroix please review this fix, as this bug causes really ugly gui :(

**Comment by kingces95** [comment]
I'm running into tall type of tooling issues evaluating this PR. Could you refresh and attach your reproduction and include a solution file? I don't think its you but that would help eliminate variables...

**Comment by kicsiede** [comment]
@kingces95 
[FormsTest.zip](https://github.com/xamarin/Xamarin.Forms/files/3062900/FormsTest.zip)

**Comment by kingces95** [comment]
WOOT! Got that to work.

**Pull request merged**
