### PR TITLE
[Enhancement] [Android][iOS] Font change of Navigation and Tabbed Page

### PR DESCRIPTION
**Pull request by dimonovdd**
### Description of Change ###

Added the FontFamily, FontSize and FontAttributes change of NavigationPage and TabbedPage 

### API Changes ###
Added:
1) NavigationPage and TabbedPage 
    - string BarFontFamily
    - double BarFontSize
    - FontAttributes BarFontAttributes

2) Xamarin.Forms.BarElement
    - BindableProperty BarFontFamilyProperty 
    - BindableProperty BarFontSizeProperty
    - BindableProperty BarFontAttributesProperty

3) Xamarin.Forms.Platform.Android.TextViewExtensions
    - void SetFont(this TextView textView, Xamarin.Forms.Font font)
    - void SetFont(this TextView textView, Typeface typeFace, float sizeSp)

4) Xamarin.Forms.Platform.Android.ViewGroupExtensions
    - void SetChildrenTextViewsFont(this AViewGroup self, Font font)

And improved NavigationPage and TabbedPage renderers

### Platforms Affected ### 

- Core/XAML
- iOS
- Android

### Video ### 
[Test video on yandex disk](https://yadi.sk/i/ows0KfEAKfGEtw)
***
This is the way I think it should be. If there are any remarks or suggestions, I'm open to discussing

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/xamarin/Xamarin.Forms?pullRequest=11717) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/xamarin/Xamarin.Forms?pullRequest=11717) before we can accept your contribution.<br/><br/>:x: dimonovdd [sign now](https://cla.dotnetfoundation.org/xamarin/Xamarin.Forms?pullRequest=11717)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/xamarin/Xamarin.Forms?pullRequest=11717) it.</sub>

**Comment by dimonovdd** [comment]
@samhouts Hi, is the merge request ok? Maybe I should make some changes?

**Comment by dimonovdd** [comment]
@rmarinho @jsuarezruiz @StephaneDelcroix 
Do you have any thoughts on this pull request?

**Comment by jfversluis** [comment]
Oh man this is awesome! Unfortunately this is too big to risk any regressions and things in Forms now :( so sorry about that! Make sure to check if this is something we already have on the roadmap for .NET MAUI and if not, open an issue with the suggestion so we can talk about it. I've also labeled it so it should come up for evaluation for .NET MAUI that was as well.

Thank you so much for your time and effort on this! I hope you know we really appreciate it!

**Comment by dimonovdd** [comment]
@jfversluis 😭

**Pull request closed without merging**
