### PR TITLE
Add Orange color to Color

### PR DESCRIPTION
**Pull request by rookiejava**
### Description of Change ###

Add Orange color to Xamarin.Forms.Color.

### Bugs Fixed ###

None

### API Changes ###

Added:
 - Color.Orange // The color that is represented by the RGB value #FFA500. (255, 165, 0)

### Behavioral Changes ###

None

### PR Checklist ###

- [x] Has tests (if omitted, state reason in description)
- [x] Rebased on top of master at time of PR
- [x] Changes adhere to coding standard
- [x] Consolidate commits as makes sense

### CODE REVIEW

**Comment by StephaneDelcroix** [comment]
I'm expecting to see a veeeeery long discussion on this PR. Should I start ?

**Comment by StephaneDelcroix** [comment]
So I start...

FFA500 is yellowish. According to wikipedia, Orange is FF7F00. and this color profiled monitor tend to agree...

There's also a ColorTypeConverter that speeds up xaml parsing of Colors. Orange should be in there too.
Also, it misses the documentation. I'd define it as:

> ORANGE. This is Orange, according to me. Some says it's a bit yellowish, but who cares?

**Comment by tpetrina** [comment]
Well, this is Orange color that we already have in .NET IIRC.

**Comment by ghuntley** [comment]
:popcorn:

**Comment by rookiejava** [comment]
@StephaneDelcroix Thank you for your time and effort to this matter. Wikipedia uses a normalized set of color coordinate systems in the color Information Box. It means that color coordinate ranges are a matter of designer choice and there is no universal standard range for many color spaces (though some ranges may be prevalent). 

In this PR, I referred to Web color table. (All predefined color values in Xamarin.Forms are exactly same with Web color table.)
- https://en.wikipedia.org/wiki/Web_colors#Color_table
- http://www.w3schools.com/colors/colors_hex.asp

What is your reference color coordinate system? If you just want to follow Wikipedia, please make new PR to fix current Color.Lime value to #BFFF00 from #00FF00. - https://en.wikipedia.org/wiki/Lime_(color)
Also, please don't forget modify documentation as below: 

> LIME. This is Lime, according to me. Some says it's a bit reddish, but who cares?

I also thank you for your comment about ColorTypeConverter. I've updated patch.

**Comment by adrianknight89** [comment]
Can the colors be aligned with .NET Framework colors? In this case, #FFA500 is the correct value.

https://msdn.microsoft.com/en-us/library/system.drawing.color.orange(v=vs.110).aspx

Since Xamarin is very deeply integrated with Microsoft, as a programmer, I'd expect .NET colors.

**Comment by rookiejava** [comment]
@adrianknight89 Thanks for your comment :-).

**Comment by StephaneDelcroix** [comment]
thanks for the fix in the converter, and the doc addition
👍

**Comment by rmarinho** [comment]
Hi, can you rebase in a single commit ?

Thanks

**Comment by StephaneDelcroix** [comment]
no need

**Comment by StephaneDelcroix** [comment]
this has been merged. Thanks for this @rookiejava. Sorry for the trolling, that was too tempting, I wasn't able to resists 😃

**Pull request merged**
