### PR TITLE
[iOS] Fix crash when going from empty to having items

### PR DESCRIPTION
**Pull request by hartez**
### Description of Change ###

Attempting to change the ItemsSource for the CollectionView on iOS from an empty source to a source with items causes a crash.

This change prevents the crash.

### Issues Resolved ### 

None

### API Changes ###
 
 None

### Platforms Affected ### 

- iOS

### Behavioral/Visual Changes ###

None

### Before/After Screenshots ### 

Not applicable

### PR Checklist ###

- [x] Has automated tests 
- [x] Rebased on top of the target branch at time of PR
- [x] Changes adhere to coding standard

### CODE REVIEW

**Comment by hartez** [comment]
UI test failure is unrelated to these changes.

**Comment by wickedw** [comment]
Hi @hartez, 

When Is this expected in the nightly build? (sorry I am unaware of the dev process, I just have this crash and tried latest nightly and did not fix).

Thanks for your help
Matt

**Comment by wickedw** [comment]
Hi,

FYI, I do not know if directly related to this code change, but code that was working (has nested collection views), now immediately crashes with this in nightly 4.0.1.268567-nightly -

I did not get round to testing original crash.

 *** Assertion failure in -[UICollectionView _endItemAnimationsWithInvalidationContext:tentativelyForReordering:animator:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKitCore_Sim/UIKit-3698.93.8/UICollectionView.m:6120
dynamic_cast error 2: One or more of the following type_info's  has hidden visibility.  They should all have public visibility.   N10__cxxabiv116__shim_type_infoE, id, N10__cxxabiv117__pbase_type_infoE.
dynamic_cast error 2: One or more of the following type_info's  has hidden visibility.  They should all have public visibility.   N10__cxxabiv116__shim_type_infoE, id, N10__cxxabiv117__pbase_type_infoE.
dynamic_cast error 2: One or more of the following type_info's  has hidden visibility.  They should all have public visibility.   N10__cxxabiv116__shim_type_infoE, id, N10__cxxabiv117__pbase_type_infoE.

Xamarin.iOS: Received unhandled ObjectiveC exception: NSInternalInconsistencyException Invalid update: invalid number of items in section 0.  The number of items contained in an existing section after the update (1) must be equal to the number of items contained in that section before the update (1), plus or minus the number of items inserted or deleted from that section (1 inserted, 0 deleted) and plus or minus the number of items moved into or out of that section (0 moved in, 0 moved out).

Best
Matt

**Comment by rros** [comment]
Is a workaround available for this issue on the latest 3.6.0 release?

**Comment by hartez** [comment]
@wickedw I think you might be seeing the same issue as reported here: https://github.com/xamarin/Xamarin.Forms/issues/5677

**Comment by jsantosh14** [comment]
Any plans to release this in 3.6 release?

**Comment by hartez** [comment]
No, but it should be in the next pre-release and the next stable.

**Comment by Cheesebaron** [comment]
I don't think this issue is isolated to Xamarin.Forms. It is a general Xamarin.iOS issue. I have the exact same problem with UITableView in a native Xamarin.iOS app. No Forms involved.

**Comment by wickedw** [comment]
@hartez will give this a go in pre8 and feedback, thanks.

**Comment by matteopiccioni** [comment]
I have this error on iOS with pre8.
Using pre7 I had not this issues.

Thanks

**Comment by Rajbandi** [comment]
I have same issue after upgrading from xf 4.0 pre7 to pre8. I have an empty list and updating with new items.

**Comment by matteopiccioni** [comment]
Unfortunately I have the same issues with the latest xf 4.0 pre9

**Comment by pedro89soares** [comment]
> Unfortunately I have the same issues with the latest xf 4.0 pre9

everything works fine on Android but it crashes on iOS.

**Comment by wickedw** [comment]
FYI, Just tried with pre9 - 

*** Assertion failure in -[UICollectionView _endItemAnimationsWithInvalidationContext:tentativelyForReordering:animator:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKitCore_Sim/UIKit-3698.93.8/UICollectionView.m:6120
 dynamic_cast error 2: One or more of the following type_info's  has hidden visibility.  They should all have public visibility.   N10__cxxabiv116__shim_type_infoE, id, N10__cxxabiv117__pbase_type_infoE.
dynamic_cast error 2: One or more of the following type_info's  has hidden visibility.  They should all have public visibility.   N10__cxxabiv116__shim_type_infoE, id, N10__cxxabiv117__pbase_type_infoE.
dynamic_cast error 2: One or more of the following type_info's  has hidden visibility.  They should all have public visibility.   N10__cxxabiv116__shim_type_infoE, id, N10__cxxabiv117__pbase_type_infoE.
Xamarin.iOS: Received unhandled ObjectiveC exception: NSInternalInconsistencyException Invalid update: invalid number of items in section 0.  The number of items contained in an existing section after the update (1) must be equal to the number of items contained in that section before the update (1), plus or minus the number of items inserted or deleted from that section (1 inserted, 0 deleted) and plus or minus the number of items moved into or out of that section (0 moved in, 0 moved out).

If I remove my nested CollectionView from the outer CollectionView, it loads.

This page was working in <Version>4.0.0.232914-pre6</Version>

Is a nested CollectionView part of the test series?

Thanks for your help

**Comment by wickedw** [comment]
I have new various crashes with CollectionView in 4.2.0.673161-pre

- One where using .Add(new item) crashes (and have to init entire collection in one go to workaround).
- One "seemingly" basic init with an empty object

If I have

 <CollectionView.ItemsLayout>
                <GridItemsLayout Orientation="Horizontal" Span="1" />
            </CollectionView.ItemsLayout>

(versus vertical)

I get 

2019-08-20 10:15:14.421626+0100 RewardTime.iOS[66163:1994370] *** Assertion failure in -[UICollectionViewData numberOfItemsInSection:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKitCore_Sim/UIKit-3698.140/UICollectionViewData.m:618
2019-08-20 10:15:14.422316+0100 RewardTime.iOS[66163:1994370] dynamic_cast error 2: One or more of the following type_info's  has hidden visibility.  They should all have public visibility.   N10__cxxabiv116__shim_type_infoE, id, N10__cxxabiv117__pbase_type_infoE.
2019-08-20 10:15:14.422417+0100 RewardTime.iOS[66163:1994370] dynamic_cast error 2: One or more of the following type_info's  has hidden visibility.  They should all have public visibility.   N10__cxxabiv116__shim_type_infoE, id, N10__cxxabiv117__pbase_type_infoE.
2019-08-20 10:15:14.422499+0100 RewardTime.iOS[66163:1994370] dynamic_cast error 2: One or more of the following type_info's  has hidden visibility.  They should all have public visibility.   N10__cxxabiv116__shim_type_infoE, id, N10__cxxabiv117__pbase_type_infoE.
2019-08-20 10:15:14.424341+0100 RewardTime.iOS[66163:1994370] Xamarin.iOS: Received unhandled ObjectiveC exception: NSInternalInconsistencyException request for number of items in section 0 when there are only 0 sections in the collection view
2019-08-20 10:15:18.318931+0100 RewardTime.iOS[66163:1994370] [AppCenterCrashes] ERROR: +[MSWrapperLogger MSWrapperLog:tag:level:]/10 Unhandled Exception:
Foundation.MonoTouchException: Objective-C exception thrown.  Name: NSInternalInconsistencyException Reason: request for number of items in section 0 when there are only 0 sections in the collection view
Native stack trace:
	0   CoreFoundation                      0x0000000114a568db __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x00000001159ddac5 objc_exception_throw + 48
	2   CoreFoundation                      0x0000000114a56662 +[NSException raise:format:arguments:] + 98
	3   Foundation                          0x0000000112c5276b -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 194
	4   UIKitCore                           0x000000011b650c76 -[UICollectionViewData numberOfItemsInSection:] + 237
	5   RewardTime.iOS                      0x0000000107767259 xamarin_dyn_objc_msgSend + 217
	6   ???                                 0x000000013fa5e393 0x0 + 5362803603

Frustrating.

**Comment by kumarc-123** [comment]
Could someone please tell us whether this issue is closed or not? I am still facing this issue when loading the Observable Collection on iOS versions below 13, i.e., in iOS 12 I am getting the same crash.

**Comment by hartez** [comment]
@kumarc-123 This issue is closed. If you are still experiencing a similar error, please open a new issue.

**Pull request merged**
