### PR TITLE
Move layout change resolution calls up to VisualElementRenderer

### LINKED ISSUE #13126: [Bug] Regression: 5.0.0-pre5 often fails to draw dynamically loaded collection view content
### Description

After updating to 5.0.0-pre5 some of my collection views don't show up the first time they are loaded.

I often employ the following pattern:

1) Have content (collection view in this case) where its IsVisible property is set to something like `IsVisible="{Binding ChatRooms.Count, Converter={StaticResource IsNotZeroConverter}}"`, where the same ObservableCollection is used as its content.
2) Have some text saying "You don't have any xxx yet, please do yyy" where its IsVisible property is true when the collection view's content count is zero.

The intent is to show an informational message if there's no content in the collection view, or else show the collection view's contents.

This has worked flawlessly until updating to pre5. What happens now is that collection views content is *never* made visible when the content has finished loading (IsVisible goes to true by the ChatRooms collection filling up after loading). The collection view's headers are shown so the view itself does get drawn, but the content inside it does not, it is drawn as if it had zero items.

If I load the page again then it displays fine, but safe to say I can't have an app where the default is to show blank content. On consecutive loads the data is cached on the client so it's instantly available to the content view.

I suspect this is caused https://github.com/xamarin/Xamarin.Forms/pull/12017, which definitely takes XF to a better direction but I think it has a bug in it.

If I remove the IsVisible=xxx on the collection view it does draw its contents properly, but this I can't do as it breaks the logic of the page. Is this some kind of race condition with drawing the items when IsVisible toggles to true?
Nevertheless this is pretty fatal as most of my pages are now empty.

Thank you.

**EDIT: please read my follow up reply**

### Basic Information

- Version with issue: XF 5.0.0-pre5
- Last known good version: XF 5.0.0-pre4
- Affected Devices: iOS. Didn't test on Android.

### Environment

<details><summary>Show/Hide Visual Studio info</summary>

```
=== Visual Studio Community 2019 for Mac (Preview) ===

Version 8.9 Preview (8.9 build 947)
Installation UUID: 2a591afe-0a7f-4f19-8e9f-143b723bd49f
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000107

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.107 (2020-02/a22ed3f094e) (64-bit)
	Package version: 612000107

=== Roslyn (Language Service) ===

3.9.0-2.20573.18+bc20ce579f9b17c9153f3f54a0690d23c482d899

=== NuGet ===

Version: 5.8.0.6860

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/5.0.100/Sdks
SDK Versions:
	5.0.100
	3.1.404
	3.1.403
MSBuild SDKs: /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	5.0.0
	3.1.10
	3.1.9

=== .NET Core 3.1 SDK ===

SDK: 3.1.404

=== Xamarin.Profiler ===

Version: 1.6.15.68
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Xamarin.Android ===

Version: 11.1.99.218 (Visual Studio Community)
Commit: xamarin-android/master/9bc0003
Android SDK: /Users/tommikiviniemi/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		None installed

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 30.0.4
SDK Build Tools Version: 30.0.2

Build Information: 
Mono: ac59637
Java.Interop: xamarin/java.interop/master@99897b2
ProGuard: Guardsquare/proguard/v7.0.0@84e8560
SQLite: xamarin/sqlite/3.32.1@1a3276b
Xamarin.Android Tools: xamarin/xamarin-android-tools/main@ab650f5

=== Microsoft OpenJDK for Mobile ===

Java SDK: /Users/tommikiviniemi/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.9.0.19
Hash: 9771026
Branch: remotes/origin/HEAD
Build date: 2020-11-21 02:03:08 UTC

=== Android Device Manager ===

Version: 16.9.0.13
Hash: bbbb387
Branch: remotes/origin/main
Build date: 2020-11-21 02:03:28 UTC

=== Apple Developer Tools ===

Xcode 12.2 (17535)
Build 12B45b

=== Xamarin.Mac ===

Xamarin.Mac not installed. Can't find /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/Version.

=== Xamarin.iOS ===

Version: 14.9.0.27 (Visual Studio Community)
Hash: f4c9327fa
Branch: main
Build date: 2020-11-19 10:57:31-0500

=== Xamarin Designer ===

Version: 16.9.0.105
Hash: f693266a2
Branch: remotes/origin/main
Build date: 2020-12-02 05:56:40 UTC

=== Build Information ===

Release ID: 809000947
Git revision: 95291d4f910c26f21816bf2bd51937ef46b99c4f
Build date: 2020-12-03 14:19:22-05
Build branch: release-8.9
Xamarin extensions: 95291d4f910c26f21816bf2bd51937ef46b99c4f

=== Operating System ===

Mac OS X 10.16.0
Darwin 20.1.0 Darwin Kernel Version 20.1.0
    Sat Oct 31 00:07:11 PDT 2020
    root:xnu-7195.50.7~2/RELEASE_X86_64 x86_64

```

</details>

### Workaround

None. Can't just have it visible at all times as it contains headers and stuff that break the layout.

### LINKED ISSUE #13418: [Bug] Issue changing visibility of any control when using ViewRenderer on 5.0
### Description
I faced an issue where hidden controls that becomes visible as response to a user action does not became visible anymore after updating from 4.8 to 5.0.0.1539-pre2 and above.
If I remove my custom ViewRenderers for iOS and Androids the bug is gone.

### Steps to Reproduce

1. Write own ViewRenderer for any purpose on Android and iOS.
2. Have a control that changes his visibility after page loads.
3. Control did not come visible when you set IsVisible property to True.

### Expected Behavior
Changing IsVisible to True makes control visible.

### Actual Behavior
Changing IsVisible to True don't make control visible.

### Basic Information

- Version with issue: 5.0.0.1539-pre2 and above
- Last known good version: 5.0.0.1487-pre1
- Platform Target Frameworks:
  - iOS:  14
  - Android: 11
- Affected Devices: Emulator and physical devices

### Reproduction Link
[https://github.com/HeikkiDev/XF5.0ChangeVisibilityBug](https://github.com/HeikkiDev/XF5.0ChangeVisibilityBug)

### Workaround
Remove my custom ViewRenderers.

### LINKED ISSUE #13492: [Bug] [UWP] LayoutChildren method is not called in custom control after upgrade Xamarin.Forms 5.0
### Description

I have created a custom control which is extended from ContentView in Xamarin.Forms. I have layout the **Content** for some scenario using LayoutChildren override method in Forms. This is working fine up to XF version 4.8. After upgrade to Xamarin.Forms 5.0, this LayouChildren override method is not called and Content also not displayed. I suspect that in Xamarin.Forms 5.0, layout process is not performed for Content.

**Note:** If i add the same custom control within Grid, custom control's Content is displayed. 

1. I simply created a small custom control to reproduce my issue. Created custom control in Xamarin.Forms

```
public class CustomContentView: ContentView
    {
        public CustomContentView()
        {
           
        }

        protected override SizeRequest OnMeasure(double widthConstraint, double heightConstraint)
        {
            return base.OnMeasure(widthConstraint, heightConstraint);
        }
        protected override void LayoutChildren(double x, double y, double width, double height)
        {
            base.LayoutChildren(x, y, width, height);
        }
    }
```

2. Created custom renderer for this Forms control in UWP renderer project. Native UWP control is extended from ContentPresenter. I have converted Forms content to native and set to content control's content. Then assigned content control to Native control. 
3. 
**Native control**

```
  public class CustomView : ContentPresenter
    {
        public CustomView()
        {
        }
    }
```

**Renderer class**

```
public class CustomRenderer : VisualElementRenderer<CustomControl.CustomContentView, CustomView>
    {
        private CustomView customView;
        public CustomRenderer()
        {
            this.AutoPackage = false;
        }
        protected override void OnElementChanged(ElementChangedEventArgs<CustomContentView> e)
        {
            if (e.NewElement == null)
            {
                return;
            }

            this.customView = new CustomView();
            this.customView.DataContext = this.Element.BindingContext;
            this.SetNativeControl(this.customView);

            if (Element.Content != null)
            {
                var renderer = Element.Content.GetOrCreateRenderer();
                var contentControl = new ContentControl();

                contentControl.Content = renderer.ContainerElement;
                this.customView.Content = contentControl;
            }
            base.OnElementChanged(e);
        }
    }
```

### Steps to Reproduce

1. Run the attached sample (Sample link given in Reproduction Link)
2. Added Button control as content in my custom control. But it is not displayed. 

### Expected Behavior

Content (Button) should be displayed

### Actual Behavior

Display with blank page.

### Basic Information

 - UWP:  All SDK version 
- NuGet Packages: Xamarin.Forms: 5.0.0.1905

### Reproduction Link

Sample link with custom control: https://github.com/bharathirajauk/MySamples/blob/master/CustomControl_XF5.0.zip?raw=true

### LINKED ISSUE #13551: [Bug] [iOS] CollectionView does not display items if `IsVisible` modified via a binding/trigger
### Description

Bind CollectionView to an item source, also bind `IsVisible` to an initially false value. When the binding for `IsVisible` changes to `true` the CollectionView does not display its items. (similar to #13203) 

### Steps to Reproduce

```xml
    <Grid RowDefinitions="*,*,*">
        <!--  Works 👍 (EDIT: doesn't work when IsVisible="false"  -->
        <CollectionView
            x:Name="ItemsView1"
            IsVisible="True" <!-- EDIT: this should be 'false' -->
            ItemsSource="{Binding Items}">
            <CollectionView.ItemTemplate>
                <DataTemplate>
                    <Frame>
                        <Label Text="{Binding}" />
                    </Frame>
                </DataTemplate>
            </CollectionView.ItemTemplate>
        </CollectionView>

        <!--  Does not work 👎  -->
        <CollectionView
            x:Name="ItemsView2"
            Grid.Row="1"
            IsVisible="{Binding Items.Count, Converter={StaticResource IntToBoolConverter}}"
            ItemsSource="{Binding Items}">
            <CollectionView.ItemTemplate>
                <DataTemplate>
                    <Frame>
                        <Label Text="{Binding}" />
                    </Frame>
                </DataTemplate>
            </CollectionView.ItemTemplate>
        </CollectionView>

        <!--  Does not work 👎  -->
        <CollectionView
            x:Name="ItemsView3"
            Grid.Row="2"
            ItemsSource="{Binding Items}">
            <View.Triggers>
                <DataTrigger
                    Binding="{Binding Items.Count}"
                    TargetType="View"
                    Value="0">
                    <Setter Property="IsVisible" Value="False" />
                </DataTrigger>
            </View.Triggers>
            <CollectionView.ItemTemplate>
                <DataTemplate>
                    <Frame>
                        <Label Text="{Binding}" />
                    </Frame>
                </DataTemplate>
            </CollectionView.ItemTemplate>
        </CollectionView>
    </Grid>
```

### Expected Behavior

Should display items after visibility is changed to `true`. 

### Actual Behavior

No items displayed.

### Basic Information

- Version with issue: 4.8.0.1821
- Last known good version: 4.8.0.1687
- Platform Target Frameworks: 
  - iOS:  14.2

### Workaround

N/A (probably can toggle via code behind)

### Repro link
Repeo: [Issue13203v2.zip](https://github.com/xamarin/Xamarin.Forms/files/5876344/Issue13203v2.zip)

### PR DESCRIPTION
**Pull request by hartez**
### Description of Change ###

The change to on-demand layout resolution in 5.0.0-pre2 moved the layout resolution to the layout renderers. Unfortunately, this meant that some ContentView uses (13492) and any custom renderer which replaced the layout renderers (13418) would not update their layout changes properly. 

These changes move the layout resolution call to the base VisualElementRenderer class on each platform; this way, they encompass content views and any custom layout renderers. 

### Issues Resolved ### 

- fixes #13418
- fixes #13492
- fixes #13551 
- fixes #13126

### API Changes ###
 
None

### Platforms Affected ### 

- iOS
- Android
- UWP

### Behavioral/Visual Changes ###

None

### Before/After Screenshots ### 

Not applicable

### Testing Procedure ###

Unfortunately, this one is hard to write a test for without breaking all of Control Gallery. Best we can do is load up the repro projects from #13418 and #13492, apply the NuGet package from this PR, and verify that the problems are fixed.

For #13551 there is an automated UI test.

### PR Checklist ###

- [ ] Targets the correct branch
- [ ] Tests are passing (or failures are unrelated)

### CODE REVIEW

**Review by PureWeen — CHANGES_REQUESTED** [review]
Same UITest across all iOS runs failed

https://dev.azure.com/xamarin/public/_releaseProgress?releaseId=2840&_a=release-environment-extension&environmentId=136487&extensionId=ms.vss-test-web.test-result-in-release-environment-editor-tab

**Comment by hartez** [comment]
> Same UITest across all iOS runs failed
> 
> https://dev.azure.com/xamarin/public/_releaseProgress?releaseId=2840&_a=release-environment-extension&environmentId=136487&extensionId=ms.vss-test-web.test-result-in-release-environment-editor-tab

Yeah, looks like this is somehow busting the default (text-only) cells. Looking into it.

**Comment by hartez** [comment]
Okay, all relevant tests are passing. iOS 12 lane just isn't running, the iOS 14 failures are the known ListView issues, and the Android stuff is just flaky tests.

**Review by rmarinho — APPROVED** [review]
Tested the nuget on the repos, and works as expected. I can see the controls now.

**Review by PureWeen — APPROVED** [review]

**Pull request merged**
