### PR TITLE
Added DependencyService.RegisterSingleton

### PR DESCRIPTION
**Pull request by Soundman32**
### Description of Change ###

Added a singleton registration function to the dependecy service

### API Changes ###
Added:
 - DependencyService.RegisterSingleton(new NewClass());

### Platforms Affected ### 
- Core/XAML (all platforms)

### Behavioral/Visual Changes ###
None

### Before/After Screenshots ### 
Not applicable

### PR Checklist ###

- [X] Has automated tests 
- [ ] Rebased on top of the target branch at time of PR
- [X] Changes adhere to coding standard

### CODE REVIEW

**Comment by Soundman32** [comment]
> 👎 DependencyServices are GlobalInstance by default, so this API doesn't do much. or am I missing something ?

I might be wrong, but there doesn't seem to be a way to set the GlobalInstance directly.  Hence this change.  There are quite a few nuget packages that use the `MyThing.Current` way to access it, and I'd like to be able to mock them out in unit tests, but without this method, I can't would out how.

**Comment by AndreiMisiukevich** [comment]
RegisterSingleton<T> is not enough
RegisterSingleton<TService, TInterface> should be added as well

**Comment by jsuarezruiz** [comment]
@Soundman32 Could you review the conflict?.

**Comment by Tommigun1980** [comment]
> RegisterSingleton is not enough
> RegisterSingleton<TService, TInterface> should be added as well

Yeah that'd be great. If you need that functionality in the meantime, I made this NuGet that allows DependencyService to return multiple implementations for an interface:
https://github.com/Tommigun1980/Xamarin.Forms.MultiDependencyResolver

**Pull request merged**
