### PR TITLE
fix 15378

### LINKED ISSUE #15378: [Bug] TapGestureRecognizer Tapped event gets triggered incorrectly on Spans when text in the span is multiline
### Description
If a span in the configuration below happens to break a line, then its TapGestureRecognizer will get triggered incorrectly when I am tapping on other spans. The exact issue is easier to explain with the aid of the screenshot at the end of the post.

### Steps to Reproduce

1. AboutPage.xaml: 

```
<ScrollView>
    <StackLayout Padding="10">
        <Label FontSize="Large">
            <Label.FormattedText>
                <FormattedString x:Name="FormattedString">
                </FormattedString>
             </Label.FormattedText>
          </Label>
      </StackLayout>
</ScrollView>
```
2. AboutPage.xaml.cs:
```
public partial class AboutPage : ContentPage
    {
        private static string text = @"abcdefghijklmnopabcdefghijklmnopabcdefghijklmnopabcdefghijklmnopabcdefghijklmnopabcdefghijklmnopabcdefghijklmnopabcdefghijklmnopabcdefghijklmnopabcdefghijklmnopabcdefghijklmnopabcdefghijklmnop";

        public AboutPage()
        {
            InitializeComponent();

            var charGroupLength = 3;
            var colour = 0;

            for (var i = 0; i < text.Length - charGroupLength; i += charGroupLength)
            {
                AddSpanForChars(text.Substring(i, charGroupLength), colour);
                colour++;
            }
        }

        private void AddSpanForChars(string word, int colour)
        {
            var s = new Span();

            switch (colour%3)
            {
                case 0:
                    s.BackgroundColor = Color.Red;
                    break;

                case 1:
                    s.BackgroundColor = Color.Green;
                    break;

                case 2:
                    s.BackgroundColor = Color.Blue;
                    break;
            }

            s.Text = word;

            FormattedString.Spans.Add(s);

            var onTapped = new TapGestureRecognizer();
            onTapped.Tapped += (sender, e) => OnTapped(sender, e, word);

            s.GestureRecognizers.Add(onTapped);
        }

        private void OnTapped(object Sender, EventArgs e, string word)
        {
            DisplayAlert("Tapped", word, "OK");
        }
    }
```
### Expected Behavior

The alert is only displayed for words that you tap on

### Actual Behavior

If a span breaks a line, then clicking any span on that line triggers the TapGestureRecognizer for the span tapped on (which should happen) but also the TapGestureRecognizer for the line-breaking span at the end of the line gets triggered (which shouldn't happen because it wasn't tapped)

### Basic Information

- Platform Target Frameworks: 
  - iOS:  Untested
  - Android: The issue is present
- NuGet Packages: Xamarin.Forms 5.0.0.2401

### Environment

<details><summary>Show/Hide Visual Studio info</summary>

```
Microsoft Visual Studio Community 2019
Version 16.11.10
VisualStudio.16.Release/16.11.10+32126.315
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Community

ASP.NET and Web Tools 2019   16.11.106.23128
ASP.NET and Web Tools 2019

ASP.NET Web Frameworks and Tools 2019   16.11.106.23128
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.11.106.23128
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   16.11.106.23128
Azure Functions and Web Jobs Tools

C# Tools   3.11.0-4.21602.3+fc14a1355c0461af5110b74b26f6478f22d26565
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

CodeMaid   12.0.300
CodeMaid is an open source Visual Studio extension to cleanup and simplify our C#, C++, F#, VB, PHP, PowerShell, R, JSON, XAML, XML, ASP, HTML, CSS, LESS, SCSS, JavaScript and TypeScript coding.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

FormatDocumentOnSave   1.0
Enables auto formatting of the code when you save a file. Visual Studio supports auto formatting of the code with the CTRL+E,D or CTRL+E,F key shortcuts but with this extension the command 'Format Document' is executed on Save.

You can find the source here: https://github.com/Elders/VSE-FormatDocumentOnSave

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft Azure Tools for Visual Studio   2.9
Support for Azure Cloud Services projects

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.113+g422d40002e.RR
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual Studio Tools for Containers   1.2
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Mono Debugging for Visual Studio   16.10.15 (552afdf)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   5.11.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Razor (ASP.NET Core)   16.1.0.2122504+13c05c96ea6bdbe550bd88b0bf6cdddf8cde1725
Provides languages services for ASP.NET Core Razor.

SQL Server Data Tools   16.0.62111.25150
Microsoft SQL Server Data Tools

SQLite & SQL Server Compact Toolbox   4.8
SQLite & SQL Server Compact Toolbox adds scripting, import, export, rename, query execution and much more to SQL Server Compact & SQLite Data Connections.

TypeScript Tools   16.0.30526.2002
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.11.0-4.21602.3+fc14a1355c0461af5110b74b26f6478f22d26565
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   16.11.0-beta.21514.6+b6c2c4f53ea3a08fa603ea93d6d2f808a62a21d1
Microsoft Visual F# Tools

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

Visual Studio Tools for Unity   4.11.4.0
Visual Studio Tools for Unity

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Foo   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   16.11.000.197 (d16-11@6934992)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.11.0.47 (remotes/origin/d16-11@e0d612363)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.10.5 (355b57a)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   12.0.0.3 (d16-11/f0e3c2d)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: c633fe9
    Java.Interop: xamarin/java.interop/d16-11@476bb5b
    ProGuard: Guardsquare/proguard/v7.0.1@912d149
    SQLite: xamarin/sqlite/3.35.4@85460d3
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-11@87af37b


Xamarin.iOS and Xamarin.Mac SDK   15.2.0.17 (738fde344)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
```

</details>

### Screenshots

For example: Tap the green "def" span on the first line. The TapGestureRecognizer for the blue "bcd" span at the end of the line gets triggered, even though I didn't tap on it. Then immediately afterwards the "def" TapGestureRecognizer is triggered as well.

image

### PR DESCRIPTION
**Pull request by maonaoda**
### Issues Resolved ### 

- fixes #15378 

### API Changes ###

 
 None

### Platforms Affected ### 

- Android

### Behavioral/Visual Changes ###

Tapped event gets triggered correctly on Label with multiline spans that are tappable.

None

### Before/After Screenshots ### 

- Brfore
demo2022090102

- After
demo2022090101

### Hoping ###
Hope it's fixed soon, not quite like changing the design...

### PR Checklist ###

- [ ] Targets the correct branch
- [ ] Tests are passing (or failures are unrelated)

### CODE REVIEW

**Comment by maonaoda** [comment]
should be related to  #13348

**Comment by Kas-code** [comment]
I would really appreciate if this can be merged in guys. This is causing a huge issue in my production app.

Is this issue fixed in MAUI? If so, then I will upgrade the app to MAUI.

**Comment by maonaoda** [comment]
not yet, since maui is using this same code↑ as xamarin so this bug also exists.

**Comment by Kas-code** [comment]
@maonaoda Thanks for the info.
I am keen to get this fixed.
What is left to do to get this merged in?
How can I help?

**Comment by maonaoda** [comment]
Submit a new Issue to [MAUI](https://github.com/dotnet/maui/issues), then waiting for them to notice and fix on Maui。
I think Xamarin is unlikely to fix,.
And change UI design may be another way to avoid this problem that i did.

**Comment by Kas-code** [comment]
@maonaoda I implemented a custom renderer which overrides LabelRenderer in my project, and also overrode the function RecalculateSpanPositions in order to use your code change inside my project.

It mostly fixes the issue but there is still a small bug.

If the span at the end of the line is only one character long then it is not clickable.

If the span at the end of the line is more than one character long, then clicking anywhere in the span, apart from the last character triggers the click event.

So I think that the spanEndX is off by one character. I've tried to look into how to fix this but I can't figure it out.

Do you have any advice?

**Comment by thisisthekap** [comment]
@jfversluis Any chance that this one is making it into a Xamarin.Forms service release?

**Comment by jfversluis** [comment]
Now that we're so close to the sunsetting of Xamarin.Forms unfortunately we won't be able to take this in anymore, we're really sorry about that. Nevertheless, thank you so much for your time and effort that you have put into this PR.

Please have a look at the evolution of Xamarin.Forms, [.NET MAUI](https://github.com/dotnet/maui). A lot of development has been going on there. Hopefully this issue was already fixed in that codebase. If not, feel free to port this over to there.

Again, thank you so much for being a contributor and Xamarin.Forms user!

**Comment by maonaoda** [comment]
I will check it on maui~

**Pull request closed without merging**
