### PR TITLE
Shell FlyoutWidth and FlyoutHeight

### PR DESCRIPTION
**Pull request by PureWeen**
### Description of Change ###

Allow users to specify the Width and Height of the flyout on shell. This let's you expand the flyout to git across the entire screen or raise the flyout up for DualScreen cases or if you want it to be just above the TabBar

### API Changes ###

Added:
 - double Shell.FlyoutWidth { get; set; } //Bindable Property
 - double Shell.FlyoutHeight {get; set;}  //Bindable Property

### Platforms Affected ### 
- Core/XAML (all platforms)
- iOS
- Android
- UWP

#### UWP

Default

image

Modified WxH

image

#### Android

Default

image

Modified WxH

image

#### iOS

Default

image

Modified WxH
image

### Testing Procedure ###
- Shell store has a demo of these properties that you can play with 

### PR Checklist ###

- [ ] Targets the correct branch
- [ ] Tests are passing (or failures are unrelated)

### CODE REVIEW

**Review by pictos — APPROVED** [review]
I tested here and it's working well

**Comment by PureWeen** [comment]
https://dev.azure.com/xamarin/public/_releaseProgress?releaseId=2596&_a=release-pipeline-progress

**Comment by jsuarezruiz** [comment]
Small changes applied to fix an issue setting the `FlyoutBackground` (Brush) in iOS:
flyout-brush-fix

**Review by jsuarezruiz — APPROVED** [review]

**Comment by themronion** [comment]
Finally!)

**Pull request merged**
