### PR TITLE
Android AppCompat: Don't do NavigationPage menu updates for disposed page

### PR DESCRIPTION
**Pull request by lirkki**
### Description of Change ###

Added a similar check for disposed object in UpdateMenu() as there is in UpdateToolbar().

### Bugs Fixed ###

- Fixed a random crash in my work area. No bug report created and no sample app available now.

### API Changes ###

None

### Behavioral Changes ###

App may stop crashing.

### PR Checklist ###

- [ ] Has tests (if omitted, state reason in description)
- [x] Rebased on top of master at time of PR
- [x] Changes adhere to coding standard
- [x] Consolidate commits as makes sense

### CODE REVIEW

**Comment by ahmedalejo** [comment]
I experience this issue but since i was catching the error, it didn´t lead to app crashes(at least not anymore)

**Comment by samhouts** [comment]
:+1:

**Comment by rmarinho** [comment]
👍

**Comment by ahmedalejo** [comment]
Hi guys,  is this merge in a nuget version already(alpha/beta)? 

Like i said the this wasn´t a issue with me because i was able try catch the error which didn´t lead to crashes, **BUT** on _Samsung Galaxy Tab 3 10.1 (**GT-p5210**)_ it crashes any ways as can be seen from **Xamarin.Insights** StackTrace

image

**Pull request merged**
