### PR TITLE
[Android] Fix issue closing the SwipeView swiping 

### LINKED ISSUE #12541: [Bug] Android Swipeview finicky swipe to close (with video and sample repo)
### Description
The swipeview has poor responsiveness and takes multiple swipe attempts to close an open swipeview.

### Steps to Reproduce

1. Left slide on slideview in listview or collection view on Androd (reproduced using Samsung s10)
2. Try to close the slideview, it will not close. You have to slide slide to the left again to close the slideview

You can download a test repo at https://github.com/lhughey/SwipeViewBug.git

### Expected Behavior
You should be able to open a right itemed slideview by swiping left, and close it by swiping right. 

### Actual Behavior
Swiping right does not close a slideview in Android

### Basic Information

- Version with issue:  - XF: 4.8.0.1560 and previous versions. I upgraded to 4.8.0.1560 hoping for a fix
- Last known good version: Unknown
- Platform Target Frameworks: Tested against 9.0

  - iOS:  
  - Android: 
        Android SDK: 
         SDK Tools Version: 26.1.1
         SDK Platform Tools Version: 30.0.4
         SDK Build Tools Version: 29.0.2
  - UWP:   
- Android Support Library Version: 
- Nuget Packages: Reactive.Fody, XF Essentials, AcUserDialogs
- Affected Devices: Android devices. Tested on Samsung s10 and s8.

### Screenshots

[N|Solid](https://nodesource.com/products/nsolid)

#### Full Video available
[https://imgur.com/a/hwpgWnV](https://imgur.com/a/hwpgWnV)

### Reproduction Link
https://github.com/lhughey/SwipeViewBug.git

### PR DESCRIPTION
**Pull request by jsuarezruiz**
### Description of Change ###

Fix issue closing the SwipeView swiping on Android.

### Issues Resolved ### 

- fixes #12541 

### API Changes ###
 
 None

### Platforms Affected ### 

- Android

### Behavioral/Visual Changes ###

None

### Before/After Screenshots ### 

Not applicable

### Testing Procedure ###

Launch Core Gallery on a **physical device**; navigate to the issue 12541; then open the SwipeView several times and swipe to close it. If it always closes without problems, the test has passed.

### PR Checklist ###

- [ ] Targets the correct branch
- [ ] Tests are passing (or failures are unrelated)

### CODE REVIEW

**Comment by mattleibow** [comment]
This works on the close each time, but I think there is now another issue as a result. If I open and then "open" again by swiping left, then it closes.

I think the logic needs to check to see which direction the swipe is going to close it before closing.

**Review by mattleibow — COMMENTED** [review]
This works on the close each time, but I think there is now another issue as a result. If I open and then "open" again by swiping left, then it closes.

I think the logic needs to check to see which direction the swipe is going to close it before closing.

**Review by rmarinho — APPROVED** [review]

**Comment by rmarinho** [comment]
@mattleibow isn't tapping the cell closing it ?

**Comment by mattleibow** [comment]
Yes, but this was more a swipe... I had a look at Teams and Mail and the swipe can be used to open the actions. And then if you swipe again I'd doesn't close but selects the default action.

**Comment by rmarinho** [comment]
Ah i got what you saying , i tested now and see that. But also i tested just with 5.0.0 without this change and the behavior is the same. So i think it's not particular to this issue.

**Review by mattleibow — APPROVED** [review]

**Pull request merged**
