### PR TITLE
[Android, Help Needed, Do Not Merge] TabbedPage child should not call disappearing on initial run

### PR DESCRIPTION
**Pull request by adrianknight89**
### Description of Change ###

Currently, there is a bug with Android TabbedPage that triggers appearing / disappearing events the wrong way. When you load a TabbedPage, the following happens:

- TabbedPage Appearing
- Page1 Appearing
- Page1 Disappearing
- Page1 Appearing

Page1 should **NOT** call its `Disappearing` event. I was able to identify how this bug happens but not why. 

In `Page.cs`, after TabbedPage invokes its `Appearing` event inside `IPageController.SendAppearing()`, it also invokes its current page's `Appearing` event like so:

`((IPageController)pageContainer?.CurrentPage)?.SendAppearing();`

Then, `TabbedPageRenderer` invokes `pager.Measure(...)` inside `OnLayout(...)` which in turn triggers `IPageController.SendDisappearing()` in `Page.cs`. I'm not sure why this is the case. This will fire `Disappearing` event for the current page.

The hack is to skip calling current page's appearing event as seen in the commit. This way, `IPageController.SendDisappearing()` will be called but not processed since `_hasAppeared` is false.

Can anyone comment why `pager.Measure(...)` sets `UserVisibleHint` of `FragmentContainer` to false?

### Bugs Fixed ###

- https://bugzilla.xamarin.com/show_bug.cgi?id=44211

### CODE REVIEW

**Comment by amccorma** [comment]
Thanks for tying to resolve this bug.

**Comment by amccorma** [comment]
was this fixed with Xamarin forms v.2.3.2.127?

**Comment by tonholis** [comment]
this bug remains in XF 2.3.4.231

**Comment by goldenkeyz-plaroche** [comment]
Hello,

If you comment lines 37 to 51 in FragmentContainer.cs, the events appears all normal....

`		//public override bool UserVisibleHint
		//{
		//	get { return base.UserVisibleHint; }
		//	set
		//	{
		//		base.UserVisibleHint = value;
		//		if (_isVisible == value)
		//			return;
		//		_isVisible = value;
		//		if (_isVisible.Value)
		//			PageController?.SendAppearing();
		//		else
		//			PageController?.SendDisappearing();
		//	}
		//}
` 
Can someone confirm that ? 
Best regards,
Paulin

**Pull request closed without merging**
