### PR TITLE
Prevent EntryRenderer from stepping on itself when setting alignment

### LINKED ISSUE #8137: [Bug] XF 4.3 Entry HorizontalTextAlignment display wrong position
### Description
Encounted since 4.3 pre1, Entry HorizontalTextAlignment display wrong position

### Basic Information

- Version with issue: 4.3
- Last known good version: 4.2
- IDE: VS 16.3.4

### Screenshots
4.2
screenshot-2019-10-22_09 40 27 578
4.3
screenshot-2019-10-22_09 27 18 38

### PR DESCRIPTION
**Pull request by hartez**
### Description of Change ###

The EntryRenderer on Android sets the vertical and horizontal alignment for text separately. For applications which are API <= 17, or for applications which do not set `android:supportsRTL="true"` in the manifest, when the renderer sets the vertical alignment it overwrites the horizontal alignment settings. 

These changes set the alignments at the same time to avoid overwriting either one.

Previously, there was no reliable way for us to automate tests for vertical/horizontal alignment for Entry on the native platforms. So this PR introduces a new automated testing mechanism for renderers, and adds vertical/horizontal alignment tests for Entry on Android. It also replaces a couple of UI tests with the new mechanism.

### Issues Resolved ### 

- fixes #8137

### API Changes ###
None

### Platforms Affected ### 
- Android

### Behavioral/Visual Changes ###
None

### Before/After Screenshots ### 
Not applicable

### Testing Procedure ###
Automated test

### PR Checklist ###
- [ ] Targets the correct branch
- [ ] Tests are passing (or failures are unrelated)

### CODE REVIEW

**Comment by jfversluis** [comment]
Still failing on "Platform Automated Test" but now just for iOS. The Android ones seem not related to this.

**Comment by hartez** [comment]
Failed UI test is unrelated.

**Comment by hartez** [comment]
LGTM

**Comment by hartez** [comment]
> Still failing on "Platform Automated Test" but now just for iOS. The Android ones seem not related to this.

Fixed that this morning - just needed to change a linking setting for the device (non-simulator) build.

**Pull request merged**
