### PR TITLE
[iOS] Fix issue disposing the EmptyView

### LINKED ISSUE #12374: [Bug] iOS XF 5.0-pre1 crash with CollectionView when using EmptyView
### Description
While testing XF 5.0-pre1 I came across some NRE of the DefaultRenderer object when using CollectionView and adding an EmptyView. This only appears to be for iOS, Android does not crash with the below samples.

### Steps to Reproduce
1. Add a CollectionView
2. Add an EmptyView 
3. Add a way to add items to the CollectionView (I have used a bound ObservableCollection)
4. From seeing the EmptyView (either from launch or from removing existing items) try add new items
5. Crash

### Steps to Reproduce with reproduction sample below
1. Launch the app on iOS simulator (did not test physical device)
2. Click each item to remove them and view the EmptyView.
3. Pull to refresh to add new items or click the AddItems button. 
4. Crash.
5. Open MainPage.xaml, remove comments around CollectionView.EmptyViewTemplate
6. Repeat steps 1-3.
7. No crash.

### Expected Behavior
New items get added to the CollectionView

### Actual Behavior
Crash with the following 
```
Unhandled Exception:
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'DefaultRenderer'.
  at Foundation.NSObject.get_SuperHandle () [0x00012] in /Library/Frameworks/Xamarin.iOS.framework/Versions/14.0.0.0/src/Xamarin.iOS/Foundation/NSObject2.cs:394 
  at UIKit.UIView.set_Frame (CoreGraphics.CGRect value) [0x00024] in /Library/Frameworks/Xamarin.iOS.framework/Versions/14.0.0.0/src/Xamarin.iOS/UIKit/UIView.g.cs:3733 
  at Xamarin.Forms.Platform.iOS.ItemsViewController`1[TItemsView].LayoutEmptyView () [0x0000f] in D:\a\1\s\Xamarin.Forms.Platform.iOS\CollectionView\ItemsViewController.cs:300 
  at Xamarin.Forms.Platform.iOS.ItemsViewController`1[TItemsView].ViewWillLayoutSubviews () [0x0003a] in D:\a\1\s\Xamarin.Forms.Platform.iOS\CollectionView\ItemsViewController.cs:163 
  at Xamarin.Forms.Platform.iOS.StructuredItemsViewController`1[TItemsView].ViewWillLayoutSubviews () [0x00000] in D:\a\1\s\Xamarin.Forms.Platform.iOS\CollectionView\StructuredItemsViewController.cs:78 
  at (wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
  at UIKit.UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate) [0x00005] in /Library/Frameworks/Xamarin.iOS.framework/Versions/14.0.0.0/src/Xamarin.iOS/UIKit/UIApplication.cs:86 
  at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) [0x0000e] in /Library/Frameworks/Xamarin.iOS.framework/Versions/14.0.0.0/src/Xamarin.iOS/UIKit/UIApplication.cs:65 
  at EmptyViewTest.iOS.Application.Main (System.String[] args) [0x00001] in /Users/bradmoore/Projects/EmptyViewTest/EmptyViewTest.iOS/Main.cs:17
```

### Basic Information

- Version with issue: 5.0.0.1487-pre1
- Last known good version: 4.8.0.1451
- IDE: Visual Studio Community 2019 for Mac, Version 8.7.8 (build 4)
- Platform Target Frameworks: 
  - iOS:  Xamarin.iOS 14.0.0.0
- Nuget Packages: Xamarin.Forms 4.8.0.1451, 5.0.0.1487-pre1. Xamarin.Essentials (although not used) 1.6.0-pre2.

### Reproduction Link

See the attached sample which will crash when you follow the steps in the main description.

[EmptyViewTest.zip](https://github.com/xamarin/Xamarin.Forms/files/5331804/EmptyViewTest.zip)

### Workaround

Move any UI code from EmptyView to EmptyViewTemplate, set just an empty object in EmptyView. From reading the (documentation)[https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/collectionview/emptyview], I don't believe this is how EmptyView and EmptyViewTemplate was intended to be used.
```
<CollectionView.EmptyView>
    <BoxView />
</CollectionView.EmptyView>

<CollectionView.EmptyViewTemplate>
    <DataTemplate>
        <Grid>
            <Label Text="Empty Template View" HorizontalOptions="Center" VerticalOptions="Center" />
        </Grid>
    </DataTemplate>
</CollectionView.EmptyViewTemplate>
```

### LINKED ISSUE #12776: [Bug] iOS CollectionView, CarouselView Cannot access disposed object. DefaultRenderer
# Description
```
NSObject.get_SuperHandle () /Library/Frameworks/Xamarin.iOS.framework/Versions/14.4.1.3/src/Xamarin.iOS/Foundation/NSObject2.cs:394
UIView.set_Frame (CoreGraphics.CGRect value) /Library/Frameworks/Xamarin.iOS.framework/Versions/14.4.1.3/src/Xamarin.iOS/UIKit/UIView.g.cs:3733
ItemsViewController`1[TItemsView].LayoutEmptyView () D:\a\1\s\Xamarin.Forms.Platform.iOS\CollectionView\ItemsViewController.cs:300
ItemsViewController`1[TItemsView].ViewWillLayoutSubviews () D:\a\1\s\Xamarin.Forms.Platform.iOS\CollectionView\ItemsViewController.cs:163
StructuredItemsViewController`1[TItemsView].ViewWillLayoutSubviews () D:\a\1\s\Xamarin.Forms.Platform.iOS\CollectionView\StructuredItemsViewController.cs:78
(wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate) /Library/Frameworks/Xamarin.iOS.framework/Versions/14.4.1.3/src/Xamarin.iOS/UIKit/UIApplication.cs:86
UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) /Library/Frameworks/Xamarin.iOS.framework/Versions/14.4.1.3/src/Xamarin.iOS/UIKit/UIApplication.cs:65
```

### Steps to Reproduce

1. Create carousel view with 3 items
2. Swipe
3. application hangs

or
1. Create collection view with custom template and empty view
2. Swipe to refresh

### Expected Behavior
App shouldn't crash

### Actual Behavior
App crashes

### Basic Information

- Version with issue: 5.0.1 - nightly
- Last known good version:
- IDE: VS for Mac
- Platform Target Frameworks: 
  - iOS: 14
- Affected Devices: iOS device

### Screenshots
image

### PR DESCRIPTION
**Pull request by jsuarezruiz**
### Description of Change ###

Hiding the native `EmptyView` we removed it from the superview (UICollectionView). This PR include changes to dispose the view and set it to null. This way, after show again the EmptyView, creates a new one and does not attempt to access a disposed view.

### Issues Resolved ### 

- fixes #12374 
- fixes #12776

### API Changes ###

 None

### Platforms Affected ### 

- iOS

### Behavioral/Visual Changes ###

None

### Before/After Screenshots ### 
fix12374

### Testing Procedure ###
Launch Core Gallery and navigate to the issue 12374. Tap each item to remove them and view the EmptyView. Then, tap the AddItems button. Without crash, the test has passed.

### PR Checklist ###

- [ ] Targets the correct branch
- [ ] Tests are passing (or failures are unrelated)

### CODE REVIEW

**Comment by vniehues** [comment]
When will this be merged? 
Is anything missing?

**Comment by rmarinho** [comment]
Can you add a UITest @jsuarezruiz  ?

**Comment by jsuarezruiz** [comment]
Added UITest.

**Comment by beeradmoore** [comment]
What timing. I came back yesterday to see what progress was on this issue because I've hit a bunch of other XF5 issues I've been slogging through. Good to see its fixed though! Thanks @jsuarezruiz

**Review by rmarinho — APPROVED** [review]

**Review by hartez — APPROVED** [review]

**Comment by vniehues** [comment]
Today after updating to the newest preview of XF my EmptyViews were just not showing anymore and a tap in the area where the EmptyView is supposed to be just crashed the app (SIGSEGV). Only tested on iOS.

**Comment by rmarinho** [comment]
Sorry @vniehues  but it didn't make into pre4, but is merged for the next pre-- 

Can you try this nugets and see if it fixes your issue..

[debug (11).zip](https://github.com/xamarin/Xamarin.Forms/files/5555071/debug.11.zip)

**Pull request merged**
