### PR TITLE
Route Navigation.(Push/Pop)Modal through Shell Navigation Manager

### LINKED ISSUE #13947: [Bug] iOS Shell PopAsync() causes null reference at RouteRequestBuilder
### Description
On iOS (simulator and device) Using Shell I have navigated to 2 subsequent using GotoAsync().  If PopAsync() is then called a NullReferenceException is thrown (see below)

### Steps to Reproduce

1. Programmatically call GotoAsync()
2. From shown Child, then call GotoAsync() (from user input button for example)
3. From Next Child call PopAsync() (again using user input as trigger)

### Expected Behavior
No Crash

### Actual Behavior
Null Reference Exception:
System.NullReferenceException: Object reference not set to an instance of an object
  at Xamarin.Forms.RouteRequestBuilder.<AddMatch>g__AddNode|27_0 (Xamarin.Forms.BaseShellItem baseShellItem, System.String nextSegment) [0x00000] in D:\a\1\s\Xamarin.Forms.Core\Shell\RouteRequestBuilder.cs:77 
  at Xamarin.Forms.RouteRequestBuilder.AddMatch (Xamarin.Forms.ShellUriHandler+NodeLocation nodeLocation) [0x0003c] in D:\a\1\s\Xamarin.Forms.Core\Shell\RouteRequestBuilder.cs:70 
  at Xamarin.Forms.ShellUriHandler.SearchForGlobalRoutes (System.String[] segments, System.Uri startingFrom, Xamarin.Forms.ShellUriHandler+NodeLocation currentLocation, System.String[] routeKeys) [0x00042] in D:\a\1\s\Xamarin.Forms.Core\Shell\ShellUriHandler.cs:441 
  at Xamarin.Forms.ShellUriHandler.GenerateRoutePaths (Xamarin.Forms.Shell shell, System.Uri request, System.Uri originalRequest, System.Boolean enableRelativeShellRoutes) [0x00133] in D:\a\1\s\Xamarin.Forms.Core\Shell\ShellUriHandler.cs:288 
  at Xamarin.Forms.ShellUriHandler.GetNavigationRequest (Xamarin.Forms.Shell shell, System.Uri uri, System.Boolean enableRelativeShellRoutes, System.Boolean throwNavigationErrorAsException, Xamarin.Forms.ShellNavigationParameters shellNavigationParameters) [0x00018] in D:\a\1\s\Xamarin.Forms.Core\Shell\ShellUriHandler.cs:185 
  at Xamarin.Forms.ShellNavigationManager.GoToAsync (Xamarin.Forms.ShellNavigationParameters shellNavigationParameters) [0x000b8] in D:\a\1\s\Xamarin.Forms.Core\Shell\ShellNavigationManager.cs:44 
  at Xamarin.Forms.ShellSection+NavigationImpl.OnPopAsync (System.Boolean animated) [0x000e9] in D:\a\1\s\Xamarin.Forms.Core\Shell\ShellSection.cs:1070 

### Basic Information

- Version with issue:
- Last known good version: unknown 4 i think worked
- Platform Target Frameworks:
  - iOS:  14.4
- NuGet Packages: n/a
- Affected Devices: iOS simulator and iPhone 7

### Environment
<details><summary>Show/Hide Visual Studio info</summary>

```
Microsoft Visual Studio Enterprise 2019 (2)
Version 16.8.6
VisualStudio.16.Release/16.8.6+31019.35
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Enterprise

ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools

ASA Service Provider   1.0

ASP.NET and Web Tools 2019   16.8.560.26713
ASP.NET and Web Tools 2019

ASP.NET Core Razor Language Services   16.1.0.2052803+84e121f1403378489b842e1797df2f3f5a49ac3c
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2019   16.8.560.26713
For additional information, visit https://www.asp.net/

Automatic Versions   2.0.48
Provides tools for managing assembly versions.

Azure App Service Tools v3.0.0   16.8.560.26713
Azure App Service Tools v3.0.0

Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.

Azure Data Lake Tools for Visual Studio   2.6.3000.0
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools   16.8.560.26713
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio   2.6.3000.0
Microsoft Azure Stream Analytics Tools for Visual Studio

C# Tools   3.8.0-5.20604.10+9ed4b774d20940880de8df1ca8b07508aa01c8cd
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

CodeMaid   11.2.231
CodeMaid is an open source Visual Studio extension to cleanup and simplify our C#, C++, F#, VB, PHP, PowerShell, R, JSON, XAML, XML, ASP, HTML, CSS, LESS, SCSS, JavaScript and TypeScript coding.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Fabric.DiagnosticEvents   1.0
Fabric Diagnostic Events

GitHub.VisualStudio   2.11.106.19330
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Material icons generator   2.0.0
This extension helps you to add material design icons to your Android, iOS or UWP project

Microsoft Azure HDInsight Azure Node   2.6.3000.0
HDInsight Node under Azure Node

Microsoft Azure Hive Query Language Service   2.6.3000.0
Language service for Hive query

Microsoft Azure Service Fabric Tools for Visual Studio   16.0
Microsoft Azure Service Fabric Tools for Visual Studio

Microsoft Azure Stream Analytics Language Service   2.6.3000.0
Language service for Azure Stream Analytics

Microsoft Azure Stream Analytics Node   1.0
Azure Stream Analytics Node under Azure Node

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2019 - v2.9.30924.1

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.113+g422d40002e.RR
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Mono Debugging for Visual Studio   16.8.43 (00471f8)
Support for debugging Mono processes with Visual Studio.

NamespaceFixer   2.9
VS Extension to fix namespaces following C# and VB.NET convention

NuGet Package Manager   5.8.1
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Regex Editor   1.0
.Net Regular Expressions tools

Snapshot Debugging Extension   1.0
Snapshot Debugging Visual Studio Extension Detailed Info

SQL Server Data Tools   16.0.62102.01130
Microsoft SQL Server Data Tools

StylerPackage Extension   1.0
StylerPackage Visual Stuido Extension Detailed Info

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   16.0.21016.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.8.0-5.20604.10+9ed4b774d20940880de8df1ca8b07508aa01c8cd
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   16.8.0-beta.20507.4+da6be68280c89131cdba2045525b80890401defd
Microsoft Visual F# Tools

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

Visual Studio Tools for Kubernetes   1.0
Visual Studio Tools for Kubernetes

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

VSColorOutput   2.73
Color output for build and debug windows - https://mike-ward.net/vscoloroutput

Xamarin   16.8.000.262 (d16-8@4d60f9c)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.8.0.507 (remotes/origin/d16-8@e87b24884)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.8.112 (86385a3)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   11.1.0.26 (d16-8/a36ce73)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: 5e9cb6d
    Java.Interop: xamarin/java.interop/d16-8@79d9533
    ProGuard: Guardsquare/proguard/proguard6.2.2@ebe9000
    SQLite: xamarin/sqlite/3.32.1@1a3276b
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-8@2fb1cbc


Xamarin.iOS and Xamarin.Mac SDK   14.10.0.4 (5a05865f6)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
```

</details>

### PR DESCRIPTION
**Pull request by PureWeen**
### Description of Change ###

When the user called "Navigation.(Push/Pop)ModalAsync"  those were operating outside the scope of Shell so it would confuse the ShellNavigationManager when trying to process cancellation tokens. This makes it so the Navigation calls to push/pop modal will correctly call Navigating/Navigated and also allow users to cancel those operations as well

### Issues Resolved ### 
- fixes #13947

### Platforms Affected ### 
- Core/XAML (all platforms)

### Testing Procedure ###
- Unit Test included

### PR Checklist ###

- [ ] Targets the correct branch
- [ ] Tests are passing (or failures are unrelated)

### CODE REVIEW

**Comment by PureWeen** [comment]
Test Failures unrelated

**Comment by jsuarezruiz** [comment]
@Shane Could you rebase to fix the conflicts?. Thanks!.

**Comment by PureWeen** [comment]
@jsuarezruiz I kicked off the UI Tests

I'd like those to run again with the previous shell PRs that got merged

**Comment by jsuarezruiz** [comment]
The failing UITests seem unrelated.
Captura de pantalla 2021-07-07 a las 10 58 53

**Review by jsuarezruiz — APPROVED** [review]
Captura de pantalla 2021-07-07 a las 11 08 33

**Comment by EricB84300** [comment]
I have a question on this fix. It seems thant since that, when you push a value by MessagingCenter on the the screen you ask NavigateTo the message was send before OnAppearing with the subscribe could run. So the message is not received.
Does anyone else get this problem ?

**Pull request merged**
