### PR TITLE
VisualElement.IsFocused make Bindable

### LINKED ISSUE #7944: [Enhancement] VisualElement.IsFocused make bindable
## Summary
I think that it would be nice to make VisualElement.IsFocused - Bindable. It’s very convenient from ViewModel to send focus to some text field, or to pick focus.

## API Changes

``` cs
VisualElement.IsFocused {get;set;}
```

### PR DESCRIPTION
**Pull request by KSemenenko**
### Description of Change ###
Solved the problem of setting focus via Binding. 
Changing the existing property "IsFocused" now  is a bindable property.
### Issues Resolved ### 

- fixes #7944

### API Changes ###
```` cs
VisualElement.IsFocused {get;set;}
````

Changed:
 - bool VisualElement.IsFocused { get; set; } 

### Platforms Affected ### 
- Core/XAML (all platforms)

### Behavioral/Visual Changes ###
None

### Before/After Screenshots ### 
Not applicable

### PR Checklist ###
1. open ControlGallery
2. Select "IsFocused Bindable Gallery"
4. Press "Focus" Button
5. Press "Unfocus" Button

- [x] Targets the correct branch
- [x] Tests are passing (or failures are unrelated)

### CODE REVIEW

**Comment by StephaneDelcroix** [comment]
I don't think this is the right solution for the problem

**Comment by StephaneDelcroix** [comment]
> fixes #7944

does not fixes it

**Comment by KSemenenko** [comment]
The problem is that IsFocused gets the value from the Renderer and changing this logic creates a large number of changes.
If you have any opinion how to do this, I will be happy to implement it. @StephaneDelcroix

**Comment by KSemenenko** [comment]
and I’ll try to do something with the IsFocused property as well.

**Comment by KSemenenko** [comment]
@StephaneDelcroix  What do you think is the solution? I left the private property, because it is set via renderer

**Comment by KSemenenko** [comment]
@StephaneDelcroix @kingces95 @samhouts  Maybe you have already watched this PR and have any comments?

**Comment by KSemenenko** [comment]
@StephaneDelcroix @kingces95 I updated the branch from the last develop

**Comment by KSemenenko** [comment]
@samhouts @StephaneDelcroix @kingces95 
any updates?

**Comment by KSemenenko** [comment]
I fixed the tests. Now everything works as it should.
@StephaneDelcroix @kingces95 @samhouts

**Comment by KSemenenko** [comment]
@samhouts @PureWeen 
any updates?

**Comment by samhouts** [comment]
@KSemenenko On the list! Thanks for your patience!

**Comment by StephaneDelcroix** [comment]
IsFocused has always been Bindable, but read-only. having it that way ensure that only one control is focused at the time, and the responsibility is on the platform.

you can still call Focus manually, to request Focus.

if you really need a BP, you can add an attached BP, defined in your code, that does just that.

I'm closing this for now

**Pull request closed without merging**
