### PR TITLE
[iOS] Added icon to context menu actions instead of text **Behavior change**

### PR DESCRIPTION
**Pull request by Sebastian1989101**
### Description of Change ###
Changed context action menu of ViewCells to Icons like it is in native apps and on Android instead of Text.

### Bugs Fixed ###

- None

### API Changes ###

- None

### Behavioral Changes ###
Instead of text the icon will appear in context actions like it is on Android.

### PR Checklist ###

- [ ] Has tests (if omitted, state reason in description)
- [ ] Rebased on top of master at time of PR
- [ ] Changes adhere to coding standard
- [ ] Consolidate commits as makes sense

### CODE REVIEW

**Comment by rmarinho** [comment]
Won't this break everyone that has a item with icon and text ? 
IF they update the app , they will see a different UI without expecting it. I don't think this could be done like this to be backwards compatible.

**Comment by rmarinho** [comment]
@Sebastian1989101 i will discuss with the team.

**Comment by jassmith** [comment]
Unfortunately this will be a massive breaking change for some of our users. The behavioral change will have to be locked behind a PlatformSpecific to be acceptable. I think we could accept it if written in that format.

**Comment by Sebastian1989101** [comment]
@jassmith so it is a "breaking" change that something works the same way on all platforms? In my opinion it is more a breaking change that it is different across the platforms because I would not expect that. Currently there is no way to handle this with a custom renderer or something. Also I'm sure that this is not 100% compatible with Apples iOS Guidelines for User Interfaces because it is not the same behaviour as it would be with a native implementation.

**Pull request closed without merging**
