### PR TITLE
Proposal to change defaults Colors from field to gets for startup perf…

### PR DESCRIPTION
**Pull request by ahmedalejo**
**DO-NOT-MERGE-!!!** 🛑

### Description of Change ###

As a continuation of a conversation in #8884  
> @ahmedalejo can you open a PR? (or link to a diff) I can time the difference.
> 
> The main issue is the API change, going from a field to a property can break existing code.

### Issues Resolved ### 
Minor startup penalty due to Colors initialization.

- fixes 

### API Changes ###
Added:
 -  Static getters where added for all well-known color fields

### Platforms Affected ### 
- Core/XAML (all platforms)

### Behavioral/Visual Changes ###
slightly faster startup

### Before/After Screenshots ### 
Not applicable

### PR Checklist ###

- [ ] Targets the correct branch
- [ ] Tests are passing (or failures are unrelated)

### CODE REVIEW

**Comment by StephaneDelcroix** [comment]
I'm sorry, but we can not do that. Even if your existing C# code will be happy to compile against this and won't se a difference, already compiled code against old version will break at runtime. It's an ABI change.

Also, whatever gain we get at startup will be paid at the time the value is actually accessed, as a function call is a bit more expensive that loading a static field.

**Comment by StephaneDelcroix** [comment]
But thanks for the effort, and for this first contribution.

**Comment by ahmedalejo** [comment]
Hi @StephaneDelcroix 

Thanks for your feedback. i got your point the last #8884 but just to get an insight on the performance improvement this might give (i.e @jonathanpeppers taking a shot at it as requested).

We could re-think on how we create defaults stuff in xamarin.forms.

I understand that it wouldn´t be merged, not even in a v7.0. i was only curioust o see what @jonathanpeppers findings could make us change the way we develop for XF and stop lagging at startup being some other XP solutions

And oh! this isn´t my first contribution. but thanks for your gentle welcome. 👍

**Comment by jonathanpeppers** [comment]
@ahmedalejo I was going to time the difference for my own knowledge, but the code doesn't compile, I have to enable C# 8:

```diff
diff --git a/Xamarin.Forms.Core/Xamarin.Forms.Core.csproj b/Xamarin.Forms.Core/Xamarin.Forms.Core.csproj
index 4be554b20..ab249fbf2 100644
--- a/Xamarin.Forms.Core/Xamarin.Forms.Core.csproj
+++ b/Xamarin.Forms.Core/Xamarin.Forms.Core.csproj
@@ -1,6 +1,7 @@
 <EF><BB><BF><Project Sdk="Microsoft.NET.Sdk">
        <PropertyGroup>
                <TargetFrameworks>netstandard2.0;netstandard1.0</TargetFrameworks>
+               <LangVersion>8.0</LangVersion>
```
But I still hit:
```
Color.cs(582,37): error CS0019: Operator '??=' cannot be applied to operands of type 'Color' and 'Color'
```
`Color` is a struct, so `??=` wouldn't work.

**Comment by StephaneDelcroix** [comment]
image

**Comment by ahmedalejo** [comment]
@jonathanpeppers, sorry, got you covered a facepalm 🤦‍♂ from. Added a fix for the issue.

**Comment by ahmedalejo** [comment]
@StephaneDelcroix that´s strange. 
thanks though for pointing that out.

**Comment by jonathanpeppers** [comment]
Before:
```
01-09 08:54:29.462  1473  1503 I ActivityTaskManager: Displayed com.xamarin.forms.helloforms/crc6450e568c951913723.MainActivity: +594ms
01-09 08:54:33.148  1473  1503 I ActivityTaskManager: Displayed com.xamarin.forms.helloforms/crc6450e568c951913723.MainActivity: +591ms
01-09 08:54:36.947  1473  1503 I ActivityTaskManager: Displayed com.xamarin.forms.helloforms/crc6450e568c951913723.MainActivity: +609ms
01-09 08:54:40.665  1473  1503 I ActivityTaskManager: Displayed com.xamarin.forms.helloforms/crc6450e568c951913723.MainActivity: +588ms
01-09 08:54:44.393  1473  1503 I ActivityTaskManager: Displayed com.xamarin.forms.helloforms/crc6450e568c951913723.MainActivity: +594ms
01-09 08:54:48.130  1473  1503 I ActivityTaskManager: Displayed com.xamarin.forms.helloforms/crc6450e568c951913723.MainActivity: +594ms
01-09 08:54:51.877  1473  1503 I ActivityTaskManager: Displayed com.xamarin.forms.helloforms/crc6450e568c951913723.MainActivity: +600ms
01-09 08:54:55.645  1473  1503 I ActivityTaskManager: Displayed com.xamarin.forms.helloforms/crc6450e568c951913723.MainActivity: +597ms
01-09 08:54:59.393  1473  1503 I ActivityTaskManager: Displayed com.xamarin.forms.helloforms/crc6450e568c951913723.MainActivity: +598ms
01-09 08:55:03.145  1473  1503 I ActivityTaskManager: Displayed com.xamarin.forms.helloforms/crc6450e568c951913723.MainActivity: +593ms
Average(ms): 595.8
Std Err(ms): 1.82452429112053
Std Dev(ms): 5.76965240624502
```
After:
```
01-09 08:52:54.044  1473  1503 I ActivityTaskManager: Displayed com.xamarin.forms.helloforms/crc6450e568c951913723.MainActivity: +602ms
01-09 08:52:57.791  1473  1503 I ActivityTaskManager: Displayed com.xamarin.forms.helloforms/crc6450e568c951913723.MainActivity: +599ms
01-09 08:53:01.527  1473  1503 I ActivityTaskManager: Displayed com.xamarin.forms.helloforms/crc6450e568c951913723.MainActivity: +587ms
01-09 08:53:05.292  1473  1503 I ActivityTaskManager: Displayed com.xamarin.forms.helloforms/crc6450e568c951913723.MainActivity: +597ms
01-09 08:53:09.028  1473  1503 I ActivityTaskManager: Displayed com.xamarin.forms.helloforms/crc6450e568c951913723.MainActivity: +593ms
01-09 08:53:12.760  1473  1503 I ActivityTaskManager: Displayed com.xamarin.forms.helloforms/crc6450e568c951913723.MainActivity: +585ms
01-09 08:53:16.510  1473  1503 I ActivityTaskManager: Displayed com.xamarin.forms.helloforms/crc6450e568c951913723.MainActivity: +591ms
01-09 08:53:20.224  1473  1503 I ActivityTaskManager: Displayed com.xamarin.forms.helloforms/crc6450e568c951913723.MainActivity: +584ms
01-09 08:53:23.945  1473  1503 I ActivityTaskManager: Displayed com.xamarin.forms.helloforms/crc6450e568c951913723.MainActivity: +585ms
01-09 08:53:27.691  1473  1503 I ActivityTaskManager: Displayed com.xamarin.forms.helloforms/crc6450e568c951913723.MainActivity: +597ms
Average(ms): 592
Std Err(ms): 2.07632153365299
Std Dev(ms): 6.5659052011974
```
There seems like there might be a small improvement here? But I would also want to benchmark actually using a few colors and see how much worse it is. Most apps are going to use a few colors, and if every call to `Color.White` is slower, it might not be worth it.

However, I agree the API break is a major concern. Any NuGet package that depends on Xamarin.Forms and uses a `Color` would start crashing at runtime!

**Comment by ahmedalejo** [comment]
Thanks a mil for the feedback.

if we get major improvements, we could change the way new features are code i didn't intend to suggest the breaking change, but instead learn from it.

**Pull request closed without merging**
