### PR TITLE
[Android] Applinks firebase 42

### PR DESCRIPTION
**Pull request by rmarinho**
### Description of Change ###

Working from #1037 ad updating packages and nugets for testing.

Updating AppLinks 
Update support libs for Android 
Update GooglePlayServices for Maps

### PR Checklist ###

- [ ] Has tests (if omitted, state reason in description)
- [ ] Rebased on top of master at time of PR
- [ ] Changes adhere to coding standard
- [ ] Consolidate commits as makes sense

### CODE REVIEW

**Comment by rmarinho** [comment]
build

**Comment by pabiagioli** [comment]
@rmarinho can you give a clue of what the problem was with #1037 ?
I would like to have this issue solved ASAP, as it is slowing down one of my products?
Like I posted before in #1037 I was able to generate a DLL with AppLinks and integrated it into my current app, but I would like to use the official NuGet from you guys. 
Why is this taking so long? I posted this patch in July 😕

**Comment by Nikdm46** [comment]
I support, as I can not finish the project because of an error
Could not load type of field 'Xamarin.Forms.Platform.Android.AppLinks.AndroidAppLinks:_client' (0) due to: Could not resolve type with token 01000013 (from typeref, class/assembly Android.Gms.Common.Apis.GoogleApiClient, Xamarin.GooglePlayServices.Basement, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null) assembly:Xamarin.GooglePlayServices.Basement, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null type:Android.Gms.Common.Apis.GoogleApiClient member:

Need fix!!!!

**Comment by pabiagioli** [comment]
```AndroidAppLinks.cs``` line 15 in the master branch has this:
```readonly GoogleApiClient _client;```
This branch, on the other hand, doesn't use ```GoogleApiClient``` because it's being deprecated by Google, and that's why you can't use the ```_client ``` field.

I don't know why you're trying to compile the updated Xamarin.GooglePlayServices.Basement with the master branch. That's not going to be possible because GoogleApiClient is not there anymore.

I tried finding the references to that field outside of the Xamarin.Forms.Platform.Android.AppLinks namespace but couldn't find any.

Is there anywhere else you are using this field?
Cheers

**Comment by rmarinho** [comment]
@pabiagioli does thsi PR look good to you? it's taking longer because we are testing update packages all around.

**Comment by Nikdm46** [comment]
@pabiagioli Hi,

Google Maps use Xamarin.GooglePlayServices.Basement v.42
AppLinks use Xamarin.GooglePlayServices.AppIndexing v.29 => AppIndexing use Xamarin.GooglePlayServices.Basement v.29
But i need Google Maps)))They use 49
And so I think a compilation error!

**Comment by nor0x** [comment]
@jassmith thanks! great to see this issue being merged. I was stucked because of this one. Any plans when this version gets on NuGet?

**Pull request merged**
