### PR TITLE
[Android] Fix gradient offset issue in Frame

### LINKED ISSUE #13100: [Bug] LinearGradientBrush GradientStop offset (Android)
### Description
Offset is ignored if using LinearGradientBrush 

### Steps to Reproduce

Using this sample XAML:
```
		<Frame BorderColor="LightGray"
				   HeightRequest="120"
				   WidthRequest="120">
				<Frame.Background>
					<LinearGradientBrush StartPoint="0.5,0" EndPoint="0.5,1">
						<GradientStop Color="Green"
									  Offset="0.0" />
						<GradientStop Color="Blue"
									  Offset="0.25" />
						<GradientStop Color="Gold"
									  Offset="1.0" />
					</LinearGradientBrush>
				</Frame.Background>
			</Frame>
```
It produces this result (ignore the red bottom border):
Unbenannt

Using the same LinearGradientBrush with same stops in a wpf project it produces this:
Unbenannt

with this xaml:
```
    <Rectangle Width="200"
               Height="100">
      <Rectangle.Fill>
        <LinearGradientBrush StartPoint="0.5,0"
                             EndPoint="0.5,1">
          <GradientStop Color="Green"
                        Offset="0.0" />
          <GradientStop Color="Blue"
                        Offset="0.25" />
          <GradientStop Color="Gold"
                        Offset="1.0" />
        </LinearGradientBrush>
      </Rectangle.Fill>
    </Rectangle>
```

### Expected Behavior
Second color should be at offset 0.25

### Actual Behavior
Second color is always at offset 0.5

### Basic Information

- Version with issue: 4.8 to 5 pre5
- Last known good version:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library / AndroidX Version: 
- NuGet Packages:
- Affected Devices:

### Environment

```
```

### PR DESCRIPTION
**Pull request by jsuarezruiz**
### Description of Change ###

Apply offsets in API Level 29 or higher in `GradientDrawable`.

### Issues Resolved ### 

- fixes #13100 

### API Changes ###
 
 None

### Platforms Affected ### 

- Android

### Behavioral/Visual Changes ###

None

### Before/After Screenshots ### 
fix13100

### Testing Procedure ###
Launch Core Gallery and navigate to the issue 13100. If both gradients render exactly the same, the test passed.

### PR Checklist ###

- [ ] Targets the correct branch
- [ ] Tests are passing (or failures are unrelated)

### CODE REVIEW

**Comment by AlleSchonWeg** [comment]
@jsuarezruiz
Could you merge this into SR 4?

**Comment by jfversluis** [comment]
@AlleSchonWeg will be in SR9! Sorry it took a while :(

**Pull request merged**
