### PR TITLE
Fixes various memory leaks in listview with group headers (#6761)

### LINKED ISSUE #6761: [Bug] GroupHeaderTemplate leaks Memory
### Description
When I repeat that I add items to ListView with GroupHeaderTemplate and clear items,
GC.GetTotalMemory(true) is increasing.

### Steps to Reproduce

1. Create ListView with GroupHeaderTemplate
2. Add items and clear items.
3. Repeat "2.".

### Expected Behavior
GC.GetTotalMemory(true) dosen't increase.
### Actual Behavior
GC.GetTotalMemory(true) increases.
### Basic Information

- Version with issue: 4.1.0.555618
- Last known good version: I don't know
- IDE: Visual Studio 2019 Professional
- Platform Target Frameworks: 
  - iOS:  12.3.1
- Nuget Packages:
- Affected Devices:
iPod touch 6
### Screenshots
sorry for this isn't specified format
[MomentAppCrashes.mp4.zip](https://github.com/xamarin/Xamarin.Forms/files/3353018/MomentAppCrashes.mp4.zip)

### Reproduction Link
[MemoryTest.zip](https://github.com/xamarin/Xamarin.Forms/files/3353028/MemoryTest.zip)

### PR DESCRIPTION
**Pull request by t-johnson**
### Description of Change ###

Fixes several places where ListView was leaking memory on IOS (and other platforms in some cases) when grouping was enabled with either a data templated defined with GroupHeaderTemplate , or a simple one set by the GroupDisplayBinding.

### Issues Resolved ### 

- fixes #6761

### API Changes ###
 None

### Platforms Affected ### 

- Core/XAML (all platforms)
- iOS
- Android
- UWP

(Most of the code changes are is in the IOS platform projects, however there is a small change in Xamarin.Forms.Core TemplatedItemList.css which will benefit all platforms. Note, I have only tested on IOS).

### Behavioral/Visual Changes ###

None

### Before/After Screenshots ### 

Not applicable

### Testing Procedure ###

I've created a test page (G6761) where there are two list views with grouping enabled.  One with a custom group header, and one with just the text header.  These lists are bound to a collection of collections, however there are no items added in the sub-collections so the lists only render the headers.  The page has a button to reload the collection, and another to force GC.
After navigating to the page, click the 'Refresh' button, and then scroll the two lists up and down a few times.  use the 'GC' button to report on the current memory usage.  You can click the Refresh button also to force the collections to be reset.

Before the fix, the total memory would climb as the user scrolls the lists, and also climb when the collections were reset.

### PR Checklist ###

- [ ] Targets the correct branch
- [ ] Tests are passing (or failures are unrelated)

### CODE REVIEW

**Comment by Tommigun1980** [comment]
Hi and thank you so much for these fixes!!

What release will this fix be in?

**Comment by t-johnson** [comment]
@Tommigun1980 the PR is against 5.0.0.  I am not sure why this is waiting so long to get merged though.

**Comment by transis2** [comment]
Waiting for a reviewer...

**Comment by Tommigun1980** [comment]
Hi! Any chance of getting this memory leak fix in at some point?

Thanks!

**Comment by t-johnson** [comment]
@jsuarezruiz any chance you can trigger the pipeline for this PR also?

**Comment by jsuarezruiz** [comment]
@t-johnson Sure.

**Comment by nickrandolph** [comment]
@jsuarezruiz can you kick the build again

**Comment by AlanYost** [comment]
@t-johnson I'm not sure how we see all the PR's that you have done in one build related to memory leaks?  I'm able to quickly test a build and have tested a few from the pipeline, but none have passed the memory tests.  I tested 5.0.0.7127 this am with no luck.
cc. @nickrandolph

**Comment by t-johnson** [comment]
@AlanYost Yeah I'm not sure how the pipeline works here, so without building it all yourself I am not sure how you can test it against your own app/sample.

Still would be nice for PRs to get either merged or rejected a whole lot faster!

**Comment by t-johnson** [comment]
@StephaneDelcroix this is waiting your review?

**Review by jsuarezruiz — APPROVED** [review]

**Review by rachelkang — COMMENTED** [review]
@t-johnson I tested on both the CG sample issue and on the original issue - unfortunately, it seems like the issue isn't fixed. What might I be missing?

On the CG - every time I click Refresh, the reported memory continues to increase. 
Similarly, in the original sample - every time I click Reload, the reported memory continues to increase.

https://user-images.githubusercontent.com/21988533/117048510-0c5d6b00-ace1-11eb-9a24-9fd00effa565.MP4

**Comment by t-johnson** [comment]
@rachelkang its been a while since I looked at this, but I believe the behavior before this fix was that even just scrolling the list up and down would leak memory so long as enough list items existed that they would go off screen.  we could see this by refreshing once, then scrolling up/down and then forcing the GC.
Repeatedly clicking the 'Refresh' button in the test does seem to show the memory increasing, however by tapping the GC we can see the memory comes back down, and is somewhat stable.

**Comment by jfversluis** [comment]
Now that we're so close to the sunsetting of Xamarin.Forms unfortunately we won't be able to take this in anymore, we're really sorry about that. Nevertheless, thank you so much for your time and effort that you have put into this PR.

Please have a look at the evolution of Xamarin.Forms, [.NET MAUI](https://github.com/dotnet/maui). A lot of development has been going on there. Hopefully this issue was already fixed in that codebase. If not, feel free to port this over to there.

Again, thank you so much for being a contributor and Xamarin.Forms user!

**Pull request closed without merging**
