### PR TITLE
[WPF] Xamarin Forms WPF Backend - Platform Project

### PR DESCRIPTION
**Pull request by mohachouch**
### Description of Change ###

This PR adds support for WPF backend on Xamarin.Forms.

NOTE: This PR only includes the Xamarin.Forms.Platform.WPF project. Other PRs will include maps, nuspec, ControlGallery...

### API Changes (Xamarin.Forms.Core) ###

Added:

public const string Device.WPF = "WPF";

### Behavioral Changes ###

You can create applications for **Windows 7/8/10** with Xamarin.Forms using the WPF backend.

### PR Checklist ###

- [ ] Has tests (if omitted, state reason in description)
- [x] Rebased on top of master at time of PR
- [x] Changes adhere to coding standard
- [x] Consolidate commits as makes sense

### CODE REVIEW

**Comment by TonyHenrique** [comment]
Xamarin + WPF = Good News

**Comment by TomLiu-GitHub** [comment]
The task of the unification of the world depends on the xamarin!!!

**Comment by eddyizm** [comment]
Really cool!

**Comment by Joebeazelman** [comment]
What does this mean for UWP?  Does it make sense supporting it, since Microsoft dropped the ball on its mobile business?  For years, WPF developers were left in uncertainty as it tried to figure out its desktop and mobile strategy. During this time, .NET went from an evolving and comprehensive platform to a highly fragmented mess. Consequently, Microsoft is now left with no option but to follow the industry instead of leading it.

Going forward, Microsoft should consolidate its .NET platform into a single, comprehensive, cross platform story.  It will help it retain its relevance in a rapidly changing and ultra competitive industry. Development tools and languages have always been its major strength, going back to its startup days as a BASIC language vendor.

**Pull request merged**
