### PR TITLE
Fix 7257 [UWP] Make Translate in combination with Scale work same as other platforms

### LINKED ISSUE #7257: [Bug] Scale/Translate works in different order between UWP and Android
### Description

When using the properties ScaleX/ScaleY and TranslationX/TranslationY on a view (in this case AbsoluteLayout) the position of the object is different between UWP and Android.

### Steps to Reproduce

With an AbsoluteLayout as the current object being drawn on, run the following code :

Xamarin.Forms.AbsoluteLayout AL = new Xamarin.Forms.AbsoluteLayout () ;
AL.BackgroundColor = Xamarin.Forms.Color.Green ;
Xamarin.Forms.AbsoluteLayout.SetLayoutBounds (AL, new Xamarin.Forms.Rectangle (0, 0, 100, 100));
Xamarin.Forms.AbsoluteLayout.SetLayoutFlags (AL, Xamarin.Forms.AbsoluteLayoutFlags.None);
AL.AnchorX = 0 ;
AL.AnchorY = 0 ;
AL.ScaleX = 0.5 ;
AL.ScaleY = 0.5 ;
AL.TranslationX = 100 ;
AL.TranslationY = 100 ;
Children.Add ( AL ) ;

### Expected Behavior

The expected behaviour is that the position of the green square should be the same on Android and on UWP (iOS not tried).
From the documentation it is not possible to tell which is expected, but they should both give the same result.

### Actual Behavior

On UWP: the green square of side 50 is at (x,y) = (200,200).
On Android: the green square of side 50 is at (x,y) = (100, 100).

### Basic Information

On Android the translate is done with non scaled coordinates, on UWP you have to multiply the translation by the scale to get the same result.

- Version with issue:
Xamarin.Forms v4.2.0.709249

- Last known good version:
- IDE: Visual Studio 2019
- Platform Target Frameworks: 
  - Android:  8.1
  - UWP:   16299
- Android Support Library Version:  v28.0.0.1
- Nuget Packages: standard Xamarin
- Affected Devices:

### PR DESCRIPTION
**Pull request by WayaFlyfeather**
### Description of Change ###

Changes the way translate-transforms are applied on FrameworkElements in UWP, when the element is also scaled.

Without this fix, the translate-transform is adjusted so as to neutralize a scaling of the transform that doesn't happen. (Probably because in 3D-projection that apparently _does_ happen, and an [adjustment is necessary](https://github.com/xamarin/Xamarin.Forms/blob/e962467bdd6ce2b612d3e5c97e0992e94bd3dd6c/Xamarin.Forms.Platform.UAP/VisualElementTracker.cs#L553-L555).)

This causes 2D scaling in combination with translating to behave differently on UWP compared to Android/iOS.

With this fix, the translation is not adjusted for scaling in 2D (as there is no need), and therefore behaves the same as on the other platforms.

### Issues Resolved ### 

- fixes #7257

### API Changes ###
 
 None

### Platforms Affected ### 

- UWP

### Behavioral/Visual Changes ###
2D translate in combination with scaling will behave like it does on Andorid/iOS. Without this fix, if something is scaled to half size, the translation will be doubled.

### Before/After Screenshots ### 
On Android, for comparison:
Android Before 7257

On UWP, before fix:
UWP 7257 Before

On UWP, after fix:
UWP 7257 After

### Testing Procedure ###

In UWP to Test Case 7257 in the Control Gallery. Check that the green and blue squares are vertically aligned with the red bar to the left, and that they are the same size. (The green square is the one with a 2D transform. The blue square is rotated an imperceptible amount in 3D, and therefore uses FrameworkElement.Projection instead of FrameworkElement.RenderTransform.)

### PR Checklist ###

- [ ] Targets the correct branch
- [ ] Tests are passing (or failures are unrelated)

### CODE REVIEW

**Comment by nickrandolph** [comment]
The changes proposed look good to me.

@WayaFlyfeather are you able to fix the build error - It looks like a missing file perhaps? 
@samhouts what else needs to happen with the PR for it to be good to merge?

**Comment by pictos** [comment]
I think the #11933 fix this issue. @mattleibow can you confirm that?

**Comment by mattleibow** [comment]
@pictos that is correct.

**Comment by pictos** [comment]
cc: @samhouts

**Comment by rmarinho** [comment]
Closing since #11933  fixes the other versions.

**Pull request closed without merging**
