### PR TITLE
[iOS] Rapidly clicking span (6 times at least) on UITest 3525 throws a null exception

### LINKED ISSUE #3930: [iOS] Rapidly clicking span on UI test 3525 throws a null exception on simulators
### Description

I was running UI test 3525 on iOS 12.0 simulators and ran into an issue. If you click the "Clickable" label several times quickly, it's going to throw a null exception. The issue seems to be coming from `CreateChildRecognizerHandler` of `EventTracker` because ['childGestures'](https://github.com/xamarin/Xamarin.Forms/blob/bd31e1e9fc8b2f9ad94cc99e0c7ab058174821f3/Xamarin.Forms.Platform.iOS/EventTracker.cs#L180) is null.

Note that I did not test this on a physical device and don't know if the issue exists there.

### PR DESCRIPTION
**Pull request by AndreiMisiukevich**
### Description of Change ###
Prevent enumeration through null collection

Fairy case for real app, but possibly somebody doesn't use NavigationPage and manages screens by setting MainPage... in theory, if user click on span and separate task starting to change MainPage it can cause the same issue like we have in UITest 3525 :) 

### Issues Resolved ### 
- fixes #3930

### API Changes ###
Added extra null check in ios EventTracker/CreateRecognizerHandler
 
### Platforms Affected ### 
iOS

### Behavioral/Visual Changes ###
UITest 3525 doesn't crash

### Before/After Screenshots ### 
Not applicable

### Testing Procedure ###
Open UITest 3525 and click 6 times rapidly

### CODE REVIEW

**Comment by AndreiMisiukevich** [comment]
@PureWeen https://github.com/xamarin/Xamarin.Forms/issues/3724

**Comment by PureWeen** [comment]
@AndreiMisiukevich   apologies but can you rebase this one please? We had some bad code get merged into master which is breaking the build for the PR

**Comment by AndreiMisiukevich** [comment]
@PureWeen should I just merge master to current branch or create new PR?

**Comment by PureWeen** [comment]
just rebase with master please
- merge our latest master into your fork
- git rebase master
- force push to your branch

Some references just in case 
https://help.github.com/articles/syncing-a-fork/

**Comment by AndreiMisiukevich** [comment]
@PureWeen done

**Pull request merged**
