### PR TITLE
[Android] Allow path-based icons to be loaded as toolbar icons

### PR DESCRIPTION
**Pull request by adrianknight89**
### Description of Change

Currently, `AppCompat` does not let you load toolbar icons from the local file system. This PR adds code so that drawables will be searched as resources first and then as files if they can't be found.
### Bugs Fixed
- https://bugzilla.xamarin.com/show_bug.cgi?id=43569
### PR Checklist
- [ ] Has tests (if omitted, state reason in description)
- [ ] Rebased on top of master at time of PR (no but MacOS stuff shouldn't be conflicting)
- [x] Changes adhere to coding standard
- [ ] Consolidate commits as makes sense

### CODE REVIEW

**Comment by jassmith** [comment]
Looks good needs a performance review.

**Comment by Emasoft** [comment]
Please approve this. It is a very urgent fix.

**Comment by Emasoft** [comment]
What are we waiting for to merge this? Please, we need this fix to be included in the next XF release.

**Comment by samhouts** [comment]
@Emasoft It's been approved and will more than likely be merged before the next release. I'm giving @adrianknight89 an opportunity to add a test page for it if he has time. :)

**Comment by adrianknight89** [comment]
Hi. I'm quite busy with work. How would the test for this work? Do you take a screenshot once the icon appears? Point to an example if you can so I can work off of it.

**Comment by adrianknight89** [comment]
@samhouts I used @emasoft's sample which is quite complex for a test page.

For your use case, I used `PCLStorage` to save a byte array and read it back as a toolbar item icon with a local file path. I'm not sure if it's acceptable that a new library has been added, but I can't think of an easier way to interact with the file system.

**Comment by StephaneDelcroix** [comment]
> For your use case, I used PCLStorage to save a byte array and read it back as a toolbar item icon with a local file path. I'm not sure if it's acceptable that a new library has been added, but I can't think of an easier way to interact with the file system.

it breaks the build...

**Comment by hartez** [comment]
@samhouts @adrianknight89 I had to remove the test case from master because it broke the build; I also removed the PCLStorage library references until the problems with the test case get resolved.

**Comment by adrianknight89** [comment]
@hartez Thanks for the update.

**Comment by alexpetin** [comment]
This PR disallows to use any android XML drawables - selector, vector, etc!

**Pull request merged**
