### PR TITLE
[Android] Fix to Issue Java.Lang.IndexOutOfBoundsException: setSpan

### PR DESCRIPTION
**Pull request by transis2**
Fix to Issue #12762
Java.Lang.IndexOutOfBoundsException: setSpan (nn ... nn) ends beyond length n-1

### CODE REVIEW

**Comment by rmarinho** [comment]
I m not sure this is the right fix.. Maybe we need something like this:

```
void UpdateText()
{
	if (EditText == null || Element == null)
		return;

	var text = Element.UpdateFormsText(Element.Text, Element.TextTransform);

	if (EditText.Text == text)
		return;

	EditText.Text = text;
	if (EditText.IsFocused)
	{
		EditText.SetSelection(EditText.Text.Length);
		EditText.ShowKeyboard();
	}
}
```

**Comment by transis2** [comment]
@rmarinho Yes, your solution is better.
Just to learn: You set the text to entry and the control will limit the size of string. Só, it will never há e an selection bigger than the size of the field, wright?

Do you want to create an PR or I can change mine with your suggestion?

**Comment by rmarinho** [comment]
@transis2  yes that's my idea, or with the check above if EditText is null (was disposed) we just return to also make it safer. 

I tried to reproduce this issue with a number ways but wasn't able, but that's the only idea i have right now to try to fix it.  
You can update your PR.

**Comment by transis2** [comment]
@rmarinho Update the fix with your suggestion.

Thanks!

**Comment by transis2** [comment]
Hi @rmarinho 

Our PR is showing thar some checks were not successful.
May I create a new one from the latest XF version ?

**Comment by rmarinho** [comment]
@transis2  i think i fixed the issue, running a new build and tests

**Comment by felipemomm** [comment]
@rmarinho When is it going to be merged? I am facing the same issue in my project, so I had to implement my own UpdateText method on OnElementPropertyChanged to avoid it (XF 4.8).

**Comment by nrmiller** [comment]
@rmarinho Is this PR still being considered? It looks like it has been around for awhile, and I'm running into this error as late as Xamarin.Forms 5.0.0.2021 on a Google Pixel 3 XL

My scenario to trigger this bug with 100% reliability:
1. Set Entry.MaxLength to 5 via XAML
2. Enter "3910" with numeric keyboard.
3. Without dismissing the keyboard, tap a radio button* to trigger setting the text to "1539.37" via a view-model property.

*Specifically, I have two radio buttons (1 for centimeters and 1 for inches). The goal is to convert what the user enters upon changing the select radio button. Because converting 3910cm yields 1539.37in and because "1539.37" > 5 characters, the crash occurs.
I tried to trigger this issue by creating a simple button and setting the Text to "000000" in the bound view-model command. This did not work, so I'm assuming something tricky is happening specifically with triggering via `RadioButtonGroup.SelectedValue`. Perhaps this is related to how MessagingCenter is used under the hood?

FWIW I've attached the stacktrace from the Xamarin Forms side (I'm stilling getting the IndexOutOfBounds on the Android side)
[entry text stacktrace.txt](https://github.com/xamarin/Xamarin.Forms/files/6781453/entry.text.stacktrace.txt)

**Pull request merged**
