### PR TITLE
Add CV back into UWP tests

### PR DESCRIPTION
**Pull request by PureWeen**
### Description of Change ###

We can pick through and leave only the passing tests in place but this will mean we have to be productive with any new tests added. Are we ready for this with CV?

### Testing Procedure ###
- make sure all the UI tests are 💚 

### PR Checklist ###

- [ ] Targets the correct branch
- [ ] Tests are passing (or failures are unrelated)

### CODE REVIEW

**Review by rmarinho — CHANGES_REQUESTED** [review]
Failing tests.

Also it seems that if tests fails the test report wasn't upload, and we also didn't notify our api (that updates the checks here) .

Can you check what happened @PureWeen ?

**Comment by PureWeen** [comment]
@rmarinho Yea I haven't gone through and commented out the failing tests yet

I first wanted to make everyone aware of this change and if they were ok with it :-) Looks like we are so I'll get this green

**Comment by rmarinho** [comment]
@PureWeen  can you rebase on top of 5.0.0 ?

**Comment by PureWeen** [comment]
Alright @rmarinho rebased and ignored all failing CarV/ColV tests

This one should be good to merge now

**Review by rmarinho — APPROVED** [review]

**Pull request merged**
