### PR TITLE
Xaml werr

### PR DESCRIPTION
**Pull request by StephaneDelcroix**
### Description of Change ###

remove the NoWarn on XamlC.

### Bugs Fixed ###

none, but this should please @kingces95  

### API Changes ###

None

### Behavioral Changes ###

Hopefully none

### PR Checklist ###

- [x] Has tests (if omitted, state reason in description)
- [x] Rebased on top of master at time of PR
- [x] Changes adhere to coding standard
- [x] Consolidate commits as makes sense

### CODE REVIEW

**Comment by kingces95** [comment]
Will review after build passes

> FixedCreateCSharpManifestResourceName.cs(10, 22): error CS0108: 'FixedCreateCSharpManifestResourceName.ResourceFilesWithManifestResourceNames' hides inherited member 'CreateManifestResourceName.ResourceFilesWithManifestResourceNames'. Use the new keyword if hiding was intended.

**Comment by StephaneDelcroix** [comment]
funny, does not fail on XS

**Comment by StephaneDelcroix** [comment]
this is a fun one. On XS, if I add the `new` keyword, I get a warning (0109) saying the `new` is not required as does not hide a inherited member :) This require a `#pragma warning remove`

**Comment by rmarinho** [comment]
👍

**Pull request merged**
