### PR TITLE
iOS and Android timers should be runnable from any thread and execute…

### PR DESCRIPTION
**Pull request by adrianknight89**
### Description of Change

This PR ensures that device timer can be started from any thread and executed on the UI thread. For a detailed discussion, see https://bugzilla.xamarin.com/show_bug.cgi?id=22706 and http://forums.xamarin.com/discussion/comment/74535
### Bugs Fixed
- https://bugzilla.xamarin.com/show_bug.cgi?id=28953 (partially - no work was done for Windows as I don't use it)

### CODE REVIEW

**Comment by TheRealAdamKemp** [comment]
The Windows code is here: https://github.com/xamarin/Xamarin.Forms/blob/272033723ea275ceb8a288fa605eafd035c79f2d/Xamarin.Forms.Platform.WinRT/WindowsBasePlatformServices.cs#L125

It looks correct to me. There is a WindowsTimer internal class right after StartTimer, and that internal class appears to be unused. Seems like a good candidate for deletion, but maybe I'm not searching in the right place.

There are similar _Timer classes in Android and iOS, and I'm not sure whether those are used or not. They're built on the .Net Timer class, which bothers me.

**Comment by adrianknight89** [comment]
I wasn't able to find any references either, so I removed those Timer classes in addition to adding minor refactoring. XF team can comment on the changes.

**Comment by samhouts** [comment]
@adrianknight89 Please rebase on master. Thanks!

**Comment by adrianknight89** [comment]
@samhouts Bear with me. First time I had to do rebase since I'm new to git. Hope it worked?

**Comment by rmarinho** [comment]
You need to add the .bak to gitignore

**Comment by adrianknight89** [comment]
See now.

**Comment by rmarinho** [comment]
@adrianknight89 can you rebase so i can run on our CI

**Comment by adrianknight89** [comment]
@rmarinho Done.

**Comment by rmarinho** [comment]
needs rebase to pass tests

**Comment by hartez** [comment]
@adrianknight89 Can you rebase this again? The UI test failures are from a test that was broken for a while; rebasing should picked up the fixed test and we can run it through again.

**Comment by adrianknight89** [comment]
Done.

**Comment by hartez** [comment]
@adrianknight89 
On first review, this looks good (and it's passing all the existing UI tests), but it definitely needs a UI test of its own. I'd suggest just adapting the repro project that Adam Kemp attached to [28953](https://bugzilla.xamarin.com/show_bug.cgi?id=28953).

**Comment by rmarinho** [comment]
Hey @adrianknight89 can you check if it's possible to add a UITest like @hartez referred ? thanks.

**Comment by adrianknight89** [comment]
DId you mean an automated test? I added a manual one.

**Comment by TheRealAdamKemp** [comment]
🎉

**Pull request merged**
