### PR TITLE
[GTK] Platform and Maps NuGet nuspecs

### PR DESCRIPTION
**Pull request by jsuarezruiz**
### Description of Change ###

Added GTK nuspecs.
- (net45) Xamarin.Forms.Platform.GTK.nuspec
- (net45) Xamarin.Forms.Maps.GTK.nuspec

### API Changes ###

None.

### Behavioral Changes ###

You can use Xamarin Forms for GTK using NuGet packages.

### PR Checklist ###

- [ ] Has tests (if omitted, state reason in description)
- [ ] Rebased on top of master at time of PR
- [ ] Changes adhere to coding standard
- [ ] Consolidate commits as makes sense

### CODE REVIEW

**Comment by rmarinho** [comment]
@jsuarezruiz can you remove the .sln changes ? 

Thanks

**Comment by jsuarezruiz** [comment]
Sure. I have discarded some unnecessary changes from the main sln and renamed the GTK nuspec.
Thanks for your feedback!

**Comment by rmarinho** [comment]
@jsuarezruiz the ID for the package too Xamarin.Forms.WPF

**Comment by rmarinho** [comment]
build

**Pull request merged**
