### PR TITLE
[Evolution] Toolbar a11y

### PR DESCRIPTION
**Pull request by samhouts**
### Description of Change ###

Building on #713, this would add VoiceOver/TalkBack/Narrator capability to ToolBarItems. Included in this change would be limited support for setting accessibility properties on the MasterDetailPage toggle button and the NavigationBar back button.

### `ToolbarItem`s
- [All] `ToolbarItem`s with `Text` will already read the `Text` if no `Accessibility.Name` or `.Hint` are supplied. No change.
- [iOS/UWP] `Accessibility.Name` will _replace_ the `Text` that is read aloud on iOS and UWP. This is consistent with the platforms.
- [Android] `Accessibility.Name` and/or `Accessibility.Hint` will _completely replace_ the `Text` that is both **visible** and read aloud on Android. This is a limitation of API<26 and may be resolved later to be consistent with iOS and UWP.

### `MasterDetailPage` Toggle Button
- [iOS/UWP] Set `Accessibility.Name` and `Accessibility.Hint` on a `MasterDetailPage` to set the text that is read aloud on the toggle button. Setting these properties will have no effect on Android.
- [Android] Add string resources to the Android project to set the text that is read aloud on the `MasterDetailPage` toggle button. 
```
 <string name="mdp_open_a11y_name">Show Master Page</string>
 <string name="mdp_close_a11y_name">Hide Master Page</string>
```

### `NavigationPage` Back Button
- [Android] Set `Accessibility.Name` and `Accessibility.Hint` on a `Page` to set the text that is read aloud on the Back arrow in the Action Bar. This will have no effect on OS back buttons.
- [UWP] Not applicable. 
- [iOS] Not supported; will read the title of the page as usual.

See https://forums.xamarin.com/discussion/94289/basic-accessibility-support-toolbaritems.

### Bugs Fixed ###

- [Bug 52656 - ToolbarItem needs accessibility support](https://bugzilla.xamarin.com/show_bug.cgi?id=52656)

### API Changes ###

None

### Behavioral Changes ###

None

### PR Checklist ###

- [x] Has tests (if omitted, state reason in description)
- [x] Rebased on top of master at time of PR
- [x] Changes adhere to coding standard
- [x] Consolidate commits as makes sense

### CODE REVIEW

**Comment by rmarinho** [comment]
OSX build is failing @samhouts

**Comment by rmarinho** [comment]
needs rebase @samhouts

**Comment by StephaneDelcroix** [comment]
Please rebase, @samhouts

**Comment by samhouts** [comment]
This is out of date and will conflict with #1199, so will reopen with a new PR when we continue a11y work shortly.

**Comment by CliffCawley** [comment]
@samhouts Any progress on this?

**Pull request closed without merging**
