### PR TITLE
Suggested workaround for bugzilla 42678 until a proper fix can be made.

### PR DESCRIPTION
**Pull request by rossdempster**
### Description of Change ###
Suggested workaround for bugzilla 42678 until a proper fix can be made.

### Bugs Fixed ###
https://bugzilla.xamarin.com/show_bug.cgi?id=42678

### API Changes ###
None.

### Behavioral Changes ###
None.

### PR Checklist ###

- [ ] Has tests (if omitted, state reason in description)
- [x] Rebased on top of master at time of PR
- [x] Changes adhere to coding standard
- [x] Consolidate commits as makes sense

### CODE REVIEW

**Comment by rmarinho** [comment]
Did you try pre2 ?

**Comment by rossdempster** [comment]
Hi rmarinho,

The fix here is actually for the issues reported by Pete Schmitz and wilhelm in that thread. It looks like there are potentially two or three different problems (possibly related?) being reported under the same bug report. Jon's issue will not be affected by this change.

Admittedly, I did not try pre2/3 to see if the issue had been fixed already. Going pre-release was never really an option because we are in the process of finalizing our production build. Patching the latest stable seemed the sensible way to go. Apologies if that is not the answer you were hoping for.

Regards,
Ross.

**Comment by rmarinho** [comment]
No worries @rossdempster i was asking , because it would save me some time of testing. I need to check that bug on that versions and master to see if we still se the issue. 

Thanks.

**Comment by rossdempster** [comment]
Makes sense @rmarinho.

I've got quite good at replicating it, so let me build these versions and see what happens. I'll get back to you.

Cheers,
Ross.

**Comment by hartez** [comment]
@rossdempster @rmarinho I believe [PR 706](https://github.com/xamarin/Xamarin.Forms/pull/706) addressed this bug (and in pretty much the same way that Ross's PR was handling it). Somehow I missed this PR when I was looking into that bug.

**Pull request closed without merging**
