### PR TITLE
[Android] Fixed Shapes drawing inconsistencies 

### LINKED ISSUE #11498: [Bug] [Shapes] Drawing inconsistencies
### Description

On Android, there are at least two issues with the Rectangle shape (not sure if it's just this shape), please see the screenshots below:

- It's drawn with some border/margin. Note `StrokeThickness` is set to zero.
- The corners don't look straight, they seem rounded (it should look like for the BoxView). On iOS, they look perfectly straight.

Please test the other shapes too. 
My suggestion is to create a StackLayout with all the possible Shapes stacked, and create a screenshot for Android and iOS and compare them to check if they look the same.

### Steps to Reproduce

```
    <StackLayout BackgroundColor="Red"
                 Spacing="0">
        <Rectangle HeightRequest="30"
                   Fill="Black"
                   StrokeThickness="0" />
        <BoxView HeightRequest="30"
                 BackgroundColor="Black" />
    </StackLayout>
```

### Expected Behavior

No border/margin and straight corners.

### Actual Behavior

Android (from the XAML preview, but in emulator it looks the same):

image

iOS (looks good):

image

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### PR DESCRIPTION
**Pull request by jsuarezruiz**
### Description of Change ###

Fixed Shapes drawing inconsistencies using `StrokeThickness= "0"` on Android.

### Issues Resolved ### 

- fixes #11498 

### API Changes ###

 None

### Platforms Affected ### 

- Android

### Behavioral/Visual Changes ###

None

#### Before
11498-before

#### After
11498-after

### Testing Procedure ###
Launch Core Gallery and navigate to the issue 11498. If the Rectangle renders without borders or artifacts (it looks the same as the BoxView below), the test has passed.

### PR Checklist ###

- [ ] Targets the correct branch
- [ ] Tests are passing (or failures are unrelated)

### CODE REVIEW

**Comment by opcodewriter** [comment]
@jsuarezruiz Awesome work!
Like I mentioned in the ticket, could you please make sure all other shapes beside the Rectangle are also rendered consistently across Android, iOS, UWP. Thank you

**Comment by jsuarezruiz** [comment]
Rebased with latest 5.0.0 branch changes and fixed conflicts.

**Review by jfversluis — CHANGES_REQUESTED** [review]
I see a red line between the boxes on Android 10 emulator with the current 5.0.0 code @jsuarezruiz

**Comment by jfversluis** [comment]
This is too big of a change to still add to Xamarin.Forms at this point in time. Thanks all for the time and effort here!

**Pull request closed without merging**
