### PR TITLE
[Bug] Fix ClearButtonVisibility.Never does not take effect on UWP

### LINKED ISSUE #8836: [Bug] ClearButtonVisibility.Never does not take effect on UWP
### Description

On UWP, specifying ClearButtonVisibility.Never on an Entry has no effect - the clear button still appears when the Entry gets focus.

Normally, I would not be too fussed by this, but if a page has a vertical stack of Entry Views, where each has HorizontalTextAlignment set to Center, tabbing between the Entry Views results in the Text in the Entry getting the focus jumping sideways, and the Text in the Entry losing focusing jumping the other direction. The Text of the Entry with focus will be misaligned with all of the other Entry Views.

It's a minor thing, but it should either be fixed, or the documentation at https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/text/entry#displaying-a-clear-button updated to say that this behavior happens and that it is by design.

### Steps to Reproduce

1. Build a vertical stack of Entry Views, with HorizontalTextAlignment set to Center, and ClearButtonVisibility set to Never. Populate each Entry with the same text.
2. Tab between the Entry Views.

For the Children of the vertical stack, I use:

                        new Entry
                        {
                            Placeholder = "Micro - fg",
                            FontSize = Device.GetNamedSize(NamedSize.Micro, typeof(Entry)),
                            HorizontalTextAlignment = TextAlignment.Center,
                            VerticalTextAlignment = TextAlignment.Center,
                            TabIndex = 3,
                            IsTabStop = true,
                            ClearButtonVisibility = ClearButtonVisibility.Never,
                            Text = "fg",
                        },
                        new Entry
                        {
                            Placeholder = "Small - fg",
                            FontSize = Device.GetNamedSize(NamedSize.Small, typeof(Entry)),
                            HorizontalTextAlignment = TextAlignment.Center,
                            VerticalTextAlignment = TextAlignment.Center,
                            TabIndex = 4,
                            IsTabStop = true,
                            ClearButtonVisibility = ClearButtonVisibility.Never,
                            Text = "fg",
                        },
                        new Entry
                        {
                            Placeholder = "Medium - fg",
                            FontSize = Device.GetNamedSize(NamedSize.Medium, typeof(Entry)),
                            HorizontalTextAlignment = TextAlignment.Center,
                            VerticalTextAlignment = TextAlignment.Center,
                            TabIndex = 5,
                            IsTabStop = true,
                        },
                        new Entry
                        {
                            Placeholder = "Large - fg",
                            FontSize = Device.GetNamedSize(NamedSize.Large, typeof(Entry)),
                            HorizontalTextAlignment = TextAlignment.Center,
                            VerticalTextAlignment = TextAlignment.Center,
                            TabIndex = 6,
                            IsTabStop = true,
                            ClearButtonVisibility = ClearButtonVisibility.Never,
                            Text = "fg",
                        },
                        new Entry
                        {
                            Placeholder = "Default - fg",
                            FontSize = Device.GetNamedSize(NamedSize.Default, typeof(Entry)),
                            HorizontalTextAlignment = TextAlignment.Center,
                            VerticalTextAlignment = TextAlignment.Center,
                            TabIndex = 7,
                            IsTabStop = true,
                            ClearButtonVisibility = ClearButtonVisibility.Never,
                            Text = "fg",
                        },
                        new Entry
                        {
                            Placeholder = "Header - fg",
                            FontSize = Device.GetNamedSize(NamedSize.Header, typeof(Entry)),
                            HorizontalTextAlignment = TextAlignment.Center,
                            VerticalTextAlignment = TextAlignment.Center,
                            TabIndex = 8,
                            IsTabStop = true,
                            ClearButtonVisibility = ClearButtonVisibility.Never,
                            Text = "fg",
                        },
                        new Entry
                        {
                            Placeholder = "Title - fg",
                            FontSize = Device.GetNamedSize(NamedSize.Title, typeof(Entry)),
                            HorizontalTextAlignment = TextAlignment.Center,
                            VerticalTextAlignment = TextAlignment.Center,
                            TabIndex = 9,
                            IsTabStop = true,
                            ClearButtonVisibility = ClearButtonVisibility.Never,
                            Text = "fg",
                        },
                        new Entry
                        {
                            Placeholder = "Subtitle - fg",
                            FontSize = Device.GetNamedSize(NamedSize.Subtitle, typeof(Entry)),
                            HorizontalTextAlignment = TextAlignment.Center,
                            VerticalTextAlignment = TextAlignment.Center,
                            TabIndex = 10,
                            IsTabStop = true,
                            ClearButtonVisibility = ClearButtonVisibility.Never,
                            Text = "fg",
                        },
                        new Entry
                        {
                            Placeholder = "Body - fg",
                            FontSize = Device.GetNamedSize(NamedSize.Body, typeof(Entry)),
                            HorizontalTextAlignment = TextAlignment.Center,
                            VerticalTextAlignment = TextAlignment.Center,
                            TabIndex = 11,
                            IsTabStop = true,
                            ClearButtonVisibility = ClearButtonVisibility.Never,
                            Text = "fg",
                        },
                        new Entry
                        {
                            Placeholder = "Caption - fg",
                            FontSize = Device.GetNamedSize(NamedSize.Caption, typeof(Entry)),
                            HorizontalTextAlignment = TextAlignment.Center,
                            VerticalTextAlignment = TextAlignment.Center,
                            TabIndex = 12,
                            IsTabStop = true,
                            ClearButtonVisibility = ClearButtonVisibility.Never,
                            Text = "fg",
                        },

### Expected Behavior

The Clear button should not appear on any of the Entry Views

### Actual Behavior

The Clear button appears on the Entry View that has focus

### Basic Information

- Version with issue: 4.3.0.991211
- IDE: VS2019
- Platform Target Frameworks: 
  - UWP:  18362

### Screenshots

HorizontallyCenteredEntryViewsUWP

### PR DESCRIPTION
**Pull request by bmacombe**
### Description of Change ###

Modifies the UWP EntryRenderer, FormsTextBox and FormsTextBoxTemplate to support optionally hiding the Delete Button as support by the other platforms.

Method used to implement this is to extract the ButtonVisible visual state and remove it from the control template when the entry is set to not display the delete button.  If it is changed back the ButtonVisible state is added back to the control template.

### Issues Resolved ### 
 - Fixes #8836

### API Changes ###
None
 
### Platforms Affected ### 
- UWP

### Behavioral/Visual Changes ###

Delete button will be shown or not shown based on the Entry's ClearButtonVisibility value.

### Before/After Screenshots ### 

Default Behavior
image

Updated behavior when clear button is set to never
image

### Testing Procedure ###
Open the issue 8836 page in the control gallery and follow the instructions.  Just clicking the toggle button will flip the state back and forth.

### PR Checklist ###

- [ ] Targets the correct branch
- [ ] Tests are passing (or failures are unrelated)

### CODE REVIEW

**Comment by bmacombe** [comment]
Rebased for conflicts

**Comment by michalsedlak** [comment]
Hi Guys, may I ask what is the status of this bug? When do you plan to review and merge this issue? Thank you.

**Comment by bmacombe** [comment]
Updated to fix conflicts

**Comment by bmacombe** [comment]
@samhouts Does the target branch of this PR need to be updated?

**Comment by michalsedlak** [comment]
I appreciate your fast feedback. Thank you!

**Pull request merged**
