### PR TITLE
ListView null checker in OnCommandCanExecuteChanged

### PR DESCRIPTION
**Pull request by AlfonChitoSalano**
### Description of Change ###

This fixes the https://github.com/xamarin/Xamarin.Forms/issues/14443 because when the refreshcommand is null it is still executed then the crash occurs.

### Issues Resolved ### 
- fixes #https://github.com/xamarin/Xamarin.Forms/issues/14443

### API Changes ###
ListView.OnCommandCanExecuteChanged

image

### Platforms Affected ### 
- Core/XAML (all platforms)

### Behavioral/Visual Changes ###
None

### Before/After Screenshots ### 
Before
image

After
image

### Testing Procedure ###
NA because it's just null checking. It rebuilds withour issues.

### PR Checklist ###
- [ ] Targets the correct branch
- [ ] Tests are passing (or failures are unrelated)

### CODE REVIEW

**Comment by thisisthekap** [comment]
@AlfonChitoSalano Thank you so much for the fix, we are running into this issue too!

Could someone please review this PR, as there is no known workaround?

**Comment by thisisthekap** [comment]
@davidortinau This one would be quite important to us.

**Comment by thisisthekap** [comment]
@jsuarezruiz @StephaneDelcroix @davidortinau This keeps being reported by our production app center instances. Can you provide any ETA when this PR is going to be processed?

**Comment by AlfonChitoSalano** [comment]
@jsuarezruiz @StephaneDelcroix @davidortinau Hello guys. it happened to us again. Would you be able to get a chance to look at this? thank you.

**Comment by thisisthekap** [comment]
@jfversluis Is this going to be integrated in one of the next service releases?

**Comment by thisisthekap** [comment]
@AlfonChitoSalano Just realized that @jfversluis just did a fix in #14580. I think this PR can be closed without merging.

**Comment by jfversluis** [comment]
Oh so sorry, I didn't see this one was here as well :(

This is indeed fixed by another PR and should be released very soon :)

THanks!

**Pull request closed without merging**
