### PR TITLE
Fix-9906 [Bug] Setting CharacterSpacing on Button leads to crash on iOS

### LINKED ISSUE #9906: [Bug] Setting CharacterSpacing on Button leads to crash on iOS
### Steps to Reproduce

1. Change the text of a button with CharacterSpacing set to 1 while the button is displayed.
2. Crash!

### Expected Behavior
Text is updated. No crash.

**Foundation.MonoTouchException: 'Objective-C exception thrown. Name: NSRangeException Reason: NSMutableRLEArray objectAtIndex:effectiveRange:: Out of bounds**

### Actual Behavior
App freezes shortly. Then crashes.

### Basic Information

- Version with issue: Xamarin.Forms 4.3.0.908675
- Last known good version: -
- IDE: Visual Studio 2019 16.4.3
- Platform Target Frameworks: iOS
  - xcode version 11.3.1
  - mono version 6.6.0.155
  - MacOS version 10.14.6
  - Xamarin.iOS version 13.10.0.17

### Reproduction Link
Open app, click second button to update text of first button. Then it should crash.

[CharacterSpacing.zip](https://github.com/xamarin/Xamarin.Forms/files/4307533/CharacterSpacing.zip)

### PR DESCRIPTION
**Pull request by yurkinh**
### Description of Change ###

Text update for controls with modified CharacterSpacing property leads to a crash on iOS.
This issue also relates to Label, Entry, Editor, Picker.
This is new PR instead of #9933

### Issues Resolved ### 

- fixes #9906 

### API Changes ###

 
 None

### Platforms Affected ### 

- iOS

### Behavioral/Visual Changes ###

None

### Before/After Screenshots ### 

Not applicable

### PR Checklist ###

- [x] Targets the correct branch
- [ ] Tests are passing (or failures are unrelated)

### CODE REVIEW

**Review by jsuarezruiz — CHANGES_REQUESTED** [review]
@yurkinh Thanks so much for the PR. Could we include a sample to validate the fix in Core Gallery (and maybe a UITest)?
Captura de pantalla 2020-12-03 a las 13 25 33
Testing without the changes, I cannot reproduce the crash.

**Comment by yurkinh** [comment]
@jsuarezruiz  I have added a page Issue9906 with a reproduction sample

**Review by jsuarezruiz — APPROVED** [review]

**Comment by jsuarezruiz** [comment]
Thanks for the repro sample @yurkinh.

**Review by rmarinho — APPROVED** [review]

**Comment by dlakes-hx** [comment]
I tried looking at the `5.0-pre5`, `5.0.0-pre6`, and `5.0.0` release notes (around the window when this was merged). It doesn't look like it was mentioned, though. Is there a timeframe/target release for when we'll see this rolled out?

**Pull request merged**
