### PR TITLE
Add secondary toolbar considerations to Shell renderers

### LINKED ISSUE #8422: [Bug] [iOS] Secondary ToolbarItems are added to regular Toolbar instead a secondary Toolbar
### Description
Bug is on iOS only.
Traditionally, XF creates a secondary Toolbar to render ToolbarItems marked as "Secondary". When using Shell, XF does not create the seondary Toolbar, it adds all ToolbarItems to the main Toolbar.

### Steps to Reproduce

1. Create a new Shell project. When using the standard template, the created Pages and ViewModels can be removed. Only one Page is needed.
2. Add a ContentPage (i.e. MainPage) if you deleted all pages.
3. Add a toolbar Item with Order "Primary" and one with Order "Secondary"
4. Add one Flyout Item with a ShellContent to the AppShell. Use MainPage for this ShellContent as DataTemplate.

or as I did:
1. Take the official Xamarin.Forms samples
2. Add an AppShell.xaml and AppShell.xaml.cs
3. Assign AppShell instance as MainPage in App.xaml.cs
4. Define MainPage as FlyoutItem/ShellContent in AppShell.xaml

Runtime:
1. Start App
2. Go to the page with the Toolbar Items

### Expected Behavior
The ToolbarItem with Order Primary is shown in Toolbar.
The ToolbarItem with Order Secondary is shown in a Secondard Toolbar below the regular Toolbar

### Actual Behavior
ToolbarItem with Order Primary and Secondary are shown in the regular Toolbar. No secondard Toolbar is shown.

### Basic Information

- Version with issue: 4.2.0.709249 / 4.3.0.947036
- Last known good version: n/a
- IDE: Visual Studio 2019 (16.3.8)
- Platform Target Frameworks:
  - iOS:  XCode 11.1 (cannot update to XCode 11.2, update crashes for whatever reason), iOS 12.0, 12.4
  - Device: Simulator with iOS 12.0 and iPhone 6 Plus with 12.4.1

### Screenshots
Secondary Toolbar without using Shell:

ShellSecondaryToolbarIssue-OK

Toolbar with using Shell:
ShellSecondaryToolbarIssue-with-Shell-NOK

### Reproduction Link
[ToolbarItemDemos with Shell.zip](https://github.com/xamarin/Xamarin.Forms/files/3820796/ToolbarItemDemos.with.Shell.zip)

### Recommendations for alternative?
Any recommendations for a nice alternative are very welcome as well.

### PR DESCRIPTION
**Pull request by jayhoogle**
### Issues Resolved ### 
- fixes #8422

### API Changes ###
 
 None

### Platforms Affected ###
- iOS

### Behavioral/Visual Changes ###
- Added rendering for a Xamarin Secondary toolbar in to the ShellPageRendererTracker which means when a user sets a ToolbarItem's Order to `Secondary` it'll appear on a new toolbar beneath the navigation bar.

#### Before
Before

#### After
After

### Testing Procedure ###
Tested on iOS 13.5 simulator, portrait and landscape, on the following devices:
- iPhone 11
- iPhone 8
- iPad Pro (4th Gen)

### PR Checklist ###

- [ ] Targets the correct branch
- [ ] Tests are passing (or failures are unrelated)

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/xamarin/Xamarin.Forms?pullRequest=10996) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/xamarin/Xamarin.Forms?pullRequest=10996) before we can accept your contribution.<br/><br/>:x: jayhoogle [sign now](https://cla.dotnetfoundation.org/xamarin/Xamarin.Forms?pullRequest=10996)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/xamarin/Xamarin.Forms?pullRequest=10996) it.</sub>

**Comment by PureWeen** [comment]
@jayhoogle out of curiosity what's your motivation for displaying the secondary items like this? Is it purely driven by the fact that that's how our NavigationPage works?

I feel like making them work like android (per the material spec)
https://material.io/design/platform-guidance/cross-platform-adaptation.html#cross-platform-guidelines

or making a toolbar like this
https://developer.apple.com/design/human-interface-guidelines/ios/bars/toolbars/

Fits more with the iOS design guidelines

thoughts?

**Comment by jayhoogle** [comment]
> @jayhoogle out of curiosity what's your motivation for displaying the secondary items like this? Is it purely driven by the fact that that's how our NavigationPage works?
> 
> 
> 
> I feel like making them work like android (per the material spec)
> 
> https://material.io/design/platform-guidance/cross-platform-adaptation.html#cross-platform-guidelines
> 
> 
> 
> or making a toolbar like this
> 
> https://developer.apple.com/design/human-interface-guidelines/ios/bars/toolbars/
> 
> 
> 
> Fits more with the iOS design guidelines
> 
> 
> 
> thoughts?

@PureWeen it is to mirror the Navigation Page, yes - thought consistency was important. But I can make it more like the iOS design guidelines if you think that would be better?

**Comment by PureWeen** [comment]
@jayhoogle For this one we want the menu to work the same way it does on android and the material guidelines with the dots and the menu that opens

https://material.io/design/platform-guidance/cross-platform-adaptation.html#cross-platform-guidelines

**Comment by samhouts** [comment]
We'll revisit this later in .NET MAUI. Closing now to do a little housekeeping. Thank you so much for the work you put into this! :)

**Pull request closed without merging**
