### PR TITLE
[UWP] Bug 57674 - XF.UWP ListView not honoring INotifyCollectionChanged 

### PR DESCRIPTION
**Pull request by gatm50**
### Description of Change ###

The ListView Renderer for UWP was not managing the OnCollectionChanged event.
Adding a new method and subscribing it to the respective handler to manage the OnCollectionChanged event

### Bugs Fixed ###

https://bugzilla.xamarin.com/show_bug.cgi?id=57674

### API Changes ###

None

### Behavioral Changes ###

None

### PR Checklist ###

- [x] Has tests (if omitted, state reason in description)
- [x] Rebased on top of master at time of PR
- [x] Changes adhere to coding standard
- [x] Consolidate commits as makes sense

### CODE REVIEW

**Comment by rmarinho** [comment]
Changes do not adhere to standards..

**Comment by samhouts** [comment]
@gatm50 Congratulations on your first pull request! 🎉 

We do use tabs instead of spaces and we do not use the `private` keyword. Would you mind pushing a new commit with these style changes? 

Thanks!

**Comment by gatm50** [comment]
Thank you @samhouts ! :) 
I have fixed the coding standard issues, please could you review it again?

**Comment by rmarinho** [comment]
Hi @gatm50 can you rebase this as we have removed WinRT.

Thanks

**Comment by gatm50** [comment]
Hi @rmarinho 
I have rebased, please let me know if is necessary something else

**Pull request merged**
