### PR TITLE
[build] post-build fix of the assembly

### LINKED ISSUE #2835: ResourceProvider Exception in Xamarin.Forms 3.0 due to Signature Change
### Description

Due to the change made in https://github.com/xamarin/Xamarin.Forms/pull/1976 for Xamarin.Forms 3.0, ResourceDictionaries that were compiled with XF 2.4 fail to load throwing the following exception:

**Can't resolve the reference 'System.Func`2<System.String,System.String> Xamarin.Forms.Internals.ResourceLoader::get_ResourceProvider()', referenced from the method 'System.Void TheExternalResourceDictionary::InitializeComponent()' in 'Xamarin.Forms.Core**

In particular, the ResourceDictionary in this case contains the styles for custom Xamarin.Forms controls that have a minimum support Xamarin.Forms version of 2.4

## Steps to Reproduce

Download the simple repro using the link at the bottom of this post. Let me walk you through the two solutions:

1. **CustomControls** - A simple class library with the ResourceDictionary
2. **ResLoaderRepro** - The Xamarin.Forms runtime app that present the problem

image

### 1- CustomControls.sln (aka CoolGrid)

This is very simple class library that contains one class, `CoolGrid`, that inherits from `Xamarin.Forms.Grid`. 

```
public class CoolGrid : Xamarin.Forms.Grid
    {
        public CoolGrid()
        {
            this.Resources = new CoolGridTheme();
        }
    }
```

The ResourceDictionary, "CoolGridTheme.xaml", is also very simple and contains a couple `OnPlatform` for height and a Style to set CoolGrid's `BackgroundColor`

```
<OnPlatform x:TypeArguments="x:Double" x:Key="Height" Default="32">
    <On Platform="Android" Value="45"/>
    <On Platform="iOS" Value="36"/>
    <On Platform="UWP" Value="32"/>
</OnPlatform>
<OnPlatform x:TypeArguments="x:Double" x:Key="MinimumHeight" Default="33">
    <On Platform="Android" Value="28"/>
    <On Platform="iOS" Value="28"/>
    <On Platform="UWP" Value="33"/>
</OnPlatform>
    
<Style x:Key="BaseCoolGridStyle" TargetType="customControls:CoolGrid">
    <Setter Property="HeightRequest" Value="{StaticResource Height}"/>
    <Setter Property="MinimumHeightRequest" Value="{StaticResource MinimumHeight}"/>
    <Setter Property="BackgroundColor" Value="DarkGray"/>
</Style>
```

The compiled result was copied to the Libs folder in the 2nd solution's folder.

### 2 - ResLoaderRepro.sln

This solution contains the Xamarin.Forms 3.0 projects (_created using the **File > New > Xamarin.Forms app > Blank App** template and only kept Android to keep it small_). 

I updated the XF NuGet page to the latest public release and added the reference to the CustomControls assembly in the Libs folder.

Finally, on MainPage, I add a single instance of CoolGrid:

```
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:customControls="clr-namespace:CustomControls;assembly=CustomControls"
             x:Class="ResLoaderRepro.MainPage">
    
    <StackLayout>
        <customControls:CoolGrid x:Name="MyCoolGrid" HeightRequest="100" WidthRequest="100"/>
    </StackLayout>
</ContentPage>
```

Here's a screenshot to better explain the simplicity of the setup:

image

## Expected Behavior

The `CoolGrid` control will render.

## Actual Behavior

An exception is thrown (see scrrenshot 4 below

**System.MissingMethodException: System.Func`2<string, string> Xamarin.Forms.Internals.ResourceLoader.get_ResourceProvider()**

Here's a screenshot of the break:

image

## Basic Information

- Version with issue:
- Last known good version: v2.5.1.527436
- IDE: VS2017 15.7.2
- Platform Target Frameworks: All
- Android Support Library Version: 23.3+
- Nuget Packages: XF 3.0+

## Screenshots

Screenshots inline with the explanation above.

## Reproduction Link

[Download the reproducible from here (3.1 MB)](https://progresssoftware-my.sharepoint.com/:u:/g/personal/mccarthy_progress_com/EXTatEGac0ZOo15fmHCktJ4BS10QdS60nWEh_aIkODGAjw?e=VxAC05)

### PR DESCRIPTION
**Pull request by StephaneDelcroix**
### Description of Change ###

[build] post-build fix of the assembly

add the IL corresponding to the old signature of the getter of ResourceLoader.ResourceProvider so code compiled against prior versions do not fail.

@alanmcgovern: could you please
 - confirm that the previewer looks for the ResourceProvider using the full signature, and not only the name
 - confirm that the old signature was never used, and it's safe not to implement the setter
 
### Bugs Fixed ###

- fixes #2835

### PR Checklist ###

- [x] Has tests (if omitted, state reason in description)
- [x] Rebased on top of the target branch at time of PR
- [x] Changes adhere to coding standard
- [x] Consolidate commits as makes sense

### CODE REVIEW

**Comment by alanmcgovern** [comment]
Can you remind me where the package shows up? Is it gonna be linked on this PR?

**Comment by jassmith** [comment]
ShameHat is adorable but no... bad name

**Comment by jassmith** [comment]
Also do we need all these dlls checked in?

**Comment by StephaneDelcroix** [comment]
> ShameHat is adorable but no... bad name

meh, yes

> Also do we need all these dlls checked in?
@jassmith we do not need the dll checked in, we could build the tool as part of our process

**Pull request merged**
