### PR TITLE
[MacOS] Image size issue (not rendered if skip setting WidthRequest and HeightRequest

### LINKED ISSUE #5204: [Feedback] Xamarin Forms on macOS requires a Width and HeightRequest
### Description

<p>When using either a webview or an image (using a URL for the source), both a HeightRequest and WidthRequest are required before the image is displayed. This is not the case on any other Forms supported platform

Simple test case URL : https://github.com/nodoid/threeplatforms

As it stands, the image will show. If you go into the MainPage.xaml file and uncomment the second Image line (and obviously comment the first!), you’ll see the image not show

There is a similar bug when using a RelativeView, but this is just being held in a StackLayout</p>
<a href="https://developercommunity.visualstudio.com/content/problem/444023/xamarin-forms-on-macos-requires-a-width-and-height.html">View on Developer Community</a>
<br>To find diagnostic information, see the <a href="https://devdiv.visualstudio.com/DevDiv/_workitems/edit/785208">original linked feedback ticket</a>.

### Source

[789503](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/789503)

### PR DESCRIPTION
**Pull request by AndreiMisiukevich**
### Description of Change ###

Possible fix for Image (Returns real size of image instead of Zero)

### Issues Resolved ### 

- #5204 (one part)

### API Changes ###

 None

### Platforms Affected ### 
- macOs

### Behavioral/Visual Changes ###

Images are renderer if skip setting WidthRequest and HeightRequest

### Before/After Screenshots ### 
Not applicable

### Testing Procedure ###

Simple test case URL : https://github.com/nodoid/threeplatforms

### CODE REVIEW

**Comment by rmarinho** [comment]
Hi can you add a test case please? Some screenshots would be great also. 

Thanks

**Comment by AndreiMisiukevich** [comment]
> Hi can you add a test case please? Some screenshots would be great also.
> 
> Thanks

Yep. I'll do it today

**Comment by AndreiMisiukevich** [comment]
Test Image

testimage

**Comment by AndreiMisiukevich** [comment]
@rmarinho done

**Comment by AndreiMisiukevich** [comment]
@rmarinho 

BEFORE:

image

AFTER:

image

**Comment by rmarinho** [comment]
after some look at it and testing I think I got a better solution @AndreiMisiukevich can you review and test #5600

**Pull request closed without merging**
