### PR TITLE
Xamarin.Forms.Map CameraChanged event

### LINKED ISSUE #1852: Map renderer giving 0 size with MoveToRegion
Bug report best practices: https://github.com/xamarin/Xamarin.Forms/wiki/Submitting-Issues

### Description
Android map renderer giving 0 size for Map
### Steps to Reproduce

1. Create a custom map
2. Move away from the map
3. Come back to the map

### Expected Behavior
The renderer displays the map

### Actual Behavior
Xamarin.Forms MapRenderer: MoveToRegion exception: Java.Lang.IllegalStateException: Error using newLatLngBounds(LatLngBounds, int): Map size can't be 0. Most likely, layout has not yet occured for the map view.  Either wait until layout has occurred or use newLatLngBounds(LatLngBounds, int, int, int) which allows you to specify the map's dimensions.
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <fcbf47a04b2e4d90beafbae627e1fca4>:0 
  at Java.Interop.JniEnvironment+InstanceMethods.CallVoidMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00069] in <402ad96b56e643ccbd17e513ae1b6078>:0 
  at Android.Runtime.JNIEnv.CallVoidMethod (System.IntPtr jobject, System.IntPtr jmethod, Android.Runtime.JValue* parms) [0x0000e] in <183d469964214eae9915d97180f9356f>:0 
  at Android.Gms.Maps.GoogleMap.MoveCamera (Android.Gms.Maps.CameraUpdate update) [0x00048] in <bcb3af9a0115492baaa7a2e17d504257>:0 
  at Xamarin.Forms.Maps.Android.MapRenderer.MoveToRegion (Xamarin.Forms.Maps.MapSpan span, System.Boolean animate) [0x000c5] in <5930f5b120c94ff2aae31bb1351fbfd2>:0 
### Basic Information

- Version with issue: 2.5.0.122203
- Last known good version: (first reported in 2.3.4)
- IDE: VS for Mac
- Platform Target Frameworks: 
  - Android: Min - API 15, Target 26
- Android Support Library Version: 
- Nuget Packages: Xamarin.Forms-2.5.0.122203, Xam.Forms.Maps-2.5.0.122203
- Affected Devices: Android phones

### PR DESCRIPTION
**Pull request by roubachof**
### Description of Change ###

Added a "camera changed" event to be notified when the maps is moved or zoomed. With the proper ```CameraChangedEventArgs``` and the ```Camera``` property, it allows developers to add customs overlays with ```SkiaSharp```, or even hide or show some controls while the map is changing.

### Issues Resolved ### 

Collaterally fixes an issue on ```Android```.

- fixes #1852. If map size is 0, and a call to `MoveCamera` is made an `IllegalStateException` will be thrown

### API Changes ###

Added:
 - ```event EventHandler<CameraChangedEventArgs> CameraChanged;```
 - ```Camera Camera { get; }```

### Platforms Affected ### 

- Core/XAML (all platforms)
- iOS
- Android
- ~~UWP~~

### Behavioral/Visual Changes ###

None.

### Before/After Screenshots ### 

Not applicable.

### Testing Procedure ###

I tested the 3 platforms with the RunAway! app:

https://github.com/roubachof/SkiaSharpnado/tree/xamarin-maps

in the SessionMap.xaml.cs (naming is bad :):

```csharp
GoogleMap.CameraChanged += GoogleMapCameraChanged;

private void GoogleMapCameraChanged(object sender, CameraChangedEventArgs e)
{
    Debug.WriteLine($"CameraChanged: pos: {e.Camera.Position.Latitude}, {e.Camera.Position.Longitude}");

    if (!_isCameraInitialized)
    {
        _isCameraInitialized = true;
    }

    if (_drawingCount == 0)
    {
        MapOverlay.InvalidateSurface();
    }
}
```

Then checked that I can indeed move and zoom the map and the overlay is updated accordingly.

image

image

image

#### Core

I created a ```Camera``` class with ```Zoom``` and ```Position``` to represent the current view photo settings.

For the ```Camera``` property, I wasn't sure how to propagate a change from the renderer to the core class for a read only property.
I reproduced the same pattern that the ```VisibleRegion``` property.

#### Android 

I added some code in the ```OnLayout``` method to return if the map size is 0, since the ```MoveToRegion``` call will fail if it's the case.

#### iOS

```MkMapView``` has no ```Zoom``` property, so I had to implement its own zoom.

#### ~~UWP~~

~~The zoom given by the ```MapControl``` is not consistent with the ```Google Maps``` and ```iOS``` custom zooms. To have the same behavior as the others platforms, I had to compute it manually (it uses the same code as the iOS one).~~

~~I added a ```OnSizeChanged``` delegate for the initial Camera assignement. It fixes also a scenario when MoveToRegion is called before the layout pass is made, and then the region set by the user is not taken into account.~~

### ~~Issues to solve on UWP before merge~~

1. ~~The zoom computation on uwp seems to be a little unaccurate, I don't really understand why. I would need a Bing maps expert for this :)~~

image

2. ~~The ```ActualCameraChanging``` event seems to be aggressively invoked and seems to take a lot of UI thread time. I tried numerous tactics without much success... It works but it is a bit laggy in my sharpnado example.~~

### PR Checklist ###

- [ ] Has automated tests 
- [x] Rebased on top of the target branch at time of PR
- [x] Changes adhere to coding standard

### CODE REVIEW

**Comment by samhouts** [comment]
@roubachof What's the status of this PR? Your last comment mentions that there is still work to be done. Is that still the case? Thanks!

**Comment by roubachof** [comment]
@samhouts It's fine for iOS and Android, but I would need some help of someone from the uwp team maybe to solve the uwp issues I met... Maybe I should split the uwp version out so you could merge the iOS and Android version?

**Comment by AlonRom** [comment]
Hi, @samhouts what is the status about this merge?

**Comment by nbsoftware** [comment]
Hello.
What's the status of this one?
I'm waiting on a fix for https://github.com/xamarin/Xamarin.Forms/issues/1852

**Comment by AlonRom** [comment]
@samhouts @hartez Hi, any status regarding this would be great. thanks

**Comment by baneageorge** [comment]
Hi, any chance to have some progress on this?

**Comment by jfversluis** [comment]
Closing this as we won't be adding anything new to Forms. Adding a tag to put it on the list to look into this for .NET MAUI.

**Pull request closed without merging**
