### PR TITLE
[XamlC] Resolve parameters in nested generics

### PR DESCRIPTION
**Pull request by akihikodaki**
### Description of Change ###

Generics can be nested; an argument for a parameter of a generic instance type can be another generic
 instance type, which has its own parameters. The parameters in a nested argument must be resolved to specialize such a generic instance type, which `ResolveGenericParameters` basically does.

Consider the following types for example:

```C#
class Foo<T>
{
}

class Bar<T>
{
}

class Quux<T> : Foo<Bar<T>>
{
}
```

Now resolve the base type of `Quux<int>`. The old rash implementation of `ResolveGenericParameters` reads arguments of `Foo`, finds `Bar` is a concrete type, and considers there is nothing to do and returns `Foo<Bar<T>>` as a resolved one. But that is not true. The new implementation checks the argument of `Bar`, finds it is a generic parameter, replaces with a concrete type, `int`, and returns `Foo<Bar<int>>`.

### Issues Resolved ### 
I was too lazy to open an issue.

### API Changes ###
 
 None

### Platforms Affected ### 

- Core/XAML (all platforms)

### Behavioral/Visual Changes ###

None

### Before/After Screenshots ### 

Not applicable

### PR Checklist ###

- [X] Has automated tests 
- [ ] Rebased on top of the target branch at time of PR
- [X] Changes adhere to coding standard

### CODE REVIEW

**Comment by samhouts** [comment]
build

**Comment by akihikodaki** [comment]
b2993dc351b1ff36635621f72d2f6bfd9d28fea4 does https://github.com/xamarin/Xamarin.Forms/pull/4061#pullrequestreview-165287388.

**Comment by samhouts** [comment]
build

**Comment by kingces95** [comment]
Awaiting @StephaneDelcroix's review...

**Pull request merged**
