### PR TITLE
[Android] Fix incorrect spacing in CollectionView with multiple spans

### LINKED ISSUE #9125: [Bug] [Android] Collection View wrong first/last item sizing (on Orientation=Vertical and Span > 1)
### Description
When using a Collection View on Android (any device) with Orientation=Vertical and Span > 1 (to get more than one column), when the DataTemplate is composed of a grid of fixed height and width, if the last item happens to sit on the rightmost slot its height is messed up. Also, the width of the first item is always messed up on ItemSizingStrategy=MeasureFirstItem . (see attached project)

### Steps to Reproduce

1. Have a DataTemplate of a Collection View composed of a Grid view with fixed height (rowdefinitions) and width (columndefinitions)
2. Populate the ItemSource so that the last item lands on the rightmost column of the collection view.

### Expected Behavior

First/last item on a Collection View to always be the size specified by the Grid col/row definitions.

### Actual Behavior

If, and only if, the last item happens to sit on the rightmost column in a Collection view it gets its height messed up. If it happens to be in any other column the item gets properly sized.
When the sizing strategy is set to MeasureFirstItem, the first item always gets its width messed up.

### Basic Information

- Version with issue: 4.4.0.991265 (known since at least 4.2, and still present in 4.6.0.129-nightly)
- Last known good version: N/A
- IDE: VS for Mac 8.3.11 (build 1)
- Android: devices with API 23 -> 28 for sure.

### Screenshots
Last item (wrong height):
Screen1

When ItemSizingStrategy="MeasureFirstItem", the first item gets wrong width as well:
Screen2

### Workaround
Add an "invisible" (enabled=false, visible=false) grid element to the Collection view in order to get the last (visible) item sized properly not being the last item in the collection anymore.

### Reproduction Link
[CollectionViewBug.zip](https://github.com/xamarin/Xamarin.Forms/files/4035531/CollectionViewBug.zip)

### LINKED ISSUE #9681: CollectionView LinearItemsLayout strange behavior on Android[Bug] [CollectionView] [Android]
### Description
The CollectionView has an unpleasant bug on Android. On UWP and iOS it hasn't been noticed.

When selecting LinearItemsLayout and setting ItemSpacing, the ItemSpacing on Android does not always work

I have created a project to repeat this bug

### Steps to Reproduce

1. Run my test project
2. Open The "Android Bug Page"
3. Click the "add Item" button several times
4. Click the "delete first item" button"

### Reproduction Link

https://github.com/dimonovdd/CollectionViewBug.git

### LINKED ISSUE #10585: [Bug] CollectionView GridLayout items spacing
### Description

When adding or removing items to collection view with GridItemsLayout and spacing between items, that spacing is not always correct. E.G. if we have Span = 2 and then remove first item in the row, the scond item will move to the left but will keep it's original horizontal spacing to the left even though there are no items to the left anymore.

It also appears that the last item has incorrect spacing as well

### Steps to Reproduce

You can checkout https://github.com/domagojmedo/IMSCovid19Tracker/tree/bug with spacing set in HomePage. If instead of the spacings we set Margin = 5 on SwipeView it's all same size and no issues there.

### Expected Behavior

Items in the CollectionView should add/remove items spacing depending on the surounding items.

### Actual Behavior

Items appear to only set the spacing once and then keep it even after the collection changes

### Basic Information

- Version with issue: 4.6
- Last known good version: N/A
- IDE: Visual Studio 16.5.4
- Platform Target Frameworks: 
  - iOS: Didn't test  
  - Android:  9.0 
  - UWP: Didn't test   
- Android Support Library Version: N/A 

### Screenshots

Before:
WhatsApp Image 2020-05-05 at 22 40 45 (1)
After swiping to remove USA:
WhatsApp Image 2020-05-05 at 22 40 45

### Reproduction Link

https://github.com/domagojmedo/IMSCovid19Tracker/tree/bug

### Workaround

If I just set Margin on items it looks much better

### LINKED ISSUE #13054: [Bug] CollectionView on Android does not layout new items properly
### Description

When adding an item to the CollectionView's ItemsSource (bound to an ObservableCollection), the CollectionView layout's ItemSpacing property is not respected (using LinearItemsLayout).

### Steps to Reproduce

1. Without clearing or resetting the ItemsSource, add a new item to the backing data source.
2. On Android, observe that the new item does not respect the ItemSpacing set on the CollectionView's layout.
3. Triggering a layout pass by, for example, changing tabs, will resolve this.

### Expected Behavior

The new items should be spaced as existing items are.

### Actual Behavior

On Android, the new items do not respect the layout's ItemSpacing property.

### Basic Information

- Version with issue: 4.8.0.1687
- Last known good version:
- Platform Target Frameworks: 
  - iOS: 14.1 (for comparison, not affected) 
  - Android: 9.0 (API 28), 10.0 (API 29)  
  - UWP:   
- Android Support Library / AndroidX Version: 
- NuGet Packages: 
- Affected Devices: Android Emulator

### Environment

<details>
  <summary>Show/Hide</summary>

```
Microsoft Visual Studio Enterprise 2019
Version 16.8.2
VisualStudio.16.Release/16.8.2+30717.126
Microsoft .NET Framework
Version 4.8.03752

Installed Version: Enterprise

ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools

ASA Service Provider   1.0

ASP.NET and Web Tools 2019   16.8.553.28003
ASP.NET and Web Tools 2019

ASP.NET Core Razor Language Services   16.1.0.2052803+84e121f1403378489b842e1797df2f3f5a49ac3c
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2019   16.8.553.28003
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.8.553.28003
Azure App Service Tools v3.0.0

Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.

Azure Data Lake Tools for Visual Studio   2.6.1000.0
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools   16.8.553.28003
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio   2.6.1000.0
Microsoft Azure Stream Analytics Tools for Visual Studio

C# Tools   3.8.0-5.20567.16+53c5d7d3cf13d88978744a32a27c5f8350a8400a
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Fabric.DiagnosticEvents   1.0
Fabric Diagnostic Events

GitHub.VisualStudio   2.11.106.19330
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft Azure HDInsight Azure Node   2.6.1000.0
HDInsight Node under Azure Node

Microsoft Azure Hive Query Language Service   2.6.1000.0
Language service for Hive query

Microsoft Azure Service Fabric Tools for Visual Studio   16.0
Microsoft Azure Service Fabric Tools for Visual Studio

Microsoft Azure Stream Analytics Language Service   2.6.1000.0
Language service for Azure Stream Analytics

Microsoft Azure Stream Analytics Node   1.0
Azure Stream Analytics Node under Azure Node

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2019 - v2.9.30924.1

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.113+g422d40002e.RR
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Mono Debugging for Visual Studio   16.8.43 (00471f8)
Support for debugging Mono processes with Visual Studio.

Node.js Tools   1.5.20902.1 Commit Hash:b474efcb6f92db52a8f8e2e6a8cb9648476885cc
Adds support for developing and debugging Node.js apps in Visual Studio

NuGet Package Manager   5.8.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Redgate SQL Change Automation   4.3.20316.22971
Extend DevOps processes to your SQL Server databases and safely automate database deployments.

Visit https://www.red-gate.com/sca/productpage for more information.

Copyright (C) 2011 Red Gate Software Ltd. All rights reserved.

This software contains components from Component Owl.
SQL Server is a registered trademark of Microsoft Corporation.
Visual Studio is a registered trademark of Microsoft Corporation.

SQL Change Automation contains code from the following open source software:

NuGet https://www.nuget.org/
SQL LocalDB Wrapper https://github.com/martincostello/sqllocaldb
Autofac https://autofac.org/
Json.NET https://json.net/
SemVer https://github.com/maxhauser/semver
Serilog https://serilog.net/
StringTemplate https://github.com/antlr/stringtemplate4
Extended WPF Toolkit https://wpftoolkit.codeplex.com/
Code InfoBox VSX http://www.codeproject.com/Articles/55196/Code-InfoBox-Visual-Studio-Extension-VSX
OctoPack https://github.com/OctopusDeploy/OctoPack
SQLite https://sqlite.org/

This product contains icons from http://www.visualpharm.com distributed under a free backlink license.

For license details or other notices relating to the above software, please see NOTICE.TXT and EULA.rtf in the SQL Change Automation application folder.
    

Snapshot Debugging Extension   1.0
Snapshot Debugging Visual Studio Extension Detailed Info

SonarLint for Visual Studio   4.28.0.24595
SonarLint is an extension to your favorite IDE that provides on-the-fly feedback to developers on new bugs and quality issues injected into their code.

SQL Server Data Tools   16.0.62010.06180
Microsoft SQL Server Data Tools

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   16.0.21016.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.8.0-5.20567.16+53c5d7d3cf13d88978744a32a27c5f8350a8400a
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   16.8.0-beta.20507.4+da6be68280c89131cdba2045525b80890401defd
Microsoft Visual F# Tools

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

Visual Studio Tools for Kubernetes   1.0
Visual Studio Tools for Kubernetes

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Foo   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   16.8.000.255 (d16-8@d002176)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.8.0.507 (remotes/origin/d16-8@e87b24884)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.8.112 (86385a3)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   11.1.0.17 (d16-8/c0e2b8e)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: be2226b
    Java.Interop: xamarin/java.interop/d16-8@79d9533
    ProGuard: Guardsquare/proguard/proguard6.2.2@ebe9000
    SQLite: xamarin/sqlite/3.32.1@1a3276b
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-8@2fb1cbc


Xamarin.iOS and Xamarin.Mac SDK   14.4.1.3 (e30c41de3)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
```
</details>

### Screenshots

Before adding a new item:
image

After adding a new item:
image

### Reproduction Link

https://github.com/EvanMulawski/XamarinFormsIssues/tree/master/XFIssues/XFIssues/XF13054

### PR DESCRIPTION
**Pull request by ChummerUA**
### Description of Change ###

Fixed incorrect spacing in CollectionView with multiple spans

### Issues Resolved ### 

- fixes #9125 
- fixes #10585  
- fixes #13054
- fixes #9681

### API Changes ###
 
 None

### Platforms Affected ### 

- Android

### Behavioral/Visual Changes ###

CollectionView doesn't add additional space to some items when layout have multiple spans anymore. Spacing now also updates correctly when ObservableCollection ItemsSource is updated.

### Before/After Screenshots ### 

Before

Screenshot_1589013087
Screenshot_1589013137
Screenshot_1589013163
Screenshot_1589013195

After
Screenshot_1589013349
Screenshot_1589013354
Screenshot_1589013406
Screenshot_1589013417

### PR Checklist ###

- [ ] Targets the correct branch
- [ ] Tests are passing (or failures are unrelated)

### CODE REVIEW

**Comment by domagojmedo** [comment]
Why is item: 5 higher than other items in first image? Same thing with item: 4 in third image

**Comment by ChummerUA** [comment]
@domagojmedo they have incorrect sizes because ItemDecoration in native renderer configured incorrectly. Also adapter need extra notifications when ItemsSource is updated in order to update ItemDecoration correctly

**Comment by domagojmedo** [comment]
@ChummerUA do you know if there is an issue for that already?

**Comment by ChummerUA** [comment]
@domagojmedo I linked issues that I found into description. There's your issue and another one

**Review by hartez — APPROVED** [review]

**Review by jsuarezruiz — APPROVED** [review]

**Comment by PureWeen** [comment]
@ChummerUA 

It looks like lots of the Android tests are failing for this one
https://dev.azure.com/xamarin/public/_releaseProgress?releaseId=2610&_a=release-environment-extension&environmentId=119947&extensionId=ms.vss-test-web.test-result-in-release-environment-editor-tab

**Comment by ChummerUA** [comment]
@PureWeen I can't see any details that can indicate me what is the reason for those failings. Anyway, I think I need to check my solution because I noticed one issue. Spacing is calculated correctly but items on the edges have incorrect size. For example, items in first and last columns of vertical grid with 3 and more than spans will have different width than ones in inner columns

**Comment by hartez** [comment]
@ChummerUA @PureWeen The Android API 27 test lane just timed out, so it did even run the tests. I'm looking to see what happened with the API 19 lanes.

**Comment by hartez** [comment]
@ChummerUA @PureWeen The API 19 test failures are happening because of a weird thing with the CarouselView's custom adapter; it does some weird things with ItemCount, so the `NotifyItemRangeChanged` calls are grinding to a halt. I'm looking into it.

**Comment by hartez** [comment]
>  Anyway, I think I need to check my solution because I noticed one issue. Spacing is calculated correctly but items on the edges have incorrect size. For example, items in first and last columns of vertical grid with 3 and more than spans will have different width than ones in inner columns

@ChummerUA @PureWeen I think I see why this is happening - the `GetItemOffsets` method is using `GetChildAdapterPosition(view)` to determine an index for the item. But the index also depends on whether there are header/footer items, so with a header in place the index is off by one and the offsets for the items on the edges are calculated wrong.

I think I see how we can fix this; the SpacingItemDecoration will need to have the SpanSizeLookup item passed in from the ItemsViewRenderer; the SpanSizeLookup. I'll implement that in the morning and see if we can fix this issue.

**Comment by ChummerUA** [comment]
@hartez 
It is happening because inner items being clipped equally from all sides in order to achieve correct spacing, while edge items are clipped only on the inner sides. In order to achieve both same sizes and correct spacing, horizontal offsets for each column in vertical collection/vertical offsets for each row in horizontal collection must have different values

**Comment by rmarinho** [comment]
@hartez  the tests on Android are taking more than 6H .. i m trying to figure if it's related with changes or not, but since it happens on all android environments i have a feeling is related with the changes.

**Comment by hartez** [comment]
@rmarinho I ran them locally on a device and they finished in 4 hours, so I don't think it's these changes causing the problem.

**Comment by rmarinho** [comment]
@hartez  they keep failing on CI..

**Comment by Cr15Denis** [comment]
similar problem #13044

**Comment by mhrastegary77** [comment]
we still have problem with this! when we update span count or device orientation the items size(Height) won't update correctly in Griditemlayout

**Pull request merged**
