### PR TITLE
[Bug] [UWP] Fix FontIcons alignment

### LINKED ISSUE #8606: [Bug] [UWP] FontIcons are not aligned correctly
### Description
On Xamarin.Forms the Icons from a Fontfile are slightly alligend to the left and top side instead of centered alignment. On Android and iOS is is correctly rendered. On UWP not. 

### Steps to Reproduce

1.  Load the demo application from the attached repo and start it on UWP / Android / iOS and compare the results. Specially on the very first icon of each font the differences are clearly visible (rhomb icon and cogwheel icon). Turn also on the gray background of each icon.

The demo app has two differnt font files included. The materialdesignicons-webfont.ttf from the web and one self extraced icon font fonticonlibrary.ttf extracted via http://fontello.com. 

### Expected Behavior
On UWP the icons should be centered vertically and horizontally sames as on Android and iOS.

### Actual Behavior
UWP font icons are slightly top/left aligned.

### Basic Information

- Version with issue: XF 4.3.0.991211
- Last known good version: 
- IDE: VS2019. latest.
- Platform Target Frameworks: 
  - iOS: Deployment Target 8.0
  - Android: 9.0
  - UWP:  version 1809, build 17763
- Affected Devices: UWP

### Screenshots
Screenshot_UWP

Screenshot_iOS

Screenshot_Android

### Reproduction Link
https://github.com/maexsp/XamarinBase/tree/XamarinFontIcons

### PR DESCRIPTION
**Pull request by tonyhallett**
### Description of Change ###

Correct icon positioning

### Issues Resolved ### 

- fixes #8606

### API Changes ###
None

 None

### Platforms Affected ### 

- UWP

### Behavioral/Visual Changes ###

Changes to being correctly positioned

### Before/After Screenshots ### 

Cannot do as doing pull request in browser.

### Testing Procedure ###

Cannot test.

### PR Checklist ###

- [ ] Targets the correct branch
- [ ] Tests are passing (or failures are unrelated)

### CODE REVIEW

**Review by jsuarezruiz — COMMENTED** [review]
@tonyhallett Thanks for the contribution!. Could you include a sample in https://github.com/xamarin/Xamarin.Forms/tree/5.0.0/Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared to validate it?

**Comment by jfversluis** [comment]
Thank you so much for taking the time to contribute this @tonyhallett ! Like Javier said; if you could add a little sample to demonstrate that would be awesome. This way it's easier for us to verify the fix now and in the future for possible regressions. Thanks!

**Comment by tonyhallett** [comment]
@jsuarezruiz @jfversluis 

I am not sure what kind of example you are looking for.
I suppose I could show a Button / ImageButton or Image with a FontImageSource then on a timer / button register my own FontImageSourceHandler replacing the broken one and update the Button / ImageButton or Image or show another one for comparison.

**Comment by tonyhallett** [comment]
I will see if can screenshot and assert pixels.

**Comment by jfversluis** [comment]
If you look at the Control Gallery project there are a lot of pages describing issues. Just a button or anything with a font icon on it that would be not properly aligned before this fix, but is properly aligned now will do :)

**Comment by tonyhallett** [comment]
@jfversluis    Yes I saw a recent example that just added a control with a radial gradient. Is there snapshot testing occurring from these UI tests ?

**Comment by jfversluis** [comment]
UI tests run through App Center where we have the possibility to look at screenshots yes. Or we run some things manually for manual verification :)

**Comment by tonyhallett** [comment]
@jfversluis 

Should I be creating screenshots ?
I did have the code below
```
#if UITEST 
using NUnit.Framework; using Xamarin.UITest; 
#endif 

#if UITEST 
[Test] public void ShouldHorizontallyCenterFontIcons() { 
RunningApp.WaitForElement(contentAutomationId); 
RunningApp.AttachScreenshotToTestContext("GithubIssue606"); } 
#endif
```
but If I ran the test from Visual Studio Test Explorer the `init` method was not called.  Perhaps you can advise on that.

> UI tests run through App Center where we have the possibility to look at screenshots yes. Or we run some things manually for manual verification :)

If I add a screenshot is there an automated test that will check future pull requests do not cause a regression ?

**Comment by jfversluis** [comment]
> but If I ran the test from Visual Studio Test Explorer the init method was not called. Perhaps you can advise on that.

That is correct, this will run as a UI test rather than a unit test :)

Had a quick look and made some minor adjustments but other than that this seems good! Thanks!

**Review by jfversluis — APPROVED** [review]

**Pull request merged**
