### PR TITLE
[Mac] NavigationPageRenderer amendments RE: Issue4388 

### LINKED ISSUE #4388: [macOS] Bugzilla40005 crashes on macOS with an NRE
### Description
If you run Bugzilla40005 it crashes with an NRE

### Steps to Reproduce

1.  Run Bugzilla40005
2.  Crashes

### Expected Behavior
doesn't crash

### Actual Behavior
Crashes

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - macOS: 10.14.2

### PR DESCRIPTION
**Pull request by AndreiMisiukevich**
### Description of Change ###

Some updates for Mac NavigationPageRenderer.
Preventing crashes, but still need to solve case, described it original ticket.

### Issues Resolved ### 
fixes #4388 #4389 

### API Changes ###
None

### Platforms Affected ### 
- Mac

### Behavioral/Visual Changes ###
No crash

### Before/After Screenshots ### 
Not applicable

### Testing Procedure ###
Run test-case 40005. See no crash

### CODE REVIEW

**Comment by AndreiMisiukevich** [comment]
Try to run 40005 issue and click back button. App crashes in native code.
Any ideas why?

**Comment by rmarinho** [comment]
Spend all afternoon around this, smallest repo :

```
		var btnGoMain = new Button
			{
				Text = "Go",
				Command = new Command(() => MainPage = new ContentPage { Content = new Label { Text = "HEllo" } })
			}; 

			var pageDemo = new ContentPage { Title = "Demo",  Content = btnGoMain };

			SetMainPage(new NavigationPage(pageDemo));
```

This doesn't crash but prints 

```
2018-12-03 18:51:59.607 Xamarin.Forms.ControlGallery.MacOS[33692:566283] View <Xamarin_Forms_Platform_MacOS_ButtonRenderer_FormsNSButton: 0x600002875ef0> has 16383 views pointing at it that can't be found.
```

So something is wrong

**Comment by rmarinho** [comment]
can pull this in If you want https://github.com/xamarin/Xamarin.Forms/commit/d9d8a3974a54c325846cd1ab29bb58761c015d33

**Comment by AndreiMisiukevich** [comment]
@rmarinho yes, please

**Comment by rmarinho** [comment]
LOt's of changes but we still can get to the hardcore problem.. something when changing the main page ,smallest repo: Keeps a zombie of the button around 

```
var btnGoMain = new Button
			{
				Text = "Go",
				Command = new Command(() => MainPage = new ContentPage { Content = new Label { Text = "HEllo" } })
			}; 
SetMainPage(new ContentPage { Title = "Demo",  Content = btnGoMain });
```

**Comment by AndreiMisiukevich** [comment]
@rmarinho @PureWeen  maybe it makes sense to merge existing amendments and continue to diving in another one
(This PR fixes original issue #4388)

**Comment by AndreiMisiukevich** [comment]
@rmarinho  any ideas?

**Comment by AndreiMisiukevich** [comment]
@rmarinho hi
fixes https://github.com/xamarin/Xamarin.Forms/issues/4389

can't reproduce 4389 as well on this brach

**Comment by AndreiMisiukevich** [comment]
@rmarinho @PureWeen 
Hey guys, it has very similar stacktrace with  https://github.com/xamarin/Xamarin.Forms/pull/4927/files

I get it if try to call dispose of control in separate task (Is it permitted at all?)

```xml
  at (wrapper managed-to-native) Foundation.NSObject.xamarin_release_managed_ref(intptr,Foundation.NSObject)
  at Foundation.NSObject.ReleaseManagedRef () [0x00001] in /Library/Frameworks/Xamarin.Mac.framework/Versions/5.2.1.12/src/Xamarin.Mac/Foundation/NSObject2.cs:235 
  at Foundation.NSObject.Dispose (System.Boolean disposing) [0x00030] in /Library/Frameworks/Xamarin.Mac.framework/Versions/5.2.1.12/src/Xamarin.Mac/Foundation/NSObject2.cs:788 
  at Foundation.NSObject.Dispose () [0x00001] in /Library/Frameworks/Xamarin.Mac.framework/Versions/5.2.1.12/src/Xamarin.Mac/Foundation/NSObject2.cs:147 
  at ObjCRuntime.Runtime.ThreadPoolDispatcher (System.Func`1[TResult] callback) [0x00010] in /Library/Frameworks/Xamarin.Mac.framework/Versions/5.2.1.12/src/Xamarin.Mac/ObjCRuntime/Runtime.cs:280 
  at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback () [0x00009] in /Library/Frameworks/Xamarin.Mac.framework/Versions/5.2.1.12/src/Xamarin.Mac/mcs/class/referencesource/mscorlib/system/threading/threadpool.cs:1210 
```

**Comment by AndreiMisiukevich** [comment]
if we remove ```base.Dispose();``` call from ```VisualElementRenderer``` - no crash.

What can be wrong?

**Comment by rmarinho** [comment]
It still crashes for me when I go back to the main gallery.

**Comment by AndreiMisiukevich** [comment]
@rmarinho yes.
But it's other issue, I guess.
This PR fixes InsertPageBefore behavior

**Comment by AndreiMisiukevich** [comment]
> It still crashes for me when I go back to the main gallery.

@rmarinho now works fine totally
Could you please re-review?

**Comment by knocte** [comment]
@AndreiMisiukevich is there an XF version released to nuget with this fix already? if yes, what version?

**Comment by AndreiMisiukevich** [comment]
@AndreiMisiukevich don't think so

**Comment by AndreiMisiukevich** [comment]
> @AndreiMisiukevich is there an XF version released to nuget with this fix already? if yes, what version?

don't think so

**Pull request merged**
