### PR TITLE
#8783 - uwp - images - when the uwp app suspends and resumes again the image source should be reupdated as uwp replaces images with transparent images onResume

### LINKED ISSUE #8783: [Bug] (UWP) Font Icons disappear after idle interval
### Description
UWP app has font icons, which display correctly. Go for a coffee and chat a bit. Come back, the page is all intact and correct **except** all icons have disappeared.

### Steps to Reproduce

1. create a page, sprinkle some font icons on it.
2. wait.
3. observe, they have all disappeared

### Expected Behavior
Not to disappear.

### Actual Behavior
 Disppeared.

NOTE - in screen shots below, the disappeared items are Font Icons, The undisappeared ones are all PNGs - we were in process of converting.

### Basic Information

- Version with issue: 4.2, 4.3
- Last known good version: none
- IDE:
- Platform Target Frameworks:  .NET Standard 2.0
 - UWP:  Windows 10, version 1809 (10.0; Build 17763)

### Screenshots

normal

disappeared

### LINKED ISSUE #9249: [Bug] [UWP] FontImageSource Disappeares on UWP after screen lock for few seconds
### Description
The Image (and Button Image) that it's source is set to FontImageSource disappears on UWP after you lock the screen for few seconds (or just Ctrl + Alt + Del then Cancel after few seconds)

### Steps to Reproduce
1.  Create Xamarin forms app add UWP only, copy this code 
```Xaml
<Button Margin="10">
        <Button.ImageSource>
	    <FontImageSource FontFamily="Arial" Glyph="X"  Size="20"   Color="Blue"/>
	</Button.ImageSource>
</Button>
```
2. Ctrl + Alt + Del
3. Wait like 5 seconds (It is interesting that the issue will not appear if you cancel quickly)
4. Cancel 
5. You will see the images gone

### Expected Behavior
Images should still be showing

### Actual Behavior
Anything assigned to FontImageSource will disappear

### Basic Information
Latest everything
* It doesn't matter which UWP target it is.
* It doesn't matter if you use Image or Button or if you use custom fonts or not.

### Screenshots
font-img-1
font-img-2

### LINKED ISSUE #10168: [Bug] (Uwp) - OnResume - ToolbarItems - are invisible after suspend and resuming the app
### Description
When the MainPage is a NavigationPage and has ToolbarItems which use an Image, then the images disappear when suspending the app and resuming it again.

In order to see this happen, we have to wait at least 15 seconds before resuming the application.

### Steps to Reproduce

1. Set the uwp version of the control gallery and run the app
2. Open the "Font ImageSource" gallery page located in the lower part of the detailPage
3. Suspend the app
4. Wait at least 15 seconds
5. Resume the app
6. The images of the toolbaritems are invisible

### Expected Behavior
The images of the toolBarItems shuldnt be invisible after a resume

### Actual Behavior
The images of the ToolbarItems are invivisble after a resume

### Basic Information

- Version with issue: changes pulled to the master branch 01.04.2020
- Last known good version: -
- IDE: Visual Studio 2019
- Platform Target Frameworks: 
  - UWP:  Tested with 16299 and 18362

### Screenshots
image

### PR DESCRIPTION
**Pull request by BrayanKhosravian**
### Description of Change ###
Uwp seems to replace images with transparent images when resuming the app after suspending it.
This only happens when we wait more then 15 seconds before we resume the app.

To fix this issue we set the `ImageSource` again when the app is resuming.
Refreshing the `ImageSource` is not enough.

To accomplish this the `ImageRenderer` has to subscribe to the `Resuming` eventhandler.

ToolbarItems can also use images. It is not enough to reset the `ImgaeSource` for the toolbaritems.
When the app resumes we have to update the toolbaritems as well.

### Issues Resolved ### 
- fixes #8783
- fixes #9249
- fixes #10168

### API Changes ###
Added:
- `async void OnResumingAsync(object sender, object e)` in the `Xamarin.Forms.Platform.UWP.ImageRenderer` which subscribed to `Windows.UI.Xaml.Application.Current.Resuming `

- `async void OnResumingAsync(object sender, object e)` in the `Xamarin.Forms.Platform.UWP.Platform` class which subscribes to `Windows.UI.Xaml.Application.Current.Resuming` in order to update the toolbar onResume

Changed:
- none
 
 Removed:
- none

### Platforms Affected ### 
- UWP

### Behavioral/Visual Changes ###
- Images are not transparent after suspending and then resuming the app again
- The images on toolbarItems are not transparent as well when reusing the app

### Before/After Screenshots ### 
- Fixed:
uwp-imagesource-onresume-fixed

- Not fixed:
uwp-imagesource-onresume-not-fixed

### Testing Procedure ###
1.) Set the uwp control galery as startup porject and run it
2.) Open the `Font ImageSource` page
3.) Suspend the app
4.) Wait 15 seconds
5.) Resume the app
6a) Images should be visible and should not be transparent
6b) the images of the toolbar should be visible as well

### PR Checklist ###

- [ ] Targets the correct branch
- [ ] Tests are passing (or failures are unrelated)

### CODE REVIEW

**Comment by BrayanKhosravian** [comment]
I think both issues are assigned to a milestone as the issues are labeled with e/3 and e/4 and im not sure what this labels mean. 
Are the labels documented anywhere?

**Comment by BrayanKhosravian** [comment]
Do you think that there is way to write a UI test which asserts this fix?

**Comment by BrayanKhosravian** [comment]
@bruzkovsky

**Comment by jfversluis** [comment]
> I think both issues are assigned to a milestone as the issues are labeled with e/3 and e/4 and im not sure what this labels mean.
> Are the labels documented anywhere?

the `e/n` labels are estimates of how much effort it would cost to fix it. It says nothing about milestones or priority :)

**Comment by BrayanKhosravian** [comment]
Ok the second commit fixes the issue with the toolbar.
It was actually hard to find the class which is responsible for rendering the toolbar.

@jsuarezruiz Thank you for helping me on gitter to find the component that is responsible for the toolbar

**Pull request merged**
