### PR TITLE
[iOS] Fix NRE in CarouselView without template

### LINKED ISSUE #12777: [Bug] CarouselView NRE if item template is not specified
### Steps to Reproduce

1. Create carousel view with 3 items
2. do not set template

### Expected Behavior
Display empty page (no crash)

### Actual Behavior
NRE

### Basic Information

- Version with issue: 5.0.1-nightly
- Last known good version:
- Platform Target Frameworks: Checked on iOS 14

### Screenshots

image

### PR DESCRIPTION
**Pull request by jsuarezruiz**
### Description of Change ###

The problem was that using Loop, always tried to use a TemplatedCell.

### Issues Resolved ### 

- fixes #12777  

### API Changes ###
 
 None

### Platforms Affected ### 

- iOS

### Behavioral/Visual Changes ###

None

### Before/After Screenshots ### 

Not applicable

### Testing Procedure ###
Launch Core Gallery and navigate to the issue 12777. Without exceptions, the test has passed.

### PR Checklist ###

- [ ] Targets the correct branch
- [ ] Tests are passing (or failures are unrelated)

### CODE REVIEW

**Comment by rmarinho** [comment]
Can you add a UITest ?

**Review by rmarinho — CHANGES_REQUESTED** [review]
Looks good, but we need to add a UITest :)

**Comment by jsuarezruiz** [comment]
Added UITest.

**Review by rmarinho — APPROVED** [review]
Good after tests

**Review by hartez — APPROVED** [review]

**Pull request merged**
