### PR TITLE
fixed WebView typo, replaced Label icons, added FlexLayout

### PR DESCRIPTION
**Pull request by davidortinau**
### Description of Change ###
Added FlexLayout xml node, snippet, and icons.

### Bugs Fixed ###
Fixed wrong Label icon images
Fixed WebView typo

### API Changes ###
None

### Behavioral Changes ###

None

### PR Checklist ###

- [ ] Has tests (if omitted, state reason in description)
- [x] Rebased on top of master at time of PR
- [x] Changes adhere to coding standard
- [x] Consolidate commits as makes sense

### CODE REVIEW

**Comment by jassmith** [comment]
build

**Comment by jassmith** [comment]
build errors due to missing files?

**Comment by davidortinau** [comment]
@jassmith I fixed the missing files and confirmed the proj builds successfully here.

**Comment by PureWeen** [comment]
build

**Comment by davidortinau** [comment]
merging per @jassmith

**Pull request merged**
